---
sidebar: sidebar 
permalink: upgrade-arl-auto-in-chassis/boot-node1-with-a900-controller-and-nvs.html 
keywords: boot, NVRAM, controller, module, node1, replacement 
summary: ARLを使用して同じシャーシ内のコントローラモデルをアップグレードする場合は、交換用コントローラモジュールでノード1をブートします。 
---
= 交換用システムモジュールでノード1をブートします
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
交換用モジュールを搭載した Node1 の起動準備が完了しました。サポートされている交換モジュールは、link:decide_to_use_the_aggregate_relocation_guide.html#supported-systems-in-chassis["サポートされるシステムマトリックス"] 。

[NOTE]
====
コントローラモジュールを交換する場合は、すべての接続を古いコントローラモジュールから交換用コントローラモジュールに移動します。

コントローラモジュールとNVRAMモジュールを交換する場合は、コンソール接続と管理接続のみを移動します。

====
.手順
. （AFF A250、AFF C250、AFF A800、またはAFF C800アップグレードのみ）Loaderプロンプトでメンテナンスモードに切り替えます。
+
「 boot_ontap maint 」を使用してください

+
.. 答え `y`混合プラットフォームの確認プロンプトが表示されます。
.. 確認プロンプトに応答し `yes` ます。
.. 100GbEインターフェイスの状態を表示します。
+
`storage port show`です。

+
次の出力例に示すように、NS224シェルフまたはストレージスイッチに接続されたすべての100GbEポートがポートとして報告されます `storage` 。

+
[listing]
----
*> storage port show
Port Type Mode    Speed(Gb/s) State    Status  VLAN ID
---- ---- ------- ----------- -------- ------- -------
e8a  ENET storage 100 Gb/s    enabled  online  30
e8b  ENET storage 100 Gb/s    enabled  online  30
e11a ENET storage 100 Gb/s    enabled  online  30
e11b ENET storage 100 Gb/s    enabled  online  30
----
.. メンテナンスモードを終了します。
+
「 halt 」



. [[A900_boot_node1]]NetApp Storage Encryption (NSE) ドライブがインストールされている場合は、次の手順を実行します。
+

NOTE: 手順 でこれまでに行ったことがない場合は、Knowledge Baseの記事を参照してください https://kb.netapp.com/onprem/ontap/Hardware/How_to_tell_if_a_drive_is_FIPS_certified["ドライブがFIPS認定かどうかを確認する方法"^] 使用している自己暗号化ドライブのタイプを確認するため。

+
.. 設定 `bootarg.storageencryption.support` 終了： `true` または `false`：
+
[cols="35,65"]
|===
| 次のドライブが使用中の場合 | 次に、 


| FIPS 140-2レベル2の自己暗号化要件に準拠したNSEドライブ | `setenv bootarg.storageencryption.support *true*` 


| ネットアップの非FIPS SED | `setenv bootarg.storageencryption.support *false*` 
|===
+
[NOTE]
====
FIPSドライブは、同じノードまたはHAペアで他のタイプのドライブと混在させることはできません。SEDと非暗号化ドライブを同じノードまたはHAペアで混在させることができます。

====
.. 特別なブートメニューに移動してオプションを選択します `(10) Set Onboard Key Manager recovery secrets`。
+
パスフレーズと、前の手順で手順 に記録しておいたバックアップ情報を入力します。を参照してください link:manage_storage_encryption_using_okm.html["オンボードキーマネージャを使用してストレージ暗号化を管理します"]。



. ノードをブートメニューでブートします。
+
「 boot_ontap menu

. ノードがブート メニューで停止した場合は、node1 で次のコマンドを実行して、古い node1 ディスクを交換用の node1 に再割り当てします。
+
`boot_after_controller_replacement`

+
少し待機したあと、交換するノードの名前を入力するように求められます。共有ディスク（Advanced Disk Partitioning（ADP；アドバンストディスクパーティショニング）またはパーティショニングされたディスクとも呼ばれます）がある場合は、HAパートナーのノード名を入力するように求められます。

+
これらのプロンプトは、コンソールメッセージに埋もれている可能性があります。ノード名を入力しなかった場合や間違った名前を入力した場合は、名前をもう一度入力するように求められます。

+
[NOTE]
====
「[localhost:disk.encryptNoSupport:alert]: FIPS認定暗号化ドライブと」、または「[localhost:diskown.errorDuringIO: error]: Error」がディスクエラーで発生した場合は、次の手順を実行します。

.. LOADERプロンプトでノードを停止します。
.. に記載されているストレージ暗号化のbootargを確認してリセットします <<A900_boot_node1,手順 2>>。
.. LOADERプロンプトでブートします。
+
「 boot_ontap 」



====
+
次の例を参考にしてください。

+
.コンソールの出力例を展開します
[%collapsible]
====
[listing]
----
LOADER-A> boot_ontap menu
.
.
<output truncated>
.
All rights reserved.
*******************************
*                             *
* Press Ctrl-C for Boot Menu. *
*                             *
*******************************
.
<output truncated>
.
Please choose one of the following:

(1)  Normal Boot.
(2)  Boot without /etc/rc.
(3)  Change password.
(4)  Clean configuration and initialize all disks.
(5)  Maintenance mode boot.
(6)  Update flash from backup config.
(7)  Install new software first.
(8)  Reboot node.
(9)  Configure Advanced Drive Partitioning.
(10) Set Onboard Key Manager recovery secrets.
(11) Configure node for external key management.
Selection (1-11)? 22/7

(22/7)                          Print this secret List
(25/6)                          Force boot with multiple filesystem disks missing.
(25/7)                          Boot w/ disk labels forced to clean.
(29/7)                          Bypass media errors.
(44/4a)                         Zero disks if needed and create new flexible root volume.
(44/7)                          Assign all disks, Initialize all disks as SPARE, write DDR labels
.
.
<output truncated>
.
.
(wipeconfig)                        Clean all configuration on boot device
(boot_after_controller_replacement) Boot after controller upgrade
(boot_after_mcc_transition)         Boot after MCC transition
(9a)                                Unpartition all disks and remove their ownership information.
(9b)                                Clean configuration and initialize node with partitioned disks.
(9c)                                Clean configuration and initialize node with whole disks.
(9d)                                Reboot the node.
(9e)                                Return to main boot menu.



The boot device has changed. System configuration information could be lost. Use option (6) to restore the system configuration, or option (4) to initialize all disks and setup a new system.
Normal Boot is prohibited.

Please choose one of the following:

(1)  Normal Boot.
(2)  Boot without /etc/rc.
(3)  Change password.
(4)  Clean configuration and initialize all disks.
(5)  Maintenance mode boot.
(6)  Update flash from backup config.
(7)  Install new software first.
(8)  Reboot node.
(9)  Configure Advanced Drive Partitioning.
(10) Set Onboard Key Manager recovery secrets.
(11) Configure node for external key management.
Selection (1-11)? boot_after_controller_replacement

This will replace all flash-based configuration with the last backup to disks. Are you sure you want to continue?: yes

.
.
<output truncated>
.
.
Controller Replacement: Provide name of the node you would like to replace:<nodename of the node being replaced>
Controller Replacement: Provide High Availability partner of node1: <nodename of the partner of the node being replaced>
Changing sysid of node node1 disks.
Fetched sanown old_owner_sysid = 536940063 and calculated old sys id = 536940063
Partner sysid = 4294967295, owner sysid = 536940063
.
.
<output truncated>
.
.
varfs_backup_restore: restore using /mroot/etc/varfs.tgz
varfs_backup_restore: attempting to restore /var/kmip to the boot device
varfs_backup_restore: failed to restore /var/kmip to the boot device
varfs_backup_restore: attempting to restore env file to the boot device
varfs_backup_restore: successfully restored env file to the boot device wrote key file "/tmp/rndc.key"
varfs_backup_restore: timeout waiting for login
varfs_backup_restore: Rebooting to load the new varfs
Terminated
<node reboots>

System rebooting...

.
.
Restoring env file from boot media...
copy_env_file:scenario = head upgrade
Successfully restored env file from boot media...
Rebooting to load the restored env file...
.
System rebooting...
.
.
.
<output truncated>
.
.
.
.
WARNING: System ID mismatch. This usually occurs when replacing a boot device or NVRAM cards!
Override system ID? {y|n} y
.
.
.
.
Login:
----
====
+
[NOTE]
====
上記の例のシステム ID は一例です。アップグレードするノードの実際のシステム ID は異なります。

プロンプトでノード名を入力するかログインプロンプトを表示するまで、ノードが数回リブートして環境変数をリストアし、システムのカードでファームウェアを更新し、他の ONTAP 更新を実行します。

====

