---
sidebar: sidebar 
permalink: upgrade-arl-auto-in-chassis/confirm-new-controllers-are-set-up-correctly.html 
keywords: ensure, controllers, new, setup, ha, pair, node1, node2, lif, cluster, high, availability 
summary: HAペアが有効になっていることを確認し、ノード1とノード2のストレージアクセスとLIFを確認し、同じシャーシ内のコントローラモデルをアップグレードしたあとにアグリゲートの所有権を確認します。 
---
= 新しいコントローラが正しくセットアップされていることを確認します
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
セットアップが正しいことを確認するには、HAペアが有効になっていることを確認します。また、ノード1とノード2がお互いのストレージにアクセスできること、およびクラスタの他のノードに属するデータLIFをどちらも所有していないことを確認します。さらに、すべてのデータアグリゲートが正しいホームノードにあること、および両方のノードのボリュームがオンラインであることを確認します。新しいノードの 1 つにユニファイドターゲットアダプタがある場合は、ポート設定をすべてリストアする必要があり、場合によってはアダプタの使用方法の変更が必要になることがあります。

.手順
. node2 のチェック後、 node2 クラスタのストレージフェイルオーバーとクラスタ HA ペアが有効になります。処理が完了すると、両方のノードに「 Completed 」と表示され、クリーンアップ処理が実行されます。
. ストレージフェイルオーバーが有効になっていることを確認します。
+
「 storage failover show 」をクリックします

+
次の例は、ストレージフェイルオーバーが有効になっている場合のコマンドの出力例を示しています。

+
[listing]
----
cluster::> storage failover show
                          Takeover
Node	    Partner       Possible      State Description
----------  -----------   ------------  ------------------
node1	    node2         true	        Connected to node2
node2	    node1         true	        Connected to node1
----
. 次のコマンドを使用して出力を調べ、 node1 と node2 が同じクラスタに属していることを確認します。
+
「 cluster show 」を参照してください

. 次のコマンドを使用して、 node1 と node2 が相互のストレージにアクセスできることを確認します。
+
「 storage failover show -fields local-missing-disks 、 partner-missing-disks 」というメッセージが表示されます

. 次のコマンドを使用して、 node1 と node2 のどちらもクラスタ内の他のノードがホーム所有するデータ LIF を所有していないことを確認します。
+
「 network interface show 」を参照してください

+
クラスタ内の他のノードがホーム所有するデータ LIF をノード 1 とノード 2 のどちらも所有していない場合は、データ LIF をホーム所有者にリバートします。

+
「 network interface revert 」の略

. アグリゲートがそれぞれのホームノードで所有されていることを確認します。
+
`storage aggregate show -owner-name <node1>`

+
`storage aggregate show -owner-name <node2>`

. オフラインになっているボリュームがないかを確認します。
+
`volume show -node <node1> -state offline`

+
`volume show -node <node2> -state offline`

. オフラインのボリュームがある場合は、セクションlink:prepare-nodes-for-upgrade.html["ノードをアップグレードする準備をします"]でキャプチャしたオフラインボリュームのリストと比較し、必要に応じて次のコマンドを各ボリュームに対して1回ずつ使用して、オフラインボリュームをオンラインにします：
+
`volume online -vserver <vserver_name> -volume <volume_name>`

. ノードごとに次のコマンドを使用して、新しいノードの新しいライセンスをインストールします。
+
`system license add -license-code <license_code,license_code,license_code...>`

+
license-code パラメータには、アルファベットの文字キーをアルファベットの大文字 28 個まで入力できます。ライセンスは一度に 1 つずつ追加することも、複数追加することもできます。各ライセンスキーをカンマで区切って指定することもできます。

. 次のいずれかのコマンドを使用して、元のノードから古いライセンスをすべて削除します。
+
「システムライセンスのクリーンアップ - 未使用 - 期限切れ」

+
`system license delete -serial-number <node_serial_number> -package <licensable_package>`

+
--
** 期限切れのライセンスをすべて削除します。
+
「システムライセンスのクリーンアップ - 期限切れ」

** 未使用のライセンスをすべて削除します。
+
'System license clean-up-unused （システムライセンスのクリーンアップ - 未使用） '

** クラスタから特定のライセンスを削除するには、ノードで次のコマンドを使用します。
+
`system license delete -serial-number <node1_serial_number> -package *`
`system license delete -serial-number <node2_serial_number> -package *`



--
+
次の出力が表示されます。

+
[listing]
----
Warning: The following licenses will be removed:
<list of each installed package>
Do you want to continue? {y|n}: y
----
+
すべてのパッケージを削除するには 'y' を入力します

. 次のコマンドを使用して出力を調べ、ライセンスが正しくインストールされていることを確認します。
+
「 system license show 」を参照してください

+
この出力を、link:prepare-nodes-for-upgrade.html["ノードをアップグレードする準備をします"]セクションでキャプチャした出力と比較できます。

. [[unset_maxwait]] 自己暗号化ドライブが構成で使用されており、 `kmip.init.maxwait`変数を `off`に設定している場合（例えば、_交換用システムモジュールでnode2を起動_、link:boot-node2-with-a900-controller-and-nvs.html#boot_node2_step1["手順 1."]）、変数を設定解除する必要があります：
+
`set diag; systemshell -node <node_name> -command sudo kenv -u -p kmip.init.maxwait`

. 両方のノードで次のコマンドを使用して SP を設定します。
+
`system service-processor network modify -node <node_name>`

+
link:other-references.html["参考資料"]を参照して、SPに関する情報については_System Administration Reference_に、system `service-processor network modify`コマンドの詳細については_ONTAP 9 Command reference_にリンクしてください。

. 新しいノードにスイッチレスクラスタを設定する場合は、link:other-references.html["参考資料"]を参照して_NetApp Support Site_にリンクし、_Transitioning to a two-node switchless cluster_の手順に従ってください。


.完了後
node1とnode2でStorage Encryptionが有効になっている場合は、link:set-up-storage-encryption-new-module.html["新しいコントローラモジュールで Storage Encryption をセットアップします"]のセクションを完了します。それ以外の場合は、link:decommission-old-system.html["古いシステムの運用を停止"]のセクションを完了します。
