---
sidebar: sidebar 
permalink: upgrade-arl-auto-in-chassis/decide-to-use-the-aggregate-relocation-guide.html 
keywords: deciding, aggregate, relocation, content, storage, controllers, administrators, ontap, ha, high, availability 
summary: 同じシャーシ内のコントローラモデル、ディスク、およびディスクに保存されているデータをアップグレードするARL手順を使用するかどうかを決定します。 
---
= この集約再配置手順を使用するかどうかを決定します
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
コントローラハードウェアをアップグレードするには、アグリゲートの再配置（ARL）方法がいくつかあります。このコンテンツでは、既存のシステムシャーシ、ディスク、およびディスクに保存されているデータを保持しながら、既存のシステムを交換用システムに変換して、HAペアのストレージコントローラをアップグレードする方法について説明します。この複雑な手順は、経験豊富なONTAP管理者のみが使用してください。

この ARL 手順がコントローラ ハードウェアのアップグレードに適しているかどうかを判断するには、サポートされているアップグレードとサポートされていないアップグレードについて、次のすべての状況を確認する必要があります。



== このARLアップグレードでサポートされています

この ARL 手順は、次の状況で使用できます。

* コントローラーのアップグレードは、 <<supported-systems,サポートされるシステムマトリックス>> 。
* NetAppの営業担当者に、コントローラのアップグレードに必要なハードウェアが揃っていることを確認しておきます。
+
** AFF A90、AFF A70、またはAFF C80コントローラ×2、およびすべてのI/Oモジュール。100GbEケーブルに必要な長さ。
** AFF A50、AFF A30、AFF C30、またはAFF C60コントローラとI/Oモジュール×2、および必要なケーブル
** ASA A150、AFF A150、またはFAS2820コントローラ
** ASA A900、AFF A900、またはFAS9500コントローラとNVRAMモジュールおよびパーツ


* アップグレードに必要な最小ONTAPバージョンを実行しています。詳細については、を参照して<<supported-systems,サポートされているシステムアップグレードの組み合わせ>>ください。
* ONTAPの管理に関する経験があり、診断権限モードで作業する場合のリスクを十分に理解していること。
* システムでONTAP 9.15.1以降が実行されており、イーサネットスイッチを使用してイーサネット接続ストレージに接続している。



NOTE: この手順 では、NetApp Storage Encryption（NSE）、NetApp Volume Encryption（NVE）、およびNetApp Aggregate Encryption（NAE）を使用できます。



== この ARL アップグレードではサポートされていません

次の状況では、この ARL 手順は使用できません。

* 新しいコントローラを新しいHAペアとしてクラスタに追加し、ボリューム移動を使用してデータを移行する。
* MetroCluster IP設定をアップグレードしています。
+
MetroCluster IP構成をアップグレードするには、link:other-references.html["参考資料"]を参照して_MetroClusterのアップグレードと拡張_コンテンツにリンクしてください。





== サポートされているシステムアップグレードの組み合わせ

次の表は、既存のシステムシャーシ、ディスク、およびそこに保存されているデータを保持しながら、既存のシステムを交換用システムに変換してコントローラのアップグレードを実行する場合にサポートされるシステムマトリックスを示しています。


CAUTION: この手順は、次のアップグレード構成に厳密に適用されます。他のシステムの組み合わせ間でのアップグレードには、この手順を使用しないでください。その他のコントローラモデルについては、link:other-references.html["参考資料"]を参照して、_ONTAP 9.8以降を実行しているコントローラハードウェアをアップグレードするための「system controller replace」コマンドの使用_および_ONTAP 9.8以降を実行しているコントローラハードウェアを手動でアップグレードするためのアグリゲートの再配置の使用_にリンクしてください。

[cols="20,20,40"]
|===
| 既存のシステム | 交換用システム | サポートされるONTAPのバージョン 


| AFF C250^1^ | AFF C30、AFF C60 | 9.16.1 


| AFF A250^1^ | AFF A30、AFF A50 | 9.16.1 


| AFF C800^1^ | AFF C80用 | 9.16.1 


| AFF A800^1^ | AFF A90またはAFF A70 | 9.15.1以降 


| AFF A220をオールSANアレイ（ASA）として構成 | ASA A150 | 9.13.1P1以降 


| AFF A220の略 | AFF A150 | 9.10.1P15、9.11.1P11、9.12.1P5以降 


| AFF A200 | AFF A150  a| 
9.10.1P15、9.11.1P11以降^2^



| AFF C190の略 | AFF A150 | 9.10.1P15、9.11.1P11、9.12.1P5以降 


| FAS2620 | FAS2820  a| 
9.11.1P7以降のパッチリリース（FAS2620）^2^

9.13.1以降（FAS2820）



| FAS2720 | FAS2820 | 9.13.1以降 


| AFF A700をASAとして構成 | ASA A900 | 9.13.1P1以降 


| AFF A700の略 | AFF A900 の略 | 9.10.1P10、9.11.1P6以降 


| FAS9000 | FAS9500 | 9.10.1P10、9.11.1P6以降 
|===
^1^ ONTAP 9.15.1以降で導入されたシステムにアップグレードすると、ONTAPは、既存のシンプロビジョニングされたすべてのボリューム（Storage Efficiencyを使用していないボリュームも含む）のストレージ効率を変換し、ハードウェアオフロード機能を使用する新しいStorage Efficiency機能を適用します。これは自動バックグラウンドプロセスであり、システムのパフォーマンスへの明らかな影響はありません。 https://docs.netapp.com/us-en/ontap/concepts/builtin-storage-efficiency-concept.html["詳細はこちら。"^]です。

^2^ AFF A200 および FAS2620 システムは、9.11.1 以降の ONTAP バージョンをサポートしていません。

[NOTE]
====
NetAppでは、可能であれば、古いシステムと交換用システムで同じバージョンのONTAPを使用することを強く推奨しています。

上記の表のONTAPの最小バージョンは必須です。これらのバージョンのONTAPにはサービスプロセッサまたはベースボード管理コントローラ（BMC）のファームウェアバージョンが適用されています。このファームウェアバージョンは、アップグレード時にシャーシ内に異なるコントローラタイプを混在させるために必要です。

====


== 別のハードウェアアップグレード手順を選択する

* link:../upgrade-arl/index.html["コントローラハードウェアのアップグレードに使用できる代替ARL方法を確認します"]です。
* コントローラーのハードウェアをアップグレードする別の方法を希望し、ボリュームの移動を行う意思がある場合は、link:other-references.html["参考資料"]を参照して_ボリュームまたはストレージを移動してアップグレードする_にリンクしてください。


.関連情報
link:other-references.html["参考資料"]を参照して、_ONTAP 9 Documentation_にリンクしてください。

.次の手順
このARL手順を使用することを決定した後、link:required-tools-and-documentation.html["必要なツールとドキュメントについて学ぶ"]。
