---
sidebar: sidebar 
permalink: upgrade-arl-auto-in-chassis/ensure-new-controllers-are-set-up-correctly.html 
keywords: ensure, controllers, new, setup, ha, pair, node1, node2, lif, cluster, high, availability 
summary: HAペアが有効になっていることを確認し、ノード1とノード2のストレージアクセスとLIFを確認し、同じシャーシ内のコントローラモデルをアップグレードしたあとにアグリゲートの所有権を確認します。 
---
= 新しいコントローラが正しくセットアップされていることを確認します
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
セットアップが正しいことを確認するには、HAペアが有効になっていることを確認します。また、ノード1とノード2がお互いのストレージにアクセスできること、およびクラスタの他のノードに属するデータLIFをどちらも所有していないことを確認します。さらに、すべてのデータアグリゲートが正しいホームノードにあること、および両方のノードのボリュームがオンラインであることを確認します。新しいノードの 1 つにユニファイドターゲットアダプタがある場合は、ポート設定をすべてリストアする必要があり、場合によってはアダプタの使用方法の変更が必要になることがあります。

.手順
. node2 のチェック後、 node2 クラスタのストレージフェイルオーバーとクラスタ HA ペアが有効になります。処理が完了すると、両方のノードに「 Completed 」と表示され、クリーンアップ処理が実行されます。
. ストレージフェイルオーバーが有効になっていることを確認します。
+
「 storage failover show 」をクリックします

+
次の例は、ストレージフェイルオーバーが有効になっている場合のコマンドの出力例を示しています。

+
[listing]
----
cluster::> storage failover show
                          Takeover
Node	    Partner       Possible      State Description
----------  -----------   ------------  ------------------
node1	    node2         true	        Connected to node2
node2	    node1         true	        Connected to node1
----
. 次のコマンドを使用して出力を調べ、 node1 と node2 が同じクラスタに属していることを確認します。
+
「 cluster show 」を参照してください

. 次のコマンドを使用して、 node1 と node2 が相互のストレージにアクセスできることを確認します。
+
「 storage failover show -fields local-missing-disks 、 partner-missing-disks 」というメッセージが表示されます

. 次のコマンドを使用して、 node1 と node2 のどちらもクラスタ内の他のノードがホーム所有するデータ LIF を所有していないことを確認します。
+
「 network interface show 」を参照してください

+
クラスタ内の他のノードがホーム所有するデータ LIF をノード 1 とノード 2 のどちらも所有していない場合は、データ LIF をホーム所有者にリバートします。

+
「 network interface revert 」の略

. アグリゲートがそれぞれのホームノードで所有されていることを確認します。
+
`storage aggregate show -owner-name <node1>`

+
`storage aggregate show -owner-name <node2>`

. オフラインになっているボリュームがないかを確認します。
+
`volume show -node <node1> -state offline`

+
`volume show -node <node2> -state offline`

. オフラインになっているボリュームがある場合は、セクションで取得したオフラインボリュームのリストと比較します link:prepare_nodes_for_upgrade.html["ノードをアップグレードする準備をします"]必要に応じて、次のコマンドを使用して、ボリュームごとに 1 回、オフラインボリュームをオンラインにします。
+
`volume online -vserver <vserver_name> -volume <volume_name>`

. ノードごとに次のコマンドを使用して、新しいノードの新しいライセンスをインストールします。
+
`system license add -license-code <license_code,license_code,license_code...>`

+
license-code パラメータには、アルファベットの文字キーをアルファベットの大文字 28 個まで入力できます。ライセンスは一度に 1 つずつ追加することも、複数追加することもできます。各ライセンスキーをカンマで区切って指定することもできます。

. 次のいずれかのコマンドを使用して、元のノードから古いライセンスをすべて削除します。
+
「システムライセンスのクリーンアップ - 未使用 - 期限切れ」

+
`system license delete -serial-number <node_serial_number> -package <licensable_package>`

+
--
** 期限切れのライセンスをすべて削除します。
+
「システムライセンスのクリーンアップ - 期限切れ」

** 未使用のライセンスをすべて削除します。
+
'System license clean-up-unused （システムライセンスのクリーンアップ - 未使用） '

** クラスタから特定のライセンスを削除するには、ノードで次のコマンドを使用します。
+
`system license delete -serial-number <node1_serial_number> -package *`
`system license delete -serial-number <node2_serial_number> -package *`



--
+
次の出力が表示されます。

+
[listing]
----
Warning: The following licenses will be removed:
<list of each installed package>
Do you want to continue? {y|n}: y
----
+
すべてのパッケージを削除するには 'y' を入力します

. 次のコマンドを使用して出力を調べ、ライセンスが正しくインストールされていることを確認します。
+
「 system license show 」を参照してください

+
でキャプチャした出力と比較できます link:prepare_nodes_for_upgrade.html["ノードをアップグレードする準備をします"] セクション。

. [[unset_maxwait]]構成で自己暗号化ドライブを使用している場合は、を設定します `kmip.init.maxwait` 変数をに設定します `off` （例：In_Boot node2と交換用システムモジュール_、 link:boot_node2_with_a900_controller_and_nvs.html#boot_node2_step1["手順 1."]）を使用している場合は、次のように変数を設定解除
+
`set diag; systemshell -node <node_name> -command sudo kenv -u -p kmip.init.maxwait`

. 両方のノードで次のコマンドを使用して SP を設定します。
+
`system service-processor network modify -node <node_name>`

+
を参照してください link:other_references.html["参考資料"] SP および _SP ONTAP 9 コマンドの詳細については ' システム管理リファレンスにリンクするには ' マニュアルページリファレンスを参照してください system の service-processor network modify コマンドの詳細については ' を参照してください

. 新しいノードにスイッチレスクラスタをセットアップする場合は、を参照してください link:other_references.html["参考資料"] ネットアップサポートサイトへのリンクを設定するには、 _ 2 ノードスイッチレスクラスタへの移行の手順に従ってください。


.完了後
ノード 1 とノード 2 でストレージ暗号化が有効になっている場合は、セクションを完了します link:set_up_storage_encryption_new_module.html["新しいコントローラモジュールで Storage Encryption をセットアップします"]。それ以外の場合は、の項を実行します link:decommission_old_system.html["古いシステムの運用を停止"]。
