---
sidebar: sidebar 
permalink: upgrade-arl-auto-in-chassis/guidelines-for-upgrading-controllers-with-arl.html 
keywords: guidelines, upgrade, ontap, controllers, old, system, chassis, disk, disks 
summary: アップグレード構成にARLを使用できるかどうかを確認します。古いシステムシャーシとディスクはそのまま使用できます。 
---
= コントローラのアップグレードに関するガイドラインを参照してください
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
アグリゲートの再配置（ARL）を使用して古いシステムシャーシとディスクを維持できるかどうかを理解するには、システムのアップグレード構成とONTAPのバージョンによって異なります。



== ARL のアップグレードがサポートされます

特定のシステム構成では、コントローラのアップグレードがサポートされています。サポートされているシステムと最小ONTAP バージョンのリストについては、link:decide-to-use-the-aggregate-relocation-guide.html#supported-systems["サポートされているシステムアップグレードの組み合わせ"]を参照してください。

新しいシャーシを含む完全なシステムとして、新しいAFF A30、AFF A50、AFF A70、AFF A90、AFF A150、AFF A900、AFF C30、AFF C60、AFF C80、FAS2820、またはFAS9500を受け取った場合は、link:other-references.html["参考資料"]を参照して、_ONTAP 9.8以降を実行しているコントローラハードウェアをアップグレードするための「system controller replace」コマンドの使用_にリンクしてください。

ARL を使用したコントローラのアップグレードは、 SnapLock Enterprise ボリュームおよび SnapLock Compliance ボリュームが設定されたシステムでサポートされます。



== 2 ノードスイッチレスクラスタ

2 ノードスイッチレスクラスタのノードをアップグレードする場合は、アップグレードの実行中もスイッチレスクラスタのノードをそのまま使用できます。スイッチクラスタに変換する必要はありません。



== スイッチ接続のクラスタ

クラスタスイッチに接続されたクラスタ内のノードをアップグレードする場合は、スイッチで実行されているmake、model、ファームウェアバージョン、RCF、およびONTAPのバージョンが、アップグレード後に交換用コントローラで実行されているバージョンと同じになることを確認する必要があります。必要に応じて、ARLを使用してコントローラをアップグレードする前にスイッチのアップグレードを実行する必要があります。

詳細については、を参照してください link:cable-node1-for-shared-cluster-HA-storage.html#connect-switch-attached-cluster["スイッチ接続クラスタへの接続"]。



== トラブルシューティングを行う

ノードペアのアップグレード中に障害が発生する可能性があります。ノードがクラッシュする、アグリゲートが再配置されない、または LIF が移行されない可能性があります。障害の原因とその解決策は、アップグレード手順の実行中に障害が発生したタイミングによって異なります。

問題が発生した場合は、詳細情報および可能な解決策について、手順の最後にあるlink:aggregate-relocation-failures.html["トラブルシューティングを行う"]セクションを参照してください。発生する可能性のある障害に関する情報は、link:overview-of-the-arl-upgrade.html["ARLアップグレードシーケンス"]の手順のフェーズごとにリストされています。

発生した問題の解決策が見つからない場合は、テクニカル サポートにお問い合わせください。

.次の手順
コントローラーのアップグレードに関するガイドラインを確認した後、link:overview-of-the-arl-upgrade.html["ARLアップグレードシーケンスについて学ぶ"]。
