---
sidebar: sidebar 
permalink: upgrade-arl-auto-in-chassis/guidelines-for-upgrading-controllers-with-arl.html 
keywords: guidelines, upgrade, ontap, controllers, old, system, chassis, disk, disks 
summary: アップグレード構成にARLを使用できるかどうかを確認します。古いシステムシャーシとディスクはそのまま使用できます。 
---
= コントローラのアップグレードに関するガイドラインを参照してください
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
アグリゲートの再配置（ARL）を使用して古いシステムシャーシとディスクを維持できるかどうかを理解するには、システムのアップグレード構成とONTAPのバージョンによって異なります。



== ARL のアップグレードがサポートされます

特定のシステム構成では、コントローラのアップグレードがサポートされます。参照link:decide_to_use_the_aggregate_relocation_guide.html#supported-systems["サポートされているシステムアップグレードの組み合わせ"]サポートされているシステムと最小 ONTAP バージョンのリストについては、こちらをご覧ください。

新しいシャーシを含む完全なシステムとして新しいAFF A30、AFF A150 A50、AFF A70、AFF、AFF、AFF A900、AFF A90 C30、AFF C60、AFF C80、FAS2820、またはFAS9500を受け取った場合は、「system controller replace」コマンドを参照して、link:other_references.html["参考資料"]ONTAP 9.8以降を実行しているコントローラハードウェアをアップグレードしてください_。

ARL を使用したコントローラのアップグレードは、 SnapLock Enterprise ボリュームおよび SnapLock Compliance ボリュームが設定されたシステムでサポートされます。



== 2 ノードスイッチレスクラスタ

2 ノードスイッチレスクラスタのノードをアップグレードする場合は、アップグレードの実行中もスイッチレスクラスタのノードをそのまま使用できます。スイッチクラスタに変換する必要はありません。



== スイッチ接続のクラスタ

クラスタスイッチに接続されたクラスタ内のノードをアップグレードする場合は、スイッチで実行されているmake、model、ファームウェアバージョン、RCF、およびONTAPのバージョンが、アップグレード後に交換用コントローラで実行されているバージョンと同じになることを確認する必要があります。必要に応じて、ARLを使用してコントローラをアップグレードする前にスイッチのアップグレードを実行する必要があります。

詳細については、を参照してください link:cable-node1-for-shared-cluster-HA-storage.html#connect-switch-attached-cluster["スイッチ接続クラスタへの接続"]。



== トラブルシューティングを行う

ノードペアのアップグレード中に障害が発生する可能性があります。ノードがクラッシュする、アグリゲートが再配置されない、または LIF が移行されない可能性があります。障害の原因とその解決策は、アップグレード手順の実行中に障害が発生したタイミングによって異なります。

問題が発生した場合は、 link:aggregate_relocation_failures.html["トラブルシューティングを行う"]詳細情報と可能な解決策については、手順の最後にあるセクションをご覧ください。発生する可能性のある障害に関する情報は、手順のフェーズごとに記載されています。 link:overview_of_the_arl_upgrade.html["ARLアップグレードシーケンス"] 。

発生した問題の解決策が見つからない場合は、テクニカル サポートにお問い合わせください。
