---
sidebar: sidebar 
permalink: upgrade-arl-auto-in-chassis/index.html 
keywords: aggregate, relocation, controller, hardware, aggregates, metrocluster, terminology, old, system, chassis, disk, disks 
summary: コントローラハードウェアをアップグレードするには、古いシステムを交換用システムに変換し、古いシステムのシャーシとディスクを残します。 
---
= ARLアップグレード手順について学ぶ
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
コントローラハードウェアをアップグレードするには、アグリゲート再配置（ARL）の方法がいくつか存在します。この手順では、既存のシステムシャーシとディスクを維持しながら、既存のシステムを交換用システムに変換することで、HAペアのストレージコントローラをアップグレードする方法について説明します。

ARLは、HA構成とクラスタインターコネクト通信を利用します。これにより、ルート以外のアグリゲートが同じクラスタ内のストレージを共有している場合に、その所有権を別のノードに移動できます。

手順の実行中に、交換用コントローラハードウェアを使用して元のコントローラハードウェアをアップグレードし、ルート以外のアグリゲートの所有権を切り替えます。ルート以外のアグリゲートを古いコントローラノード間で移行します。交換用ノードを設置したら、ルート以外のアグリゲートを古いコントローラノードから交換用コントローラノードに移行します。アップグレードするノードでホストされているデータには、アップグレード手順の実行中にアクセスできます。処理を続行する前に、クラスタ内のノード間でデータ LIF を移行することもできます。

交換するコントローラハードウェアは、既存のシステムモデルタイプによって異なります。

[cols="30,70"]
|===
| 既存のシステム | 作業 


| AFF A250、AFF C250 | 2台のAFF A250またはAFF C250コントローラを新しいコントローラおよびI/Oモジュールと交換します。 


| AFF A800、AFF C800 | 2台のAFF A800またはAFF C800コントローラを新しいコントローラおよびI/Oモジュールと交換します。 


| AFF A220、AFF A200、AFF C190、FAS2620、またはFAS2720 | 古いコントローラの各ノードのコントローラモジュールを新しいモジュールと交換します。 


| AFF A700またはFAS9000 | 古いコントローラの各ノードのコントローラモジュールとNVRAMモジュールを新しいモジュールと交換します。*注*：I/Oカード、データケーブル、ディスクシェルフ、およびディスクを移動、切断、再接続する必要はありません。 
|===

NOTE: このドキュメントでは、ノード名の参照としてのみ * node1 * と * node2 * という用語が使用されています。この手順を実行する場合は、ノードの実際の名前に置き換える必要があります。



== 要件および制限事項

アップグレード手順を開始する前に、重要な要素を考慮する必要があります。


NOTE: アップグレード手順を開始する前に、以下の重要な情報をすべて確認する必要があります。

* この手順は複雑で、 ONTAP の高度な管理スキルがあることを前提としています。また、以下の内容を読んで理解する必要があります。 link:guidelines_for_upgrading_controllers_with_arl.html["コントローラーのアップグレードに関するガイドライン"]そしてlink:overview_of_the_arl_upgrade.html["ARLアップグレードシーケンス"]アップグレードを開始する前に。
* この手順は、交換用コントローラハードウェアが新しく購入されていて、他のシステムで使用されていないことを前提としています。使用済みのコントローラを「 wipeconfig 」コマンドで準備するために必要な手順は、この手順には含まれていません。交換用コントローラハードウェアが以前に別の ONTAP クラスタまたはスタンドアロンのシングルノードシステムとして使用されていた場合は、テクニカルサポートにお問い合わせください。
* この手順を使用して、ノードが 3 つ以上あるクラスタのコントローラハードウェアをアップグレードできますが、クラスタ内の HA ペアごとに手順を個別に実行する必要があります。
* ONTAPのバージョンでサポートされていないスイッチおよびアップグレード先の交換用システムがある場合は、を参照してください link:other_references.html["参考資料"] Hardware Universe にリンクするには、次の手順を実行します。
* AFF A250およびAFF C250システムは、クラスタインターコネクトに10/25GbEオンボードポートを使用します。AFFA250またはAFF C250システムの2ノードスイッチレスクラスタをAFF A50、AFF A30、AFF C60、またはAFF C30システムにアップグレードするには、両ノードのスロット1にX60132A 4ポート10/25GbEカードを使用する必要があります。これにより、クラスタLIF用のクラスタインターコネクトが、ターゲットプラットフォーム上の一時ポートに提供されます。
* AFF A30、AFF A50、AFF A70、AFF A90、AFF A1K、AFF C30、AFF C60、AFF C80、FAS70、およびFAS90システムは、クラスタ接続とHA接続の両方で100GbEネットワークポートを共有します。これらのシステムでは、従来のクラスタスイッチとの10GbEまたは25GbEクラスタ接続をサポートできますが、NetApp 10GbEおよび25GbEスイッチが不要になった場合は、100GbEクラスタ速度に更新することを推奨します。詳細については、次のナレッジベースの記事を参照してください。
+
--
** link:https://kb.netapp.com/on-prem/ontap/OHW/OHW-KBs/How_to_configure_10G_or_25G_cluster_ports_on_a_new_cluster_setup["新しいクラスタセットアップで10Gまたは25Gのクラスタポートを設定する方法"^]
** link:https://kb.netapp.com/on-prem/ontap/OHW/OHW-KBs/How_to_convert_existing_10G_or_25G_cluster_ports_to_40G_or_100G_cluster_ports["既存の10Gまたは25Gのクラスタポートを40Gまたは100Gのクラスタポートに変換する方法"^]


--
+
既存のノードのクラスタポートe0aまたはe0bを新しいノードのクラスタポートにリンクできない場合は、次の詳細を参照してください。

+
** link:https://mysupport.netapp.com/site/bugs-online/product/ONTAP/JiraNgage/CONTAP-166978["NetApp Bugs OnlineのバグIDCONTAP-166978"^]
** https://mysupport.netapp.com/site/bugs-online/product/ONTAP/BURT/1127315["NetApp Bugs OnlineのバグID1127315"^]


* ASA A900、AFF A900、およびFAS9500システムは、ハイライン電源（200V~240V）のみをサポートします。AFF A700またはFAS9000システムをローライン電源（100~120V）で実行している場合、この手順 を使用する前に、AFF A700またはFAS9000の入力電源を変換する必要があります。
* ダウンタイムを含む既存のシステムからアップグレードする場合は、link:decide_to_use_the_aggregate_relocation_guide.html#supported-systems-in-chassis["サポートされるシステムマトリックス"]ストレージを移動してコントローラ ハードウェアをアップグレードするか、テクニカル サポートにお問い合わせください。参照link:other_references.html["参考資料"]_ボリュームまたはストレージの移動によるアップグレード_にリンクします。




== コントローラのアップグレードプロセスを自動化する

この手順には、手順を自動化するための手順が用意されています。この手順では、自動ディスク割り当てとネットワークポートの到達可能性チェックを使用して、コントローラのアップグレードを簡易化します。
