---
sidebar: sidebar 
permalink: upgrade-arl-auto-in-chassis/move-non-root-aggr-nas-lifs-node1-from-node2-to-upgraded-node1.html 
keywords: moving, non-root, aggregates, nas, lif, node1, node2 
summary: ARLを使用して同じシャーシ内のコントローラモデルをアップグレードする場合、ノード2のノード1のNASデータLIFがノード2からノード1に再配置されたことを確認します。 
---
= ノード1のルート以外のアグリゲートとNASデータLIFをノード2からアップグレード後のノード1に移動します。
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
ノード 1 のネットワーク構成を確認した後、ノード 1 が所有する NAS データ LIF をノード 2 からノード 1 に再配置し、SAN LIF がノード 1 に存在することを確認する必要があります。

.このタスクについて
リモート LIF は、アップグレード手順中に SAN LUN へのトラフィックを処理します。アップグレード中のクラスタまたはサービスの健全性のために、SAN LIF を移動する必要はありません。SAN LIF は、新しいポートにマッピングする必要がある場合を除き、移動されません。

node1 をオンラインにした後、LIF が正常であり、正しいポートに配置されていることを確認します。

.手順
. 再配置処理を再開します。
+
[source, cli]
----
system controller replace resume
----
+
システムは次のタスクを実行します。

+
--
** クラスタクォーラムチェック
** システム ID の確認
** イメージのバージョンチェック
** ターゲットプラットフォームのチェック
** ネットワーク到達可能性チェック


--
+
システムはネットワーク到達可能性チェックのこの段階で操作を一時停止します。

. ネットワーク到達可能性チェックを実行します。
+
[source, cli]
----
network port reachability show -node node1
----
+
インターフェイスグループポートおよび VLAN ポートを含むすべての接続ポートのステータスが「 OK 」であることを確認します。

. 次のアップグレードでは、FCP SAN LIFを再割り当てする必要があります。
+
[cols="35,65"]
|===
| 既存のシステム | 交換用システム 


| AFF A250用 | AFF A30、AFF A50 


| AFF C250用 | AFF C30、AFF C60 


| AFF A800用 | AFF A70、AFF A90 


| AFF C800用 | AFF C80用 
|===
+
その他のすべてのシステムのアップグレードについては、に進みます<<resume_relocation_step4,手順 4>>。

+
.. FCPまたはFC-NVMeデータアクセスに使用するFCP SAN LIFを正しいホームポートに再割り当てします。
+
[source, cli]
----
network interface show -vserver <vserver_hosting_fcp_lifs>
----
.. 現在のノードがアップグレード後のノード1であり、現在のポートが「status oper」になっているLIFについては（ポートはAFF A800ノードに存在していたがAFF A90ノードには存在しないため）、現在のポートをオンラインにする前に変更します。
+
FC LIFを移動する必要があるFCターゲットポートへの物理的な接続が確立されていることを確認します。

+
--
... LIF のステータスを「 down 」に設定します。
+
[source, cli]
----
network interface modify -vserver <vserver_name> -lif <lif_name>  -status-admin down
----
... LIFのホームポートを変更します。
+
[source, cli]
----
network interface modify -vserver <vserver_name> -lif <lif_name> - home-node <node1> -home-port <FC_target_port>
----
... LIFのステータスを「up」に設定します。
+
[source, cli]
----
network interface modify -vserver <vserver> -lif <lif_name>  -status-admin up
----


--
+
node1のホームにあるFC SAN LIFごとに手順aとbを繰り返します。



. [[resume_relocation_step4]]再配置操作を再開します
+
[source, cli]
----
system controller replace resume
----
+
システムは次のチェックを実行します。

+
--
** クラスタの健全性チェック
** クラスタ LIF のステータスを確認します


--
+
これらのチェックの実行後、システムは、 node1 で所有されているルート以外のアグリゲートと NAS データ LIF を新しい node1 に再配置します。

+
リソースの再配置が完了すると、コントローラの交換処理が一時停止します。

. アグリゲートの再配置処理と NAS データ LIF の移動処理のステータスを確認します。
+
[source, cli]
----
system controller replace show-details
----
+
コントローラ交換用手順が一時停止している場合は、エラーがある場合はチェックして修正し、次に「問題 re sume 」をクリックして操作を続行します。

. 必要に応じて、移動された LIF を復元して元に戻すか、または node1 への自動再配置に失敗した node1 LIF を手動で移行して変更します。
+
[role="tabbed-block"]
====
.移動したLIFを復元して元に戻す
--
.. 移動した LIF をリストします。
+
[source, cli]
----
cluster controller-replacement network displaced-interface show
----
.. LIF が表示されなくなった場合は、ホームノードをノード 1 にリストアします。
+
[source, cli]
----
cluster controller-replacement network displaced-interface restore-home-node -node <node1_nodename> -vserver <vserver name> -lif-name <lif_name>
----


--
.LIFを手動で移行および変更する
--
.. 自動的に再配置できなかった LIF をノード 1 に移行します。
+
[source, cli]
----
network interface migrate -vserver <vserver name> -lif <lif_name> -destination-node <node1_nodename> -destination-port <port_on_node1>
----
.. 移行された LIF のホーム ノードとホーム ポートを変更します。
+
[source, cli]
----
network interface modify -vserver <vserver_name> -lif <data_lif_name> -home-node <node1_nodename> -home-port <home_port>
----


--
====
. この処理を再開すると、必要なポストチェックの実行をシステムに求めるプロンプトが表示されます。
+
[source, cli]
----
system controller replace resume
----
+
次のポストチェックが実行されます。

+
** クラスタクォーラムチェック
** クラスタの健全性チェック
** アグリゲートの再構築チェック
** アグリゲートのステータスを確認します
** ディスクのステータスを確認します
** クラスタ LIF のステータスを確認します
** ボリュームチェック



