---
sidebar: sidebar 
permalink: upgrade-arl-auto-in-chassis/move-non-root-aggr-and-nas-data-lifs-back-to-node2.html 
keywords: moving, non-root, aggregates, nas, lif, node1, node2 
summary: ARLを使用して同じシャーシ内のコントローラモデルをアップグレードする場合、ノード1のノード2のNASデータLIFがノード1からノード2に再配置されたことを確認します。 
---
= ルート以外のアグリゲートと NAS データ LIF を node2 に戻します
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
ノード 2 のネットワーク構成を確認した後、ノード 2 が所有する NAS データ LIF をノード 1 からノード 2 に再配置し、SAN LIF がノード 2 に存在することを確認する必要があります。

.このタスクについて
リモート LIF は、アップグレード手順中に SAN LUN へのトラフィックを処理します。アップグレード中のクラスタまたはサービスの健全性のために、SAN LIF を移動する必要はありません。SAN LIF は、新しいポートにマッピングする必要がある場合を除き、移動されません。

node2 をオンラインにした後、LIF が正常であり、正しいポートに配置されていることを確認します。

.手順
. 再配置処理を再開します。
+
[source, cli]
----
system controller replace resume
----
+
システムは次のタスクを実行します。

+
--
** クラスタクォーラムチェック
** システム ID の確認
** イメージのバージョンチェック
** ターゲットプラットフォームのチェック
** ネットワーク到達可能性チェック


--
+
システムはネットワーク到達可能性チェックのこの段階で操作を一時停止します。

. 再配置処理を再開します。
+
[source, cli]
----
system controller replace resume
----
+
システムは次のチェックを実行します。

+
--
** クラスタの健全性チェック
** クラスタ LIF のステータスを確認します


--
+
これらのチェックが完了すると、ルート以外のアグリゲートとNASデータLIFが、交換用コントローラで実行中のnode2に再配置されます。

+
リソースの再配置が完了すると、コントローラの交換処理が一時停止します。

. アグリゲートの再配置処理と NAS データ LIF の移動処理のステータスを確認します。
+
[source, cli]
----
system controller replace show-details
----
+
コントローラ交換用手順が一時停止している場合は、エラーがある場合はチェックして修正し、次に「問題 re sume 」をクリックして操作を続行します。

. 必要に応じて、移動された LIF を復元して元に戻すか、node2 への自動再配置に失敗した node2 LIF を手動で移行して変更します。
+
[role="tabbed-block"]
====
.移動したLIFを復元して元に戻す
--
.. 移動した LIF をリストします。
+
[source, cli]
----
cluster controller-replacement network displaced-interface show
----
.. LIF が取り外された場合、ホームノードを node2 にリストアします。
+
[source, cli]
----
cluster controller-replacement network displaced-interface restore-home-node -node <node2_nodename> -vserver <vserver name> -lif-name <lif_name>
----


--
.LIFを手動で移行および変更する
--
.. 自動的に再配置できなかった LIF をノード 2 に移行します。
+
[source, cli]
----
network interface migrate -vserver <vserver name> -lif <lif_name> -destination-node <node2_nodename> -destination-port <port_on_node2>
----
.. 移行された LIF のホーム ノードとホーム ポートを変更します。
+
[source, cli]
----
network interface modify -vserver <vserver_name> -lif <data_lif_name> -home-node <node2_nodename> -home-port <home_port>
----


--
====
. この処理を再開すると、必要なポストチェックの実行をシステムに求めるプロンプトが表示されます。
+
[source, cli]
----
system controller replace resume
----
+
次のポストチェックが実行されます。

+
** クラスタクォーラムチェック
** クラスタの健全性チェック
** アグリゲートの再構築チェック
** アグリゲートのステータスを確認します
** ディスクのステータスを確認します
** クラスタ LIF のステータスを確認します
** ボリュームチェック



