---
sidebar: sidebar 
permalink: upgrade-arl-auto-in-chassis/move-non-root-aggr-and-nas-data-lifs-back-to-node2.html 
keywords: moving, non-root, aggregates, nas, lif, node1, node2 
summary: ARLを使用して同じシャーシ内のコントローラモデルをアップグレードする場合、ノード1のノード2のNASデータLIFがノード1からノード2に再配置されたことを確認します。 
---
= ルート以外のアグリゲートと NAS データ LIF を node2 に戻します
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
ノード2でネットワーク設定を確認し、ノード1からノード2にアグリゲートを再配置する前に、現在ノード1にあるノード2に属するNASデータLIFがノード1からノード2に再配置されていることを確認します。また、SAN LIFがノード2に存在することも確認する必要があります。

.このタスクについて
アップグレード手順の実行中、リモート LIF は SAN LUN へのトラフィックを処理します。アップグレード時にクラスタやサービスの健全性を維持するために、 SAN LIF を移動する必要はありません。SAN LIF は、新しいポートにマッピングする必要がないかぎり移動されません。node2 をオンラインにしたあと、 LIF が正常に機能しており、適切なポートに配置されていることを確認する必要があります。

.手順
. 再配置処理を再開します。
+
「システムコントローラの交換が再開」

+
システムは次のタスクを実行します。

+
--
** クラスタクォーラムチェック
** システム ID の確認
** イメージのバージョンチェック
** ターゲットプラットフォームのチェック
** ネットワーク到達可能性チェック


--
+
ネットワーク到達可能性チェックのこの段階で処理が一時停止します。

. 再配置処理を再開します。
+
「システムコントローラの交換が再開」

+
システムは次のチェックを実行します。

+
--
** クラスタの健全性チェック
** クラスタ LIF のステータスを確認します


--
+
これらのチェックが完了すると、ルート以外のアグリゲートとNASデータLIFが、交換用コントローラで実行中のnode2に再配置されます。

+
リソースの再配置が完了すると、コントローラの交換処理が一時停止します。

. アグリゲートの再配置処理と NAS データ LIF の移動処理のステータスを確認します。
+
「 system controller replace show-sdetails 」というエラーが表示されます

+
コントローラ交換用手順が一時停止している場合は、エラーがある場合はチェックして修正し、次に「問題 re sume 」をクリックして操作を続行します。

. 必要に応じて、取り外した LIF をリストアしてリバートします。取り外した LIF を表示します。
+
cluster controller -replacement network ヒエラー（クラスタコントローラ交換ネットワークが取り外されました） -interface show

+
LIF が取り外された場合、ホームノードを node2 にリストアします。

+
クラスタ・コントローラ交換ネットワークが取り外されましたインタフェース・リストア -home-node

. この処理を再開すると、必要なポストチェックの実行をシステムに求めるプロンプトが表示されます。
+
「システムコントローラの交換が再開」

+
次のポストチェックが実行されます。

+
** クラスタクォーラムチェック
** クラスタの健全性チェック
** アグリゲートの再構築チェック
** アグリゲートのステータスを確認します
** ディスクのステータスを確認します
** クラスタ LIF のステータスを確認します
** ボリュームチェック



