---
sidebar: sidebar 
permalink: upgrade-arl-auto-in-chassis/verify-node2-installation.html 
keywords: verifying, verify, node, install, installation, NVRAM, controller, module, modules 
summary: ARLを使用して同じシャーシ内のコントローラモデルをアップグレードする場合は、ノード2のインストールと交換用モジュールを確認します。 
---
= node2 のインストールを確認します
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
ノード2のインストールと交換用システムモジュールを確認する必要があります。物理ポートは変更されないため、古いnode2の物理ポートを交換するnode2にマッピングする必要はありません。

.このタスクについて
交換用システムモジュールでノード1をブートしたら、正しく取り付けられていることを確認します。node2 がクォーラムに参加するまで待ってから、コントローラの交換処理を再開する必要があります。

手順のこの時点で、 node2 がクォーラムに参加する間、処理が一時停止します。

.手順
. node2 がクォーラムに参加していることを確認します
+
cluster show -node node2 -fields health`

+
「 health 」フィールドの出力は「 true 」でなければなりません。

. この手順は以下のアップグレード構成に適用されます。その他のシステムアップグレードの場合は、この手順をスキップして<<verify-node2-step3,手順 3>> ：
+
** 2ノードのスイッチレスクラスタ
** スイッチ接続された AFF A250 または AFF C250 システムを AFF A50、AFF A30、AFF C30、または AFF C60 システムにアップグレードします。


+
--
node2 が自動的にクォーラムに参加しない場合:

.. ポート e1a と e1b の IPspace を確認します。
+
「 network port show 」のように表示されます

.. IPspace が「Cluster」でない場合は、e1a と e1b の IPspace を「Cluster」に変更します。
+
`network port modify -node <node_name> -port <port> -ipspace Cluster`

.. ポート e1a と e1b の IPspace が「Cluster」であることを確認します。
+
「 network port show 」のように表示されます

.. ノード2のクラスタLIFをe1aとe1bに移行します。
+
`network interface migrate -vserver Cluster -lif <cluster_lif1> -destination-node <node2_name> -destination-port <port_name`



--
. [[verify-node2-step3]]node2 と node1 が同じクラスターの一部であり、クラスターが正常であることを確認します。
+
「 cluster show 」を参照してください

. advanced 権限モードに切り替えます。
+
「高度」

. この手順は、AFF A250またはAFF C250からAFF A50、AFF A30、AFF C60、またはAFF C30への2ノードスイッチレス構成のアップグレードにのみ適用されます。その他のシステムアップグレードの場合は、この手順をスキップして、 <<verify-node2-step6,手順 6>> ：
+
e4a、e2a、e1a、e1b ポートまたは e4a、e4b、e1a、e1b ポートが「クラスター」ブロードキャスト ドメイン内のクラスター ポートであることを確認します。

+
AFF A50、AFF A30、AFF C30、およびAFF C60システムは、クラスタポートとHAポートを共有します。ノード1とノード2のすべてのクラスタLIFをe4a、e4b、またはe4a、e2aに安全に移行できます

+
.. すべてのクラスタ LIF のホーム ポートと現在のポートを一覧表示します。
+
`network interface show -role Cluster -fields home-port,curr-port`

.. [[migrate-cluster-lif-step-4b]]ノード1とノード2で、e1aをホームポートとして使用しているクラスタLIFをe4aに移行します。
+
`network interface migrate -vserver Cluster -lif <cluster_lif1> -destination-node <node> -destination-port e4a`

.. ノード1とノード2で、移行したクラスタLIFを変更します。 <<migrate-cluster-lif-step-4b,サブステップb>> e4a をホームポートとして使用するには:
+
`network  interface modify -vserver Cluster -lif <cluster_lif> -home-port e4a`

.. クラスターがクォーラム内にあることを確認します。
+
「 cluster show 」を参照してください

.. 繰り返す<<migrate-cluster-lif-step-4b,サブステップbとサブステップc>>各ノードの 2 番目のクラスタ LIF を e2a または e4b に移行して変更するには、次のようにします。
+
e2aが存在し、100GbEネットワークポートである場合、これがデフォルトの2番目のクラスタポートになります。e2aが100GbEネットワークポートでない場合、ONTAPはe4bを2番目のクラスタポートおよびHAポートとして使用します。

.. 「クラスター」ブロードキャスト ドメインから e1a と e1b を削除します。
+
`broadcast-domain remove-ports -broadcast-domain Cluster -ipspace Cluster -ports <node_name>:e1a`

.. クラスタポートe4a、e2a、またはe4a、e4bのみが「クラスタ」ブロードキャストドメインにあることを確認します。
+
`broadcast domain show`

.. 有効なクラスター HA 接続のみが使用され、冗長接続がないことを確認するために、e1a ノード 1 と e1a ノード 2、および e1b ノード 1 と e1b ノード 2 間のケーブル接続を削除します。


. [[verify-node2-step6]]コントローラー交換操作のステータスを確認し、一時停止状態であり、新しいコントローラーのインストールとケーブルの移動という物理的なタスクを実行するためにノード2が停止される前と同じ状態であることを確認します。
+
「 system controller replace show 」と表示されます

+
「 system controller replace show-sdetails 」というエラーが表示されます

. コントローラの交換処理を再開します。
+
「システムコントローラの交換が再開」

. コントローラの交換処理が一時停止し、次のメッセージが表示されます。
+
[listing]
----
Cluster::*> system controller replace show
Node          Status                       Error-Action
------------  ------------------------     ------------------------------------
Node2         Paused-for-intervention      Follow the instructions given in
                                           Step Details
Node1         None

Step Details:
--------------------------------------------
To complete the Network Reachability task, the ONTAP network configuration must be manually adjusted to match the new physical network configuration of the hardware. This includes:


1. Re-create the interface group, if needed, before restoring VLANs. For detailed commands and instructions, refer to the "Re-creating VLANs, ifgrps, and broadcast domains" section of the upgrade controller hardware guide for the ONTAP version running on the new controllers.
2. Run the command "cluster controller-replacement network displaced-vlans show" to check if any VLAN is displaced.
3. If any VLAN is displaced, run the command "cluster controller-replacement network displaced-vlans restore" to restore the VLAN on the desired port.
2 entries were displayed.
----
+

NOTE: この手順 では、 VLAN 、 ifgrp 、およびブロードキャストドメインのセクションの再作成が、 node2 で _ ネットワーク設定の名前が _Restore に変更されています。

. コントローラの交換が一時停止状態になった状態で、に進みます <<node2 でネットワーク設定をリストアします>>。




== node2 でネットワーク設定をリストアします

node2 がクォーラムにあり、 node1 と通信できることを確認したら、 node1 の VLAN 、インターフェイスグループ、およびブロードキャストドメインが node2 に表示されていることを確認します。また、 node2 のすべてのネットワークポートが正しいブロードキャストドメインに設定されていることを確認します。

.このタスクについて
VLAN 、インターフェイスグループ、およびブロードキャストドメインの作成と再作成の詳細については、を参照してください link:other_references.html["参考資料"] をクリックして、 _Network Management_content にリンクします。

.手順
. アップグレードした node2 上のすべての物理ポートを表示します。
+
network port show -node node2`

+
ノードのすべての物理ネットワークポート、 VLAN ポート、およびインターフェイスグループポートが表示されます。この出力から、 ONTAP によって「 Cluster 」ブロードキャストドメインに移動された物理ポートを確認できます。この出力を使用して、インターフェイスグループメンバーポート、 VLAN ベースポート、または LIF をホストするスタンドアロンの物理ポートとして使用するポートを決定できます。

. クラスタのブロードキャストドメインの一覧を表示します。
+
「 network port broadcast-domain show 」

. node2 のすべてのポートの到達可能性を表示します。
+
network port reachability show -node node2`

+
次の例のような出力が表示されます。ポート名とブロードキャスト名はさまざまです。

+
[listing]
----
Cluster::> reachability show -node node1
  (network port reachability show)
Node      Port     Expected Reachability                Reachability Status
--------- -------- ------------------------------------ ---------------------
Node1
          a0a      Default:Default                      ok
          a0a-822  Default:822                          ok
          a0a-823  Default:823                          ok
          e0M      Default:Mgmt                         ok
          e1a      Cluster:Cluster                      ok
          e1b      -                                    no-reachability
          e2a      -                                    no-reachability
          e2b      -                                    no-reachability
          e3a      -                                    no-reachability
          e3b      -                                    no-reachability
          e7a      Cluster:Cluster                      ok
          e7b      -                                    no-reachability
          e9a      Default:Default                      ok
          e9a-822  Default:822                          ok
          e9a-823  Default:823                          ok
          e9b      Default:Default                      ok
          e9b-822  Default:822                          ok
          e9b-823  Default:823                          ok
          e9c      Default:Default                      ok
          e9d      Default:Default                      ok
20 entries were displayed.
----
+
上記の例では、コントローラの交換後に node2 がブートし、クォーラムに参加しています。到達可能性のない複数のポートがあり、到達可能性スキャンを保留しています。

. [[restore_node2 _step4] 次のコマンドを使用して、 node2 の各ポートの到達可能性を「 ok 」以外の到達可能性ステータスで修復します。
+
'network port reachability repair-Node_node_name -- port_port_port_name_`

+
--
.. 物理ポート
.. VLAN ポート


--
+
次の例のような出力が表示されます。

+
[listing]
----
Cluster ::> reachability repair -node node2 -port e9d
----
+
[listing]
----
Warning: Repairing port "node2:e9d" may cause it to move into a different broadcast domain, which can cause LIFs to be re-homed away from the port. Are you sure you want to continue? {y|n}:
----
+
上記の例に示すように、ポートの到達可能性ステータスが、現在配置されているブロードキャストドメインの到達可能性ステータスと異なる場合があることを示す警告メッセージが表示されます。ポートと回答 'y' または 'n' の接続を適宜確認します

+
すべての物理ポートに想定される到達可能性があることを確認します。

+
「 network port reachability show 」のように表示されます

+
到達可能性の修復が実行されると、 ONTAP は正しいブロードキャストドメインにポートを配置しようとします。ただし、ポートの到達可能性を判別できず、既存のどのブロードキャストドメインにも属していない場合、 ONTAP はこれらのポート用に新しいブロードキャストドメインを作成します。

. ポートの到達可能性を確認します
+
「 network port reachability show 」のように表示されます

+
すべてのポートが正しく設定され、正しいブロードキャストドメインに追加されている場合、「 network port reachability show 」コマンドは、接続されているすべてのポートの到達可能性ステータスを「 ok 」、物理的に接続されていないポートのステータスを「 no-reachability 」と報告する必要があります。この 2 つ以外のステータスが報告されたポートがある場合は、到達可能性修復を実行し、の手順に従ってブロードキャストドメインにポートを追加または削除します <<restore_node2_step4,手順 4>>。

. すべてのポートがブロードキャストドメインに配置されたことを確認します。
+
「 network port show 」のように表示されます

. ブロードキャストドメインのすべてのポートで、正しい Maximum Transmission Unit （ MTU ；最大伝送ユニット）が設定されていることを確認します。
+
「 network port broadcast-domain show 」

. 次の手順に従って、リストアが必要な SVM および LIF のホームポートがある場合は、それらを指定して LIF のホームポートをリストアします。
+
.. 移動された LIF を表示します。
+
「 dispaced-interface show 」

.. LIF のホームノードとホームポートをリストアします。
+
「変位インターフェイスのリストア-home-node-node-node_node_name _- vserver_vserver_name _-lif - name_lif_name_name_」のように指定します



. すべての LIF にホームポートがあり、意図的に稼働状態になっていることを確認します。
+
network interface show -fields home-port 、 status-admin


