---
permalink: upgrade/migrate-fas2820-aggregates-epsilon-lifs.html 
sidebar: sidebar 
keywords: fas2820, ndu, nondisruptive, upgrade, node1, node4, migrate, aggregates, lifs 
summary: 'ノード 1 のデータ アグリゲート、イプシロン、および論理インターフェイス (LIF) をノード 4 に移行します。' 
---
= FAS2820ノード1上のデータアグリゲート、イプシロン、LIFをノード4に移行する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
FAS2820ノード 1 上のデータ アグリゲート、イプシロン、および論理インターフェイス (LIF) をノード 4 に移行します。

.このタスクについて
ノード4 で次の手順を実行します。

.手順
. node4 の LOADER プロンプトで、パートナー システム ID を設定します。
+
[source, cli]
----
setenv partner-sysid <system_ID_of_node1>
----
. パートナーのシステム ID を確認します。
+
[source, cli]
----
printenv partner-sysid
----
. 変更を保存します。
+
[source, cli]
----
saveenv
----
. ノードをブートメニューでブートします。
+
[source, cli]
----
boot_ontap menu
----
. ブートメニューでオプションを選択 `6 Update flash from backup config`/var ファイル システムを node4 に復元します。
+
これにより、オールフラッシュベースの構成がディスクへの最後のバックアップに置き換えられます。

. 「 y 」と入力して続行します。
+
[NOTE]
====
ノードが自動的にリブートし、/varファイルシステムの新しいコピーがロードされます。

ノードからシステムIDの不一致の警告が報告されました。入力するコマンド `y` システムIDを上書きします。

====
. クラスタLIFを移行します。
+
[source, cli]
----
set -privilege advanced
----
+
[source, cli]
----
network port show
----
+
[NOTE]
====
FAS2820 を交換用コントローラにアップグレードするときにシステム クラスタ ポートが類似していない場合は、ノード 4 のインターフェイスを一時的にクラスタ ポートに変更する必要がある場合があります。

[source, cli]
----
network port modify -node <node4> -port <port_name> -mtu 9000 -ipspace Cluster
----
====
+
[source, cli]
----
network interface migrate -vserver Cluster -lif <cluster_LIF>  -destination-node <node4> -destination-port <port_name>
----
. クラスターがクォーラムに達するまで待機し、クラスター ノードが正常であることを確認します。
+
[source, cli]
----
– cluster show
----
+

NOTE: 現在の状態では、HAペアとストレージフェイルオーバーは無効のままです。

. クラスタLIFをノード4の一時的な25Gクラスタポートに移動します。
+
[source, cli]
----
network interface modify -vserver Cluster -lif <cluster_LIF> -home-node <node4> -home-port <port_name>
----
. アップグレードするFAS2820クラスタでインターフェイス グループとデータ VLAN が使用されている場合にのみ、この手順を完了してください。それ以外の場合は、<<migrate_node1_nod4,手順 11>> 。
+
交換用コントローラーの物理ネットワーク ポート名は、 FAS2820のものとは異なります。これにより、VLAN が置き換えられ、ノード 4 上のインターフェース グループが誤って構成される可能性があります。

+
.. 置き換えられた VLAN を表示します。
+
[source, cli]
----
cluster controller-replacement network displaced-vlans show
----
.. 置き換えられた VLAN を復元します。
+
[source, cli]
----
cluster controller-replacement network displaced-vlans restore
----
.. 誤って構成されたインターフェース グループを修正します。 FAS2820とアップグレードするコントローラー間のポート名は異なる場合があります。正しいメンバー ポートを使用してインターフェイス グループを更新します。
+
[source, cli]
----
ifgrp remove-port -node <node2> -ifgrp <ifgrp_name> -port <port_name>
----
+
[source, cli]
----
ifgrp add-port -node <node2> -ifgrp <ifgrp_name> -port <port_name>
----




[[migrate_node1_nod4]]
. ノード1のデータアグリゲートをノード4に移行します。
+
[source, cli]
----
storage aggregate relocation start -aggregate-list <aggregate_list_name> -node <node1> -destination <node4> -ndo-controller-upgrade true -override-destination-checks true
----
. データ集計ステータスを表示します:
+
[source, cli]
----
storage aggregate show
----
. イプシロンを node1 から削除し、node4 に移動して移行します。
+
.. ノード1からイプシロンを削除します。
+
[source, cli]
----
cluster modify -epsilon false -node <node1>
----
.. イプシロンをノード4に移動します。
+
[source, cli]
----
cluster modify -epsilon true -node <node4>
----


. クラスターのステータスを表示して、イプシロンの変更を確認します。
+
[source, cli]
----
cluster show
----
. すべてのデータネットワークLIFを表示します。
+
[source, cli]
----
network interface show -role data
----
. すべてのデータLIFをノード4に移行します。
+
[source, cli]
----
network interface migrate -vserver <vserver_name> -lif <lif_name> -destination-node <node4> -destination-port <port_name>
----
. クラスタ内のすべてのデータLIFのステータスを表示します。
+
[source, cli]
----
network interface show -role data
----
. LIFがダウンしている場合は、その管理ステータスを `up`各 LIF に対して次のコマンドを 1 回入力します。
+
[source, cli]
----
network interface modify -vserver <vserver_name> -lif <lif_name> -status-admin up
----
. クラスタ管理LIFを移行します。
+
[source, cli]
----
network interface migrate -vserver <vserver_name> -lif <cluster_mgmt_lif> -destination-node <node4> -destination-port <port_name>
----
. クラスタ管理LIFのステータスを表示します。
+
[source, cli]
----
network interface show -role cluster-mgmt
----
. ノード 1 を停止します。
+
[source, cli]
----
halt -node <node1> -inhibit-takeover true -ignore-quorum-warnings true
----


.次の手順
link:convert-fas2820-node1-drive-shelf.html["node1をドライブシェルフに変換し、node3に接続します"]
