---
permalink: upgrade/upgrade-decide-to-use-this-guide.html 
sidebar: sidebar 
keywords:  
summary: このコンテンツでは、ストレージまたはボリュームを移動することで、クラスタ内の AFF システムまたは FAS システムのコントローラハードウェアをアップグレードする方法について説明します。 
---
= ボリュームまたはストレージを移動してアップグレードするかどうかを決定します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
このコンテンツでは、ストレージまたはボリュームを移動してクラスタ内のAFF、FAS、またはASAシステムのコントローラハードウェアをアップグレードする方法について説明します。

この手順 は、次の状況でコントローラハードウェアをアップグレードする場合に使用します。


NOTE: ONTAP 9.8 では、自動ポート配置機能が導入され、ハードウェアのアップグレード手順が簡略化されています。

* 元のノードと新しいノードに互換性があり、サポートされている。
* 元のノードと新しいノードでONTAP 9.0以降が実行されている。可能な場合は、元のノードと新しいノードで同じバージョンのONTAPを実行することをNetAppで推奨します。
+
コントローラのアップグレードに複数のONTAPバージョンが混在する場合は、を参照してください。 https://docs.netapp.com/us-en/ontap/upgrade/concept_mixed_version_requirements.html["バージョンが混在したONTAPクラスタ"^] を参照してください。

* 元のノードの IP アドレス、ネットワークマスク、およびゲートウェイを新しいノードで再利用する。
* ストレージまたはボリュームを移動することで、コントローラハードウェアをアップグレードすることを計画している。
* ストレージを移動してアップグレードする場合は、停止を伴う手順を実行する準備ができている。
+
ボリュームの移動によるアップグレードは無停止で実行できます。

* サポート対象モデルのノードをディスクシェルフに変換し、新しいノードに接続することを計画している。


MetroCluster構成をアップグレードする場合は、を参照してください。 https://docs.netapp.com/us-en/ontap-metrocluster/upgrade/concept_choosing_an_upgrade_method_mcc.html["MetroCluster 構成をアップグレード、更新、または拡張します"^]。

.関連情報
* xref:upgrade-considerations.adoc[コントローラハードウェアのアップグレードに関する考慮事項]
* link:../choose_controller_upgrade_procedure.html["コントローラハードウェアをアップグレードする方法を選択します"]
* https://docs.netapp.com/us-en/ontap-metrocluster/maintain/concept_where_to_find_procedures_for_mcc_maintenance_tasks.html["MetroCluster のメンテナンスタスクの手順の参照先"^]
* https://hwu.netapp.com["NetApp Hardware Universe の略"^]

