---
permalink: upgrade/upgrade_migrate_aggregates_epsilon_lifs_node1_to_node4.html 
sidebar: sidebar 
keywords: ndu, nondisruptive, upgrade, node1, node4, migrate, aggregates, lifs 
summary: ノード1のデータアグリゲート、イプシロン、およびLIFをノード4に移行します。 
---
= ノード1のデータアグリゲート、イプシロン、およびLIFをノード4に移行します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
AFF A250 node1をドライブシェルフに変換する前に、node1のデータアグリゲート、イプシロン、および論理インターフェイス（LIF）をAFF A400 node4に移行します。

.手順
. ノード4のLOADERプロンプトで、ノードをブートメニューでブートします。
+
「 boot_ontap menu

. オプションを選択します `6 Update flash from backup config` /varファイルシステムをnode4にリストアします。
+
これにより、オールフラッシュベースの構成がディスクへの最後のバックアップに置き換えられます。

. 「 y 」と入力して続行します。
+
[NOTE]
====
ノードが自動的にリブートし、/varファイルシステムの新しいコピーがロードされます。

ノードからシステムIDの不一致の警告が報告されました。入力するコマンド `y` システムIDを上書きします。

====
. クラスタLIFを移行します。
+
「 advanced 」の権限が必要です

+
「 network port show 」のように表示されます

+
[NOTE]
====
AFF A250をAFF A400にアップグレードするときにシステムクラスタポートが異なる場合は、ノード4のインターフェイスを一時的にクラスタポートに変更しなければならないことがあります。

`network port modify -node _node4_ -port _port_name_ -mtu 9000 -ipspace Cluster`

====
+
`network interface migrate -vserver Cluster -lif _cluster_LIF_  -destination-node _node4_ -destination-port _port_name_`

. クラスタがクォーラムに参加するまで待ってから、クラスタノードが正常であることを確認します。
+
`– cluster show`

+

NOTE: 現在の状態では、HAペアとストレージフェイルオーバーは無効のままです。

. クラスタLIFをノード4の一時的な25Gクラスタポートに移動します。
+
`network interface modify`

. アップグレードするAFF A250クラスタでインターフェイスグループとデータVLANが使用されている場合は、この手順を実行します。そうでない場合は、に進みます <<migrate_node1_nod4,手順 8>>。
+
AFF A250システムとAFF A400システムでは、物理ネットワークポート名が異なります。そのため、ノード4でインターフェイスグループが正しく設定されておらず、VLANが削除される可能性があります。正しく設定されていないインターフェイスグループと削除されたVLANを確認し、必要に応じて修正します。



[[migrate_node1_nod4]]
. ノード1のデータアグリゲートをノード4に移行します。
+
`storage aggregate relocation start -aggregate-list _aggregate_list_name_ -node _node1_ -destination _node4_ -ndo-controller-upgrade true -override-destination-checks true`

. クラスタ内のすべてのデータアグリゲートのステータスを表示します。
+
`storage aggregate show`

. イプシロンを移行するには、ノード1からIFを削除し、ノード4に移動します。
+
.. ノード1からイプシロンを削除します。
+
`cluster modify -epsilon false -node _node1_`

.. イプシロンをノード4に移動します。
+
`cluster modify -epsilon true -node _node4_`



. クラスタのステータスを表示します。
+
「 cluster show 」を参照してください

. すべてのデータネットワークLIFを表示します。
+
`network interface show -role data`

. すべてのデータLIFをノード4に移行します。
+
`network interface migrate -vserver _vserver_name_ -lif _lif_name_ -destination-node _node4_ -destination-port _port_name_`

. クラスタ内のすべてのデータLIFのステータスを表示します。
+
`network interface show -role data`

. LIF が 1 つでも停止している場合は、次のコマンドを LIF ごとに 1 回入力して、 LIF の管理ステータスを「 up 」に設定します。
+
「network interface modify -vserver vserver_name __-lif LIF_name -status-admin up

. クラスタ管理LIFを移行します。
+
`network interface migrate -vserver _vserver_name_ -lif cluster_mgmt -destination-node _node4_ -destination-port _port_name_`

. クラスタ管理LIFのステータスを表示します。
+
`network interface show cluster_mgmt`

. ノード 1 を停止します。
+
`halt -node _node1_ -inhibit-takeover true -ignore-quorum-warnings true`



.次の手順
link:upgrade_convert_node1_drive_shelf_connect_node3.html["node1をドライブシェルフに変換し、node3に接続します"]
