---
permalink: upgrade/upgrade-restore-root-volume-config.html 
sidebar: sidebar 
keywords: Controller Hardware Upgrade Express Guide 
summary: ルートボリュームからブートデバイスに構成情報をリストアする必要があります。 
---
= ルートボリューム構成をリストア
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ルートボリュームからブートデバイスに構成情報をリストアする必要があります。


NOTE: FAS8300、AFF A400、FAS8700のように、ポート「e0a」と「e0b」をハイアベイラビリティ（HA）インターコネクトポートとして使用するシステムにコントローラをインプレースアップグレードする場合、 を確認します link:upgrade-prepare-when-moving-storage.html#assign_lifs["管理LIFまたはクラスタ間LIFを再割り当てしました"] アップグレード手順 を開始する前に、元のシステムのポート「e0a」と「e0b」で設定します。

.このタスクについて
これらの手順は、 node3 と node4 で実行する必要があります。まず一方のノードでそれぞれの手順を完了してから、次の手順に進みます。

.手順
. LOADER プロンプトからブートメニューにアクセスします。
+
「 boot_ontap menu

. ブート・メニューから '(6) Update flash from backup config' を選択し ' 続行するかどうかを確認するメッセージが表示されたら 'y' を入力します次のいずれかを選択してください。
+
[listing]
----
(1) Normal Boot.
(2) Boot without /etc/rc.
(3) Change password.
(4) Clean configuration and initialize all disks.
(5) Maintenance mode boot.
(6) Update flash from backup config.
(7) Install new software first.
(8) Reboot node.
(9) Configure Advanced Drive Partitioning.
Selection (1-9)? 6
Controller Hardware Upgrade Express Guide 19
Upgrading controller hardware by moving storage
This will replace all flash-based configuration with the last backup to disks. Are you sure you want to continue?: y
----
+
フラッシュの更新プロセスが数分間実行され、システムがリブートします。

. システム ID の不一致を確認するプロンプトが表示されたら、「 y 」と入力します。
+
[listing]
----
WARNING: System id mismatch. This usually occurs when replacing CF or NVRAM cards!
Override system id? {y|n} [n] y
----
+
起動シーケンスは正常に実行されます。



コントローラのアップグレードに失敗し、「rlib_port_ipspace _assign」というエラーメッセージが表示された場合は、交換用システムでHAポートとして使用されている元のシステムのネットワークポートのLIFをリバートして削除する必要があります。詳細については、を参照してください link:https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Systems/FAS_Systems/PANIC_%3A_rlib_port_ipspace_assign%3A_port_e0a_could_not_be_moved_to_HA_ipspace["こちらの技術情報アーティクル"^]。
