---
permalink: upgrade/upgrade_considerations_move_san_lifs.html 
sidebar: sidebar 
keywords: cluster, san, environment, lif, original, node, unjoin, original, move san lifs 
summary: SAN LIF の移動が必要になるのは、クラスタの内容を変更する場合だけです。 
---
= SAN LIF の移動に関する考慮事項
:icons: font
:imagesdir: ../media/


[role="lead"]
クラスタにノードを追加したりクラスタからノードを削除するなど、クラスタの構成を変更する場合は、 SAN LIF を移動するだけで済みます。LIF を移動した場合、 FC ファブリックを再ゾーニングしたり、クラスタに接続されたホストとその新しいターゲットインターフェイスとの間に新しい iSCSI セッションを作成したりする必要はありません。

SAN LIF を移動するには、「 network interface modify 」コマンドを使用します。SAN LIF を移動するには、 LIF をオフラインにし、別のホームノードやポートに移動してから、移動先の新しい場所で LIF をオンラインに戻す必要があります。Asymmetric Logical Unit Access （ ALUA ；非対称論理ユニットアクセス）は、任意の ONTAP 解決策の一部として冗長パスと自動選択を提供します。このため、移動時に LIF がオフラインになっても、 I/O の中断は生じません。ホストは再試行してから、 I/O を別の LIF に移動するだけです。

LIF の移動中は、システムを停止することなく次のタスクを実行できます。

* クラスタの 1 つの HA ペアを、 LUN データにアクセスするホストにはまったく支障のない形で、アップグレードした HA ペアに置き換えます
* ターゲットインターフェイスカードをアップグレードします
* Storage Virtual Machine （ SVM ）のリソースをクラスタ内のノードセットから同じクラスタ内の別のノードセットに移行する
* ホストサーバがオンラインのときに、ホストサーバによる LUN データへのアクセスを中断することなく、 SAN LUN を新しい HA ペアに移動できます


詳細については、を参照してください https://docs.netapp.com/us-en/ontap/san-admin/move-san-lifs-task.html["SAN LIF の移動"^] SAN ストレージ管理に関するドキュメントの手順
