---
permalink: upgrade/upgrade_reassign_drives_node2_to_node4.html 
sidebar: sidebar 
keywords: ndu, nondisruptive, upgrade, node2, node4, reassign, drives 
summary: ノード2からノード4にドライブを再割り当てする前に、ノード2をノード4に物理的に接続します。 
---
= ドライブをノード2からノード4に再割り当てします
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
AFF A250 node2をNS224ドライブシェルフに変換してAFF A400 node4に接続したら、node2に属していたドライブをnode4に再割り当てする必要があります。

.作業を開始する前に
ノード3とノード4の両方でLOADERプロンプトがスタンバイになっていることを確認します。

.このタスクについて
ノード4で次の手順を実行します。

.手順
. LOADERプロンプトで、ノード4をメンテナンスモードでブートします。
+
「 boot_ontap maint 」を使用してください

. 100GbEインターフェイスの状態を表示します。
+
`storage port show`

. 100GbEインターフェイスをストレージポートに設定します。
+
`storage port modify -p e0c -m storage`

+
`storage port modify -p e0d -m storage`

. 100GbEインターフェイスのモードが変更されたことを確認します。
+
`storage port show`

+
次の例のような出力が表示されます。

+
[listing]
----
*> storage port modify -p e0c -m storage
Nov 10 16:27:23 [localhost:nvmeof.port.modify:notice]: Changing NVMe-oF port e0c to storage mode.

Nov 10 16:27:29 [localhost:nvmeof.subsystem.add:notice]: NVMe-oF subsystem added at address fe80::2a0:98ff:fefa:8885.

*> storage port modify -p e0d -m storage
Nov 10 16:27:34 [localhost:nvmeof.port.modify:notice]: Changing NVMe-oF port e0d to storage mode.

Nov 10 16:27:38 [localhost:nvmeof.subsystem.add:notice]: NVMe-oF subsystem added at address fe80::2a0:98ff:fefa:8886.

*> storage port show
Port Type Mode    Speed(Gb/s) State    Status  VLAN ID
---- ---- ------- ----------- -------- ------- -------
e0c  ENET storage 100 Gb/s    enabled  online  30
e0d  ENET storage 100 Gb/s    enabled  offline 30
----
. すべての接続ドライブを表示します。
+
「ディスクショー V 」

. ローカルシステムIDの値を記録します。これはノード4のシステムIDです。また、「owner」列でノード1とノード2のシステムIDを記録します。
. すべてのドライブをノード2からノード4に再割り当てします。
+
`disk reassign -s _node2_system_ID_ -d _node4_system_ID_ -p _node1_system_ID_`

. 再割り当てしたすべてのドライブが新しいシステムIDで表示されることを確認します。
+
`disk show -s _node4_System_ID_`

+

NOTE: ドライブが表示されない場合は、*停止*し、テクニカルサポートにお問い合わせください。

. node2のルートアグリゲートがの出力に報告され、アグリゲートがオンラインになっていることを確認します。
+
「 aggr status 」を入力します

. メンテナンスモードを終了します。
+
「 halt 」



.次の手順
link:upgrade_migrate_aggregates_epsilon_lifs_node1_to_node4.html["ノード1のデータアグリゲート、イプシロン、およびLIFをノード4に移行します"]
