---
permalink: upgrade/upgrade-map-network-ports-ontap-9-7-or-earlier.html 
sidebar: sidebar 
keywords: enable, node3, node4, node, communicate, cluster, network, upgrade, physical, port, configure, setting, intend, data, map, map network ports using ontap 9.7 or earlier 
summary: アップグレード後に node3 と node4 がクラスタ内およびネットワークと相互に通信できるようにするには、物理ポートがクラスタやデータなどの目的の用途に応じた設定で正しく設定されていることを確認する必要があります。 
---
= ONTAP 9.7 以前を使用してネットワークポートをマッピングします
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
アップグレード後に node3 と node4 がクラスタ内およびネットワークと相互に通信できるようにするには、物理ポートがクラスタやデータなどの目的の用途に応じた設定で正しく設定されていることを確認する必要があります。

.作業を開始する前に
以下の手順は、 ONTAP 9.7 以前を実行するシステムに該当します。ONTAP 9.8以降を実行している場合は、の手順 を使用する必要があります link:upgrade-map-network-ports-ontap-9-8.html["ONTAP 9.8以降を使用してネットワークポートをマッピングします"]。

.このタスクについて
これらの手順は、 node3 と node4 で実行する必要があります。


NOTE: 次のコマンド例では、「 node1 」と呼んでいます。この段階で手順の交換用ノード「 node3 」と「 node4 」の名前は実際には「 node1 」と「 node2 」です。

.手順
. ONTAP 9.8以降を実行しているシステムの場合は、* STOP *をクリックします。の手順を使用する必要があります link:upgrade-map-network-ports-ontap-9-8.html["ONTAP 9.8以降を使用してネットワークポートをマッピングします"]。
. storage_, の移動時のアップグレードの準備でメモしておいたノード 1 とノード 2 のポートと LIF の設定情報を確認します。 link:upgrade-prepare-when-moving-storage.html#prepare_move_store_3["手順 3"]。
. storage_ 、 link:upgrade-prepare-when-moving-storage.html#prepare_move_store_3["手順 3"]。
+
https://hwu.netapp.com["NetApp Hardware Universe の略"^]

. 次の変更を行います。
+
.. node3 と node4 をクラスタプロンプトでブートしていない場合は、それらをブートします。
.. 「 Cluster 」ブロードキャストドメインに正しいポートを追加します。
+
「network port modify -node _node_name --port_port_name_-mtu 9000 -ipspace Cluster」

+
次の例では 'Cluster ポート e1b を node1 に追加します

+
network port modify -node node1 -port e1b -ipspace Cluster -mtu 9000`

.. LIF を 1 つずつ新しいポートに移行します。
+
「network interface migrate -vserver_vserver_name __ lif_lif_name_-source-node node1 -destination-node node1 -destination-port_name_`

+
SAN データ LIF は、オフラインの場合にのみ移行できます。

.. クラスタ LIF のホームポートを変更します。
+
「network interface modify -vserver Cluster -lif LIF_name–home-port_port_name_`」です

.. クラスタブロードキャストドメインから古いポートを削除します。
+
「network port broadcast-domain remove-ports -ipspace Cluster -broadcast-domain Cluster -ports_node1：port_」のようになります

.. node3 と node4 の健全性状態を表示します。
+
'cluster show -node-node1_-fields health`

.. 各クラスタ LIF がポート 7700 をリスンしている必要があります。クラスタ LIF がポート 7700 をリスンしていることを確認します。
+
`::> network connections listening show -vserver Cluster `

+
次の 2 ノードクラスタの例に示すように、クラスタポートでリスンしているポート 7700 は想定される結果です。

+
[listing]
----
Cluster::> network connections listening show -vserver Cluster
Vserver Name     Interface Name:Local Port     Protocol/Service
---------------- ----------------------------  -------------------
Node: NodeA
Cluster          NodeA_clus1:7700               TCP/ctlopcp
Cluster          NodeA_clus2:7700               TCP/ctlopcp
Node: NodeB
Cluster          NodeB_clus1:7700               TCP/ctlopcp
Cluster          NodeB_clus2:7700               TCP/ctlopcp
4 entries were displayed.
----
.. ポート7700をリスンしていない各クラスタLIFについて、LIFの管理ステータスをに設定します。 `down` 次に `up`：
+
`::> net int modify -vserver Cluster-lif cluster_lif_cluster-status-admin down；net int modify -vserver Cluster-lif cluster_lif_-status-admin up

+
手順（ g ）を繰り返して、クラスタ LIF がポート 7700 でリスンしていることを確認します。



. 新しいコントローラの物理ポート・レイアウトに合わせて、 VLAN および「 ifgrp config 」を変更します。
. node3 と node4 に存在しなくなった node1 ポートと node2 ポートを削除します（ advanced 権限レベル）。
+
'network port delete -node1_-port_port_name_`

. [[map_97_7] ノード管理ブロードキャストドメインを調整し、必要に応じてノード管理 LIF とクラスタ管理 LIF を移行します。
+
.. LIF のホームポートを表示します。
+
network interface show -fields home-node 、 home-port

.. ポートを含むブロードキャストドメインを表示します。
+
「network port broadcast-domain show -ports_node_name：port_name_`

.. 必要に応じて、ブロードキャストドメインにポートを追加またはドメインから削除します。
+
「 network port broadcast-domain add-ports 」と入力します

+
「 network port broadcast-domain remove-ports 」と入力します

.. 必要に応じて LIF のホームポートを変更します。
+
「network interface modify -vserver _vserver_name __ lif_lif_name_–home-port_port_name_`



. 必要に応じて、のコマンドを使用して、クラスタ間ブロードキャストドメインを調整し、クラスタ間 LIF を移行します <<map_97_7,手順 7>>。
. 必要に応じて、のコマンドを使用して、他のブロードキャストドメインを調整してデータ LIF を移行します <<map_97_7,手順 7>>。
. すべての LIF フェイルオーバーグループを調整します。
+
'network interface modify -failover-group_failover_group'-failover-policy_failover_policy_`

+
次のコマンドは、フェイルオーバーポリシーを broadcast-domain-wide に設定し、フェイルオーバーグループ「 fg1 」のポートを「 node1 」の LIF 「 data1 」のフェイルオーバーターゲットとして使用します。

+
「 network interface modify -vserver node1 -lif data1 -failover-policy broadcast-domain-wide -failover-group fg1 」というメッセージが表示されます

. ノード 3 とノード 4 のネットワークポートの属性を表示します。
+
network port show -node node1



.完了後
これで物理ポートのマッピングが完了しました。アップグレードを完了するには、に進みます link:upgrade-final-steps-ontap-9-7-or-earlier-move-storage.html["ONTAP 9.7 以前で最終アップグレード手順を実行します"]。
