---
permalink: upgrade/upgrade_migrate_lifs_aggregates_node2_to_node1.html 
sidebar: sidebar 
keywords: ndu, nondisruptive, upgrade, node1, node2, migrate, aggregates, lifs 
summary: ノード2の論理インターフェイス（LIF）とデータアグリゲートをノード1に移行します。 
---
= ノード2のLIFとデータアグリゲートをノード1に移行します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
AFF A250 node2をドライブシェルフに変換する前に、node2の論理インターフェイス（LIF）とデータアグリゲートをnode1に移行します。

.作業を開始する前に
次の要件を満たしていることを確認します。

* AFF A250コントローラとAFF A400コントローラでは、同じONTAPリリースおよびパッチバージョンが実行されます。
+
[NOTE]
====
** 各AFF A400に、AFF A250で実行されているバージョンと同じバージョンのONTAPをネットブートしてインストールする必要があります。
** 各AFF A400のプライマリブートイメージとバックアップブートイメージのONTAPバージョンが同じである必要があります。
** AFF A400クラスタが以前に設定されていた場合は、を実行して残りのクラスタ構成をクリアする必要があります `wipeconfig` ブートメニューから選択します。


====
* 両方のAFF A400コントローラがLOADERプロンプトでスタンバイになっています。
* 適切なケーブル配線をすべて用意しておきます。


.このタスクについて
次の手順は、AFF A250 node1で実行します。

.手順
. advanced 権限レベルに切り替えます。
+
「 advanced 」の権限が必要です

. ストレージフェイルオーバーの自動ギブバックを無効にします。
+
`storage failover modify -node _node1_ -auto-giveback false`

. HAペアの両方のノードでLIFの自動リバートを無効にします。
+
`network interface modify -lif * -auto-revert false`

. すべてのデータネットワークLIFのステータスを表示します。
+
`network interface show -role data`

. クラスタ管理LIFのステータスを表示します。
+
`network interface show -role cluster_mgmt`

. ノード2でホストされているStorage Virtual MachineからすべてのデータLIFを移行します。
+
`network interface migrate -vserver _vserver_name_ -lif _lif_name_ -destination-node _node1_ -destination-port _port_name_`

+

NOTE: このコマンドは、SAN以外のLIFのみを移行します。iSCSI LIFとFCP LIFの移行には使用できません。

. クラスタ内のすべてのデータLIFのステータスを表示します。
+
`network interface show -role data`

. LIF が 1 つでも停止している場合は、次のコマンドを LIF ごとに 1 回入力して、 LIF の管理ステータスを「 up 」に設定します。
+
「network interface modify -vserver vserver_name __-lif LIF_name -status-admin up

. クラスタ内のすべてのデータアグリゲートのステータスを表示します。
+
`storage aggregate show`

. フェールオーバー適格性を表示します。
+
「 storage failover show 」をクリックします

. ノード2のデータアグリゲートをノード1に移行します。
+
`storage aggregate relocation start -aggregate _aggregate_name_ -node _node2_ -destination _node1_`

. クラスタ内のすべてのデータアグリゲートのステータスを表示します。
+
`storage aggregate show`

. クラスタ内のすべてのデータボリュームのステータスを表示します。
+
volume show

. を表示します `ha` イプシロンのステータスと所有権：
+
「 cluster show 」を参照してください

. 無効にします `cluster ha`：
+
cluster ha modify -configured false

. を表示します `ha` イプシロンのステータスと所有権：
+
「 cluster show 」を参照してください

. ノード 2 を停止します。
+
`halt -node _node2_ -inhibit-takeover true -ignore-quorum-warnings true`



.次の手順
link:upgrade_convert_node2_drive_shelf_connect_node4.html["node2をドライブシェルフに変換し、node4に接続します"]
