---
permalink: upgrade/upgrade-convert-node-to-shelf.html 
sidebar: sidebar 
keywords: node, support, model, process, upgrading, upgrade, moving, move, convert, drive, shelf, attach, convert an original node to a drive shelf 
summary: 元のノードがサポート対象のモデルである場合、ストレージを移動してアップグレードする処理中に、ノードをドライブシェルフに変換し、同じクラスタ内の新しいノードに接続できます。 
---
= 元のノードをドライブシェルフに変換します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
元のノードがサポート対象のモデルである場合、ストレージを移動してアップグレードする処理中に、ノードをドライブシェルフに変換し、同じクラスタ内の新しいノードに接続できます。

.作業を開始する前に
を確認しておく必要があります link:upgrade-considerations.html["コントローラハードウェアのアップグレードに関する考慮事項"] ノードのドライブシェルフへの変換について説明しています。ご使用の構成に固有のガイダンスが必要な場合は、テクニカルサポートにお問い合わせください。

.手順
. 変換するノードのコントローラモジュールを適切な IOM モジュールと交換します。
+
https://hwu.netapp.com["NetApp Hardware Universe の略"^]

. ドライブシェルフ ID を設定します。
+
シャーシを含む各ドライブシェルフには、一意の ID が必要です。

. 必要に応じて、他のドライブシェルフ ID をリセットします。
. 新しいノードに接続されているドライブシェルフの電源をオフにしてから、新しいノードの電源をオフにします。
. 変換したドライブシェルフを新しいシステムの SAS ポートに接続し、アウトオブバンド ACP ケーブルを使用している場合は新しいノードの ACP ポートに接続します。
. 変換したドライブシェルフおよび新しいノードに接続されているその他のドライブシェルフの電源をオンにします。
. 新しいノードの電源をオンにしてから、各ノードで Ctrl+C キーを押してブートプロセスを中断し、ブート環境プロンプトにアクセスします。

