---
permalink: upgrade/upgrade-attach-shelves-reassign-disks.html 
sidebar: sidebar 
keywords: reassign, disk, belong, node1, node2, node3, node4, node, attach, storage, shelves, shelf, reassign, ownership, attach storage shelves reassign disk ownership 
summary: ノード 1 とノード 2 に属していたディスクを、それぞれノード 3 とノード 4 に再割り当てする必要があります。 
---
= ストレージシェルフを接続し、ディスク所有権を再割り当てします
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ノード 1 とノード 2 に属していたディスクを、それぞれノード 3 とノード 4 に再割り当てする必要があります。

.このタスクについて
このセクションの手順は、node3とnode4で実行します。次のステップに進む前に、node3、次にnode4で各ステップを完了してください。

[[reassign-spare-disks-step1]]
.手順
. 以前に接続されていたシェルフからストレージシェルフケーブルを接続します。
+
** node1のケーブルをnode3に接続します。
** node2のケーブルをnode4に接続します。
+

CAUTION: このアップグレード手順中は、node3またはnode4に新しいディスク シェルフを接続しないでください。コントローラーのアップグレードが完了したら、システムに新しいディスク シェルフを無停止で接続できます。



. 電源装置とシェルフの物理的な接続を確認します。
. node3 の LOADER プロンプトから、メンテナンスモードでブートします。
+
「 boot_ontap maint 」を使用してください

. node3 のシステム ID を表示します。
+
「ディスクショー V 」

+
[listing]
----
*> disk show -v
Local System ID: 101268854
...
----
+
node3のシステムIDを記録して、<<reassign-disks-and-aggregates,手順 5>>で使用します。

. [[reassign-disks-and-aggregates]]ディスクとデータアグリゲートを再割り当てします：
+
[role="tabbed-block"]
====
.ノード3に再割り当て
--
node1の予備ディスク、ルートアグリゲートに属するディスク、およびすべてのデータアグリゲートをnode3に再割り当てします：

`disk reassign -s <node1_sysid> -d <node3_sysid> -p <node4_sysid>`

** パラメータ `node1_sysid`は、_元のノードのシャットダウン_で記録した値です。link:upgrade-shutdown-remove-original-nodes.html#shutdown_node_step5["手順 5"]。
** パラメータ `-p <node2_sysid>`は、共有ディスクが存在する場合にのみ指定してください。


--
.node4に再割り当て
--
node2の予備ディスク、ルートアグリゲートに属するディスク、およびすべてのデータアグリゲートをnode4に再割り当てします：

`disk reassign -s <node2_sysid> -d <node4_sysid> -p <node3_sysid>`

** パラメータ `node2_sysid`は、「元のノードのシャットダウン」で記録した値です。link:upgrade-shutdown-remove-original-nodes.html#shutdown_node_step5["手順 5"]。
** パラメータ `-p <node3_sysid>`は、共有ディスクが存在する場合にのみ指定してください。


--
====
+
次のようなメッセージが表示されます。

+
[listing]
----
Partner node must not be in Takeover mode during disk reassignment from maintenance mode.
Serious problems could result!!
Do not proceed with reassignment if the partner is in takeover mode. Abort reassignment (y/n)?n

After the node becomes operational, you must perform a takeover and giveback of the HA partner node to ensure disk reassignment is successful.
Do you want to continue (y/n)?y
----
. 「 y 」と入力して続行します。
+
次のようなメッセージが表示されます。

+
[listing]
----
The system displays the following message:
Disk ownership will be updated on all disks previously belonging to Filer with sysid
<sysid>.
Do you want to continue (y/n)? y
----
. 「 y 」と入力して続行します。
. options フィールドで node1 のルートアグリゲートが「 root 」に設定され、他のアグリゲートがオンラインであることを確認します。
+
「 aggr status 」を入力します

+
次のような出力が表示されます。

+
[listing]
----
*> aggr status
           Aggr State           Status                Options
          aggr0 online          raid_dp, aggr         root
                                64-bit
----
. [[reassign-spare-disks-step9]]メンテナンスモードを終了します：
+
「 halt 」

. node4 で<<reassign-spare-disks-step1,手順 1.>>から<<reassign-spare-disks-step9,手順 9>>を繰り返します。


.次の手順
ストレージシェルフを取り付け、ディスクの所有権を再割り当てした後、link:upgrade-restore-root-volume-config.html["ルートボリューム構成を復元する"]。
