---
permalink: upgrade/upgrade_move_delete_recreate_san_lifs.html 
sidebar: sidebar 
keywords: cluster, san, environment, delete, lif, re-create, move san lifs, create 
summary: クラスタの内容とクラスタ環境に応じて、 SAN LIF を移動、削除、または作成するか、削除した SAN LIF を再作成する必要があります。 
---
= SAN LIFの移動、削除、または作成
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
クラスタの内容とクラスタ環境に応じて、 SAN LIF を移動、削除、または作成するか、削除した SAN LIF を再作成する必要があります。



== SAN LIF の移動に関する考慮事項

クラスタにノードを追加したりクラスタからノードを削除するなど、クラスタの構成を変更する場合は、 SAN LIF を移動するだけで済みます。LIF を移動した場合、 FC ファブリックを再ゾーニングしたり、クラスタに接続されたホストとその新しいターゲットインターフェイスとの間に新しい iSCSI セッションを作成したりする必要はありません。

SAN LIF を移動するには、「 network interface modify 」コマンドを使用します。SAN LIF を移動するには、 LIF をオフラインにし、別のホームノードやポートに移動してから、移動先の新しい場所で LIF をオンラインに戻す必要があります。Asymmetric Logical Unit Access （ ALUA ；非対称論理ユニットアクセス）は、任意の ONTAP 解決策の一部として冗長パスと自動選択を提供します。このため、移動時に LIF がオフラインになっても、 I/O の中断は生じません。ホストは再試行してから、 I/O を別の LIF に移動するだけです。

LIF の移動中は、システムを停止することなく次のタスクを実行できます。

* クラスタの 1 つの HA ペアを、 LUN データにアクセスするホストにはまったく支障のない形で、アップグレードした HA ペアに置き換えます
* ターゲットインターフェイスカードをアップグレードします
* Storage Virtual Machine （ SVM ）のリソースをクラスタ内のノードセットから同じクラスタ内の別のノードセットに移行する
* ホストサーバがオンラインのときに、ホストサーバによる LUN データへのアクセスを中断することなく、 SAN LUN を新しい HA ペアに移動できます


詳細については、を参照してください https://docs.netapp.com/us-en/ontap/san-admin/move-san-lifs-task.html["SAN LIF の移動"^] SAN ストレージ管理に関するドキュメントの手順



== 不要になったSAN LIFを削除する

クラスタが SAN 環境にある場合は、元のノードをクラスタから削除する前に、不要になった SAN LIF を元のノードから削除する必要があります。

.手順
. iSCSI イニシエータを使用している場合は、次の手順を実行します。
+
.. 元のノードのSVMに現在接続されているアクティブなイニシエータの一覧を表示します。+`iscsi connection show -vserver _Vserver_name -lif_old_lif_`
+
次の例は、 SVM vs1 に接続されたアクティブなイニシエータを使用したコマンドの出力を示しています。

+
[listing]
----
cluster::> iscsi connection show -vserver vs1 -lif data2
          Tpgroup        Conn  Local           Remote          TCP Recv
Vserver   Name     TSIH  ID    Address         Address         Size
--------- -------- ----- ----- --------------- --------------- --------
vs1       data         9     1 10.229.226.166  10.229.136.188    131400
----
.. 元のノードにログインしているイニシエータがある場合は、ホストコンピュータからセッションをログアウトします。


. ポートセットリストを表示して、元のノードの iSCSI LIF または FC LIF がポートセットに属しているかどうかを確認します。
+
lun portset show

+
次に、「 lun portset show 」コマンドの出力例を示します。

+
[listing]
----
cluster:> lun portset show
Virtual
Server    Portset      Protocol Port Names              Igroups
--------- ------------ -------- ----------------------- ------------
js11      ps0          mixed    LIF1,                   igroup1
                                LIF2
          ps1          iscsi    LIF3                    igroup2
          ps2          fcp      LIF4                    -
3 entries were displayed.
----
. 元のノードのいずれかの iSCSI または FC LIF がポートセットのメンバーである場合は、ポートセットから削除します。
+
`lun portset remove -vserver _vserver_name -portset_portset_name __ port-name _lif_name_`

. 元のノードの LIF を削除します。
+
「network interface delete -vserver _vserver_name _-lif_lif_name_`」のように指定します





== 新しい SAN LIF を作成するか、削除した SAN LIF を再作成します

クラスタ環境の要件に応じて、この手順で削除した新しい SAN LIF を作成するか、または SAN LIF を再作成することができます。を使用して、 SAN LIF を作成または再作成できます https://docs.netapp.com/us-en/ontap-sm-classic/online-help-96-97/task_creating_network_interfaces.html["ネットワークインターフェイスが作成されます"^] OnCommand ® System Manager_documentation を使用したクラスタ管理の手順

.次の手順
link:upgrade-remove-original-nodes.html["元のノードをクラスターから削除する"]
