---
permalink: upgrade/upgrade-map-network-ports-ontap-9-8.html 
sidebar: sidebar 
keywords: enable, node3, node4, node, communicate, cluster, network, upgrade, physical, port, correct, configure, setting, data, map network ports using ontap 9.8 
summary: node3 と node4 がアップグレード後にクラスタ内およびネットワークと相互に通信できるようにするには、物理ポートがクラスタやデータなどの目的の用途に応じた設定で正しく設定されていることを確認する必要があります。 
---
= ONTAP 9.8 を使用してネットワークポートをマッピングします
:icons: font
:imagesdir: ../media/


[role="lead"]
node3 と node4 がアップグレード後にクラスタ内およびネットワークと相互に通信できるようにするには、物理ポートがクラスタやデータなどの目的の用途に応じた設定で正しく設定されていることを確認する必要があります。

これらの手順は ONTAP 9.8 を実行しているシステムに適用されます。ONTAP 9.7 以前を実行している場合は、の手順を使用する必要があります xref:upgrade-map-network-ports-ontap-9-7-or-earlier.adoc[ONTAP 9.7 以前を使用してネットワークポートをマッピングします]。

これらの手順は、 node3 と node4 で実行する必要があります。


NOTE: 次のコマンド例では、「 node1 」と呼んでいます。この段階で手順の交換用ノード「 node3 」と「 node4 」の名前は実際には「 node1 」と「 node2 」です。

.手順
. ONTAP 9.7 以前を実行しているシステムの場合は、 * stop * と入力します。の手順を使用する必要があります xref:upgrade-map-network-ports-ontap-9-7-or-earlier.adoc[ONTAP 9.7 以前を使用してネットワークポートをマッピングします]。
. storage_, の移動時のアップグレードの準備でメモしておいたノード 1 とノード 2 のポートと LIF の設定情報を確認します。 link:upgrade-prepare-when-moving-storage.html#prepare_move_store_3["手順 3"]。
. storage_ 、 link:upgrade-prepare-when-moving-storage.html#prepare_move_store_3["手順 3"]。
+
https://hwu.netapp.com["NetApp Hardware Universe の略"^]

. 次の変更を行います。
+
.. node3 と node4 にまだログインしていない場合は、ブートしてログインします。
.. クラスタブロードキャストドメインに追加するポートを変更します。
+
network port modify -node node_name -port port_name -mtu 9000 -ipspace Cluster `

+
次の例では 'node1' に 'Cluster' port e1b を追加します

+
network port modify -node node1 -port e1b -ipspace Cluster -mtu 9000`

.. LIF を 1 つずつ新しいポートに移行します。
+
「 network interface migrate -vserver vserver_name -lif lif_name -source-node node1 -destination-node node1 -destination-port port_name 」の略

+
すべてのクラスタ LIF が移行され、クラスタ通信が確立されたら、クラスタがクォーラムに参加する必要があります。

.. クラスタ LIF のホームポートを変更します。
+
「 network interface modify -vserver Cluster -lif <lif_name> – home-port <port_name> 」という形式になります

.. 'Cluster' ブロードキャスト・ドメインから古いポートを削除します
+
「 network port broadcast-domain remove-ports -ipspace Cluster -broadcast-domain Cluster -port node1 ： port 」のようになります

.. node3 と node4 の健全性状態を表示します。
+
cluster show -node node1 -fields health`

.. クラスタ LIF がポート 7700 をリスンしていることを確認します。
+
`::> network connections listening show -vserver Cluster `

+
各クラスタ LIF がポート 7700 をリスンしている必要があります。

+
次の 2 ノードクラスタの例に示すように、クラスタポートでリスンしているポート 7700 は想定される結果です。

+
[listing]
----
Cluster::> network connections listening show -vserver Cluster
Vserver Name     Interface Name:Local Port     Protocol/Service
---------------- ----------------------------  -------------------
Node: NodeA
Cluster          NodeA_clus1:7700               TCP/ctlopcp
Cluster          NodeA_clus2:7700               TCP/ctlopcp
Node: NodeB
Cluster          NodeB_clus1:7700               TCP/ctlopcp
Cluster          NodeB_clus2:7700               TCP/ctlopcp
4 entries were displayed.
----
.. 必要に応じて、ポート 7700 でリスンしていない各クラスタ LIF の管理ステータスを「 down 」に設定してから「 up 」に設定します。
+
`::> net int modify -vserver Cluster -lif <cluster-lif> -status-admin down ； net int modify -vserver Cluster -lif <cluster-lif> -status-admin up

+
手順（ g ）を繰り返して、クラスタ LIF がポート 7700 でリスンしていることを確認します。



. [[map_9.8_5] データ LIF をホストしている物理ポートのブロードキャストドメインメンバーシップを変更します。これは、に示すように、手動で実行できます link:upgrade-map-network-ports-ontap-9-7-or-earlier.html#map_9.7_7["ONTAP 9.7 以前のバージョンを使用してネットワークポートをマッピングし、手順 7 を実行します"]。推奨される方法は、 ONTAP 9.8 で導入された拡張ネットワーク到達可能性スキャンおよび修復手順を使用することです。次の手順 5 の手順（ a ）から（ g ）までを参照してください。
+
.. すべてのポートの到達可能性ステータスを表示します。
+
「 network port reachability show 」のように表示されます

.. 物理ポートと VLAN ポートの到達可能性を修復するには、各ポートで次のコマンドを 1 つずつ実行します。
+
「機能修復 - node node_name -port port_name 」

+
次のような警告が表示されます。「 y 」または「 n 」を確認し、必要に応じて入力します。

+
[listing]
----
Warning: Repairing port "node_name:port" may cause it to move into a
different broadcast domain, which can cause LIFs to be re-homed away
from the port. Are you sure you want to continue? {y|n}:
----
.. ONTAP が修復を完了できるようにするには、最後のポートで「 reachability repair 」コマンドを実行してから約 1 分待ちます。
.. クラスタのすべてのブロードキャストドメインを一覧表示します。
+
「 broadcast-domain show 」

.. 到達可能性の修復が実行されると、 ONTAP は正しいブロードキャストドメインにポートを配置しようとします。ただし、ポートの到達可能性を特定できず、既存のブロードキャストドメインに対応していない場合は、 ONTAP によってそれらのポート用の新しいブロードキャストドメインが作成されます。すべてのメンバーポートがインターフェイスグループのメンバーポートになる場合は、必要に応じて、新しく作成したブロードキャストドメインを削除できます。ブロードキャストドメインを削除する
+
'broadcast-domain delete -broadcast-domain broadcast_domain'

.. インターフェイスグループの設定を確認し、必要に応じてメンバーポートを追加または削除します。インターフェイスグループポートにメンバーポートを追加します。
+
ifgrp add-port node_name -ifgrp ifgrp_name -port port_name - ポート port_name

+
インターフェイスグループポートからメンバーポートを削除します。

+
ifgrp remove-port -node node_name -ifgrp ifgrp_name -port port_name - ポート port_name

.. 必要に応じて VLAN ポートを削除し、再作成します。VLAN ポートを削除します。
+
'vlan delete -node node_name -vlan-name vlan_port'

+
VLAN ポートを作成します。

+
'vlan create -node node_name -vlan-name vlan_port'

+

NOTE: アップグレードするシステムのネットワーク構成の複雑さによっては、手順 5 、手順（ a ）から（ g ）を繰り返して、必要に応じてすべてのポートを正しく配置する必要があります。



. システムに VLAN が設定されていない場合は、に進みます <<map_98_7,手順 7>>。VLAN が設定されている場合は、すでに存在しないポートまたは別のブロードキャストドメインに移動されたポートで設定されていたポート上で、取り外された VLAN を復元します。
+
.. 取り外された VLAN を表示します。
+
「 displaced-vlans show 」を参照してください

.. 取り外した VLAN を目的の宛先ポートに復元します。
+
「 dispaced-vlans restore -node node_name -port port_name -destination port destination_port 」という形式で指定します

.. すべての取り外された VLAN が復元されたことを確認します。
+
「 displaced-vlans show 」を参照してください

.. VLAN は、作成後約 1 分後に適切なブロードキャストドメインに自動的に配置されます。リストアした VLAN が適切なブロードキャストドメインに配置されていることを確認します。
+
「 network port reachability show 」のように表示されます



. [[map_98_7] ONTAP 9.8 以降では、ネットワークポートの到達可能性が修復手順の際にブロードキャストドメイン間でポートが移動されると、 ONTAP によって LIF のホームポートが自動的に変更されます。LIF のホームポートが別のノードに移動された場合や割り当てが解除された場合、その LIF は移動された LIF として表示されます。ホームポートがなくなった、または別のノードに再配置された、取り外した LIF のホームポートをリストアします。
+
.. ホームポートの LIF が別のノードに移動されたか、すでに存在していない可能性がある LIF を表示します。
+
「 dispaced-interface show 」

.. 各 LIF のホームポートをリストアします。
+
「 dispaced-interface restore -vserver vserver_name -lif -name lif_name 」のようになります

.. すべての LIF ホームポートがリストアされたことを確認します。
+
「 dispaced-interface show 」



+
すべてのポートが正しく設定され、正しいブロードキャストドメインに追加されている場合、 network port reachability show コマンドで、接続されているすべてのポートのプレゼンスステータスが OK と報告され、物理的な接続がないポートのステータスは no-reachability と報告される必要があります。これら 2 つ以外のステータスを報告しているポートがある場合は、に記載されているように、到達可能性を修復します <<map_98_5,手順 5>>。

. 正しいブロードキャストドメインに属するポート上ですべての LIF が意図的に稼働していることを確認します。
+
.. 管理上の理由で停止している LIF がないか確認します。
+
network interface show -vserver vserver_name -status-admin down

.. 動作上ダウンしている LIF がないか確認します。 `network interface show -vserver vserver_name -status -oper down``
.. 変更する必要がある LIF のホームポートを変更します。
+
「 network interface modify -vserver vserver_name -lif lif -home-port home_port 」のようになります

+

NOTE: iSCSI LIF の場合、ホームポートを変更するには LIF が管理上停止している必要があります。

.. ホームでない LIF をそれぞれのホームポートにリバートします。
+
「 network interface revert * 」の略





これで物理ポートのマッピングが完了しました。アップグレードを完了するには、に進みます xref:upgrade-final-upgrade-steps-in-ontap-9-8.adoc[ONTAP 9.8 で最後のアップグレード手順を実行します]。
