---
permalink: upgrade/upgrade-move-internal-drives.html 
sidebar: sidebar 
keywords: node, support, model, upgrading, upgrade, moving, move, storage, internal, sata, drive, ssd, drive, shelf, attach, cluster, transfer, sas, drive, move internal drives from an original node 
summary: 元のノードがサポート対象のモデルである場合、ストレージを移動してアップグレードする処理中に、ノードの内蔵SATAドライブ、SSD、またはSASドライブを、同じクラスタ内の新しいノードに接続されているドライブシェルフに移動できます。 
---
= 内蔵ドライブを元のノードから移動します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
元のノードがサポート対象のモデルである場合、ストレージを移動してアップグレードする処理中に、ノードの内蔵SATAドライブ、SSD、またはSASドライブを、同じクラスタ内の新しいノードに接続されているドライブシェルフに移動できます。

.作業を開始する前に
* を確認しておく必要があります link:upgrade-considerations.html["コントローラハードウェアのアップグレードに関する考慮事項"] 内蔵ドライブの移動について
+
ご使用の構成に固有のガイダンスが必要な場合は、テクニカルサポートにお問い合わせください。

* 元のノードのSATA、SSD、またはSASドライブキャリアが、新しいドライブシェルフと互換性がある必要があります。
* 互換性のあるドライブシェルフが新しいノードにすでに接続されている必要があります。
* ドライブシェルフには、元のノードのSATA、SSD、またはSASドライブキャリアを収容するための十分な空きベイが必要です。


.手順
. システムの前面からベゼルをそっと取り外します。
. [[move_int_drive_2]] ドライブキャリアの左側にあるリリースボタンを押します。
+
キャリアのカムハンドルが途中まで開き、キャリアがミッドプレーンから外れます。

. カムハンドルを完全に引き下げてミッドプレーンからキャリアを外し、キャリアをドライブシェルフからそっと引き出します。
+

NOTE: 取り外し、取り付け、持ち運びなど、ドライブを扱うときは常に両手で作業してください。ただし、キャリアの下側のむき出しになっている基板に手を置かないでください。

. カムハンドルを開いた状態で、キャリアを新しいドライブシェルフのスロットに挿入し、キャリアが停止するまでしっかりと押し込みます。
+

NOTE: キャリアを挿入するときは両手を使います。

. [[move_int_drive_5] キャリアがミッドプレーンに完全に収まり、カチッという音がして固定されるまで、カムハンドルを閉じます。
+
ハンドルは、キャリアの前面に揃うようにゆっくりと閉じる必要があります。

. 繰り返します ,手順 2 から ,手順 5 新しいシステムに移動するすべてのドライブについて確認します。

