---
sidebar: sidebar 
permalink: upgrade-arl-auto-app-9151/complete-preparation-for-upgrade.html 
keywords: ip, address, external, key, management, server, storage, encryption, upgrading, authentication 
summary: 'コマンドを使用して、ONTAP 9.15.1以降を実行するコントローラをアップグレードする場合、ストレージ暗号化の設定と管理、認証キーの管理、およびSnapMirror関係の休止を `system controller replace` 行います。' 
---
= アップグレードの準備を完了する
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
Onboard Key Manager（OKM）を使用したONTAPライセンスとStorage Encryptionの管理について学習します。必要に応じて、SnapMirror関係を休止します。



== ONTAPライセンスについて学ぶ

ONTAPライセンスの詳細については、を参照してください https://docs.netapp.com/us-en/ontap/system-admin/manage-licenses-concept.html["ライセンス管理"^]。


NOTE: ライセンスされていない機能をコントローラで使用すると、ライセンス契約に違反する可能性があります。



== オンボードキーマネージャを使用してストレージ暗号化を管理します

暗号化キーの管理には、オンボードキーマネージャ（OKM）を使用します。OKMが設定されている場合は、アップグレードを開始する前にパスフレーズとバックアップデータを記録しておく必要があります。

.手順
. クラスタ全体のパスフレーズを記録します。
+
これは、CLIまたはREST APIを使用してOKMを設定または更新したときに入力したパスフレーズです。

. パスフレーズとキーマネージャーの操作を確認してください：
+
「セキュリティキーマネージャオンボード同期」

+
プロンプトが表示されたら、前の手順で記録したクラスタ全体のOKMパスフレーズを入力します。

. 以下のコマンドの出力を確認して、cc-modeが有効になっていることを確認します：
+
`security key-manager config show`

. key-manager情報をバックアップします。
+
「 securitykey manager onboard show-backup 」を参照してください





== オプションで、SnapMirror関係を休止します

手順を続行する前に、すべての SnapMirror 関係が休止状態になっていることを確認する必要があります。休止された SnapMirror 関係は、リブート後およびフェイルオーバー後も休止状態のままです。

.手順
. デスティネーションクラスタの SnapMirror 関係のステータスを確認します。
+
「 Snapmirror show 」のように表示されます

+
[NOTE]
====
このステータスが「Transferring」の場合は、転送を中止する必要があります。snapmirror abort -destination -vserver _vserver_name _`

====
+
SnapMirror 関係の状態が「 Transferring 」でない場合は、中止は失敗します。

. クラスタ間のすべての関係を休止します。
+
`snapmirror quiesce -destination-vserver *`



.次の手順
アップグレードの準備後、link:relocate_non_root_aggr_nas_data_lifs_node1_node2.html["node1が所有する非ルートアグリゲートとNASデータLIFをnode2に再配置する"]。
