---
sidebar: sidebar 
permalink: upgrade-arl-auto-app-9151/decide_to_use_the_aggregate_relocation_guide.html 
keywords: deciding, aggregate, relocation, content, storage, controllers, administrators, ontap, ha, high, availability 
summary: 'コマンドを使用して、ONTAP 9.15.1以降を実行するコントローラをARLでアップグレードするかどうかを決定します `system controller replace` 。' 
---
= この集約再配置手順を使用するかどうかを決定します
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
コントローラハードウェアのアップグレードには、アグリゲート再配置（ARL）の方法が複数あります。このARL手順では、ONTAP 9.15.1以降で導入されたAFFおよびFASストレージシステムのHAコントローラペアを、既存のデータとディスクを維持しながら新しいコントローラにアップグレードする方法について説明します。これは複雑な手順であるため、経験豊富なONTAP管理者のみが使用してください。

この ARL 手順がコントローラ ハードウェアのアップグレードに適しているかどうかを判断するには、サポートされているアップグレードとサポートされていないアップグレードについて、次のすべての状況を確認する必要があります。



== このARL手順でサポートされているアップグレード

次の状況では、この ARL 手順を使用してノードのペアをアップグレードできます。

* ONTAP 9.15.1以降を実行している。
* 新しいコントローラを新しいHAペアとしてクラスタに追加したり、ボリューム移動手順を使用してデータを移行したりすることはありません。
* ONTAPの管理経験があり、diagnostic権限モードで作業する場合のリスクを十分に理解していること。
* ハードウェアアップグレードの組み合わせは、 <<sys_commands_9151_supported_systems,サポートされているモデルマトリックス>> 。



NOTE: この手順 では、NetApp Storage Encryption（NSE）、NetApp Volume Encryption（NVE）、およびNetApp Aggregate Encryption（NAE）を使用できます。



== このARL手順ではアップグレードはサポートされていません

次の状況では、この ARL 手順を使用してノードのペアをアップグレードすることはできません。

* 次のいずれかのアップグレードを実行しています。
+
|===
| 既存のコントローラ | 交換用コントローラ 


| AFF A250用 | AFF A50、AFF A30 


| AFF A800用 | AFF A70、AFF A90 


| AFF C250用 | AFF C30、AFF C60 


| AFF C800用 | AFF C80用 
|===
+
上記の表に記載されているアップグレードを実行するには、「to _use "system controller replace"コマンドを使用して、同じシャーシ内のコントローラモデルをアップグレードする」を参照してくださいlink:other_references.html["参考資料"]。

* MetroCluster FCまたはIP構成をアップグレードしています。MetroCluster構成をアップグレードするには、MetroClusterのアップグレードおよび拡張に関するドキュメント_へのリンクを参照してください link:other_references.html["参考資料"] 。




== サポートされているシステムアップグレードの組み合わせ

以下の表は、ONTAP 9.15.1以降で導入されたAFFおよびFASシステムにおいて、ARLを使用したサポートされているコントローラアップグレードの組み合わせを示しています。コントローラアップグレードの組み合わせがリストにない場合は、テクニカルサポートにお問い合わせください。

|===
| 既存のコントローラ | 交換用コントローラ | ONTAP以降でサポート 


| AFF A400 | AFF A50^2^ | 9.16.1 


| AFF A300 | AFF A50^2^ | 9.16.1 


| AFF A220、AFF A150 | AFF A20^2^ | 9.16.1^1^ 


| AFF C400 | AFF C60、AFF C80 | 9.16.1 


| FAS8200、FAS8300、FAS9000 | FAS70、FAS90、FAS50 | FAS70では9.15.1P3、FAS50ではFAS90 9.16.1P2 


| FAS8700 | FAS70、FAS90 | 9.15.1P3 


| FAS9500 | FAS90 | 9.15.1P3 


| AFF A300、AFF A400、AFF A700 | AFF A70 ^2^、AFF A90 ^2^、AFF A1K | 9.15.1 


| AFF A900 の略 | AFF A90 ^2^、AFF A1K | 9.15.1 
|===
^1^ AFF A20にアップグレードするには、まずコントローラモジュールをIOM12モジュールと交換して、AFF A150またはAFF A220をDS224Cシェルフに変換する必要があります。を参照して link:../upgrade/upgrade-convert-node-to-shelf.html["元のノードをドライブシェルフに変換します"]

^2^ AFF A20、AFF A50、AFF A70、およびAFF A90は、HA構成で2台のコントローラを搭載し、1台のシャーシにオンボードディスクを搭載した統合システムです。

* 内蔵ドライブを搭載したAFF A20、AFF A50、AFF A70、またはAFF A90にアップグレードする場合は、アップグレード前にこれらの内蔵ドライブの所有権を削除する必要があります。アップグレードが完了したら、AFF A20、AFF A50、AFF A70、またはAFF A90の各ノードに内蔵ドライブを割り当て、データアグリゲートの作成に使用できます。ルートアグリゲートやデータアグリゲートを内蔵ドライブに移行する必要はありません。
* 内蔵ドライブのないAFF A20、AFF A50、AFF A70、またはAFF A90にアップグレードする場合は、アップグレード完了後に内蔵ドライブを割り当てる必要はありません。




== 別のハードウェアアップグレード手順を選択する

* link:../upgrade-arl/index.html["コントローラハードウェアのアップグレードに使用できる代替ARL方法を確認します"]です。
* コントローラハードウェアを別の方法でアップグレードして、ボリュームの移動を希望する場合は、を参照してください link:other_references.html["参考資料"] をクリックして、ボリュームまたは storage _ を移動して _ Upgrade にリンクします。


.関連情報
参照link:other_references.html["参考資料"] _ONTAP 9 ドキュメント_にリンクします。
