---
sidebar: sidebar 
permalink: upgrade-arl-auto-app-9151/decide_to_use_the_aggregate_relocation_guide.html 
keywords: deciding, aggregate, relocation, content, storage, controllers, administrators, ontap, ha, high, availability 
summary: 'コマンドを使用して、ONTAP 9.15.1以降を実行するコントローラをARLでアップグレードするかどうかを決定します `system controller replace` 。' 
---
= アグリゲートの再配置手順を使用するかどうかを決定します
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
この手順では、既存のデータとディスクを残したまま、HAペアのストレージコントローラを新しいコントローラにアップグレードする方法について説明します。これは複雑な手順であり、経験豊富な管理者のみが使用する必要があります。

この手順は、次の状況で使用できます。

* ONTAP 9.15.1 以降を実行している必要があります。
* 新しいコントローラを新しいHAペアとしてクラスタに追加したり、ボリューム移動手順を使用してデータを移行したりすることはありません。
* ONTAP の管理経験があり、 diagnostic 権限モードで作業する場合のリスクが十分にあります。



NOTE: この手順 では、NetApp Storage Encryption（NSE）、NetApp Volume Encryption（NVE）、およびNetApp Aggregate Encryption（NAE）を使用できます。

次の状況では、この手順を使用できません。

* AFF A800をAFF A70またはAFF A90にアップグレードする。AFF A800のこのアップグレードを実行するには、「to _use "system controller replace"コマンドを使用して、同じシャーシ内のコントローラモデルをアップグレードする」を参照してください link:other_references.html["参考資料"] 。
* バックエンドストレージに外付けアレイを使用して、VシリーズシステムまたはFlexArray仮想化ストレージシステムをアップグレードする場合。VシリーズまたはFlexArrayシステムのアップグレードオプションについては、テクニカルサポートにお問い合わせください。
* MetroClusterのFCまたはIP構成をアップグレードする。MetroCluster構成をアップグレードするには、MetroClusterのアップグレードおよび拡張に関するドキュメント_へのリンクを参照してください link:other_references.html["参考資料"] 。


[[sys_commands_9151_supported_systems]]次の表は、コントローラのアップグレードでサポートされるモデルマトリックスを示しています。

|===
| 既存のコントローラ | 交換用コントローラ | ONTAP以降でサポート 


| FAS8200 、 FAS8300 、 FAS8700 、 FAS9000 | FAS70、FAS90 | 9.15.1P3 


| FAS9500 | FAS90 | 9.15.1P3 


| AFF A300、AFF A400、AFF A700 | AFF A70、AFF A90、AFF A1K | 9.15.1 


| AFF A900 の略 | AFF A90、AFF A1K | 9.15.1 
|===
[NOTE]
====
AFF A70とAFF A90は、1台のシャーシに2台のオンボードディスクと2台のコントローラを搭載した統合システムです。

* 内蔵ドライブを搭載したAFF A70またはAFF A90にアップグレードする場合は、アップグレード前にドライブの所有権を削除する必要があります。アップグレードが完了したら、内蔵ドライブをAFF A70ノードまたはAFF A90ノードに割り当て、データアグリゲートの作成に使用できます。ルートアグリゲートまたはデータアグリゲートを内蔵ドライブに移行する必要はありません。
* 内蔵ドライブのないAFF A70またはAFF A90にアップグレードする場合は、アップグレードの完了後に内蔵ドライブを割り当てる必要はありません。


コントローラのアップグレードモデルの組み合わせが上記の表にない場合は、テクニカルサポートにお問い合わせください。

====
コントローラハードウェアを別の方法でアップグレードして、ボリュームの移動を希望する場合は、を参照してください link:other_references.html["参考資料"] をクリックして、ボリュームまたは storage _ を移動して _ Upgrade にリンクします。

を参照してください link:other_references.html["参考資料"] から ONTAP 9 ドキュメントセンターにリンクして、 ONTAP 9 製品ドキュメントにアクセスできます。
