---
sidebar: sidebar 
permalink: upgrade-arl-auto-app-9151/decide_to_use_the_aggregate_relocation_guide.html 
keywords: deciding, aggregate, relocation, content, storage, controllers, administrators, ontap, ha, high, availability 
summary: 'コマンドを使用して、ONTAP 9.15.1以降を実行するコントローラをARLでアップグレードするかどうかを決定します `system controller replace` 。' 
---
= アグリゲートの再配置手順を使用するかどうかを決定します
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
この手順では、既存のデータとディスクを残したまま、HAペアのストレージコントローラを新しいコントローラにアップグレードする方法について説明します。これは複雑な手順であり、経験豊富な管理者のみが使用する必要があります。



== ARL のアップグレードがサポートされます

ノードのペアは、次の状況でアップグレードできます。

* ONTAP 9.15.1以降を実行している。
* 新しいコントローラを新しいHAペアとしてクラスタに追加したり、ボリューム移動手順を使用してデータを移行したりすることはありません。
* ONTAPの管理経験があり、diagnostic権限モードで作業する場合のリスクを十分に理解していること。



NOTE: この手順 では、NetApp Storage Encryption（NSE）、NetApp Volume Encryption（NVE）、およびNetApp Aggregate Encryption（NAE）を使用できます。

[[sys_commands_9151_supported_systems]]次の表は、コントローラのアップグレードでサポートされるモデルマトリックスを示しています。

|===
| 既存のコントローラ | 交換用コントローラ | ONTAP以降でサポート 


| AFF A400 | AFF A50^2^ | 9.16.1 


| AFF A300 | AFF A50^2^ | 9.16.1 


| AFF A220、AFF A150 | AFF A20^2^ | 9.16.1^1^ 


| FAS8200、FAS8300、FAS9000 | FAS70、FAS90、FAS50 | FAS70では9.15.1P3、FAS50ではFAS90 9.16.1P2 


| FAS8700 | FAS70、FAS90 | 9.15.1P3 


| FAS9500 | FAS90 | 9.15.1P3 


| AFF A300、AFF A400、AFF A700 | AFF A70 ^2^、AFF A90 ^2^、AFF A1K | 9.15.1 


| AFF A900 の略 | AFF A90 ^2^、AFF A1K | 9.15.1 
|===
^1^ AFF A20にアップグレードするには、まずコントローラモジュールをIOM12モジュールと交換して、AFF A150またはAFF A220をDS224Cシェルフに変換する必要があります。を参照して link:../upgrade/upgrade-convert-node-to-shelf.html["元のノードをドライブシェルフに変換します"]

^2^ AFF A20、AFF A50、AFF A70、およびAFF A90は、HA構成で2台のコントローラを搭載し、1台のシャーシにオンボードディスクを搭載した統合システムです。

* 内蔵ドライブを搭載したAFF A20、AFF A50、AFF A70、またはAFF A90にアップグレードする場合は、アップグレード前にこれらの内蔵ドライブの所有権を削除する必要があります。アップグレードが完了したら、AFF A20、AFF A50、AFF A70、またはAFF A90の各ノードに内蔵ドライブを割り当て、データアグリゲートの作成に使用できます。ルートアグリゲートやデータアグリゲートを内蔵ドライブに移行する必要はありません。
* 内蔵ドライブのないAFF A20、AFF A50、AFF A70、またはAFF A90にアップグレードする場合は、アップグレード完了後に内蔵ドライブを割り当てる必要はありません。


コントローラのアップグレードモデルの組み合わせが上記の表にない場合は、テクニカルサポートにお問い合わせください。



== ARL のアップグレードはサポートされていません

次の状況では、ARLを使用してアップグレードを実行できません。

* 次のいずれかのアップグレードを実行しています。
+
|===
| 既存のコントローラ | 交換用コントローラ 


| AFF A250用 | AFF A50、AFF A30 


| AFF A800用 | AFF A70、AFF A90 


| AFF C250用 | AFF C30、AFF C60 


| AFF C800用 | AFF C80用 
|===
+
上記の表に記載されているアップグレードを実行するには、「to _use "system controller replace"コマンドを使用して、同じシャーシ内のコントローラモデルをアップグレードする」を参照してくださいlink:other_references.html["参考資料"]。

* バックエンドストレージに外付けアレイを使用して、VシリーズシステムまたはFlexArray仮想化ストレージシステムをアップグレードする。VシリーズまたはFlexArrayシステムのアップグレードオプションについては、テクニカルサポートにお問い合わせください。
* MetroCluster FCまたはIP構成をアップグレードしています。MetroCluster構成をアップグレードするには、MetroClusterのアップグレードおよび拡張に関するドキュメント_へのリンクを参照してください link:other_references.html["参考資料"] 。


コントローラハードウェアを別の方法でアップグレードして、ボリュームの移動を希望する場合は、を参照してください link:other_references.html["参考資料"] をクリックして、ボリュームまたは storage _ を移動して _ Upgrade にリンクします。

.関連情報
を参照してください link:other_references.html["参考資料"] から ONTAP 9 ドキュメントセンターにリンクして、 ONTAP 9 製品ドキュメントにアクセスできます。
