---
sidebar: sidebar 
permalink: upgrade-arl-auto-app-9151/guidelines_for_upgrading_controllers_with_arl.html 
keywords: guidelines, upgrading, controllers, ARL 
summary: 'ONTAP 9.15.1以降で導入されたコントローラーに `system controller replace`コマンドを使用してアップグレードできるかどうかを確認してください。' 
---
= ARL を使用したコントローラのアップグレードに関するガイドライン
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
ARL を使用して ONTAP 9.15.1 以降で導入されたコントローラのペアにアップグレードできるかどうかは、プラットフォームと、元のコントローラおよび交換用コントローラの両方の構成によって異なります。



[[supported-upgrades-for-arl]]
== ARL のアップグレードがサポートされます

このARLの手順を使用してノードのペアをアップグレードする前に、次の要件を確認して、構成がサポートされていることを確認してください。

* 元のコントローラと交換用コントローラでARLを実行できることを確認します。
* 定義済みのすべてのアグリゲートのサイズと、元のシステムでサポートされているディスクの数を確認してください。次に、アグリゲート サイズとサポートされているディスクの数を、新しいシステムでサポートされるアグリゲート サイズおよびディスクの数と比較します。link:other-references.html["参考資料"]を参照して、この情報が掲載されている _Hardware Universe_ にリンクしてください。新しいシステムでサポートされるアグリゲート サイズおよびディスクの数は、元のシステムでサポートされるアグリゲート サイズおよびディスクの数以上である必要があります。
* クラスタ混合ルールにおいて、元のコントローラが交換された際に、新しいノードが既存のノードと共にクラスタの一部となることができるかどうかを検証します。クラスタ混合ルールの詳細については、link:other-references.html["参考資料"]を参照して _Hardware Universe_ にアクセスしてください。
* 次の構成のAFF 700などのシステムを使用している場合は、ノードごとに2つのクラスタポートにクラスタLIFを移行し、ホームポートを変更します。
* ノードごとに2つ以上のクラスタポート
* ポートe4a、e4b、e4c、e4dを作成するためのブレークアウトモードのslot4のクラスタインターコネクトカードと、ポートe4e、 e4f、e4g、およびe4h
+

NOTE: ノードごとにクラスタポートが2つ以上あるコントローラのアップグレードを実行すると、アップグレード後に新しいコントローラのクラスタLIFが失われる可能性があります。

+
詳細については、ナレッジベースの記事を参照して link:https://kb.netapp.com/on-prem/ontap/Ontap_OS/OS-KBs/How_to_delete_unwanted_or_unnecessary_cluster_LIFs["不要なクラスタLIFや不要なクラスタLIFを削除する方法"^]ください。



ARL を使用したコントローラのアップグレードは、 SnapLock Enterprise ボリュームおよび SnapLock Compliance ボリュームが設定されたシステムでサポートされます。



[[two-node-switchless-clusters]]
== 2 ノードスイッチレスクラスタ

2 ノードスイッチレスクラスタのノードをアップグレードする場合は、アップグレードの実行中もスイッチレスクラスタのノードをそのまま使用できます。スイッチクラスタに変換する必要はありません。



[[upgrades-not-supported-for-arl]]
== ARL のアップグレードはサポートされていません

元のコントローラに接続されているディスクシェルフがサポートされない交換用コントローラはアップグレードできません。

link:other-references.html["参考資料"]を参照して、ディスクサポート情報の _Hardware Universe_ にリンクしてください。

内部ドライブを搭載したエントリーレベルのコントローラーをアップグレードする場合は、link:other-references.html["参考資料"] を参照して「ボリュームまたはストレージの移動によるアップグレード」にリンクし、「ボリュームの移動による clustered Data ONTAP 実行中のノードペアのアップグレード」の手順に進んでください。



[[troubleshoot]]
== トラブルシューティングを行う

コントローラのアップグレード中に問題が発生した場合は、link:aggregate_relocation_failures.html["トラブルシューティングを行う"]詳細情報および可能な解決策については、こちらをご覧ください。

発生した問題に対する解決策 が見つからない場合は、テクニカルサポートにお問い合わせください。

.次の手順
ARLを使用してコントローラーをアップグレードするためのガイドラインを確認した後、link:overview_of_the_arl_upgrade.html["ARLアップグレードシーケンスについて学ぶ"]。
