---
sidebar: sidebar 
permalink: upgrade-arl-auto-app-9151/guidelines_for_upgrading_controllers_with_arl.html 
keywords: guidelines, upgrading, controllers, ARL 
summary: 'ONTAP 9.15.1以降を実行するコントローラをコマンドを使用してアップグレードできるかどうかを確認します。 `system controller replace`' 
---
= ARL を使用したコントローラのアップグレードに関するガイドライン
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
ONTAP 9.15.1以降を実行するコントローラのペアをARLを使用してアップグレードできるかどうかを理解するには、プラットフォームと元のコントローラと交換用コントローラの両方の構成によって異なります。



== ARL のアップグレードがサポートされます

このARLの手順を使用してノードのペアをアップグレードする前に、次の要件を確認して、構成がサポートされていることを確認してください。

* 元のコントローラと交換用コントローラでARLを実行できることを確認します。
* 定義済みのすべてのアグリゲートのサイズと、元のシステムでサポートされているディスク数を確認します。次に、サポートされるアグリゲートのサイズとディスク数を、新しいシステムでサポートされるアグリゲートのサイズとディスク数と比較します。この情報が利用可能な_ Hardware Universe _へのリンクについては、を参照して link:other_references.html["参考資料"] ください。新しいシステムでサポートされるアグリゲートサイズとディスク数は、元のシステムでサポートされるアグリゲートサイズとディスク数以上であることが必要です。
* 元のコントローラを交換したときに、クラスタに新しいノードが既存のノードと一緒にクラスタに追加できるかどうかを混在ルールで検証します。クラスタ混在ルールの詳細については、_ Hardware Universe _へのリンクを参照して link:other_references.html["参考資料"] ください。
* 次の構成のAFF 700などのシステムを使用している場合は、ノードごとに2つのクラスタポートにクラスタLIFを移行し、ホームポートを変更します。
* ノードごとに2つ以上のクラスタポート
* ポートe4a、e4b、e4c、e4dを作成するためのブレークアウトモードのslot4のクラスタインターコネクトカードと、ポートe4e、 e4f、e4g、およびe4h
+

NOTE: ノードごとにクラスタポートが2つ以上あるコントローラのアップグレードを実行すると、アップグレード後に新しいコントローラのクラスタLIFが失われる可能性があります。

+
詳細については、ナレッジベースの記事を参照して link:https://kb.netapp.com/on-prem/ontap/Ontap_OS/OS-KBs/How_to_delete_unwanted_or_unnecessary_cluster_LIFs["不要なクラスタLIFや不要なクラスタLIFを削除する方法"^]ください。



ARL を使用したコントローラのアップグレードは、 SnapLock Enterprise ボリュームおよび SnapLock Compliance ボリュームが設定されたシステムでサポートされます。



== 2 ノードスイッチレスクラスタ

2 ノードスイッチレスクラスタのノードをアップグレードする場合は、アップグレードの実行中もスイッチレスクラスタのノードをそのまま使用できます。スイッチクラスタに変換する必要はありません。



== ARL のアップグレードはサポートされていません

元のコントローラに接続されているディスクシェルフがサポートされない交換用コントローラはアップグレードできません。

を参照してください link:other_references.html["参考資料"] ディスクサポート情報の Hardware Universe にリンクするには、次の手順を実行します。

内蔵ドライブを搭載したエントリレベルのコントローラをアップグレードする場合は、_ボリュームまたはストレージの移動によるアップグレード_へのリンクを参照し、「_ボリュームの移動によるclustered Data ONTAPを実行するノードのペアのアップグレード_」の手順を参照して link:other_references.html["参考資料"] ください。



== トラブルシューティングを行う

コントローラのアップグレード中に問題が発生した場合の詳細と考えられる解決方法については、を参照して link:aggregate_relocation_failures.htmll["トラブルシューティングを行う"] ください。

発生した問題に対する解決策 が見つからない場合は、テクニカルサポートにお問い合わせください。
