---
sidebar: sidebar 
permalink: upgrade-arl-auto-app-9151/install_boot_node4.html 
keywords: install, boot, node4, install ONTAP 
summary: 'コマンドを使用してONTAP 9.15.1以降を実行しているコントローラをアップグレードする場合、ノード4をインストールしてブートし、ONTAPソフトウェアをインストールし `system controller replace` ます。' 
---
= ノード 4 をインストールしてブートします
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
ノード4をラックに取り付け、ノード2の接続をノード4に転送し、ノード4をブートして、ONTAPをインストールします。次に、このセクションで説明するように、ノード2の任意のスペアディスク、ルートボリュームに属するディスク、および以前にノード3に再配置されていなかったルート以外のアグリゲートを再割り当てします。

.このタスクについて
再配置処理はこのフェーズの開始時に一時停止されます。このプロセスはほとんどが自動化されており、処理は一時停止してステータスを確認できます。この処理は手動で再開する必要があります。

node2 に同じバージョンの ONTAP 9 がインストールされていない場合は、 node4 をネットブートする必要があります。node4 のインストールが完了したら、 Web サーバに格納されている ONTAP 9 イメージからブートします。その後、の手順に従って、後続のシステムのブートに使用する正しいファイルをブートメディアデバイスにダウンロードできます link:prepare_for_netboot.html["ネットブートを準備"]。

.手順
. [[auto_install4_stp1] ノード 4 に十分なラックスペースがあることを確認します。
+
node4 が node2 とは別のシャーシにある場合は、 node3 と同じ場所に node4 を配置できます。node2 と node4 が同じシャーシにある場合は、 node4 が適切なラックの場所にすでに存在しているとします。

. ノードモデルの _Installation and Setup Instructions _ の手順に従って、ノード 4 をラックに設置します。
. ノード 4 をケーブル接続します。 node2 から node4 に接続を移動します。
+
各ノード 4 のプラットフォームについて、『 Installation and Setup Instructions 』または『 FlexArray Virtualization Installation Requirements and Reference_for the node4 』、該当するディスクシェルフのドキュメント、および _High Availability management _ の手順に従って、次の接続をケーブル接続します。

+
を参照してください link:other_references.html["参考資料"] FlexArray 仮想化インストール要件およびリファレンスとハイアベイラビリティ管理へのリンク。

+
** コンソール（リモート管理ポート）
** クラスタポートとHAポート
** データポート
** クラスタポートとノード管理ポート
** Serial-Attached SCSI（SAS）およびEthernetストレージポート
** SAN構成：iSCSIイーサネット、FC、NVMe/FCスイッチポート
+
[NOTE]
====
異なるコントローラモデルやカードモデル間で相互運用性を確保するために、新旧のコントローラ間のインターコネクトケーブルの変更が必要になる場合があります。ご使用のシステムのイーサネットストレージシェルフのケーブル接続マップについては、を参照して link:https://docs.netapp.com/us-en/ontap-systems/index.html["システムのインストール手順"^] ください。

ONTAP 9.15.1以降で導入されたコントローラでは、クラスタインターコネクトとHAインターコネクトで同じポートが使用されます。スイッチ接続構成では、同様のポートを同じクラスタスイッチに接続する必要があります。たとえば、既存のコントローラからAFF A1Kにアップグレードする場合は、両方のノードのe1aポートを一方のスイッチに接続し、両方のノードのe7aポートをもう一方のスイッチに接続する必要があります。

====


. node4 への電源を入れてから、コンソール端末で Ctrl+C キーを押してブートプロセスを中断し、ブート環境プロンプトにアクセスします。
+

NOTE: node4 をブートすると、次の警告メッセージが表示される場合があります。

+
....
WARNING: The battery is unfit to retain data during a power outage. This is likely
         because the battery is discharged but could be due to other temporary
         conditions.
         When the battery is ready, the boot process will complete
         and services will be engaged. To override this delay, press 'c' followed
         by 'Enter'
....
. 手順 4 で警告メッセージが表示された場合は、次の操作を実行します。
+
.. NVRAM バッテリ低下以外の問題を示すコンソールメッセージがないか確認し、必要に応じて対処します。
.. バッテリの充電と起動プロセスが完了するまで待ちます。
+

WARNING: * 注意：遅延は無視しないでください。バッテリーの充電に失敗すると、データが失われるおそれがあります。 *

+

NOTE: を参照してください link:prepare_for_netboot.html["ネットブートを準備"]。



. 次のいずれかを実行してネットブート接続を設定します。
+

NOTE: ネットブート接続として管理ポートおよび IP を使用する必要があります。アップグレードの実行中にデータ LIF IP を使用しないでください。データ LIF が停止する可能性があります。

+
[cols="30,70"]
|===
| 動的ホスト構成プロトコル（ DHCP ）の状態 | 作業 


| 実行中です | ブート環境プロンプトで次のコマンドを使用して、自動的に接続を設定します。 ifconfig e0M -auto 


| 実行されていません  a| 
ブート環境プロンプトで次のコマンドを入力して、接続を手動で設定します。
`ifconfig e0M -addr=_filer_addr_ -mask=_netmask_ -gw=_gateway_ -dns=_dns_addr_ -domain=_dns_domain_`

`_filer_addr_` は、ストレージシステムのIPアドレスです（必須）。
`_netmask_` は、ストレージシステムのネットワークマスクです（必須）。
`_gateway_` は、ストレージシステムのゲートウェイです（必須）。
`_dns_addr_` は、ネットワーク上のネームサーバのIPアドレスです（オプション）。
`_dns_domain_` は、DNSドメイン名です（オプション）。


NOTE: インターフェイスによっては、その他のパラメータが必要になる場合もあります。ファームウェア・プロンプトで「 help ifconfig 」と入力すると、詳細が表示されます。

|===
. ノード 4 でネットブートを実行します。
+
netboot\http://<web_server_ip/path_to_web-accessible_directory>/<ontap_version>_image.tgz`

+
「 <path_the_web-accessible_directory> 」は、手順 1 の「 <ONTAP_version>_image.tgz 」をダウンロードした場所に配置する必要があります link:prepare_for_netboot.html["ネットブートを準備"]。

+

NOTE: トランクを中断しないでください。

. 起動メニューからオプション（ 7 ） Install new software first （新しいソフトウェアを最初にインストール）を選択します。
+
このメニューオプションを選択すると、新しい ONTAP イメージがブートデバイスにダウンロードおよびインストールされます。

+
次のメッセージは無視してください。

+
`This procedure is not supported for Non-Disruptive Upgrade on an HA pair`

+
コントローラのアップグレードではなく、 ONTAP による環境の無停止アップグレードも記録されています。

+

NOTE: 新しいノードを希望するイメージに更新する場合は、必ずネットブートを使用してください。別の方法で新しいコントローラにイメージをインストールした場合、正しいイメージがインストールされないことがあります。この問題環境 All ONTAP リリースオプションを指定してネットブート手順 を実行する `(7) Install new software` ブートメディアを消去して、両方のイメージパーティションに同じONTAP バージョンを配置します。

. 手順を続行するかどうかを確認するメッセージが表示されたら、「 y 」と入力し、パッケージの入力を求められたら URL を入力します。
+
http://<web_server_ip/path_to_web-accessible_directory>/<ontap_version>_image.tgz` にアクセスします

. 次の手順を実行してコントローラモジュールをリブートします。
+
.. 次のプロンプトが表示されたら 'n' を入力してバックアップ・リカバリをスキップします
+
....
Do you want to restore the backup configuration now? {y|n}
....
.. 次のプロンプトが表示されたら 'y' と入力して再起動します
+
....
The node must be rebooted to start using the newly installed software. Do you want to reboot now? {y|n}
....
+
コントローラモジュールはリブートしますが、ブートメニューで停止します。これは、ブートデバイスが再フォーマットされたことにより、構成データをリストアする必要があるためです。



. ブート・メニューからメンテナンス・モード「 5 」を選択し、ブートを続行するように求めるプロンプトが表示されたら「 y 」と入力します。
. コントローラとシャーシが HA 構成になっていることを確認します。
+
「 ha-config show 」

+
次に 'ha-config show コマンドの出力例を示します

+
....
Chassis HA configuration: ha
Controller HA configuration: ha
....
+

NOTE: システムは、 HA ペア構成かスタンドアロン構成かを PROM に記録します。状態は、スタンドアロンシステムまたは HA ペア内のすべてのコンポーネントで同じである必要があります。

. コントローラとシャーシが HA として構成されていない場合は、次のコマンドを使用して構成を修正します。
+
「 ha-config modify controller ha 」を参照してください

+
「 ha-config modify chassis ha 」を参照してください

. イーサネットシェルフへの接続に使用するすべてのイーサネットポートがストレージとして構成されていることを確認します。
+
`storage port show`

+
表示される出力は、システム構成によって異なります。次の出力例は、スロット11にストレージカードが1つ搭載されたノードに対するものです。システムの出力は異なる場合があります。

+
[listing]
----
*> storage port show
Port Type Mode    Speed(Gb/s) State    Status  VLAN ID
---- ---- ------- ----------- -------- ------- -------
e11a ENET storage 100 Gb/s    enabled  online  30
e11b ENET storage 100 Gb/s    enabled  online  30
----
. ストレージに設定されていないポートを変更します。
+
`storage port modify -p <port> -m storage`

+
ストレージシェルフに接続されたすべてのイーサネットポートは、ディスクとシェルフにアクセスできるようにストレージとして構成する必要があります。

. メンテナンスモードを終了します。
+
「 halt 」

+
ブート環境のプロンプトで Ctrl+C を押し、 AUTOBOOT を中断します。

. [auto_install4_step15]] ノード 3 で、システムの日付、時刻、およびタイムゾーンを確認します。
+
「食事」

. node4 で、ブート環境のプロンプトで次のコマンドを使用して日付を確認します。
+
「日付」

. 必要に応じて、 node4 に日付を設定します。
+
`set date <mm/dd/yyyy>`

. node4 で、ブート環境のプロンプトで次のコマンドを使用して時間を確認します。
+
「時間」

. 必要に応じて、 node4 に時間を設定します。
+
`set time <hh:mm:ss>`

. ブートローダーのnode4にあるパートナーシステムIDを設定します。
+
`setenv partner-sysid <node3_sysid>`

+
ノード4の場合、 `partner-sysid` node3のノードである必要があります。

+
設定を保存します。

+
'aveenv

. [[auto_install4_step21]を確認します `partner-sysid` ノード4の場合：
+
printenv partner-sysid

. [[auto_install4_step24]] NetAppストレージ暗号化（NSE）ドライブが取り付けられている場合は、次の手順を実行します。
+

NOTE: 手順 でこれまでに行ったことがない場合は、Knowledge Baseの記事を参照してください https://kb.netapp.com/onprem/ontap/Hardware/How_to_tell_if_a_drive_is_FIPS_certified["ドライブがFIPS認定かどうかを確認する方法"^] 使用している自己暗号化ドライブのタイプを確認するため。

+
.. 設定 `bootarg.storageencryption.support` 終了： `true` または `false`。
+
[cols="35,65"]
|===
| 次のドライブが使用中の場合 | 次に、 


| FIPS 140-2レベル2の自己暗号化要件に準拠したNSEドライブ | `setenv bootarg.storageencryption.support *true*` 


| ネットアップの非FIPS SED | `setenv bootarg.storageencryption.support *false*` 
|===
.. 特別なブートメニューに移動してオプションを選択します `(10) Set Onboard Key Manager recovery secrets`。
+
パスフレーズと、前の手順で手順 に記録しておいたバックアップ情報を入力します。を参照してください link:manage_storage_encryption_using_okm.html["オンボードキーマネージャを使用してストレージ暗号化を管理します"]。



. ノードをブートメニューに追加します。
+
「 boot_ontap menu

. [[auto_check_4_step11]] node4で、ブートメニューに移動し、22/7を使用して隠しオプションを選択します `boot_after_controller_replacement`。プロンプトで node2 と入力し、次の例のように node2 のディスクを node4 に再割り当てします。
+
.コンソールの出力例を展開します
[%collapsible]
====
[listing]
----
LOADER-A> boot_ontap menu
.
.
<output truncated>
.
All rights reserved.
*******************************
*                             *
* Press Ctrl-C for Boot Menu. *
*                             *
*******************************
.
<output truncated>
.
Please choose one of the following:
(1)  Normal Boot.
(2)  Boot without /etc/rc.
(3)  Change password.
(4)  Clean configuration and initialize all disks.
(5)  Maintenance mode boot.
(6)  Update flash from backup config.
(7)  Install new software first.
(8)  Reboot node.
(9)  Configure Advanced Drive Partitioning.
(10) Set Onboard Key Manager recovery secrets.
(11) Configure node for external key management.
Selection (1-11)? 22/7
(22/7)                          Print this secret List
(25/6)                          Force boot with multiple filesystem disks missing.
(25/7)                          Boot w/ disk labels forced to clean.
(29/7)                          Bypass media errors.
(44/4a)                         Zero disks if needed and create new flexible root volume.
(44/7)                          Assign all disks, Initialize all disks as SPARE, write DDR labels
.
.
<output truncated>
.
.
(wipeconfig)                        Clean all configuration on boot device
(boot_after_controller_replacement) Boot after controller upgrade
(boot_after_mcc_transition)         Boot after MCC transition
(9a)                                Unpartition all disks and remove their ownership information.
(9b)                                Clean configuration and initialize node with partitioned disks.
(9c)                                Clean configuration and initialize node with whole disks.
(9d)                                Reboot the node.
(9e)                                Return to main boot menu.
The boot device has changed. System configuration information could be lost. Use option (6) to
restore the system configuration, or option (4) to initialize all disks and setup a new system.
Normal Boot is prohibited.
Please choose one of the following:
(1)  Normal Boot.
(2)  Boot without /etc/rc.
(3)  Change password.
(4)  Clean configuration and initialize all disks.
(5)  Maintenance mode boot.
(6)  Update flash from backup config.
(7)  Install new software first.
(8)  Reboot node.
(9)  Configure Advanced Drive Partitioning.
(10) Set Onboard Key Manager recovery secrets.
(11) Configure node for external key management.
Selection (1-11)? boot_after_controller_replacement
This will replace all flash-based configuration with the last backup to disks. Are you sure
you want to continue?: yes
.
.
<output truncated>
.
.
Controller Replacement: Provide name of the node you would like to replace:
<nodename of the node being replaced>
Changing sysid of node node2 disks.
Fetched sanown old_owner_sysid = 536940063 and calculated old sys id = 536940063
Partner sysid = 4294967295, owner sysid = 536940063
.
.
<output truncated>
.
.
varfs_backup_restore: restore using /mroot/etc/varfs.tgz
varfs_backup_restore: attempting to restore /var/kmip to the boot device
varfs_backup_restore: failed to restore /var/kmip to the boot device
varfs_backup_restore: attempting to restore env file to the boot device
varfs_backup_restore: successfully restored env file to the boot device wrote
    key file "/tmp/rndc.key"
varfs_backup_restore: timeout waiting for login
varfs_backup_restore: Rebooting to load the new varfs
Terminated
<node reboots>
System rebooting...
.
.
Restoring env file from boot media...
copy_env_file:scenario = head upgrade
Successfully restored env file from boot media...
Rebooting to load the restored env file...
.
System rebooting...
.
.
.
<output truncated>
.
.
.
.
WARNING: System ID mismatch. This usually occurs when replacing a
boot device or NVRAM cards!
Override system ID? {y|n} y
.
.
.
.
Login:
----
====
+

NOTE: 上記のコンソールの出力例では、アドバンストディスクパーティショニング（ ADP ）ディスクを使用するシステムの場合は ONTAP からパートナーノード名の入力を求められます。

. [[auto_check_4_step27]] LOADERプロンプトでブートします。
+
「 boot_ontap menu

+
これで、ブート時に以前に割り当てられていたすべてのディスクをノードで検出できるようになり、想定どおりにブートできるようになります。

+
交換するクラスタノードがルートボリューム暗号化を使用している場合、ONTAPはディスクからボリューム情報を読み取ることができません。ルートボリュームのキーをリストアします。

+
ルートボリュームが暗号化されている場合は、システムがルートボリュームを検出できるように、オンボードキー管理シークレットをリカバリします。

+
.. 特別なブートメニューに戻ります。
`LOADER> boot_ontap menu`
+
[listing]
----
Please choose one of the following:
(1) Normal Boot.
(2) Boot without /etc/rc.
(3) Change password.
(4) Clean configuration and initialize all disks.
(5) Maintenance mode boot.
(6) Update flash from backup config.
(7) Install new software first.
(8) Reboot node.
(9) Configure Advanced Drive Partitioning.
(10) Set Onboard Key Manager recovery secrets.
(11) Configure node for external key management.

Selection (1-11)? 10
----
.. （10）Set Onboard Key Manager Recovery secrets（オンボードキーマネージャリカバリシークレットの設定）*を選択します
.. 入力するコマンド `y` 次のプロンプトが表示されます。
+
`This option must be used only in disaster recovery procedures. Are you sure? (y or n): y`

.. プロンプトで、キー管理ツールのパスフレーズを入力します。
.. プロンプトが表示されたら、バックアップデータを入力します。
+

NOTE: でパスフレーズとバックアップデータを入手しておく必要があります link:prepare_nodes_for_upgrade.html["ノードをアップグレードする準備をします"] この手順のセクション。

.. システムが再度特別な起動メニューを起動したら、オプション*（1）Normal Boot *を実行します
+

NOTE: この段階でエラーが発生する場合があります。エラーが発生した場合は、システムが正常にブートするまでの手順を繰り返し <<auto_check_4_step27,ステップ27>> ます。




