---
sidebar: sidebar 
permalink: upgrade-arl-auto-app-9151/move_non_root_aggr_and_nas_data_lifs_node2_from_node3_to_node4.html 
keywords: move, non-root, aggregates, nas, lif, node2, node3, node4 
summary: 'コマンドを使用して、ONTAP 9.15.1以降を実行するコントローラをアップグレードする際に、ノード3にあるノード2のNASデータLIFがノード3からノード4に再配置されたことを確認します `system controller replace` 。' 
---
= node2 によって所有されているルート以外のアグリゲートと NAS データ LIF を、 node3 から node4 に移動します
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
ノード 4 のネットワーク設定を確認し、ノード 3 からノード 4 にアグリゲートを再配置する前に、ノード 2 に現在ノード 3 に属する NAS データ LIF が、ノード 3 からノード 4 に再配置されていることを確認する必要があります。また、ノード 4 に SAN LIF が存在することも確認する必要があります。

.このタスクについて
アップグレード手順の実行中、リモート LIF は SAN LUN へのトラフィックを処理します。アップグレード時にクラスタやサービスの健全性を維持するために、 SAN LIF を移動する必要はありません。SAN LIF は、新しいポートにマッピングする必要がないかぎり移動されません。ノード 4 をオンラインにしたあと、 LIF が正常に機能しており、適切なポートに配置されていることを確認します。

.手順
. 到達可能性スキャンを使用して、iSCSI LIFが正しいホームポートを自動的に検出します。FCおよびNVMe/FC SAN LIFは自動的には移動しません。アップグレード前のホームポートは引き続き表示されます。
+
ノード4のSAN LIFを確認します。

+
.. 「停止」処理ステータスを報告しているiSCSI SAN LIFを新しいデータポートに変更します。
+
`network interface modify -vserver <vserver> -lif <iscsi_san_lif> admin down`

+
`network interface modify -vserver <vserver> -lif <iscsi_san_lif> port <new_port> node <node>`

+
`network interface modify -vserver <vserver> -lif <iscsi_san_lif>`

.. 新しいコントローラのホームにあるFCおよびNVMe/FC SAN LIFを変更し、新しいコントローラのFCPポートに「停止」の動作ステータスを報告します。
+
`network interface modify -vserver <vserver> -lif <fc_san_lif> admin down`

+
`network interface modify -vserver <vserver> -lif <fc_san_lif> port <new_port> node <node>`

+
`network interface modify -vserver <vserver> -lif <fc_san_lif>`



. 再配置処理を再開します。
+
「システムコントローラの交換が再開」

+
システムは次のタスクを実行します。

+
** クラスタクォーラムチェック
** システム ID の確認
** イメージのバージョンチェック
** ターゲットプラットフォームのチェック
** ネットワーク到達可能性チェック


+
ネットワーク到達可能性チェックのこの段階で処理が一時停止します。

. 再配置処理を再開します。
+
「システムコントローラの交換が再開」

+
システムは次のチェックを実行します。

+
** クラスタの健全性チェック
** クラスタ LIF のステータスを確認します


+
これらのチェックの実行後、システムによって、 node2 によって所有されているルート以外のアグリゲートと NAS データ LIF が新しいコントローラ node4 に再配置されます。リソースの再配置が完了すると、コントローラの交換処理が一時停止します。

. アグリゲートの再配置処理と NAS データ LIF の移動処理のステータスを確認します。
+
「 system controller replace show-sdetails 」というエラーが表示されます

+
コントローラ交換用手順が一時停止している場合は、エラーがある場合はチェックして修正し、次に「問題 re sume 」をクリックして操作を続行します。

. 必要に応じて、取り外した LIF をリストアしてリバートします。取り外した LIF を表示します。
+
cluster controller -replacement network ヒエラー（クラスタコントローラ交換ネットワークが取り外されました） -interface show

+
LIF が取り外された場合は、ホームノードをノード 4 にリストアします。

+
クラスタ・コントローラ交換ネットワークが取り外されましたインタフェース・リストア -home-node

. この処理を再開すると、必要なポストチェックの実行をシステムに求めるプロンプトが表示されます。
+
「システムコントローラの交換が再開」

+
次のポストチェックが実行されます。

+
** クラスタクォーラムチェック
** クラスタの健全性チェック
** アグリゲートの再構築チェック
** アグリゲートのステータスを確認します
** ディスクのステータスを確認します
** クラスタ LIF のステータスを確認します
** ボリュームチェック



