---
sidebar: sidebar 
permalink: upgrade-arl-auto-app-9151/prepare_nodes_for_upgrade.html 
keywords: preparing, nodes, upgrade 
summary: 'ONTAP 9.15.1以降で導入されたコントローラへのアップグレード時に、 `system controller replace`コマンドを使用してノードを準備し、一連の事前チェックを実行します。' 
---
= ノードをアップグレードする準備をします
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
コントローラー交換プロセスは、一連の事前チェックから始まります。また、手順の後半で使用するために、元のノードに関する情報も収集します。事前チェックでいずれかの項目が失敗した場合は、アップグレードを続行する前に、アグリゲート所有権を修正する必要があります。



[[step-1-prepare-node1-and-node2]]
== ステップ1：ノード1とノード2を準備する

コントローラーの交換プロセスを開始し、node1とnode2で事前チェックを実行します。必要に応じて、使用されている自己暗号化ドライブの種類を特定します。

.手順
. ONTAP コマンドラインで次のコマンドを入力して、コントローラの交換プロセスを開始します。
+
[source, cli]
----
system controller replace start -nodes <node_names>
----
+
[NOTE]
====
このコマンドは、advanced権限レベルでのみ実行でき `system controller replace start`ます。

[source, cli]
----
set -privilege advanced
----
====
+
以下のような出力が表示されます。出力には、クラスタで実行されている ONTAP バージョンが表示されます：

+
....
Warning: 1. Current ONTAP version is 9.15.1

2. Verify that NVMEM or NVRAM batteries of the new nodes are charged, and charge them if they are not. You need to physically check the new nodes to see if the NVMEM or NVRAM batteries are charged. You can check the battery status either by connecting to a serial console or using SSH, logging into the Service Processor (SP) or Baseboard Management Controller (BMC) for your system, and use the system sensors to see if the battery has a sufficient charge.

Attention: Do not try to clear the NVRAM contents. If there is a need to clear the contents of NVRAM, contact NetApp technical support.

3. If a controller was previously part of a different cluster, run wipeconfig before using it as the replacement controller.

4. Note: This is not a MetroCluster configuration. Controller replacement supports only ARL based procedure.
Do you want to continue? {y|n}: y
....
. 選択 `y`すると、次の出力が表示されます：
+
....
Controller replacement operation: Prechecks in progress.
Controller replacement operation has been paused for user intervention.
....
+
システムでは次の事前確認が実行され、あとで手順で使用するために各事前確認の出力が記録されます。

+
[cols="35,65"]
|===
| 事前チェック | 説明 


| クラスタの健常性チェック | クラスタ内のすべてのノードが正常であることを確認します。 


| アグリゲートの再配置ステータスチェック | アグリゲートの再配置がすでに実行中であるかどうかを確認します。別のアグリゲートの再配置を実行中の場合、チェックは失敗します。 


| モデル名のチェック（ Model Name Check | この手順でコントローラモデルがサポートされているかどうかを確認します。モデルがサポートされていない場合、タスクは失敗します。 


| クラスタクォーラムチェック | 交換するノードがクォーラムにあることを確認します。ノードがクォーラムを構成していない場合は、タスクが失敗します。 


| イメージのバージョンチェック | 置換されるノードが同じバージョンのONTAPを実行していることを確認します。ONTAPイメージのバージョンが異なる場合、タスクは失敗します。新しいノードには、元のノードにインストールされているものと同じバージョンのONTAP 9.xがインストールされている必要があります。新しいノードに異なるバージョンのONTAPがインストールされている場合は、インストール後に新しいコントローラをネットブートする必要があります。ONTAPのアップグレード手順については、link:other-references.html["参考資料"]を参照して_Upgrade ONTAP_にリンクしてください。 


| HA ステータスチェック | 交換する両方のノードがハイアベイラビリティ（ HA ）ペア構成になっているかどうかを確認します。コントローラでストレージフェイルオーバーが有効になっていない場合、タスクは失敗します。 


| アグリゲートステータスチェック | ホーム所有者でないアグリゲートを交換するノードが所有している場合、そのタスクは失敗します。ローカル以外のアグリゲートを所有するノードは使用しないでください。 


| ディスクステータスチェック | 交換対象のノードに欠落したディスクまたは障害のあるディスクがある場合、タスクは失敗します。ディスクが欠落している場合は、link:other-references.html["参考資料"]を参照して、_CLI を使用したディスクおよびアグリゲートの管理_、_CLI を使用した論理ストレージの管理_、および_HA ペアの管理_にリンクし、HA ペアのストレージを設定してください。 


| データ LIF ステータスチェック | 交換するノードにローカル以外のデータ LIF があるかどうかを確認します。ホーム所有者でないデータ LIF がノードに含まれないようにしてください。ローカル以外のデータ LIF がいずれかのノードに含まれている場合、タスクは失敗します。 


| クラスタ LIF ステータス | 両方のノードでクラスタ LIF が動作しているかどうかを確認します。クラスタ LIF が停止している場合は、タスクは失敗します。 


| AutoSupport ステータスチェック | AutoSupport 通知が設定されていないと、タスクは失敗します。コントローラの交換用手順 を開始する前に、 AutoSupport を有効にする必要があります。 


| CPU 利用率チェック | 交換するノードの CPU 利用率が 50% を超えていないかどうかを確認します。CPU 使用率がかなりの時間にわたって 50% を超えると、タスクは失敗します。 


| アグリゲートの再構築チェック | いずれかのデータアグリゲートで再構築が実行されているかどうかを確認しますアグリゲートの再構築を実行中の場合、タスクは失敗します。 


| ノードアフィニティジョブチェック | ノードアフィニティジョブが実行されているかどうかを確認します。ノードアフィニティジョブが実行中の場合、チェックは失敗します。 
|===
. コントローラの交換処理が開始されて事前確認が完了すると、処理が一時停止するため、ノード 3 の設定時にあとで必要になる可能性がある出力情報を収集できます。
+
[NOTE]
====
次の構成のAFF 700などのシステムを使用している場合は、アップグレードを開始する前に、クラスタLIFをノードごとに2つのクラスタポートに移行してホームポートに戻します。

** ノードごとに2つ以上のクラスタポート
** ポートe4a、e4b、e4c、e4dを作成するためのブレークアウトモードのslot4のクラスタインターコネクトカードと、ポートe4e、 e4f、e4g、およびe4h


ノードごとにクラスタポートが2つ以上あるコントローラのアップグレードを実行すると、アップグレード後に新しいコントローラのクラスタLIFが失われる可能性があります。

詳細については、ナレッジベースの記事を参照して link:https://kb.netapp.com/on-prem/ontap/Ontap_OS/OS-KBs/How_to_delete_unwanted_or_unnecessary_cluster_LIFs["不要なクラスタLIFや不要なクラスタLIFを削除する方法"^]ください。

====
. システムコンソールで、コントローラの交換用手順の指示に従って、次のコマンドセットを実行します。
+
各ノードに接続されているシリアルポートで、次のコマンドの出力を個別に実行して保存します。

+
[source, cli]
----
vserver services name-service dns show
----
+
[source, cli]
----
network interface show -curr-node <local> -role cluster,intercluster,node-mgmt,cluster-mgmt,data
----
+
[source, cli]
----
network port show -node <local> -type physical
----
+
[source, cli]
----
service-processor show -node <local> -instance
----
+
[source, cli]
----
network fcp adapter show -node <local>
----
+
[source, cli]
----
network port ifgrp show -node <local>
----
+
[source, cli]
----
system node show -instance -node <local>
----
+
[source, cli]
----
run -node <local> sysconfig
----
+
[source, cli]
----
storage aggregate show -r
----
+
[source, cli]
----
storage aggregate show -node <local>
----
+
[source, cli]
----
volume show -node <local>
----
+
[source, cli]
----
system license show -owner <local>
----
+
[source, cli]
----
storage encryption disk show
----
+
[source, cli]
----
security key-manager onboard show-backup
----
+
[source, cli]
----
security key-manager external show
----
+
[source, cli]
----
security key-manager external show-status
----
+
[source, cli]
----
network port reachability show -detail -node <local>
----
+

NOTE: オンボードキーマネージャ（OKM）を使用したNetApp Volume Encryption（NVE）またはNetApp Aggregate Encryption（NAE）を使用している場合は、手順の後半の工程でキー管理ツールの再同期を実行できるように、キー管理ツールのパスフレーズを準備しておいてください。

. システムで自己暗号化ドライブを使用している場合は、Knowledge Baseの文書を参照してください https://kb.netapp.com/onprem/ontap/Hardware/How_to_tell_if_a_drive_is_FIPS_certified["ドライブがFIPS認定かどうかを確認する方法"^] アップグレード対象のHAペアで使用されている自己暗号化ドライブのタイプを確認する。ONTAP ソフトウェアは、次の2種類の自己暗号化ドライブをサポートしています。
+
--
** FIPS認定のNetApp Storage Encryption（NSE）SASドライブまたはNVMeドライブ
** FIPS非対応の自己暗号化NVMeドライブ（SED）


https://docs.netapp.com/us-en/ontap/encryption-at-rest/support-storage-encryption-concept.html#supported-self-encrypting-drive-types["サポートされている自己暗号化ドライブの詳細を確認できます"^]。

--




[[step-2-correct-aggregate-ownership-if-an-arl-precheck-fails]]
== ステップ2：ARLの事前チェックが失敗した場合は、アグリゲートの所有権を修正します

アグリゲートステータスチェックに失敗した場合は、パートナーノードが所有するアグリゲートをホーム所有者ノードに戻し、事前確認プロセスを再度開始する必要があります。

.手順
. パートナーノードが現在所有しているアグリゲートをホーム所有者ノードに戻します。
+
[source, cli]
----
storage aggregate relocation start -node <source_node> -destination <destination_node> -aggregate-list *
----
. node1 と node2 のどちらも現在の所有者（ホーム所有者ではない）アグリゲートを所有していないことを確認します。
+
[source, cli]
----
storage aggregate show -nodes <node_name> -is-home false -fields owner-name, home-name, state
----
+
次の例は、アグリゲートの現在の所有者とホーム所有者の両方がノードにある場合のコマンドの出力例を示しています。

+
[listing]
----
cluster::> storage aggregate show -nodes node1 -is-home true -fields owner-name,home-name,state
aggregate   home-name  owner-name  state
---------   ---------  ----------  ------
aggr1       node1      node1       online
aggr2       node1      node1       online
aggr3       node1      node1       online
aggr4       node1      node1       online

4 entries were displayed.
----
. コントローラ交換プロセスを再開します。
+
[source, cli]
----
system controller replace start -nodes <node_names>
----




[[step-3-prepare-node3-and-node4]]
== ステップ3：ノード3とノード4を準備する

node3とnode4のビルドがNODAR（保存データの暗号化なし）イメージであるかどうかを確認してください。ビルドがNODARイメージの場合は、DARE（保存データの暗号化）イメージをインストールする必要があります。

.このタスクについて
node3とnode4で以下の手順を実行します。

.手順
. ノードをブートメニューでブートします。
+
[source, cli]
----
LOADER> boot_ontap menu
----
. システムシェルに入ります：
+
[source, cli]
----
systemshell
----
. [[check-build]]ビルドがNODARイメージであるかどうかを確認します。
+
[source, cli]
----
cat /BUILD
----
+
コマンド出力で、 `build-type`がNODAR イメージであるかどうかを確認します。例えば、 `DEBUG SIM NODAR`。

+

NOTE:  `build-type`がNODAR画像でない場合、そのビルドはDARE画像です。

. ビルドがNODARイメージの場合は、DAREイメージをインストールしてください。
+
.. システムシェルとブートメニューを終了します。
+
[source, cli]
----
halt
----
.. DAREイメージをインストールします。詳細については、ナレッジベースの記事link:https://kb.netapp.com/on-prem/ontap/Ontap_OS/OS-KBs/Netbooting_a_FAS_and_AFF_Controller_in_ONTAP_9["ONTAP 9 での FAS および AFF コントローラのネットブート"^]を参照してください。




.次の手順
ノードを準備した後、link:complete-preparation-for-upgrade.html["アップグレードの準備を完了する"]。
