---
sidebar: sidebar 
permalink: upgrade-arl-auto-app-9151/set_up_storage_encryption_new_module.html 
keywords: set up storage, encryption, controller, module, node 
summary: '必要に応じて、コマンドを使用してONTAP 9.15.1以降を実行するコントローラをアップグレードする際に、ストレージ暗号化を設定し、SSL証明書をインストールし、キー管理サーバをセットアップし `system controller replace` ます。' 
---
= 新しいコントローラモジュールで Storage Encryption をセットアップします
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
交換したコントローラまたは新しいコントローラの HA パートナーで Storage Encryption が使用されている場合は、 SSL 証明書のインストールやキー管理サーバのセットアップなど、新しいコントローラモジュールを Storage Encryption 用に設定する必要があります。

.このタスクについて
この手順には、新しいコントローラモジュールで実行する手順が含まれています。コマンドは正しいノードで入力する必要があります。

.手順
. キー管理サーバがまだ使用可能であり、ステータスと認証キー情報が正しいことを確認します。
+
「 security key-manager external show-status 」

+
「 securitykey manager onboard show-backup 」を参照してください

. 前の手順で確認したキー管理サーバを、新しいコントローラのキー管理サーバのリストに追加します。
+
.. キー管理サーバを追加します。
+
「security key-manager external add-servers -key-servers_key_manager_server_ip_address _」のように指定します

.. リストされている各キー管理サーバについて、同じ手順を繰り返します。最大 4 台のキー管理サーバをリンクできます。
.. キー管理サーバが正常に追加されたことを確認します。
+
「 security key-manager external show 」と入力します



. 新しいコントローラモジュールで、キー管理セットアップウィザードを実行して、キー管理サーバをセットアップしてインストールします。
+
既存のコントローラモジュールと同じキー管理サーバをインストールする必要があります。

+
.. 新しいノードでキー管理サーバセットアップウィザードを起動します。
+
「 security key-manager external enable 」と入力します

.. ウィザードの手順に従って、キー管理サーバを設定します。


. リンクされたすべてのキー管理サーバから新しいノードに認証キーをリストアします。
+
'security key-manager external restore -node _new_controller_name_`


