---
sidebar: sidebar 
permalink: upgrade-arl-auto-app-9151/stage_6_index.html 
keywords: complete upgrade, node, unified, target, storage, encryption, stage 6 
summary: 'ONTAP 9.15.1以降を実行しているコントローラでコマンドを使用したARLアップグレードのステージ6プロセスシーケンス `system controller replace` 。' 
---
= ステージ6の概要
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
ステージ6では、新しいノードが正しくセットアップされていることを確認し、暗号化が有効な新しいノードがある場合は、ストレージ暗号化またはNetApp Volume Encryptionを設定およびセットアップします。また、古いノードの運用を停止し、SnapMirrorの処理を再開する必要があります。

.手順
. link:manage-authentication-using-kmip-servers.html["KMIP サーバを使用して認証を管理します"]
. link:ensure_new_controllers_are_set_up_correctly.html["新しいコントローラが正しくセットアップされていることを確認します"]
. link:set_up_storage_encryption_new_module.html["新しいコントローラモジュールで Storage Encryption をセットアップします"]
. link:set_up_netapp_volume_encryption_new_module.html["新しいコントローラモジュールでNetApp VolumeまたはAggregate Encryptionをセットアップします"]
. link:decommission_old_system.html["古いシステムの運用を停止"]
. link:resume_snapmirror_operations.html["SnapMirror 処理を再開します"]


[NOTE]
====
AFF A20、AFF A50、AFF A70、AFF A90、AFF A1K、FAS70、およびFAS90システムは、クラスタ接続とHA接続の両方で100GbEネットワークポートを共有します。これらのシステムでは、従来のクラスタスイッチとの10GbEまたは25GbEクラスタ接続をサポートできますが、NetApp 10GbEおよび25GbEスイッチが不要になった場合は、100GbEクラスタ速度に更新することを推奨します。詳細については、次のナレッジベースの記事を参照してください。

* link:https://kb.netapp.com/on-prem/ontap/OHW/OHW-KBs/How_to_configure_10G_or_25G_cluster_ports_on_a_new_cluster_setup_on_AFF_ASA_A1K_A90_A70_FAS90_FAS70["AFF / ASA A1K、A90、A70、FAS90、FAS70の新しいクラスタセットアップで10Gまたは25Gのクラスタポートを構成する方法"^]
* link:https://kb.netapp.com/on-prem/ontap/OHW/OHW-KBs/How_to_convert_an_existing_cluster_from_10G_or_25G_cluster_ports_to_40G_or_100G_cluster_ports_on_an_AFF_ASA_A1K_A90_A70_FAS90_FAS70["AFF / ASA A1K、A90、A70、FAS90、FAS70で既存のクラスタを10Gまたは25Gのクラスタポートから40Gまたは100Gのクラスタポートに変換する方法"^]


AFF A20システムは、クラスタ接続とHA接続の両方で10GbEおよび25GbEネットワークポートを共有します。これらは、AFF A20システムでサポートされる唯一のネットワークポートクラスタ接続です。

既存のノードのクラスタポートe0aまたはe0bを新しいノードのクラスタポートにリンクできない場合は、を参照してください link:https://mysupport.netapp.com/site/bugs-online/product/ONTAP/JiraNgage/CONTAP-166978["NetApp Bugs OnlineのバグIDCONTAP-166978"^]。

====