---
sidebar: sidebar 
permalink: upgrade-arl-auto/decide_to_use_the_aggregate_relocation_guide.html 
keywords: aggregate relocation, decide to use, upgrade, model, matrix, replacement, controller 
summary: 'ONTAP 9.5 を実行しているコントローラを "system controller replace" コマンドを使用して 9.7 にアップグレードするために "ARL を使用するかどうかを決定します' 
---
= この集約再配置手順を使用するかどうかを決定します
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
コントローラハードウェアをアップグレードするには、アグリゲート再配置（ARL）の方法が複数あります。この手順では、ONTAP 9.7、9.6、または9.5を実行しているシステムで、「システムコントローラ置換コマンド」を使用してARLを使用してコントローラハードウェアをアップグレードする方法について説明します。この複雑な手順は、経験豊富なONTAP管理者のみが使用してください。

この ARL 手順がコントローラ ハードウェアのアップグレードに適しているかどうかを判断するには、サポートされているアップグレードについて次の状況をすべて確認する必要があります。

* ONTAP 9.5 、 9.6 、または 9.7 を実行しているネットアップコントローラをアップグレードする場合。本ドキュメントは、 ONTAP 9.8 へのアップグレードには適用されません。
* 新しいコントローラを新しいHAペアとしてクラスタに追加したり、ボリューム移動を使用してデータを移行したりすることはありません。
* ONTAP の管理経験があり、 diagnostic 権限モードで作業する場合のリスクが十分にあります。
* ハードウェアアップグレードの組み合わせは、 <<sys_commands_95_97_supported_systems,サポートされているモデルマトリックス>> 。
* MetroCluster 構成をアップグレードする場合は、 4 ノード以上の FC 構成になり、すべてのノードで ONTAP 9.6 または 9.7 を実行します。


[NOTE]
====
* AFF A800やAFF C800など、同じシャーシ内のコントローラモジュールを交換してシステムをアップグレードする場合、 NetApp、link:../upgrade-arl-auto-in-chassis/index.html["ARLを使用してコントローラモデルをアップグレードし、既存のシステムシャーシとディスクを維持します。"] 。この ARL 手順には、アップグレード手順中にコントローラを取り外したり取り付けたりするときに、内部ディスクがシャーシ内で安全な状態を保つための手順が含まれています。
+
link:../upgrade-arl-auto-in-chassis/decide-to-use-the-aggregate-relocation-guide.html#supported-systems-in-chassis["既存のシステムシャーシとディスクを維持しながら、ARLを使用してサポートされているシステムアップグレードの組み合わせについて学習します。"]。

* この手順 では、NetApp Storage Encryption（NSE）、NetApp Volume Encryption（NVE）、およびNetApp Aggregate Encryption（NAE）を使用できます。


====


== サポートされているシステムアップグレードの組み合わせ

次の表は、この ARL 手順を使用したコントローラのアップグレードでサポートされるモデル マトリックスを示しています。

[cols="50,50"]
|===
| 古いコントローラ | 交換用コントローラ 


| FAS8020 、 FAS8040 、 FAS8060 、 FAS8080 | FAS8200 、 FAS8300 、 FAS8700 、 FAS9000 


| AFF8020 、 AFF8040 、 AFF8060 、 AFF8080 | AFF A300 、 AFF A400 、 AFF A700 ^1 ^ 、 AFF A800^2^ 


| FAS8200 | FAS8700 、 FAS9000 、 FAS8300 ^4^ 、 ^5^ 


| AFF A300 | AFF A700 ^1 ^ 、 AFF A800 ^2 ^ ^ 、 ^3^ 、 AFF A400 ^ 4 ^ ^ 、 ^5^ 
|===

NOTE: コントローラのアップグレードモデルの組み合わせが上記の表にない場合は、テクニカルサポートにお問い合わせください。

^1 ^ARL AFF A700 システムの自動アップグレードは、 ONTAP 9.7P2 からサポートされています。

^2^ 内蔵ディスクと外付けディスクをサポートする AFF A800 システムに更新する場合は、内蔵 NVMe ディスクのルートアグリゲートに関する具体的な手順に従う必要があります。を参照してください link:set_fc_or_uta_uta2_config_on_node3.html#step14["ノード 3 の UTA / UTA2 ポートを確認して設定します。手順 14"] および link:set_fc_or_uta_uta2_config_node4.html#step14["ノード 4 の UTA / UTA2 ポートの確認と設定、手順 14"]。

^3^ARL AFF A300 から AFF A800 システムへの自動アップグレードは、 ONTAP 9.7P5 からサポートされています。

^4^ARL AFF A300 から AFF A400 への自動アップグレード、および FAS8200 から FAS8300 への自動アップグレードは、 ONTAP 9.7P8 からサポートされています。

^5^ AFF A300 から AFF A400 または FAS8200 を 2 ノードスイッチレスクラスタ構成で FAS8300 システムにアップグレードする場合は、コントローラのアップグレード用の一時的なクラスタポートを選択する必要があります。AFF A400 および FAS8300 システムは、イーサネットバンドルとして、メザニンカードポートはイーサネットタイプ、 FC タイプの FC バンドルとして、 2 種類の構成で提供されます。

* AFF A400 または FAS8300 では、イーサネットタイプの構成の場合、 2 つのメザニンポートのいずれかを一時的なクラスタポートとして使用できます。
* AFF A400 または FC タイプの構成で FAS8300 を使用する場合は、 4 ポートの 10GbE ネットワークインターフェイスカード（パーツ番号 X1147A ）を追加して一時的なクラスタポートを提供する必要があります。
* 一時的なクラスタポートを使用したコントローラのアップグレードが完了したら、クラスタ LIF を無停止で e3a および e3b 、 AFF A400 システムの 100GbE ポート、 FAS8300 システムの e0c および e0d 、 100GbE ポートに移行できます。




== 別のハードウェアアップグレード手順を選択する

* link:../upgrade-arl/index.html["コントローラハードウェアのアップグレードに使用できる代替ARL方法を確認します"]です。
* コントローラハードウェアを別の方法でアップグレードして、ボリュームの移動を希望する場合は、を参照してください link:other_references.html["参考資料"] をクリックして、ボリュームまたは storage _ を移動して _ Upgrade にリンクします。


.関連情報
参照link:other_references.html["参考資料"] _ONTAP 9 ドキュメント_にリンクします。
