---
sidebar: sidebar 
permalink: upgrade-arl-auto/ensure_new_controllers_are_set_up_correctly.html 
keywords: confirm, controllers, set up, ha, node3, node4, node2, lif, cluster, high, availability 
summary: 'ONTAP 9.5 を実行しているコントローラを "system controller replace" コマンドを使用してアップグレードした後 "HA ペアを有効にし " ノード 3 とノード 4 のストレージアクセスを確認し " アグリゲートの所有権を確認します' 
---
= 新しいコントローラが正しくセットアップされていることを確認します
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
正しいセットアップを確認するには、 HA ペアを有効にする必要があります。さらに、 node3 と node4 が相互のストレージにアクセスできること、およびクラスタ内の他のノードに属するデータ LIF を所有していないことを確認する必要があります。また、 node3 が node1 のアグリゲートを所有しており、 node4 が node2 のアグリゲートを所有していること、および両方のノードのボリュームがオンラインであることを確認する必要があります。

.手順
. node2 のチェック後、 node2 クラスタのストレージフェイルオーバーとクラスタ HA ペアが有効になります。処理が完了すると、両方のノードに「 Completed 」と表示され、クリーンアップ処理が実行されます。
. ストレージフェイルオーバーが有効になっていることを確認します。
+
「 storage failover show 」をクリックします

+
次の例は、ストレージフェイルオーバーが有効になっている場合のコマンドの出力例を示しています。

+
....
cluster::> storage failover show
                  Takeover
Node     Partner  Possible   State Description
-------- -----    -------    ------------------
node3    node4    true       Connected to node4
node4    node3    true       Connected to node3
....
. 次のコマンドを使用して、 node3 と node4 が同じクラスタに属していることを確認します。出力を確認します。
+
「 cluster show 」を参照してください

. 次のコマンドを使用して、 node3 と node4 が相互のストレージにアクセスできることを確認します。出力を確認します。
+
「 storage failover show -fields local-missing-disks 、 partner-missing-disks 」というメッセージが表示されます

. 次のコマンドを使用して、 node3 と node4 がクラスタ内の他のノードによってホーム所有されているデータ LIF を所有していないことを確認します。
+
「 network interface show 」を参照してください

+
node3 と node4 がクラスタ内の他のノードによってホーム所有されているデータ LIF を所有していない場合は、データ LIF をホーム所有者にリバートします。

+
「 network interface revert 」の略

. ノード 3 がノード 1 のアグリゲートを所有していること、およびノード 4 がノード 2 のアグリゲートを所有していることを確認します。
+
'storage aggregate show-owner-name<node3 >`

+
「 storage aggregate show-owner-name <node4 > 」という形式で指定します

. オフラインになっているボリュームがないかを確認します。
+
volume show -node <node3 > -state offline`

+
volume show -node <node4 > -state offline`

. オフラインになっているボリュームがある場合は、セクションで取得したオフラインボリュームのリストと比較します link:prepare_nodes_for_upgrade.html["ノードをアップグレードする準備をします"]必要に応じて、次のコマンドを使用して、ボリュームごとに 1 回、オフラインボリュームをオンラインにします。
+
'volume online -vserver <vserver_name> -volume <volume_name>`

. ノードごとに次のコマンドを使用して、新しいノードの新しいライセンスをインストールします。
+
'system license add - license-code <license_code, license_code, license_code...>`

+
license-code パラメータには、アルファベットの文字キーをアルファベットの大文字 28 個まで入力できます。ライセンスは一度に 1 つずつ追加することも、複数追加することもできます。各ライセンスキーをカンマで区切って指定することもできます。

. 次のいずれかのコマンドを使用して、元のノードから古いライセンスをすべて削除します。
+
「システムライセンスのクリーンアップ - 未使用 - 期限切れ」

+
「 system license delete -serial -number <node-serial_number> -package <license_package> 」という 2 つのライセンスがあります

+
--
** 期限切れのライセンスをすべて削除します。
+
「システムライセンスのクリーンアップ - 期限切れ」

** 未使用のライセンスをすべて削除します。
+
'System license clean-up-unused （システムライセンスのクリーンアップ - 未使用） '

** クラスタから特定のライセンスを削除するには、ノードで次のコマンドを使用します。
+
system license delete -serial-number <node1 _serial_number>-package *`

+
system license delete -serial-number <node2 _ serial_number> -package *`



--
+
次の出力が表示されます。

+
....
Warning: The following licenses will be removed:
<list of each installed package>
Do you want to continue? {y|n}: y
....
+
すべてのパッケージを削除するには 'y' を入力します

. 次のコマンドを使用して出力を調べ、ライセンスが正しくインストールされていることを確認します。
+
「 system license show 」を参照してください

+
出力を、セクションでキャプチャした出力と比較できます link:prepare_nodes_for_upgrade.html["ノードをアップグレードする準備をします"]。

. 構成に NetApp Storage Encryption （ NSE ）を使用していた場合は、「 setenvbootarg .bootarg.storageencryption.support 」コマンドを「 true 」に設定し、「 <kmip.init.maxwait>` variable 」を「 off 」に設定します（を参照） link:install_boot_node4.html#step27["Node4 をインストールしてブートします（手順 27 ）"]）を使用している場合は、変数をリセットする必要があります。
+
`set diag; systemshell -node <node_name > コ \'83\'7d ンド sudo kenv -u -p kmip.init.maxwait`



. [[Step13]] 両方のノードで次のコマンドを使用して、 SP を設定します。
+
「 system service-processor network modify -node <node_name > 」のように指定します

+
を参照してください link:other_references.html["参考資料"] SP および _SP ONTAP 9 コマンドの詳細については ' システム管理リファレンスにリンクするには ' マニュアルページリファレンスを参照してください system の service-processor network modify コマンドの詳細については ' を参照してください

. 新しいノードの 1 つで次の操作を実行します。
+
.. advanced 権限レベルに切り替えます。
+
「 advanced 」の権限が必要です

.. 次のコマンドを入力します。
+
「 storage failover modify -node <node_name > -CIFS-NDO -duration default | medium | low 」

+
*** システムのワークロードが 50% ～ 75% の場合は、「 m edium 」と入力します。
*** システムのワークロードが 75% ～ 100% の場合は 'low' と入力します


.. admin レベルに戻ります。
+
「特権管理者」

.. システムをリブートして、変更が有効になっていることを確認します。


. 新しいノードにスイッチレスクラスタをセットアップする場合は、を参照してください link:other_references.html["参考資料"] ネットアップサポートサイトへのリンクを設定するには、 _ 2 ノードスイッチレスクラスタへの移行の手順に従ってください。


ノード 3 とノード 4 でストレージ暗号化が有効になっている場合は、セクションを完了します link:set_up_storage_encryption_new_module.html["新しいコントローラモジュールで Storage Encryption をセットアップします"]。それ以外の場合は、の項を実行します link:decommission_old_system.html["古いシステムの運用を停止"]。
