---
sidebar: sidebar 
permalink: upgrade-arl-auto/guidelines_for_upgrading_controllers_with_arl.html 
keywords: upgrade, controllers, guidelines, ARL, aggregate relocation, supported upgrades, two-node, cluster, troubleshoot 
summary: 'ONTAP 9.5 を実行しているコントローラを "system controller replace" コマンドを使用して 9.7 にアップグレードできるかどうかを理解します' 
---
= ARL を使用したコントローラのアップグレードに関するガイドライン
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
アグリゲートの再配置（ ARL ）を使用して ONTAP 9.5 を実行するコントローラのペアを ONTAP 9.7 にアップグレードできるかどうかは、プラットフォームと、元のコントローラと交換用コントローラの両方の構成によって異なります。



== ARL のアップグレードがサポートされます

この ARL 手順 for ONTAP 9.5 を使用して ONTAP 9.7 にノードのペアをアップグレードする場合は、 ARL が元のコントローラと交換用コントローラで実行可能であることを確認する必要があります。

元のシステムでサポートされるすべての定義済みアグリゲートのサイズとディスク数を確認する必要があります。次に、サポートされるアグリゲートサイズとディスク数を、新しいシステムでサポートされるアグリゲートサイズとディスク数と比較する必要があります。を参照してください link:other_references.html["参考資料"] この情報がある Hardware Universe にリンクするには、次の手順を実行します。新しいシステムでサポートされるアグリゲートサイズとディスク数は、元のシステムでサポートされるアグリゲートサイズとディスク数以上であることが必要です。

元のコントローラを交換したときに、新しいノードが既存のノードとクラスタの一部になることができるかどうかは、クラスタ混在ルールで検証する必要があります。クラスタ混在ルールの詳細については、を参照してください link:other_references.html["参考資料"] Hardware Universe にリンクするには、次の手順を実行します。


NOTE: AFF システムのアップグレードを実行する前に、 ONTAP をリリースバージョン 9.5P1 以降にアップグレードする必要があります。これらのリリースレベルは、アップグレードを成功させるために必要です。


NOTE: 内蔵ドライブをサポートするシステム（ FAS2700 または AFF A250 など）をアップグレードする場合でも内蔵ドライブがないときは、を参照してください link:other_references.html["参考資料"] および、 _ アグリゲートの再配置に含まれる手順を使用して、使用している ONTAP のバージョンに適したコントローラ Hardware_content を手動でアップグレードします。

ONTAP 9.6P11 、 9.7P8 、またはそれ以降のリリースを使用している場合は、 Connectivity 、 live, and Availability Monitor （ CLAM ）のテイクオーバーを有効にして、特定のノード障害が発生したときにクラスタをクォーラムに戻すことを推奨します。「 kernel-service 」コマンドには、 advanced 権限レベルのアクセスが必要です。詳細については、を参照してください https://kb.netapp.com/Support_Bulletins/Customer_Bulletins/SU436["ネットアップの技術情報アーティクル SU436 ：「 clam takeover default configuration changed"^]。

ARL を使用したコントローラのアップグレードは、 SnapLock Enterprise ボリュームおよび SnapLock Compliance ボリュームが設定されたシステムでサポートされます。



== 2 ノードスイッチレスクラスタ

2 ノードスイッチレスクラスタのノードをアップグレードする場合は、アップグレードの実行中もスイッチレスクラスタのノードをそのまま使用できます。スイッチクラスタに変換する必要はありません。



== ARL のアップグレードはサポートされていません

次のアップグレードは実行できません。

* 元のコントローラに接続されたディスクシェルフをサポートしない交換用コントローラへの接続
+
を参照してください link:other_references.html["参考資料"] ディスクサポート情報の Hardware Universe にリンクするには、次の手順を実行します。

* 内蔵ドライブを搭載したエントリレベルのコントローラ。たとえば、 FAS 2500 などです。
+
内蔵ドライブを搭載したエントリレベルのコントローラをアップグレードする場合は、を参照してください link:other_references.html["参考資料"] ボリュームまたは storage を移動して _Upgrade にリンクし、 Data ONTAP に移動して、 clustered 手順を実行するノードのペアをアップグレードする _ に進みます。





== トラブルシューティング

コントローラのアップグレード中に問題が発生した場合は、を参照してください link:troubleshoot.html["トラブルシューティングを行う"] 詳細および解決策については、手順の末尾にあるセクションを参照してください。

発生した問題に対する解決策 が見つからない場合は、テクニカルサポートにお問い合わせください。
