---
sidebar: sidebar 
permalink: upgrade-arl-auto/guidelines_for_upgrading_controllers_with_arl.html 
keywords: upgrade, controllers, guidelines, ARL, aggregate relocation, supported upgrades, two-node, cluster, troubleshoot 
summary: 'ONTAP 9.5 を実行しているコントローラを "system controller replace" コマンドを使用して 9.7 にアップグレードできるかどうかを理解します' 
---
= ARL を使用したコントローラのアップグレードに関するガイドライン
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
アグリゲートの再配置（ ARL ）を使用して ONTAP 9.5 を実行するコントローラのペアを ONTAP 9.7 にアップグレードできるかどうかは、プラットフォームと、元のコントローラと交換用コントローラの両方の構成によって異なります。



[[supported-upgrades-for-arl]]
== ARL のアップグレードがサポートされます

この ARL 手順 for ONTAP 9.5 を使用して ONTAP 9.7 にノードのペアをアップグレードする場合は、 ARL が元のコントローラと交換用コントローラで実行可能であることを確認する必要があります。

定義済みのすべてのアグリゲートのサイズと、元のシステムでサポートされているディスクの数を確認する必要があります。次に、アグリゲート サイズとサポートされているディスクの数を、新しいシステムでサポートされているアグリゲート サイズおよびディスクの数と比較する必要があります。link:other-references.html["参考資料"]を参照して、この情報が掲載されている _Hardware Universe_ にアクセスしてください。新しいシステムでサポートされるアグリゲート サイズおよびディスクの数は、元のシステムでサポートされているアグリゲート サイズおよびディスクの数以上である必要があります。

クラスタ混合ルールにおいて、元のコントローラが交換された場合に、新しいノードが既存のノードと共にクラスタの一部となることができるかどうかを検証する必要があります。クラスタ混合ルールの詳細については、link:other-references.html["参考資料"]を参照して _Hardware Universe_ にアクセスしてください。


NOTE: AFF システムのアップグレードを実行する前に、 ONTAP をリリースバージョン 9.5P1 以降にアップグレードする必要があります。これらのリリースレベルは、アップグレードを成功させるために必要です。


NOTE: 内蔵ドライブをサポートするシステム（例：FAS2700 または AFF A250）をアップグレードする場合で、内蔵ドライブが搭載されていない場合は、link:other-references.html["参考資料"]を参照し、お使いの ONTAP バージョンに適した _Aggregate Relocation to Manually Upgrade Controller Hardware_ コンテンツの手順を使用してください。

ONTAP 9.6P11 、 9.7P8 、またはそれ以降のリリースを使用している場合は、 Connectivity 、 live, and Availability Monitor （ CLAM ）のテイクオーバーを有効にして、特定のノード障害が発生したときにクラスタをクォーラムに戻すことを推奨します。「 kernel-service 」コマンドには、 advanced 権限レベルのアクセスが必要です。詳細については、を参照してください https://kb.netapp.com/Support_Bulletins/Customer_Bulletins/SU436["ネットアップの技術情報アーティクル SU436 ：「 clam takeover default configuration changed"^]。

ARL を使用したコントローラのアップグレードは、 SnapLock Enterprise ボリュームおよび SnapLock Compliance ボリュームが設定されたシステムでサポートされます。



[[two-node-switchless-clusters]]
== 2 ノードスイッチレスクラスタ

2 ノードスイッチレスクラスタのノードをアップグレードする場合は、アップグレードの実行中もスイッチレスクラスタのノードをそのまま使用できます。スイッチクラスタに変換する必要はありません。



[[upgrades-not-supported-for-arl]]
== ARL のアップグレードはサポートされていません

次のアップグレードは実行できません。

* 元のコントローラに接続されたディスクシェルフをサポートしない交換用コントローラへの接続
+
link:other-references.html["参考資料"]を参照して、ディスクサポート情報の _Hardware Universe_ にリンクしてください。

* 内部ドライブを備えたエントリーレベルのコントローラ（例：FAS2750）。
+
内部ドライブを搭載したエントリーレベルのコントローラーをアップグレードする場合は、link:other-references.html["参考資料"] を参照して「ボリュームまたはストレージの移動によるアップグレード」にリンクし、「ボリュームを移動することによるクラスタ化された Data ONTAP を実行するノードペアのアップグレード」の手順に進んでください。





[[metrocluster-fc-configuration]]
== MetroCluster FC 構成

MetroCluster FC構成では、できるだけ早くディザスタリカバリ/フェイルオーバーサイトのノードを交換する必要があります。MetroCluster構成内のコントローラモデルの不一致はサポートされません。コントローラモデルの不一致により、災害復旧ミラーリングがオフラインになる可能性があるためです。  `-skip-metrocluster-check true` 2 番目のサイトでノードを交換するときに MetroCluster チェックをバイパスするコマンド。



[[troubleshoot]]
== トラブルシューティングを行う

ノードペアのアップグレード中に障害が発生する可能性があります。ノードがクラッシュする、アグリゲートが再配置されない、または LIF が移行されない可能性があります。障害の原因とその解決策は、アップグレード手順の実行中に障害が発生したタイミングによって異なります。

ARL アップグレードの概要のセクションで、手順のさまざまなフェーズを説明している表を参照してください。発生する可能性のある障害の情報は、手順のフェーズ別に表示されます。

コントローラのアップグレード中に問題が発生した場合は、link:aggregate_relocation_failures.html["トラブルシューティングを行う"]セクション。発生する可能性のある障害に関する情報は、手順のフェーズごとにリストされています。link:overview_of_the_arl_upgrade.html["ARLアップグレードシーケンス"] 。

発生した問題に対する解決策 が見つからない場合は、テクニカルサポートにお問い合わせください。
