---
sidebar: sidebar 
permalink: upgrade-arl-auto/index.html 
keywords: aggregate, relocation, controller, hardware, aggregates, flexarray, metrocluster, terminology 
summary: 交換用コントローラハードウェアを使用して元のコントローラハードウェアをアップグレードし、ルート以外のアグリゲートの所有権を切り替えます。 
---
= 「 system controller replace 」コマンドを使用して、 ONTAP 9.5 を実行するコントローラハードウェアを ONTAP 9.7 にアップグレードします
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
手順の実行中に、交換用コントローラハードウェアを使用して元のコントローラハードウェアをアップグレードし、ルート以外のアグリゲートの所有権を切り替えます。アグリゲートをノードからノードに複数回移行して、アップグレード手順全体を通じて少なくとも 1 つのノードがアグリゲートからデータを提供していることを確認します。また、処理を続行する前に、データ論理インターフェイス（ LIF ）を移行し、新しいコントローラのネットワークポートをインターフェイスグループに割り当てます。

この情報では、元のノードの名前は「 node1 」と「 node2 」になり、新しいノードの名前は「 node3 」と「 node4 」になります。説明されている手順では、「 node1 」は「 node3 」に置き換えられ、「 node2 」は「 node4 」に置き換えられます。

「 node1 」、「 node2 」、「 node3 」、および「 node4 」は、元のノードと新しいノードを区別するためだけに使用されます。手順を使用するときは、元のノードと新しいノードの実際の名前を置き換える必要があります。ただし実際には、ノードの名前は変更されません。「 node3 」の名前は「 node1 」と同じで、「 node4 」の名前はコントローラハードウェアのアップグレード後に「 node2 」と同じです。

この情報の中で、「 FlexArray 仮想化ソフトウェアを搭載したシステム」とは、これらの新しいプラットフォームに属するシステムを指します。「 V シリーズシステム」という用語は、ストレージアレイに接続可能な独立したハードウェアシステムを指します。

.注意すべき重要な情報
* この手順は複雑で、 ONTAP の高度な管理スキルがあることを前提としています。また、内容を読んで理解しておく必要があります link:guidelines_for_upgrading_controllers_with_arl.html["ARL を使用したコントローラのアップグレードに関するガイドライン"] および  アップグレードを開始する前に、
* この手順は、交換用コントローラハードウェアが新しく購入され、使用されていないことを前提としています。使用済みのコントローラを「 wipeconfig 」コマンドで準備するために必要な手順は、この手順には含まれていません。交換用コントローラハードウェアを以前に使用していた場合は、テクニカルサポートに問い合わせる必要があります。特に、コントローラが Data ONTAP 7-Mode を実行していた場合は、テクニカルサポートにお問い合わせください。
* この手順を使用して、ノードが 3 つ以上あるクラスタのコントローラハードウェアをアップグレードできますが、クラスタ内の HA ペアごとに手順を個別に実行する必要があります。
* この FlexArray システム、 V シリーズシステム、 AFF システム、および手順環境 FAS 仮想化ソフトウェアを搭載したシステムです。必要なライセンスがインストールされていれば、 ONTAP 9.5 以降にリリースされた FAS システムをストレージアレイに接続できます。既存の V シリーズシステムは、 ONTAP 9.5 でサポートされます。ストレージアレイと V シリーズのモデルの詳細については、を参照してください link:other_references.html["参考資料"] Hardware Universe にリンクして、 V シリーズサポートマトリックスにアクセスしてください。
* ONTAP 9.6 以降では、この手順環境システムで 4 ノード MetroCluster 構成以上を実行しています。MetroCluster 構成サイトは物理的に異なる場所に設置できるため、 HA ペアの場合は各 MetroCluster サイトでコントローラの自動アップグレードを個別に実行する必要があります。
* AFF A320 システムからアップグレードする場合は、ボリューム移動を使用してコントローラハードウェアをアップグレードするか、テクニカルサポートにお問い合わせください。ボリュームの移動を希望する場合は、を参照してください link:other_references.html["参考資料"] をクリックして、ボリュームまたは storage _ を移動して _ Upgrade にリンクします。

