---
sidebar: sidebar 
permalink: upgrade-arl-auto/map_ports_node2_node4.html 
keywords: map, node2, ports, cluster, broadcast domains, physical ports 
summary: 'ONTAP 9.5 を実行しているコントローラを 9.7 にアップグレードするときに "system controller replace" コマンドを使用して "node2 の物理ポートが node4 に正しくマッピングされていることを確認します' 
---
= node2 のポートを node4 にマッピングします
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
node2 の物理ポートが node4 の物理ポートに正しくマッピングされていることを確認する必要があります。これにより、 node4 はクラスタ内の他のノードと通信し、アップグレード後にネットワークと通信できるようになります。

.このタスクについて
を参照してください link:other_references.html["参考資料"] Hardware Universe にリンクして新しいノードのポートに関する情報を取得するには、次の手順を実行します。このセクションの後半の情報を使用します。

ノード 4 のソフトウェア設定がノード 4 の物理的な接続と一致していること、およびアップグレードを続行する前に IP 接続がリストアされていることが必要です。

ポート設定は、ノードのモデルによって異なる場合があります。元のノードのポートと LIF の構成を、新しいノードの構成と互換性を持つようにする必要があります。これは、新しいノードがブート時に同じ設定を再生するためです。つまり、ノード 4 のブート時に、 Data ONTAP が node2 で使用されていたポートで LIF をホストするように試行するためです。

したがって、 node2 の物理ポートが node4 の物理ポートに直接マッピングされない場合は、ブート後にクラスタ、管理、およびネットワーク接続をリストアするためにソフトウェア設定の変更が必要となります。また、 node2 のクラスタポートが node4 のクラスタポートに直接マッピングされていない場合は、正しい物理ポートでクラスタ LIF をホストするソフトウェア設定が変更されるまで、リブート時に node4 がクォーラムに自動的に再参加しないことがあります。

.手順
. node2 、ポート、ブロードキャストドメイン、 IPspace のすべてのケーブル接続情報を表に記録します。
+
[cols="7*"]
|===
| LIF | Node2 ポート | ノード 2 の IPspace | ノード 2 のブロードキャストドメイン | Node4 ポート | ノード 4 の IPspace | ノード 4 のブロードキャストドメインが必要です 


| クラスタ 1 |  |  |  |  |  |  


| クラスタ 2 |  |  |  |  |  |  


| クラスタ 3 |  |  |  |  |  |  


| クラスタ 4 |  |  |  |  |  |  


| ノード管理 |  |  |  |  |  |  


| クラスタ管理 |  |  |  |  |  |  


| データ 1 |  |  |  |  |  |  


| データ 2. |  |  |  |  |  |  


| データ 3 |  |  |  |  |  |  


| データ 4. |  |  |  |  |  |  


| SAN |  |  |  |  |  |  


| クラスタ間ポート |  |  |  |  |  |  
|===
. ノード 4 、ポート、ブロードキャストドメイン、および IPspace のすべてのケーブル接続情報を表に記録します。
. セットアップが 2 ノードスイッチレスクラスタかどうかを確認するには、次の手順を実行します。
+
.. 権限レベルを advanced に設定します。
+
'cluster::> set -privilege advanced

.. セットアップが 2 ノードスイッチレスクラスタかどうかを確認します。
+
'cluster::> network options switchless-cluster show

+
[listing]
----
cluster::*> network options switchless-cluster show
Enable Switchless Cluster: false/true
----
+
このコマンドの値は、システムの物理状態と一致している必要があります。

.. 管理者権限レベルに戻ります。
+
[listing]
----
cluster::*> set -privilege admin
cluster::>
----


. ノード 4 をクォーラムに追加する手順は、次のとおりです。
+
.. ノード 4 をブートします。を参照してください link:install_boot_node4.html["ノード 4 をインストールしてブートします"] ノードをブートします（まだブートしていない場合）。
.. 新しいクラスタポートが Cluster ブロードキャストドメインにあることを確認します。
+
「network port show -node _-port_port_-fields broadcast-domain」を指定します

+
次の例は、ポート「 e0a 」が node4 にあるクラスタドメイン内にあることを示しています。

+
[listing]
----
cluster::> network port show -node node4 -port e0a -fields broadcast-domain
node       port broadcast-domain
---------- ---- ---------------
node4      e0a  Cluster
----
.. クラスタポートが Cluster broadcast-domain にない場合は、次のコマンドを使用して追加します。
+
'broadcast-domain add-ports -ipspace Cluster-broadcast-domain Cluster-ports_node: port_`

.. クラスタブロードキャストドメインに適切なポートを追加します。
+
network port modify -node -port -ipspace Cluster -mtu 9000`

+
次の例では、 node4 にクラスタポート「 e1b 」を追加します。

+
network port modify -node node4 -port e1b -ipspace Cluster -mtu 9000`

.. LIF を 1 つずつ新しいポートに移行します。
+
「network interface migrate -vserver Cluster -lif LIF_name -source-node node4 destination -node node4 -destination-port_name_`

.. クラスタ LIF のホームポートを変更します。
+
「network interface modify -vserver Cluster -lif LIF_name–home-port_port_name_`」です

.. クラスタブロードキャストドメインから古いポートを削除します。
+
「 network port broadcast-domain remove-ports 」と入力します

+
次のコマンドは、ノード 4 のポート「 e0d 」を削除します。

+
「 network port broadcast-domain remove-ports -ipspace Cluster -broadcast-domain Cluster -ports node4 ： e0d

.. ノード 4 が再びクォーラムメンバーになったことを確認します。
+
cluster show -node node4 -fields health`



. [[auto_map_4_Step5] クラスタ LIF およびノード管理 / クラスタ管理 LIF をホストしているブロードキャストドメインを調整します。各ブロードキャストドメインに正しいポートが含まれていることを確認します。ホストしているブロードキャストドメイン間または LIF がホームにあるブロードキャストドメイン間でポートを移動することはできないため、次の手順に示すように、 LIF を移行して変更しなければならない場合があります。
+
.. LIF のホームポートを表示します。
+
network interface show -fields home-node 、 home-port

.. このポートを含むブロードキャストドメインを表示します。
+
「network port broadcast-domain show -ports_node_name：port_name_`

.. ブロードキャストドメインのポートを追加または削除します。
+
「 network port broadcast-domain add-ports 」「 network port broadcast-domain remove-ports 」

.. LIF のホームポートを変更します。
+
「network interface modify -vserver _vserver_-lif lif_name _–home-port_port_name_`」です



. 必要に応じて、と同じコマンドを使用して、クラスタ間ブロードキャストドメインを調整してクラスタ間 LIF を移行します <<auto_map_4_Step5,手順 5>>。
. 必要に応じて、のコマンドと同じコマンドを使用して、他のブロードキャストドメインを調整してデータ LIF を移行します <<auto_map_4_Step5,手順 5>>。
. node2 に存在しないポートが残っている場合は、次の手順に従って削除します。
+
.. どちらかのノードで advanced 権限レベルにアクセスします。
+
「 advanced 」の権限が必要です

.. ポートを削除します。
+
'network port delete -node_node_name -- port_port_port_name_`

.. admin レベルに戻ります。
+
「特権管理者」



. すべての LIF フェイルオーバーグループを調整します。
+
'network interface modify -failover-group_failover_group'-failover-policy_failover_policy_`

+
次のコマンドは ' フェイルオーバー・ポリシーを broadcast-domain-wide に設定し ' フェイルオーバー・グループ fg1 のポートを 'node4 の LIF のフェイルオーバー・ターゲットとして使用します

+
'network interface modify -vserver node4 -lif data1 failover-policy broadcast-domainwide -failover-group fg1

+
を参照してください link:other_references.html["参考資料"] ネットワーク管理 _ または _ ONTAP 9 コマンド：マニュアルページリファレンス _ および _ LIF でのフェイルオーバー設定の詳細については、 _ を参照してください。

. ノード 4 で変更を確認します。
+
「 network port show -node node4 」

. 各クラスタ LIF がポート 7700 をリスンしている必要があります。クラスタ LIF がポート 7700 をリスンしていることを確認します。
+
`::> network connections listening show -vserver Cluster `

+
次の 2 ノードクラスタの例に示すように、クラスタポートでリスンしているポート 7700 は想定される結果です。

+
[listing]
----
Cluster::> network connections listening show -vserver Cluster
Vserver Name     Interface Name:Local Port     Protocol/Service
---------------- ----------------------------  -------------------
Node: NodeA
Cluster          NodeA_clus1:7700               TCP/ctlopcp
Cluster          NodeA_clus2:7700               TCP/ctlopcp
Node: NodeB
Cluster          NodeB_clus1:7700               TCP/ctlopcp
Cluster          NodeB_clus2:7700               TCP/ctlopcp
4 entries were displayed.
----
. ポート7700をリスンしていない各クラスタLIFについて、LIFの管理ステータスをに設定します。 `down` 次に `up`：
+
`::> net int modify -vserver Cluster-lif cluster_lif_cluster-status-admin down；net int modify -vserver Cluster-lif cluster_lif_-status-admin up

+
手順 11 を繰り返して、クラスタ LIF がポート 7700 でリスンしていることを確認します。


