---
sidebar: sidebar 
permalink: upgrade-arl-auto/map_ports_node1_node3.html 
keywords: map, port, node1, node3, settings, restore, cluster 
summary: 'ONTAP 9.5 を実行しているコントローラを 9.7 にアップグレードするときに "system controller replace" コマンドを使用して "node1 の物理ポートが node3 に正しくマッピングされていることを確認します' 
---
= ポートを node1 から node3 にマッピングします
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
node1 の物理ポートが node3 の物理ポートに正しくマッピングされていることを確認する必要があります。これにより、 node3 はクラスタ内の他のノードおよびアップグレード後にネットワークと通信できるようになります。

.このタスクについて
を参照してください link:other_references.html["参考資料"] Hardware Universe にリンクして新しいノードのポートに関する情報を取得するには、次の手順を実行します。このセクションの後半の情報を使用します。

ポート設定は、ノードのモデルによって異なる場合があります。元のノードのポートと LIF の設定を、新しいノードの計画的な使用と設定に対応させる必要があります。これは、新しいノードがブート時に同じ設定を再生するためです。つまり、ノード 3 をブートすると、 ONTAP は、ノード 1 で使用されていたポートで LIF をホストしようとします。

そのため、 node1 の物理ポートが node3 の物理ポートに直接マッピングされていない場合は、ブート後にクラスタ、管理、およびネットワーク接続をリストアするためにソフトウェア設定の変更が必要になります。また、ノード 1 のクラスタポートがノード 3 のクラスタポートに直接マッピングされていない場合、ノード 3 は、正しい物理ポートでクラスタ LIF をホストするソフトウェア設定を変更するまで、リブート時にクォーラムに自動的に再参加しないことがあります。

.手順
. node1 、ポート、ブロードキャストドメイン、および IPspace のすべての node1 ケーブル接続情報を表に記録します。
+
|===
| LIF | Node1 ポート | ノード 1 の IPspace | ノード 1 のブロードキャストドメインです | Node3 ポート | ノード 3 の IPspace | ノード 3 のブロードキャストドメイン 


| クラスタ 1 |  |  |  |  |  |  


| クラスタ 2 |  |  |  |  |  |  


| クラスタ 3 |  |  |  |  |  |  


| クラスタ 4 |  |  |  |  |  |  


| ノード管理 |  |  |  |  |  |  


| クラスタ管理 |  |  |  |  |  |  


| データ 1 |  |  |  |  |  |  


| データ 2. |  |  |  |  |  |  


| データ 3 |  |  |  |  |  |  


| データ 4. |  |  |  |  |  |  


| SAN |  |  |  |  |  |  


| クラスタ間ポート |  |  |  |  |  |  
|===
. ノード 3 、ポート、ブロードキャストドメイン、および IPspace のすべてのケーブル接続情報を表に記録します。
. セットアップが 2 ノードスイッチレスクラスタかどうかを確認するには、次の手順を実行します。
+
.. 権限レベルを advanced に設定します。
+
'cluster::> set -privilege advanced

.. セットアップが 2 ノードスイッチレスクラスタかどうかを確認します。
+
'cluster::> network options switchless-cluster show

+
[listing]
----
cluster::*> network options switchless-cluster show

Enable Switchless Cluster: false/true
----
+
このコマンド出力の値は、システムの物理状態と一致する必要があります。

.. 管理者権限レベルに戻ります。
+
[listing]
----
cluster::*> set -privilege admin

cluster::>
----


. ノード 3 をクォーラムに配置するには、次の手順を実行します
+
.. ノード 3 をブートします。を参照してください link:install_boot_node3.html["node3 をインストールしてブートします"] ノードをブートします（まだブートしていない場合）。
.. 新しいクラスタポートが Cluster ブロードキャストドメインにあることを確認します。
+
「network port show -node _-port_port_-fields broadcast-domain」を指定します

+
次の例は、ポート「 e0a 」が node3 のクラスタドメインにあることを示しています。

+
[listing]
----
 cluster::> network port show -node _node3_ -port e0a -fields broadcast-domain

 node       port broadcast-domain
 ---------- ---- ----------------
 node3      e0a  Cluster
----
.. クラスタポートが Cluster broadcast-domain にない場合は、次のコマンドを使用して追加します。
+
'broadcast-domain add-ports -ipspace Cluster-broadcast-domain Cluster-ports_node: port_`

+
次の例は、ノード 3 にクラスタポート「 e1b 」を追加します。

+
[listing]
----
network port modify -node node3 -port e1b -ipspace Cluster -mtu 9000
----
.. クラスタブロードキャストドメインに適切なポートを追加します。
+
network port modify -node -port -ipspace Cluster -mtu 9000`

+
次の例では、 node4 にクラスタポート「 e1b 」を追加します。

+
[listing]
----
network port modify -node node4 -port e1b -ipspace Cluster -mtu 9000
----
.. LIF を 1 つずつ新しいポートに移行します。
+
「network interface migrate -vserver Cluster -lif LIF_name -source-node _node3_node3_destination-node-node3 _ destination-port_port_name_`

.. クラスタ LIF のホームポートを変更します。
+
「network interface modify -vserver Cluster -lif LIF_name–home-port_port_name_`」です

.. クラスタブロードキャストドメインから古いポートを削除します。
+
「 network port broadcast-domain remove-ports 」と入力します

+
次のコマンドは、ノード 3 のポート「 e0d 」を削除します。

+
「 network port broadcast-domain remove-ports -ipspace Cluster -broadcast-domain Cluster ‑ ports node3 ： e0d

.. ノード 3 が再びクォーラムに参加したことを確認します。
+
cluster show -node node3 -fields health`



. [[auto_map_3_step5] クラスタ LIF とノード管理 / クラスタ管理 LIF をホストするブロードキャストドメインを調整します。各ブロードキャストドメインに正しいポートが含まれていることを確認します。ポートをホストしているブロードキャストドメイン間や LIF のホームになっているブロードキャストドメイン間で移動することはできないため、 LIF を移行して変更する必要がある場合があります。
+
.. LIF のホームポートを表示します。
+
network interface show -fields home-node 、 home-port

.. このポートを含むブロードキャストドメインを表示します。
+
「network port broadcast-domain show -ports_node_name：port_name_`

.. ブロードキャストドメインのポートを追加または削除します。
+
「 network port broadcast-domain add-ports 」と入力します

+
「 network port broadcast-domain remove-ports 」と入力します

.. LIF のホームポートを変更します。
+
「network interface modify -vserver vserver-lif lif_name _–home-port_port_name_`」になります



. に示すコマンドを使用して、クラスタ間 LIF に使用されるネットワークポートのブロードキャストドメインメンバーシップを調整します <<auto_map_3_step5,手順 5>>。
. 必要に応じて、のコマンドと同じコマンドを使用して、他のブロードキャストドメインを調整してデータ LIF を移行します <<auto_map_3_step5,手順 5>>。
. ノード 1 にノード 3 に存在しないポートがある場合は、次の手順に従って削除します。
+
.. どちらかのノードで advanced 権限レベルにアクセスします。
+
「 advanced 」の権限が必要です

.. ポートを削除します。
+
'network port delete -node_node_name -- port_port_port_name_`

.. admin レベルに戻ります。
+
「特権管理者」



. すべての LIF フェイルオーバーグループを調整します。
+
'network interface modify -failover-group_failover_group'-failover-policy_failover_policy_`

+
次のコマンドは、フェイルオーバーポリシーを「 broadcast-domain-wide 」に設定し、ノード 3 の LIF 「 data1 」のフェイルオーバーターゲットとして、フェイルオーバーグループ「 fg1 」のポートを使用します。

+
network interface modify -vserver node3 -lif data1 failover-policy broadcast-domain-domainwide -failover-group fg1

+
を参照してください link:other_references.html["参考資料"] をクリックして、 _Network Management_ または _ONTAP 9 コマンド：マニュアルページリファレンスにリンクしてください。

. ノード 3 で変更内容を確認します。
+
network port show -node node3

. 各クラスタ LIF がポート 7700 をリスンしている必要があります。クラスタ LIF がポート 7700 をリスンしていることを確認します。
+
`::> network connections listening show -vserver Cluster `

+
次の 2 ノードクラスタの例に示すように、クラスタポートでリスンしているポート 7700 は想定される結果です。

+
[listing]
----
Cluster::> network connections listening show -vserver Cluster
Vserver Name     Interface Name:Local Port     Protocol/Service
---------------- ----------------------------  -------------------
Node: NodeA
Cluster          NodeA_clus1:7700               TCP/ctlopcp
Cluster          NodeA_clus2:7700               TCP/ctlopcp
Node: NodeB
Cluster          NodeB_clus1:7700               TCP/ctlopcp
Cluster          NodeB_clus2:7700               TCP/ctlopcp
4 entries were displayed.
----
. ポート7700をリスンしていない各クラスタLIFについて、LIFの管理ステータスをに設定します。 `down` 次に `up`：
+
`::> net int modify -vserver Cluster-lif cluster_lif_cluster-status-admin down；net int modify -vserver Cluster-lif cluster_lif_-status-admin up

+
手順 11 を繰り返して、クラスタ LIF がポート 7700 でリスンしていることを確認します。


