---
sidebar: sidebar 
permalink: upgrade-arl-auto/move_non_root_aggr_and_nas_data_lifs_node2_from_node3_to_node4.html 
keywords: move, non-root, aggregates, nas, lif, node2, node3, node4 
summary: 'ONTAP 9.5 を実行しているコントローラを "system controller replace" コマンドを使用して 9.7 にアップグレードする場合 " ノード 3 の NAS データ LIF を node3 から node4 に移動します' 
---
= node2 によって所有されているルート以外のアグリゲートと NAS データ LIF を、 node3 から node4 に移動します
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ノード 4 のインストールの確認が完了し、ノード 3 からノード 4 にアグリゲートを再配置する前に、現在ノード 3 にある node2 に属する NAS データ LIF をノード 3 からノード 4 に移動する必要があります。また、ノード 4 に SAN LIF が存在することを確認する必要があります。

アップグレード手順の実行中、リモート LIF は SAN LUN へのトラフィックを処理します。アップグレード時にクラスタやサービスの健全性を維持するために、 SAN LIF を移動する必要はありません。SAN LIF は、新しいポートにマッピングする必要がないかぎり移動されません。ノード 4 をオンラインにしたあと、 LIF が正常に機能しており、適切なポートに配置されていることを確認します。

.手順
. 再配置処理を再開します。
+
「システムコントローラの交換が再開」

+
システムは次のタスクを実行します。

+
** クラスタクォーラムチェック
** システム ID の確認
** イメージのバージョンチェック
** ターゲットプラットフォームのチェック
** ネットワーク到達可能性チェック


+
ネットワーク到達可能性チェックのこの段階で処理が一時停止します。

. ネットワークとすべての VLAN 、インターフェイスグループ、およびブロードキャストドメインが正しく設定されていることを手動で確認してください。
. 再配置処理を再開します。
+
「システムコントローラの交換が再開」

+
[listing]
----
To complete the "Network Reachability" phase, ONTAP network configuration must be manually adjusted to match the new physical network configuration of the hardware. This includes assigning network ports to the correct broadcast domains,creating any required ifgrps and VLANs, and modifying the home-port parameter of network interfaces to the appropriate ports.Refer to the "Using aggregate relocation to upgrade controller hardware on a pair of nodes running ONTAP 9.x" documentation, Stages 3 and 5. Have all of these steps been manually completed? [y/n]
----
. 「 y 」と入力して続行します。
. システムは次のチェックを実行します。
+
** クラスタの健全性チェック
** クラスタ LIF のステータスを確認します


+
これらのチェックの実行後、システムによって、 node2 によって所有されているルート以外のアグリゲートと NAS データ LIF が新しいコントローラ node4 に再配置されます。リソースの再配置が完了すると、システムは一時停止します。

. アグリゲートの再配置処理と NAS データ LIF の移動処理のステータスを確認します。
+
「 system controller replace show-sdetails 」というエラーが表示されます

. ルート以外のアグリゲートと NAS データ LIF がノード 4 に正常に再配置されたことを手動で確認します。
+
いずれかのアグリゲートに再配置が失敗した場合、または拒否された場合は、アグリゲートを手動で再配置するか、必要に応じて拒否またはデスティネーションのチェックを無視する必要があります。を参照してください link:relocate_failed_or_vetoed_aggr.html["障害が発生したアグリゲートを再配置するか"] を参照してください。

. 次の手順を実行して、ノード 4 の正しいポートに SAN LIF があることを確認します。
+
.. 次のコマンドを入力し、出力を確認します。
+
'network interface show -data-protocol iscsi|fcp-home-node <node4 >`

+
次の例のような出力が返されます。

+
[listing]
----
cluster::> net int show -data-protocol iscsi|fcp -home-node node3
        Logical    Status     Network           Current Current Is
Vserver Interface  Admin/Oper Address/Mask      Node    Port    Home
------- ---------- ---------- ----------------- ------- ------- ---
vs0
        a0a        up/down    10.63.0.53/24     node3   a0a     true
        data1      up/up      10.63.0.50/18     node3   e0c     true
        rads1      up/up      10.63.0.51/18     node3   e1a     true
        rads2      up/down    10.63.0.52/24     node3   e1b     true
vs1
        lif1       up/up      172.17.176.120/24 node3   e0c     true
        lif2       up/up      172.17.176.121/24 node3   e1a     true
----
.. ノード 4 に、ノード 2 に存在しないポート上にある SAN LIF または SAN LIF のグループがある場合、または別のポートにマッピングする必要がある場合は、次の手順を実行して、ノード 4 の該当するポートにそれらの SAN LIF またはグループを移動します。
+
... 次のコマンドを入力して、 LIF のステータスを down に設定します。
+
「 network interface modify -vserver <vserver_name> -lif <LIF_NAME> -status-admin down 」という形式で指定します

... ポートセットから LIF を削除します。
+
`portset remove -vserver <vserver_name> -portset <portset_name> -port-name <port_name> の形式で指定します

... 次のいずれかのコマンドを入力します。
+
**** 次のコマンドを入力して、 1 つの LIF を移動します。
+
「 network interface modify -vserver <vserver_name> -lif <lif_name> -home-port <new_home_port>` 」の形式で指定します

**** 次のコマンドを入力して、単一のポートまたは間違ったポートのすべての LIF を新しいポートに移動します。
+
network interface modify ｛ -home-node <port_on_node1> -role data ｝ -home-node <node1> -role data ｝ -home-port <new_home_port_on_node1> ’ 3 を参照してください

**** LIF をポートセットに再度追加します。
+
`portset add -vserver <vserver_name> -portset <portset_name> -port-name <port_name> の形式で指定します

+

NOTE: リンク速度が元のポートと同じポートに SAN LIF を移動していることを確認する必要があります。





.. 次のコマンドを入力して、すべての LIF のステータスを「 up 」に変更し、ノード上のトラフィックを LIF が受け入れて送信できるようにします。
+
「 network interface modify -home-node <port_name> -home-port <port_name> -home-port <node4 > -lif data -statusadmin up 」の形式で指定します

.. 次のコマンドを入力し、出力を調べて、 LIF が正しいポートに移動されていること、およびどちらかのノードで次のコマンドを入力して LIF のステータスが「 up 」になっていることを確認します。
+
'network interface show -home-node <node4 > -role data

.. LIF が 1 つでも停止している場合は、次のコマンドを LIF ごとに 1 回入力して、 LIF の管理ステータスを up に設定します。
+
「 network interface modify -vserver <vserver_name> -lif <lif_name> -status-admin up 」の形式で指定します



. この処理を再開すると、必要なポストチェックの実行をシステムに求めるプロンプトが表示されます。
+
「システムコントローラの交換が再開」

+
次のポストチェックが実行されます。

+
** クラスタクォーラムチェック
** クラスタの健全性チェック
** アグリゲートの再構築チェック
** アグリゲートのステータスを確認します
** ディスクのステータスを確認します
** クラスタ LIF のステータスを確認します



