---
sidebar: sidebar 
permalink: upgrade-arl-auto/move_non_root_aggr_nas_lifs_node1_from_node2_to_node3.html 
keywords: aggregate relocation, lifs, node3, node1, node2, NAS 
summary: 'を使用して、ONTAP 9.5を実行しているコントローラを9.7にアップグレードする場合は、node2のnode1 NASデータLIFをnode2からnode3に移動します `system controller replace` コマンド' 
---
= ノード 1 で所有されているルート以外のアグリゲートと NAS データ LIF を、ノード 2 からノード 3 に移動します
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
ノード 3 のインストールを確認し、 node2 から node3 にアグリゲートを再配置する前に、 node2 に現在あるノード 2 に属する NAS データ LIF を node2 から node3 に移動する必要があります。また、ノード 3 に SAN LIF が存在することも確認する必要があります。

.このタスクについて
アップグレード手順の実行中、リモート LIF は SAN LUN へのトラフィックを処理します。アップグレード時にクラスタやサービスの健全性を維持するために、 SAN LIF を移動する必要はありません。SAN LIF は、新しいポートにマッピングする必要がないかぎり移動されません。ノード 3 をオンラインにしたあと、 LIF が正常に機能しており、適切なポートに配置されていることを確認します。

.手順
. 再配置処理を再開します。
+
「システムコントローラの交換が再開」

+
システムは次のタスクを実行します。

+
** クラスタクォーラムチェック
** システム ID の確認
** イメージのバージョンチェック
** ターゲットプラットフォームのチェック
** ネットワーク到達可能性チェック


+
ネットワーク到達可能性チェックのこの段階で処理が一時停止します。

. ネットワークとすべての VLAN 、インターフェイスグループ、およびブロードキャストドメインが正しく設定されていることを手動で確認してください。
. 再配置処理を再開します。
+
「システムコントローラの交換が再開」

+
[listing]
----
To complete the "Network Reachability" phase, ONTAP network configuration must
be manually adjusted to match the new physical network configuration of the
hardware. This includes assigning network ports to the correct broadcast
domains, creating any required ifgrps and VLANs, and modifying the home-port
parameter of network interfaces to the appropriate ports. Refer to the "Using
aggregate relocation to upgrade controller hardware on a pair of nodes running
ONTAP 9.x" documentation, Stages 3 and 5. Have all of these steps been manually
completed? [y/n]
----
. 「 y 」と入力して続行します。
. システムは次のチェックを実行します。
+
** クラスタの健全性チェック
** クラスタ LIF のステータスを確認します


+
これらのチェックの実行後、 node1 で所有されているルート以外のアグリゲートと NAS データ LIF が新しいコントローラ node3 に再配置されます。リソースの再配置が完了すると、システムは一時停止します。

. アグリゲートの再配置処理と NAS データ LIF の移動処理のステータスを確認します。
+
「 system controller replace show-sdetails 」というエラーが表示されます

. ルート以外のアグリゲートと NAS データ LIF がノード 3 に正常に再配置されたことを確認します。
+
いずれかのアグリゲートに再配置が失敗した場合、または拒否された場合は、アグリゲートを手動で再配置するか、必要に応じて拒否またはデスティネーションのチェックを無視する必要があります。を参照してください link:relocate_failed_or_vetoed_aggr.html["障害が発生したアグリゲートを再配置するか"] を参照してください。

. 次の手順を実行して、ノード 3 の正しいポートに SAN LIF があることを確認します。
+
.. 次のコマンドを入力し、出力を確認します。
+
'network interface show -data-protocol _iscsi|fcp_-home-node _node3 _`

+
次の例のような出力が返されます。

+
[listing]
----
cluster::> net int show -data-protocol iscsi|fcp -home-node node3

        Logical   Status     Network           Current  Current Is
Vserver Interface Admin/Oper Address/Mask      Node     Port    Home
------- --------- ---------- ----------------- -------- ------- ----
vs0
        a0a       up/down     10.63.0.53/24     node3   a0a     true
        data1     up/up       10.63.0.50/18     node3   e0c     true
        rads1     up/up       10.63.0.51/18     node3   e1a     true
        rads2     up/down     10.63.0.52/24     node3   e1b     true
vs1
        lif1      up/up       172.17.176.120/24 node3   e0c     true
        lif2      up/up       172.17.176.121/24 node3   e1a     true
----
.. ノード 3 に、ノード 1 に存在しないポート上にある SAN LIF または SAN LIF のグループがある場合、または別のポートにマッピングする必要がある場合は、次の手順を実行して、ノード 3 の該当するポートにそれらの SAN LIF またはグループを移動します。
+
... LIF のステータスを down に設定します。
+
「network interface modify -vserver _Vserver_name --lif_lif_name_-status-admin down」を指定します

... ポートセットから LIF を削除します。
+
`portset remove -vserver _Vserver_name -portset_portset_name__-port-name _port_name_`

... 次のいずれかのコマンドを入力します。
+
**** 1 つの LIF を移動します。
+
「network interface modify -vserver _Vserver_name -lif_lif_name_-home-port_`

**** 存在しない、または間違ったポート上のすべての LIF を新しいポートに移動します。
+
'network interface modify｛-home-node port_port_on_node1_-role data｝-home-node _new_home_port_on_node3 _`

**** LIF をポートセットに再度追加します。
+
`portset add -vserver _Vserver_name -portset_portset_name__-port-name _port_name_`

+

NOTE: SAN LIF を、元のポートとリンク速度が同じポートに移動したことを確認する必要があります。





.. ノードでトラフィックを許可して送信できるように、すべての LIF のステータスを「 up 」に変更します。
+
'network interface modify -home-node port_name_--home-node3_lif data-status admin up

.. いずれかのノードで次のコマンドを入力し、その出力を調べて、 LIF が正しいポートに移動されていること、および LIF のステータスが「 up 」になっていることを確認します。
+
'network interface show -home-node node_node3 -- role data `

.. LIF が 1 つでも停止している場合は、次のコマンドを LIF ごとに 1 回入力して、 LIF の管理ステータスを「 up 」に設定します。
+
「network interface modify -vserver vserver_name __-lif LIF_name -status-admin up



. この処理を再開すると、必要なポストチェックの実行をシステムに求めるプロンプトが表示されます。
+
「システムコントローラの交換が再開」

+
次のポストチェックが実行されます。

+
** クラスタクォーラムチェック
** クラスタの健全性チェック
** アグリゲートの再構築チェック
** アグリゲートのステータスを確認します
** ディスクのステータスを確認します
** クラスタ LIF のステータスを確認します



