---
sidebar: sidebar 
permalink: upgrade-arl-auto/overview_of_the_arl_upgrade.html 
keywords: aggregate relocation, upgrade, process, overview, stages 
summary: 「 system controller replace 」コマンドを使用して、 ONTAP 9.5 を実行するコントローラを 9.7 にアップグレードする手順 の動作を理解します。 
---
= ARL アップグレードの概要
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ARL を使用してノードをアップグレードする前に、手順の動作について理解しておく必要があります。このコンテンツでは、手順はいくつかの段階に分かれています。



== ノードペアをアップグレードします

ノードペアをアップグレードするには、元のノードを準備し、元のノードと新しいノードの両方で一連の手順を実行する必要があります。その後、元のノードの運用を停止できます。



== ARL アップグレードシーケンスの概要

手順では、交換用コントローラハードウェアを使用して元のコントローラハードウェアを一度に 1 台ずつアップグレードし、 HA ペア構成を利用してルート以外のアグリゲートの所有権を切り替えます。すべてのルート以外のアグリゲートで、アップグレード後の正しいノードである最終デスティネーションに到達するために、 2 つの再配置を実行する必要があります。

各アグリゲートにはホーム所有者と現在の所有者があります。ホーム所有者はアグリゲートの実際の所有者であり、現在の所有者は一時的な所有者です。

次の表に、各フェーズで実行するタスクの概要と、そのフェーズの最後で実行したアグリゲートの所有権の状態を示します。詳細な手順については、手順の後半で説明します。

[cols="25,75"]
|===
| 段階 | 手順 


| link:stage_1_index.html["ステージ 1 ：アップグレードを準備"]  a| 
ステージ1では、事前確認を実行し、必要に応じてアグリゲートの所有権を修正します。OKMを使用してストレージ暗号化を管理していて、SnapMirror関係を休止することができる場合は、特定の情報を記録する必要があります。

ステージ 1 終了時のアグリゲートの所有権：

* node1 は、 node1 アグリゲートのホーム所有者と現在の所有者です。
* node2 には、 node2 アグリゲートのホーム所有者と現在の所有者を指定します。




| link:stage_2_index.html["ステージ 2 ：移行してノード 1 を撤去"]  a| 
ステージ2で、ノード1の非ルートアグリゲートとNASデータLIFをノード2に再配置します。このプロセスは主に自動化されており、ステータスを確認するために処理が一時停止します。この処理は手動で再開する必要があります。必要に応じて、障害が発生したアグリゲートまたは拒否されたアグリゲートを再手順 の後半で使用するために必要なノード1の情報を記録してから、ノード1を撤去する必要があります。ネットブートnode3とnode4には、あとで手順 で準備することもできます。

ステージ 2 終了時のアグリゲートの所有権：

* node2 には、 node1 アグリゲートの現在の所有者を指定します。
* node2 には、 node2 アグリゲートのホーム所有者と現在の所有者を指定します。




| link:stage_3_index.html["ステージ 3 ：node3 をインストールしてブートします"]  a| 
ステージ 3 で、ノード 3 をインストールしてブートし、クラスタポートとノード管理ポートを node1 から node3 にマッピングし、ノード 3 のインストールを確認します。必要に応じて、ノード3でFCまたはUTA / UTA2設定を設定し、ノード3がクォーラムに参加していることを確認します。さらに、node1のNASデータLIFとルート以外のアグリゲートをnode2からnode3に再配置し、SAN LIFがnode3にあることを確認します。

ステージ 3 終了時のアグリゲートの所有権：

* node3 は、 node1 アグリゲートのホームの所有者であること、および現在の所有者であること。
* node2 には、 node2 アグリゲートのホーム所有者と現在の所有者を指定します。




| link:stage_4_index.html["ステージ 4 ：ノード 2 の移動と撤去"]  a| 
ステージ4で、ノード2の非ルートアグリゲートとSAN以外のデータLIFをノード3に再配置します。また、必要なnode2の情報を記録し、node2を撤去します。

ステージ 4 終了時のアグリゲートの所有権：

* node3 は、 node1 に属していたアグリゲートのホーム所有者および現在の所有者です。
* node2 には、 node2 アグリゲートのホーム所有者を指定します。
* node3 は、 node2 アグリゲートの現在の所有者です。




| link:stage_5_index.html["ステージ 5 ：ノード 4 をインストールしてブートします"]  a| 
ステージ 5 で、 node4 をインストールしてブートし、 node2 のクラスタポートとノード管理ポートを node4 にマッピングし、 node4 のインストールを確認します。必要に応じて、ノード4でFCまたはUTA / UTA2設定を設定し、ノード4がクォーラムに参加していることを確認します。node2のNASデータLIFとルート以外のアグリゲートもnode3からnode4に再配置し、SAN LIFがnode4にあることを確認します。

ステージ 5 終了時のアグリゲートの所有権：

* node3 は、 node1 に属していたアグリゲートのホーム所有者および現在の所有者です。
* node4 は、 node2 に属していたアグリゲートのホーム所有者および現在の所有者です。




| link:stage_6_index.html["ステージ 6 ：アップグレードを完了します"]  a| 
ステージ6では、新しいノードが正しくセットアップされていることを確認し、暗号化が有効な新しいノードがある場合は、ストレージ暗号化またはNetApp Volume Encryptionを設定およびセットアップします。また、古いノードの運用を停止し、SnapMirrorの処理を再開する必要があります。

|===