---
sidebar: sidebar 
permalink: upgrade-arl-auto/recreate_vlans_ifgrps_broadcast_domains_node4.html 
keywords: node4, interface group, VLANs, broadcast domains, re-create 
summary: 'ONTAP 9.5 を実行しているコントローラを "system controller replace" コマンドを使用して 9.7 にアップグレードする場合 " ノード 2 の VLAN " インターフェイスグループ " およびブロードキャストドメインをノード 4 に再作成します' 
---
= ノード 4 で VLAN 、インターフェイスグループ、およびブロードキャストドメインを再作成します
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ノード 4 がクォーラムにあり、ノード 3 と通信できることを確認したら、ノード 2 の VLAN 、インターフェイスグループ、およびブロードキャストドメインをノード 4 に再作成する必要があります。node3 のポートは、新しく作成したブロードキャストドメインにも追加する必要があります。

.このタスクについて
VLAN 、インターフェイスグループ、およびブロードキャストドメインの作成と再作成の詳細については、を参照してください link:other_references.html["参考資料"] およびリンク先： _ ネットワーク管理 _ 。

.手順
. で記録した node2 の情報を使用して、 node4 に VLAN を再作成します link:relocate_non_root_aggr_nas_lifs_from_node2_to_node3.html["ルート以外のアグリゲートと NAS データ LIF を node2 から node3 に再配置します"] セクション。
+
「network port vlan create -node_node4」-vlan_vlan-names_

. で記録した node2 の情報を使用して、 node4 にインターフェイスグループを再作成します link:relocate_non_root_aggr_nas_lifs_from_node2_to_node3.html["ルート以外のアグリゲートと NAS データ LIF を node2 から node3 に再配置します"] セクション。
+
「network port ifgrp create -node _node4」-ifgrp_port_ifgrp_name -distr-func

. で記録した node2 の情報を使用して、 node4 にブロードキャストドメインを再作成します link:relocate_non_root_aggr_nas_lifs_from_node2_to_node3.html["ルート以外のアグリゲートと NAS データ LIF を node2 から node3 に再配置します"] セクション。
+
「network port broadcast-domain create -ipspace Default -broadcast-domain _broadcast_domain_names _-mtu_mtu_size_-ports_node_name：port_name、node_name：port_name、node_name：port_name

. 新たに作成したブロードキャストドメインにノード 4 のポートを追加します。
+
「network port broadcast-domain add-ports -broadcast-domain broadcast_domain_names」-ports_node_name：port_name、node_name：port_name、node_name：port_name


