---
sidebar: sidebar 
permalink: upgrade-arl-auto/relocate_non_root_aggr_nas_lifs_from_node2_to_node3.html 
keywords: relocate, non-root, aggregates, nas, lif, node2, node3 
summary: 'ONTAP 9.5 を実行しているコントローラを "system controller replace" コマンドを使用して 9.7 にアップグレードする場合は " ノード 2 のルート以外のアグリゲートをノード 3 に移動します' 
---
= ルート以外のアグリゲートと NAS データ LIF を node2 から node3 に再配置します
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ノード2をノード4に交換する前に、ノード2が所有するルート以外のアグリゲートとNASデータLIFをノード3に再配置します。

.作業を開始する前に
前の段階で確認したあとに、 node2 のリソースリリースが自動的に開始されます。ルート以外のアグリゲートと SAN 以外のデータ LIF が node2 から node3 に移行されます。

.このタスクについて
アップグレード手順の実行中、リモート LIF は SAN LUN へのトラフィックを処理します。アップグレード時にクラスタやサービスの健全性を維持するために、 SAN LIF を移動する必要はありません。

アグリゲートと LIF の移行が完了すると、検証のために処理が一時停止されます。この段階で、ルート以外のアグリゲートと SAN 以外のデータ LIF がすべて node3 に移行されているかどうかを確認する必要があります。


NOTE: アグリゲートおよび LIF のホーム所有者は変更されません。現在の所有者のみが変更されます。

.手順
. ルート以外のすべてのアグリゲートがオンラインで、ノード 3 でそれらの状態になっていることを確認します。
+
storage aggregate show -node _node3 --state online -root false

+
次の例は、 node2 のルート以外のアグリゲートがオンラインになっていることを示しています。

+
....
cluster::> storage aggregate show -node node3 state online -root false

Aggregate      Size         Available   Used%   State   #Vols  Nodes  RAID     Status
----------     ---------    ---------   ------  -----   -----  ------ -------  ------
aggr_1         744.9GB      744.8GB      0%     online  5      node2  raid_dp  normal
aggr_2         825.0GB      825.0GB      0%     online  1      node2  raid_dp  normal
2 entries were displayed.
....
+
アグリゲートがオフラインになった場合、または node3 で外部になった場合は、各アグリゲートに対して次のコマンドを実行してそれらのアグリゲートをオンラインにします。

+
storage aggregate online -aggregate _aggr_name_`

. node3 で次のコマンドを実行し、出力を調べて、すべてのボリュームがノード 3 でオンラインになっていることを確認します。
+
volume show -node _node3 --state offline`

+
node3 にオフラインのボリュームがある場合は、各ボリュームに対して次のコマンドを実行してそれらのボリュームをオンラインにします。

+
'volume online -vserver_name_-volume_name_`

+
このコマンドで使用する'_vserver_name_'は'前のvolume showコマンドの出力にあります

. LIF が正しいポートに移動され、ステータスが「 up 」になっていることを確認します。LIF が 1 つでも停止している場合は、次のコマンドを LIF ごとに 1 回入力して、 LIF の管理ステータスを「 up 」に設定します。
+
「network interface modify -vserver _vserver_name -- lif_lif_name_-home-node_name__-status-admin up

. データ LIF を現在ホストしているポートが新しいハードウェアに存在しない場合は、ブロードキャストドメインから削除します。
+
「 network port broadcast-domain remove-ports 」と入力します



. [[Step5] ] 次のコマンドを入力し、出力を調べて、 node2 にデータ LIF が残っていないことを確認します。
+
network interface show -curr-node _node2 -role data

. インターフェイスグループまたは VLAN が設定されている場合は、次の手順を実行します。
+
.. node3 の起動後に node3 に VLAN とインターフェイスグループの情報を再作成できるように、 VLAN とインターフェイスグループの情報を記録します。
.. インターフェイスグループから VLAN を削除します。
+
「 network port vlan delete -node _nodename 」 -port_ifgrp --vlan-id_vlan_ID_`

.. 次のコマンドを入力し、ノードに設定されているインターフェイスグループがないかどうかを確認します。
+
「network port ifgrp show -node _node2」-ifgrp _ifgrp_nameのように表示されます

+
次の例に示すように、ノードのインターフェイスグループ情報が表示されます。

+
[listing]
----
cluster::> network port ifgrp show -node node2 -ifgrp a0a -instance
                 Node: node3
 Interface Group Name: a0a
Distribution Function: ip
        Create Policy: multimode_lacp
          MAC Address: 02:a0:98:17:dc:d4
   Port Participation: partial
        Network Ports: e2c, e2d
             Up Ports: e2c
           Down Ports: e2d
----
.. ノードにインターフェイスグループが設定されている場合は、それらのグループの名前とグループに割り当てられているポートを記録し、ポートごとに次のコマンドを 1 回入力してポートを削除します。
+
「 network port ifgrp remove-port -node_nodename 」 -ifgrp _ifgrp_name -port_netport_ 」のようになります




