---
sidebar: sidebar 
permalink: upgrade-arl-auto/relocate_non_root_aggr_nas_data_lifs_node1_node2.html 
keywords: relocate, non-root, nonroot, aggregates, NAS, data, lif s, node1, node2 
summary: ルート以外のアグリゲートと NAS データ LIF をノード 1 からノード 2 に移動します 
---
= ノード 1 が所有するルート以外のアグリゲートと NAS データ LIF をノード 2 に再配置します
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ノード 1 をノード 3 に交換する前に、ルート以外のアグリゲートと NAS データ LIF をノード 1 からノード 2 に移動してから、ノード 1 のリソースをノード 3 に移動する必要があります。

この処理は、タスクの開始時にすでに一時停止されている必要があります。手動で再開する必要があります。

アップグレード手順の実行中、リモート LIF は SAN LUN へのトラフィックを処理します。アップグレード時にクラスタやサービスの健全性を維持するために、 SAN LIF を移動する必要はありません。ノード 3 をオンラインにしたあと、 LIF が正常に機能しており、適切なポートに配置されていることを確認する必要があります。


NOTE: アグリゲートおよび LIF のホーム所有者は変更されず、現在の所有者のみが変更されます。

.手順
. アグリゲートの再配置処理と NAS データ LIF の移動処理を再開します。
+
「システムコントローラの交換が再開」

+
ルート以外のアグリゲートと NAS データ LIF はすべて、 node1 から node2 に移行されます。

+
処理が一時停止することで、ノード 1 のルート以外のアグリゲートと SAN 以外のデータ LIF がすべて node2 に移行されているかどうかを確認できます。

. アグリゲートの再配置処理と NAS データ LIF の移動処理のステータスを確認します。
+
「 system controller replace show-sdetails 」というエラーが表示されます

. 処理が一時停止したまま、ルート以外のすべてのアグリゲートが node2 でそれぞれの状態でオンラインになっていることを確認します。
+
「 storage aggregate show -node <node2> -state online -root false 」のように表示されます

+
次の例は、 node2 のルート以外のアグリゲートがオンラインになっていることを示しています。

+
[listing]
----
cluster::> storage aggregate show -node node2 state online -root false

Aggregate  Size     Available  Used%  State  #Vols  Nodes  RAID Status
---------  -------  ---------  -----  ------ -----  ------ --------------
aggr_1     744.9GB  744.8GB    0%     online     5  node2  raid_dp,normal
aggr_2     825.0GB  825.0GB    0%     online     1  node2  raid_dp,normal
2 entries were displayed.
----
+
アグリゲートがオフラインになった場合、または node2 で外部になった場合は、各アグリゲートに対して 1 回、 node2 で次のコマンドを使用してアグリゲートをオンラインにします。

+
「 storage aggregate online -aggregate <aggr_name>` 」という名前になります

. node2 で次のコマンドを使用し、出力を調べて、すべてのボリュームがオンラインであることを確認します。
+
volume show -node <node2> -state offline`

+
node2 上にオフラインのボリュームがある場合は、各ボリュームに対して 1 回、 node2 で次のコマンドを使用してオンラインにします。

+
'volume online -vserver <vserver-name> -volume <volume-name>`

+
このコマンドで使用する '<vserver-name> は ' 前の volume show コマンドの出力にあります



. [[step5] - データ LIF をホストしているポートが新しいハードウェアに存在しない場合は、ブロードキャストドメインから削除します。
+
「 network port broadcast-domain remove-ports 」と入力します

. 停止している LIF がある場合は、次のコマンドを LIF ごとに 1 回入力して、 LIF の管理ステータスを「 up 」に設定します。
+
「 network interface modify -vserver _Vserver_name -lif LIF_name `-home-node_nodename __ -status-admin up

. インターフェイスグループまたは VLAN が設定されている場合は、次の手順を実行します。
+
.. まだ保存していない場合は、 VLAN および ifgrp の情報を記録して、ノード 3 のブート後に VLAN および ifgrp を作成し直すことができます。
.. 次のコマンドを入力して、インターフェイスグループから VLAN を削除します。
+
「 network port vlan delete -node _nodename 」 -port_ifgrp --vlan-id_vlan_ID_`

+

NOTE: 対処方法に従って、 vlan delete コマンドで表示されるエラーを解決します。

.. 次のコマンドを入力し、その出力を調べて、ノードにインターフェイスグループが設定されているかどうかを確認します。
+
「 network port ifgrp show -node nodename 」 -ifgrp _ifgrp_name のように表示されます

+
次の例に示すように、ノードのインターフェイスグループ情報が表示されます。

+
[listing]
----
cluster::> network port ifgrp show -node node1 -ifgrp a0a -instance
                 Node: node1
 Interface Group Name: a0a
Distribution Function: ip
        Create Policy: multimode_lacp
          MAC Address: 02:a0:98:17:dc:d4
   Port Participation: partial
        Network Ports: e2c, e2d
             Up Ports: e2c
           Down Ports: e2d
----
.. ノードにインターフェイスグループが設定されている場合は、それらのグループの名前とグループに割り当てられているポートを記録し、ポートごとに次のコマンドを 1 回入力してポートを削除します。
+
「 network port ifgrp remove-port -node_nodename 」 -ifgrp _ifgrp_name -port_netport_ 」のようになります




