---
sidebar: sidebar 
permalink: upgrade-arl-auto/set_up_netapp_volume_encryption_new_module.html 
keywords: set up, netapp volume encryption, controller, module, nve, node 
summary: '必要に応じて、を使用してONTAP 9.5を実行しているコントローラを9.7にアップグレードする場合は、NVEまたはNAE用に新しいコントローラモジュールを設定します `system controller replace` コマンド' 
---
= 新しいコントローラモジュールでNetApp VolumeまたはAggregate Encryptionをセットアップします
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
新しいコントローラの交換したコントローラまたはハイアベイラビリティ（HA）パートナーがNetApp Volume Encryption（NVE）またはNetApp Aggregate Encryption（NAE）を使用している場合は、新しいコントローラモジュールをNVEまたはNAE用に設定する必要があります。

.このタスクについて
この手順には、新しいコントローラモジュールで実行する手順が含まれています。コマンドは正しいノードで入力する必要があります。

[role="tabbed-block"]
====
.ONTAP 9.6および9.7
--
* ONTAP 9.6または9.7を実行しているコントローラでNVEまたはNAEを設定します

.手順
. キー管理サーバがまだ使用可能であり、ステータスと認証キー情報が正しいことを確認します。
+
「 securitykey manager key query -node node 」を参照してください

. 前の手順で確認したキー管理サーバを新しいコントローラのキー管理サーバリストに追加します。
+
.. キー管理サーバを追加します。
+
「security key-manager -add_key_manager_server_ip_address_`」

.. リストされている各キー管理サーバについて、同じ手順を繰り返します。
+
最大 4 台のキー管理サーバをリンクできます。

.. キー管理サーバが正常に追加されたことを確認します。
+
「 securitykey -manager show 」を参照してください



. 新しいコントローラモジュールで、キー管理セットアップウィザードを実行して、キー管理サーバをセットアップしてインストールします。
+
既存のコントローラモジュールと同じキー管理サーバをインストールする必要があります。

+
.. 新しいノードでキー管理サーバセットアップウィザードを起動します。
+
security key-manager setup -node _new_controller_name_`

.. ウィザードの手順に従って、キー管理サーバを設定します。


. リンクされたすべてのキー管理サーバから新しいノードに認証キーをリストアします。
+
** 外部キー管理ツールの認証をリストアします。
+
「セキュリティキーマネージャの外部リストア」

+
このコマンドには、オンボードキーマネージャ（ OKM ）のパスフレーズが必要です。

+
詳細については、技術情報アーティクルを参照してください https://kb.netapp.com/onprem/ontap/dm/Encryption/How_to_restore_external_key_manager_server_configuration_from_the_ONTAP_boot_menu["ONTAP ブートメニューから外部キー管理サーバの設定をリストアする方法"^]。

** OKM の認証をリストアします：
+
「セキュリティキーマネージャオンボード同期」





--
.ONTAP 9.5
--
* ONTAP 9.5*を実行しているコントローラでNVEまたはNAEを設定します

.手順
. キー管理サーバがまだ使用可能であり、ステータスと認証キー情報が正しいことを確認します。
+
「 securitykey -manager key show 」を参照してください

. 前の手順で確認したキー管理サーバを新しいコントローラのキー管理サーバリストに追加します。
+
.. キー管理サーバを追加します。
+
「security key-manager -add_key_manager_server_ip_address_`」

.. リストされている各キー管理サーバについて、同じ手順を繰り返します。
+
最大 4 台のキー管理サーバをリンクできます。

.. キー管理サーバが正常に追加されたことを確認します。
+
「 securitykey -manager show 」を参照してください



. 新しいコントローラモジュールで、キー管理セットアップウィザードを実行して、キー管理サーバをセットアップしてインストールします。
+
既存のコントローラモジュールと同じキー管理サーバをインストールする必要があります。

+
.. 新しいノードでキー管理サーバセットアップウィザードを起動します。
+
security key-manager setup -node _new_controller_name_`

.. ウィザードの手順に従って、キー管理サーバを設定します。


. リンクされたすべてのキー管理サーバから新しいノードに認証キーをリストアします。
+
** 外部キー管理ツールの認証をリストアします。
+
「セキュリティキーマネージャの外部リストア」

+
このコマンドには、オンボードキーマネージャ（ OKM ）のパスフレーズが必要です。

+
詳細については、技術情報アーティクルを参照してください https://kb.netapp.com/onprem/ontap/dm/Encryption/How_to_restore_external_key_manager_server_configuration_from_the_ONTAP_boot_menu["ONTAP ブートメニューから外部キー管理サーバの設定をリストアする方法"^]。

** OKM の認証をリストアします：
+
'security key-manager setup -node _node_name _`





--
====
.完了後
認証キーを使用できなかったか、外部キー管理サーバにアクセスできなかったためにボリュームがオフラインになっていないかを確認します。volume online コマンドを使用して ' これらのボリュームをオンラインに戻します
