---
sidebar: sidebar 
permalink: upgrade-arl-auto/set_fc_or_uta_uta2_config_node4.html 
keywords: fc configuration, uta configuration, UTA2 configuration, configure FC ports, UTA/UTA2 card, node4, target, adapter, ports 
summary: 'ONTAP 9.5 を実行しているコントローラを "system controller replace" コマンドを使用して 9.7 にアップグレードする場合は "node4 オンボード FC ポート "UTA/UTA2 ポート " または UTA/UTA2 カードを設定します' 
---
= ノード 4 で FC または UTA / UTA2 設定を設定します
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
ノード 4 でオンボードの FC ポート、オンボードのユニファイドターゲットアダプタ（ UTA / UTA2 ）ポート、または UTA / UTA2 カードが使用されている場合は、残りの手順を完了する前に設定する必要があります。

.このタスクについて
完了する必要があるかもしれません<<ノード 4 の FC ポートを設定します>>または<<ノード 4 の UTA / UTA2 ポートを確認して設定してください>>、または両方のセクション。

[NOTE]
====
ストレージディスクを搭載したシステムをアップグレードする場合、ノード4にオンボードFCポート、オンボードUTA / UTA2ポート、またはUTA / UTA2カードがない場合は、に進みます。link:reassign-node2-disks-to-node4.html["ノード2のディスクをノード4に再割り当てします。"]

ノード 4 に十分なラックスペースがあることを確認してください。node4 と node2 が別々のシャーシにある場合は、 node4 を node3 と同じ場所に配置できます。node2 と node4 が同じシャーシにある場合は、 node4 が適切なラックの場所にすでに存在しているとします。

====


== ノード 4 の FC ポートを設定します

node4 にオンボードまたはアドオン FC アダプタ上の FC ポートがある場合、システムの出荷時にポートが事前構成されていないため、ノードをサービスに投入する前にノード上でポート構成を設定する必要があります。必要に応じてポートを構成しないと、サービスが中断される可能性があります。

.作業を開始する前に
セクションに保存した node2 の FC ポート設定の値を確認しておく必要があります link:prepare_nodes_for_upgrade.html["ノードをアップグレードする準備をします"]。

.このタスクについて
システムに FC 構成がない場合は、このセクションをスキップしてかまいません。システムにオンボード UTA / UTA2 ポートまたは UTA / UTA2 アダプタが搭載されている場合は、で設定します <<ノード 4 の UTA / UTA2 ポートを確認して設定してください>>。


IMPORTANT: このセクションのコマンドをメンテナンス モードのシェル プロンプトで入力します。

.手順
. システム上のすべての FC および統合ネットワーク アダプタに関する情報を表示します。
+
「 system node hardware unified-connect show 」を参照してください

. ノード 4 の FC 設定とノード 1 から前に取得した設定を比較します。
. 必要に応じて、ノード 4 の FC ポートを変更します。
+
** ターゲット ポートとしてプログラムするには:
+
ucadmin modify -m fc -t target_adapter_`

+
例えば： `ucadmin modify -m fc -t target 2a`

** イニシエータポートをプログラミングする場合：
+
ucadmin modify -m fc -t initiator_adapter_`

+
`-t` は FC4 のタイプで ' ターゲットまたはイニシエータです

+
例えば： `ucadmin modify -m fc -t initator 2b`



. ノードを停止します。
+
「 halt 」

. LOADERプロンプトからシステムをブートします。
+
「 boot_ontap menu

. コマンドを入力したら、ブート環境のプロンプトでシステムが停止するまで待ちます。
. 保守モードのブート・メニューからオプション「 5 」を選択します。


. [[step8]]このセクションをスキップしてlink:reassign-node2-disks-to-node4.html["ノード2のディスクをノード4に再割り当てします。"]node4 に UTA/UTA2 カードまたは UTA/UTA2 オンボード ポートがない場合。




== ノード 4 の UTA / UTA2 ポートを確認して設定してください

ノード 4 でオンボード UTA / UTA2 ポートまたは UTA / UTA2A カードが使用されている場合は、アップグレードしたシステムの使用方法に応じて、ポートの設定を確認して設定する必要があります。

.作業を開始する前に
UTA / UTA2 ポートに対応する正しい SFP+ モジュールが必要です。

.このタスクについて
UTA / UTA2 ポートは、ネイティブの FC モードまたは UTA / UT2A モードに設定できます。FC モードでは FC イニシエータと FC ターゲットがサポートされます。 UTA / UTA2 モードを使用すると、 NIC と FCoE の同時トラフィックで同じ 10GbE SFP+ インターフェイスを共有し、 FC ターゲットをサポートすることができます。


NOTE: ネットアップのマーケティング資料では、 UTA2 という用語を CNA アダプタとポートという意味で使用している場合があります。ただし、 CLI では CNA という用語が使用されます。

UTA / UTA2 ポートはアダプタまたはコントローラ上に次の構成で配置されます。

* UTA / UTA2 カードは、コントローラと同時に注文しても、希望するパーソナリティを持つ未設定の状態で出荷されます。
* コントローラとは別に発注した UTA / UTA2 カードは、デフォルトの FC ターゲットパーソナリティとして出荷されます。
* 新しいコントローラのオンボード UTA / UTA2 ポートは、要求したパーソナリティを持つように（出荷前に）設定されています。


ただし、ノード 4 の UTA / UTA2 ポートの設定を確認し、必要に応じて変更してください。


WARNING: このセクションのコマンドをメンテナンス モードのシェル プロンプトで入力します。

.手順
. ノード 4 でポートが現在どのように構成されているかを確認します。
+
「 system node hardware unified-connect show 」を参照してください

+
次の例のような出力が表示されます。

+
....
*> ucadmin show
                Current  Current    Pending   Pending   Admin
Node   Adapter  Mode     Type       Mode      Type      Status
----   -------  ---      ---------  -------   --------  -------
f-a    0e       fc       initiator  -          -        online
f-a    0f       fc       initiator  -          -        online
f-a    0g       cna      target     -          -        online
f-a    0h       cna      target     -          -        online
f-a    0e       fc       initiator  -          -        online
f-a    0f       fc       initiator  -          -        online
f-a    0g       cna      target     -          -        online
f-a    0h       cna      target     -          -        online
*>
....
. 現在の SFP+ モジュールが目的の用途と一致しない場合は、正しい SFP+ モジュールに交換します。
+
ネットアップの担当者に連絡して、正しい SFP+ モジュールを入手します。

. 設定を確認します。
+
ucadmin show

+
ucadmin show コマンドの出力結果を調べ、 UTA / UTA2 ポートが希望するパーソナリティに対応しているかどうかを確認します。

+
次の例の出力は ' アダプタ「 1b 」の FC4 タイプがイニシエータに変更され ' アダプタ「 2a 」および「 2b 」のモードが「 cna' 」に変更されていることを示しています

+
....
*> ucadmin show
Node  Adapter  Current Mode  Current Type  Pending Mode  Pending Type  Admin Status
----  -------  ------------  ------------  ------------  ------------  ------------
f-a   1a       fc             initiator    -             -             online
f-a   1b       fc             target       -             initiator     online
f-a   2a       fc             target       cna           -             online
f-a   2b       fc             target       cna           -             online
4 entries were displayed.
*>
....
. 次のいずれかを実行します。
+
[cols="30,70"]
|===
| CNA ポートの状況 | 次に、 


| 希望するパーソナリティがない | に進みます <<auto_check_4_step5,手順 5>>。 


| あなたがほしい人格を持っている | ステップ5からステップ9をスキップして、<<auto_check_4_step10,手順 10>> 。 
|===
. [[auto_check_4_step5] 次のいずれかの操作を実行します。
+
[cols="30,70"]
|===
| を設定する場合 | 次に、 


| UTA / UTA2 カードのポート | へ移動<<auto_check_4_step6,手順 6>> 


| オンボードの UTA/UTA2 ポート | ステップ6をスキップして<<auto_check_4_step7,手順 7>>。 
|===
. [[auto_check_4_step6]]アダプタがイニシエーターモードであり、UTA/UTA2 ポートがオンラインの場合は、UTA/UTA2 ポートをオフラインにします。
+
storage disable adapter_adapter_adapter_adapter_name_`

+
ターゲットモードのアダプタは、メンテナンスモードで自動的にオフラインになります。

. [[auto_check_4_step7] 現在の構成が目的の用途に一致しない場合は、必要に応じて構成を変更します。
+
`ucadmin modify -m fc|cna -t initiator|target <adapter_name>`

+
** 「 -m 」はパーソナリティ・モード、 FC または 10GbE UTA です。
** `-t` は FC4 のタイプ、「 target 」または「 initiator 」です。
+

NOTE: テープ ドライブおよびMetroCluster構成には FC イニシエーターを使用する必要があります。  SAN クライアントには FC ターゲットを使用する必要があります。



. 次のコマンドを各ポートごとに 1 回入力して、ターゲット ポートをオンラインにします。
+
`storage enable adapter <adapter_name>`

. ポートをケーブル接続します。


. [[auto_check_4_step10]]メンテナンスモードを終了:
+
「 halt 」

. ノードをブートメニューでブートします。
+
「 boot_ontap menu



.次の手順
* AFF A800システムにアップグレードする場合は、に進みますlink:reassign-node2-disks-to-node4.html#auto_check_4_step9["ノード2のディスクをノード4に再割り当て（手順9）"]。
* その他のシステムアップグレードについては、link:reassign-node2-disks-to-node4.html["ノード2のディスクをノード4の手順1に再割り当てします。"] 。

