---
sidebar: sidebar 
permalink: upgrade-arl-auto/set_up_netapp_volume_encryption_new_module.html 
keywords: set up, netapp volume encryption, controller, module, nve, node 
summary: 'ONTAP 9.5 を実行しているコントローラを 9.7 にアップグレードする場合は、必要に応じて、「 system controller replace` コマンド」を使用して、 NVE 用の新しいコントローラモジュールを設定します。' 
---
= 新しいコントローラモジュールで NetApp Volume Encryption をセットアップします
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
交換したコントローラまたは新しいコントローラの HA パートナーで NetApp Volume Encryption を使用している場合は、新しいコントローラモジュールで NetApp Volume Encryption を設定する必要があります。

.このタスクについて
この手順には、新しいコントローラモジュールで実行する手順が含まれています。コマンドは正しいノードで入力する必要があります。

.手順
. キー管理サーバがまだ使用可能であり、ステータスと認証キー情報が正しいことを確認します。
+
[cols="30,70"]
|===
| この ONTAP バージョンの場合 ... | 使用するコマンド 


| ONTAP 9.6 または 9.7 | 「 securitykey manager key query -node node 」を参照してください 


| ONTAP 9.5 | 「 securitykey -manager key show 」を参照してください 
|===
. 前の手順で確認したキー管理サーバを新しいコントローラのキー管理サーバリストに追加します。
+
.. キー管理サーバを追加します。
+
「security key-manager -add_key_manager_server_ip_address_`」

.. リストされている各キー管理サーバについて、同じ手順を繰り返します。
+
最大 4 台のキー管理サーバをリンクできます。

.. キー管理サーバが正常に追加されたことを確認します。
+
「 securitykey -manager show 」を参照してください



. 新しいコントローラモジュールで、キー管理セットアップウィザードを実行して、キー管理サーバをセットアップしてインストールします。
+
既存のコントローラモジュールと同じキー管理サーバをインストールする必要があります。

+
.. 新しいノードでキー管理サーバセットアップウィザードを起動します。
+
security key-manager setup -node _new_controller_name_`

.. ウィザードの手順に従って、キー管理サーバを設定します。


. リンクされたすべてのキー管理サーバから新しいノードに認証キーをリストアします。
+
** 外部キー管理ツールの認証をリストアします。
+
「セキュリティキーマネージャの外部リストア」

+
このコマンドには、オンボードキーマネージャ（ OKM ）のパスフレーズが必要です。

** OKM の認証をリストアします：
+
[cols="30,70"]
|===
| この ONTAP バージョンの場合 ... | 使用するコマンド 


| ONTAP 9.6 または 9.7 | 「セキュリティキーマネージャオンボード同期」 


| ONTAP 9.5 | 'security key-manager setup -node _node_name _` 
|===




.完了後
認証キーを使用できなかったか、外部キー管理サーバにアクセスできなかったためにボリュームがオフラインになっていないかを確認します。volume online コマンドを使用して ' これらのボリュームをオンラインに戻します
