---
sidebar: sidebar 
permalink: upgrade-arl-auto/stage_6_index.html 
keywords: complete upgrade, node, unified, target, storage, encryption, MetroCluster, stage 6 
summary: ONTAP 9.5 から 9.7 までを実行しているコントローラでは、 system controller replace コマンドを使用して、 ARL アップグレードのステージ 6 プロセスシーケンスを実行します。 
---
= ステージ 6 ：アップグレードを完了します
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ステージ6では、新しいノードが正しくセットアップされていることを確認し、暗号化が有効な新しいノードがある場合は、ストレージ暗号化またはNetApp Volume Encryptionを設定およびセットアップします。また、古いノードの運用を停止し、SnapMirrorの処理を再開する必要があります。

.手順
. link:get_ip_address_of_external_kms_for_storage_encryption.html["ストレージ暗号化用の外部キー管理サーバの IP アドレスを取得します"]
. link:ensure_new_controllers_are_set_up_correctly.html["新しいコントローラが正しくセットアップされていることを確認します"]
. link:set_up_storage_encryption_new_module.html["新しいコントローラモジュールで Storage Encryption をセットアップします"]
. link:set_up_netapp_volume_encryption_new_module.html["新しいコントローラモジュールでNetApp VolumeまたはAggregate Encryptionをセットアップします"]
. link:decommission_old_system.html["古いシステムの運用を停止"]
. link:resume_snapmirror_operations.html["SnapMirror 処理を再開します"]


.MetroCluster FC構成の場合
MetroCluster FC 構成の場合は、できるだけ早くディザスタリカバリ / フェイルオーバーサイトのノードを交換する必要があります。コントローラモデルの不一致が原因で原因ディザスタリカバリのミラーリングがオフラインになる可能性があるため、 MetroCluster 内のコントローラモデルの不一致はサポートされません。2 番目のサイトでノードを交換するときに MetroCluster チェックを省略するには、コマンドの -'kip-metrocluster-check true' オプションを使用します。
