---
sidebar: sidebar 
permalink: upgrade-arl-auto/stage_3_index.html 
keywords: stage 3, install node3, non-SAN data LIFs, non-root aggregates 
summary: ONTAP 9.5 から 9.7 までのコントローラでは、 system controller replace コマンドを使用して、 ARL アップグレードのステージ 3 プロセスシーケンスを実行します。 
---
= ステージ3の概要
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
ステージ3では、ノード3をインストールしてブートし、クラスタポートとノード管理ポートをノード1からノード3にマッピングし、ノード1のディスクをノード3に再割り当てして、ノード3のインストールを確認します。必要に応じて、ノード3でFCまたはUTA / UTA2設定を設定し、ノード3がクォーラムに参加していることを確認します。さらに、node1のNASデータLIFとルート以外のアグリゲートをnode2からnode3に再配置し、SAN LIFがnode3にあることを確認します。

.手順
. link:install_boot_node3.html["node3 をインストールしてブートします"]
. link:set_fc_or_uta_uta2_config_on_node3.html["ノード 3 で FC または UTA / UTA2 設定を設定します"]
. link:reassign-node1-disks-to-node3.html["ノード1のディスクをノード3に再割り当て"]
. link:map_ports_node1_node3.html["ポートを node1 から node3 にマッピングします"]
. link:join_quorum_node_has_different_ports_stage3.html["ノードのネットワークポートのセットが異なる場合のクォーラムの追加"]
. link:verify_node3_installation.html["ノード 3 のインストールを確認します"]
. link:move_non_root_aggr_nas_lifs_node1_from_node2_to_node3.html["ノード 1 で所有されているルート以外のアグリゲートと NAS データ LIF を、ノード 2 からノード 3 に移動します"]

