---
sidebar: sidebar 
permalink: upgrade-arl-auto/verify_node3_installation.html 
keywords: install, boot, node3, join quorum, restore, key, manager 
summary: 'system controller replace" コマンドを使用して ONTAP 9.5 を実行しているコントローラを 9.7 にアップグレードする場合 " ノード 3 がクォーラムに参加していることを確認し " ノード 1 の VLAN " インタフェースグループ " ブロードキャストドメインを再作成し " キー管理ツールの設定をリストアします' 
---
= ノード 3 のインストールを確認します
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
node3 のインストールとブートが完了したら、正しくインストールされていることを確認する必要があります。node3 がクォーラムに参加するのを待ってから、再配置処理を再開する必要があります。

.このタスクについて
手順のこの時点で、 node3 がクォーラムに参加する間、処理が一時停止します。

.手順
. ノード 3 がクォーラムに参加していることを確認し
+
cluster show -node node3 -fields health`

. ノード 3 が node2 と同じクラスタに含まれており、ノード 3 が正常であることを確認します。
+
「 cluster show 」を参照してください

. 処理のステータスを確認し、 node3 の設定情報が node1 と同じであることを確認します。
+
「 system controller replace show-sdetails 」というエラーが表示されます

+
node3 の設定が異なる場合は、手順の後半でシステムが停止する可能性があります。

. 交換したコントローラが MetroCluster 構成に対して正しく設定されていることを確認します。 MetroCluster 構成は正常な状態であり、スイッチオーバーモードではないことが必要です。を参照してください link:verify_health_of_metrocluster_config.html["MetroCluster 構成の健全性を確認"]。




== ノード 3 に、 VLAN 、インターフェイスグループ、およびブロードキャストドメインを再作成します

node3 がクォーラムにあり、 node2 と通信できることを確認したら、ノード 3 にある node1 の VLAN 、インターフェイスグループ、およびブロードキャストドメインを再作成する必要があります。node3 のポートは、新しく作成したブロードキャストドメインにも追加する必要があります。

.このタスクについて
VLAN 、インターフェイスグループ、およびブロードキャストドメインの作成と再作成の詳細については、を参照してください link:other_references.html["参考資料"] およびリンク先： _ ネットワーク管理 _ 。

.手順
. に記録された node1 情報を使用して、 node3 に VLAN を再作成します link:relocate_non_root_aggr_and_nas_data_lifs_node1_node2.html["ノード 1 が所有するルート以外のアグリゲートと NAS データ LIF をノード 2 に再配置します"] セクション。
+
'network port vlan create -node_node_name -- vlan_vlan-names_

. に記録されている node1 の情報を使用して、ノード 3 にインターフェイスグループを再作成します link:relocate_non_root_aggr_and_nas_data_lifs_node1_node2.html["ノード 1 が所有するルート以外のアグリゲートと NAS データ LIF をノード 2 に再配置します"] セクション。
+
「network port ifgrp create -node _node_name」-ifgrp _port_ifgrp_names_-distr-func」という形式で指定します

. に記録されている node1 の情報を使用して、ノード 3 にブロードキャストドメインを再作成します link:relocate_non_root_aggr_and_nas_data_lifs_node1_node2.html["ノード 1 が所有するルート以外のアグリゲートと NAS データ LIF をノード 2 に再配置します"] セクション。
+
「network port broadcast-domain create -ipspace Default -broadcast-domain _broadcast_domain_names _-mtu_mtu_size_-ports_node_name：port_name、node_name：port_name、node_name：port_name

. node3 のポートを、新しく作成したブロードキャストドメインに追加します。
+
「network port broadcast-domain add-ports -broadcast-domain broadcast_domain_names」-ports_node_name：port_name、node_name：port_name、node_name：port_name





== ノード 3 でキー管理ツールの設定をリストアします

NetApp Aggregate Encryption（NAE）またはNetApp Volume Encryption（NVE）を使用してアップグレードするシステムのボリュームを暗号化する場合は、暗号化設定を新しいノードに同期する必要があります。key-managerをリストアしない場合は、ARLを使用してノード2からノード3にアグリゲートを再配置すると、暗号化されたボリュームがオフラインになります。

.手順
. オンボードキーマネージャの暗号化設定を同期するには、クラスタプロンプトで次のコマンドを実行します。
+
|===
| この ONTAP バージョンの場合 ... | 使用するコマンド 


| ONTAP 9.6 または 9.7 | 「セキュリティキーマネージャオンボード同期」 


| ONTAP 9.5 | 'security key-manager setup -node _node_name _` 
|===
. オンボードキーマネージャのクラスタ全体のパスフレーズを入力します。

