---
sidebar: sidebar 
permalink: upgrade-arl-auto/verify_node4_installation.html 
keywords: verify, node4, installation, MetroCluster, restore, key, manager 
summary: 'ONTAP 9.5 を実行しているコントローラを "system controller replace" コマンドを使用してアップグレードするときに "node4 が定足数に参加し "node1 の VLAN " インタフェースグループ " ブロードキャストドメインを再作成し " キー管理ツールの構成を復元することを確認します' 
---
= ノード 4 のインストールを確認します
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
node4 のインストールとブートの完了後、正しくインストールされていること、クラスタの一部であること、および node3 と通信できることを確認する必要があります。

手順のこの時点で、ノード 4 がクォーラムに参加する間、処理が一時停止します。

.手順
. ノード 4 がクォーラムに参加していることを確認し
+
cluster show -node node4 -fields health`

. 次のコマンドを入力して、 node4 が node3 と同じクラスタに含まれていること、および正常であることを確認します。
+
「 cluster show 」を参照してください

. 処理のステータスを確認し、 node4 の設定情報が node2 と同じであることを確認します。
+
「 system controller replace show-sdetails 」というエラーが表示されます

+
ノード 4 の設定が異なる場合は、あとで手順でシステムが停止する可能性があります。

. 交換したコントローラが MetroCluster 構成に対して正しく設定されており、スイッチオーバーモードでないことを確認します。
+

CAUTION: * 注意：この段階では、 MetroCluster 構成は正常な状態ではなく、エラーが発生していて解決できます。を参照してください link:verify_health_of_metrocluster_config.html["MetroCluster 構成の健全性を確認"]。





== ノード 4 で VLAN 、インターフェイスグループ、およびブロードキャストドメインを再作成します

ノード 4 がクォーラムにあり、ノード 3 と通信できることを確認したら、ノード 2 の VLAN 、インターフェイスグループ、およびブロードキャストドメインをノード 4 に再作成する必要があります。node3 のポートは、新しく作成したブロードキャストドメインにも追加する必要があります。

VLAN 、インターフェイスグループ、およびブロードキャストドメインの作成と再作成の詳細については、を参照してください link:other_references.html["参考資料"] およびリンク先： _ ネットワーク管理 _ 。

.手順
. で記録した node2 の情報を使用して、 node4 に VLAN を再作成します link:relocate_non_root_aggr_nas_lifs_from_node2_to_node3.html["ルート以外のアグリゲートと NAS データ LIF を node2 から node3 に再配置します"] セクション。
+
「 network port vlan create -node <node4 > -vlan <vlan-names> 」のように指定します

. で記録した node2 の情報を使用して、 node4 にインターフェイスグループを再作成します link:relocate_non_root_aggr_nas_lifs_from_node2_to_node3.html["ルート以外のアグリゲートと NAS データ LIF を node2 から node3 に再配置します"] セクション。
+
「 network port ifgrp create -node <node4 > -ifgrp <port_ifgrp_names> -distr-func 」のように指定します

. で記録した node2 の情報を使用して、 node4 にブロードキャストドメインを再作成します link:relocate_non_root_aggr_nas_lifs_from_node2_to_node3.html["ルート以外のアグリゲートと NAS データ LIF を node2 から node3 に再配置します"] セクション。
+
「 network port broadcast-domain create -ipspace Default -broadcast-domain <broadcast_domain_names> -mtu <mtu_size> -ports <node_name ： port_name 、 node_name ： port_name ： port_name 」

. 新たに作成したブロードキャストドメインにノード 4 のポートを追加します。
+
「 network port broadcast-domain add-ports -broadcast-domain <broadcast_domain_names> -ports <node_name ： port_name 、 node_name ： port_name ： port_name 」





== ノード 4 でキー管理ツールの設定をリストアします

NetApp Volume Encryption （ NVE ）を使用してアップグレードするシステムのボリュームを暗号化する場合は、暗号化設定を新しいノードに同期する必要があります。ノード 1 のアグリゲートの ARL がノード 2 からノード 4 に完了すると、暗号化されたボリュームがオフラインになります。

.手順
. オンボードキーマネージャの暗号化設定を同期するには、クラスタプロンプトで次のコマンドを実行します。
+
|===
| この ONTAP バージョンの場合 ... | 使用するコマンド 


| ONTAP 9.6 または 9.7 | セキュリティキー管理ツールのオンボード同期 


| ONTAP 9.5 | security key-manager setup -node <node_name > 
|===
. オンボードキーマネージャのクラスタ全体のパスフレーズを入力します。

