---
sidebar: sidebar 
permalink: upgrade-arl-auto-mendocino/decide_to_use_the_aggregate_relocation_guide.html 
keywords: deciding, aggregate, relocation, content, storage, controllers, administrators, ontap, ha, high, availability, aff, a700, a900 
summary: ARL を使用して、新しい AFF A900 コントローラを搭載した AFF A700 HA ペアのストレージコントローラをアップグレードするかどうかを決定します。 
---
= アグリゲートの再配置手順を使用するかどうかを決定します
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
このコンテンツでは、 AFF A700 HA ペアのストレージコントローラを新しい AFF A900 コントローラにアップグレードし、同時に既存のデータとディスクをすべて残す方法について説明します。これは複雑な手順であり、経験豊富な管理者のみが使用する必要があります。

このマニュアルは、次のような状況で使用することを想定しています。

* ネットアップの営業担当者に、 AFF A900 コントローラモジュール、 NVS 、およびアップグレードに必要な部品を受け取っていることを確認しておきます。
* ONTAP 9.10.1 RC2 以降を実行している。
* 新しいコントローラを新しい HA ペアとしてクラスタに追加し、ボリューム移動を使用してデータを移行する必要はありません。
* ONTAP の管理経験があり、 diagnostic 権限モードで作業する場合のリスクが十分にあります。


このマニュアルは、次の場合には使用しないでください。

* AFF A700 システムで FlexArray 仮想化ソフトウェアを使用している場合は、この手順を * 使用しないでください。
* クラスタインターコネクトおよびイーサネット接続ストレージに共有スイッチを使用している場合は、この手順を使用しないでください。


Fabric MetroCluster または MetroCluster IP 設定のアップグレードについては、を参照してください link:other_references.html["参考資料"] MetroCluster アップグレードおよび Expansion コンテンツにリンクするには、次の手順を実行します。


NOTE: この手順では、 NetApp Storage Encryption （ NSE ）および NetApp Volume Encryption （ NVE ）を使用できます。

コントローラハードウェアを別の方法でアップグレードして、ボリュームの移動を希望する場合は、を参照してください link:other_references.html["参考資料"] をクリックして、ボリュームまたは storage _ を移動して _ Upgrade にリンクします。

を参照してください link:other_references.html["参考資料"] から ONTAP 9 ドキュメントセンターにリンクして、 ONTAP 9 製品ドキュメントにアクセスできます。
