---
sidebar: sidebar 
permalink: upgrade-arl-auto-mendocino/guidelines_for_upgrading_controllers_with_arl.html 
keywords: guidelines, upgrade, aff, a900, a700, ontap, controllers 
summary: ARL を使用して、 ONTAP 9.10.1 RC2 以降を実行する AFF A700 コントローラのペアを AFF A900 システムにアップグレードする方法は、システムとコントローラの構成によって異なります。 
---
= ARL を使用した AFF A700 から AFF A900 へのアップグレードに関するガイドライン
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ARL を使用して、 ONTAP 9.10.1 RC2 以降を実行する AFF A700 コントローラのペアを AFF A900 システムにアップグレードするには、システムと、元のコントローラと交換用コントローラの両方の構成が必要です。



== ARL のアップグレードがサポートされます

ARL を使用して AFF A900 にアップグレードし、コントローラモジュールと NVS のみを交換する方法がサポートされています。 AFF新しいシャーシを含む、完全なシステムとして新しい AFF A900 システムを購入した場合は、を参照してください link:other_references.html["参考資料"] ONTAP 9.8 以降の _content を実行しているコントローラハードウェアをアップグレードするには、 "system controller replace" コマンドを使用してください。


WARNING: このガイドは、 AFF ONTAP 9.10.1 RC2 以降を実行する AFF A900 への環境 A700 のアップグレードを厳密に対象としています。他のシステムの組み合わせについては、このガイドを使用してアップグレードを実行しないでください。

ARL を使用したコントローラのアップグレードは、 SnapLock Enterprise ボリュームおよび SnapLock Compliance ボリュームが設定されたシステムでサポートされます。



== 2 ノードスイッチレスクラスタ

2 ノードスイッチレスクラスタのノードをアップグレードする場合は、アップグレードの実行中もスイッチレスクラスタのノードをそのまま使用できます。スイッチクラスタに変換する必要はありません。



== トラブルシューティングを行う

コントローラのアップグレード中に問題が発生した場合は、を参照してください link:troubleshoot_index.html["トラブルシューティングを行う"] 詳細および解決策については、手順の末尾にあるセクションを参照してください。

発生した問題に対する解決策が見つからない場合は、テクニカルサポートにお問い合わせください。
