= ノード 4 の FC ポートを設定します
:allow-uri-read: 




== ノード 4 の FC ポートを設定します

node4 にオンボードまたはアドオン FC アダプタ上の FC ポートがある場合、システムの出荷時にポートが事前構成されていないため、ノードをサービスに投入する前にノード上でポート構成を設定する必要があります。必要に応じてポートを構成しないと、サービスが中断される可能性があります。

.作業を開始する前に
セクションに保存した node2 の FC ポート設定の値を確認しておく必要があります link:prepare_nodes_for_upgrade.html["ノードをアップグレードする準備をします"]。

.このタスクについて
システムに FC 構成がない場合は、このセクションをスキップしてかまいません。システムにオンボード UTA / UTA2 ポートまたは UTA / UTA2 アダプタが搭載されている場合は、で設定します <<ノード 4 の UTA / UTA2 ポートを確認して設定してください>>。


IMPORTANT: このセクションのコマンドをメンテナンス モードのシェル プロンプトで入力します。

.手順
. システム上のすべての FC および統合ネットワーク アダプタに関する情報を表示します。
+
「 system node hardware unified-connect show 」を参照してください

. ノード 4 の FC 設定とノード 1 から前に取得した設定を比較します。
. 必要に応じて、ノード 4 の FC ポートを変更します。
+
** ターゲット ポートとしてプログラムするには:
+
ucadmin modify -m fc -t target_adapter_`

+
例えば： `ucadmin modify -m fc -t target 2a`

** イニシエータポートをプログラミングする場合：
+
ucadmin modify -m fc -t initiator_adapter_`

+
`-t` は FC4 のタイプで ' ターゲットまたはイニシエータです

+
例えば： `ucadmin modify -m fc -t initator 2b`



. ノードを停止します。
+
「 halt 」

. LOADERプロンプトからシステムをブートします。
+
「 boot_ontap menu

. コマンドを入力したら、ブート環境のプロンプトでシステムが停止するまで待ちます。
. 保守モードのブート・メニューからオプション「 5 」を選択します。

