= 
:allow-uri-read: 


node2 に同じバージョンの ONTAP 9 がインストールされていない場合は、 node4 をネットブートする必要があります。node4 のインストールが完了したら、 Web サーバに格納されている ONTAP 9 イメージからブートします。その後、の手順に従って、後続のシステムのブートに使用する正しいファイルをブートメディアデバイスにダウンロードできます link:prepare_for_netboot.html["ネットブートを準備"]。

[IMPORTANT]
====
* AFF A800 または AFF C800 コントローラのアップグレードの場合、ノード 2 を取り外す前に、シャーシ内のすべてのドライブがミッドプレーンにしっかりと固定されていることを確認する必要があります。詳細については、を参照してください link:../upgrade-arl-auto-affa900/replace-node1-affa800.html["AFF A800またはAFF C800コントローラモジュールを交換"]。
* ストレージアレイに接続されている V シリーズシステム、またはストレージアレイに接続されている FlexArray 仮想化ソフトウェアを使用するシステムをアップグレードする場合は、これで完了です <<auto_install4_step1,手順 1.>> から <<auto_install4_step21,手順 21>>をクリックしてから、このセクションの指示に従ってください link:set_fc_or_uta_uta2_config_node4.html#configure-fc-ports-on-node4["ノード 4 の FC ポートを設定します"] およびへ link:set_fc_or_uta_uta2_config_node4.html#check-and-configure-utauta2-ports-on-node4["ノード 4 の UTA / UTA2 ポートを確認して設定してください"]、保守モードでコマンドを入力します。その後、このセクションに戻ってからを使用して再開する必要があります <<auto_install4_step23,手順 23>>。
* ストレージディスクを備えたシステムをアップグレードする場合は、このセクション全体を完了してから、 link:set_fc_or_uta_uta2_config_node4.html["ノード 4 で FC または UTA / UTA2 設定を設定します"]クラスタープロンプトでコマンドを入力します。


====
.手順
. [[auto_install4_stp1] ノード 4 に十分なラックスペースがあることを確認します。
+
node4 が node2 とは別のシャーシにある場合は、 node3 と同じ場所に node4 を配置できます。node2 と node4 が同じシャーシにある場合は、 node4 が適切なラックの場所にすでに存在しているとします。

. ノードモデルの _Installation and Setup Instructions _ の手順に従って、ノード 4 をラックに設置します。
. ノード 4 をケーブル接続します。 node2 から node4 に接続を移動します。
+
ノード4プラットフォームの_インストールおよびセットアップ手順_または_ FlexArray仮想化インストール要件およびリファレンス_の手順書、該当するディスクシェルフドキュメント、および_ HAペア管理_を使用して、次の接続をケーブル接続します。

+
FlexArray仮想化インストール要件およびReference_and_HA pair management_へのリンクを参照してくださいlink:other_references.html["参考資料"]。

+
** コンソール（リモート管理ポート）
** クラスタポート
** データポート
** クラスタポートとノード管理ポート
** ストレージ
** SAN 構成： iSCSI イーサネットおよび FC スイッチポート
+

NOTE: ほとんどのプラットフォームモデルには一意のインターコネクトカードモデルがあるため、インターコネクトカード / FC-VI カードまたはインターコネクト / FC-VI ケーブルの接続を node2 から node4 に移動する必要はありません。MetroCluster 構成の場合は、 FC-VI ケーブルの接続を node2 から node4 に移動する必要があります。新しいホストに FC-VI カードがない場合は、 FC-VI カードの移動が必要になることがあります。



. ノード 4 の電源をオンにしてから、コンソール端末で Ctrl+C キーを押してブートプロセスを中断し、ブート環境プロンプトにアクセスします。
+

NOTE: node4 をブートすると、次の警告メッセージが表示される場合があります。

+
....
WARNING: The battery is unfit to retain data during a power outage. This is likely
         because the battery is discharged but could be due to other temporary
         conditions.
         When the battery is ready, the boot process will complete
         and services will be engaged. To override this delay, press 'c' followed
         by 'Enter'
....
. 手順 4 で警告メッセージが表示された場合は、次の操作を実行します。
+
.. NVRAM バッテリ低下以外の問題を示すコンソールメッセージがないか確認し、必要に応じて対処します。
.. バッテリの充電と起動プロセスが完了するまで待ちます。
+

WARNING: * 注意：遅延は無視しないでください。バッテリーの充電に失敗すると、データが失われるおそれがあります。 *

+

NOTE: を参照してください link:prepare_for_netboot.html["ネットブートを準備"]。




