= ノード 4 の FC ポートを設定します
:allow-uri-read: 




== ノード 4 の FC ポートを設定します

ノード 4 にオンボードまたは FC アダプタのいずれかの FC ポートがある場合は、ポートが事前に構成されていないため、ノードを稼働状態にする前にポートの設定を行う必要があります。ポートが設定されていないと、サービスが停止する可能性があります。

.作業を開始する前に
セクションに保存した node2 の FC ポート設定の値を確認しておく必要があります link:prepare_nodes_for_upgrade.html["ノードをアップグレードする準備をします"]。

.このタスクについて
システムに FC 構成がない場合は、このセクションをスキップしてかまいません。システムにオンボード UTA / UTA2 ポートまたは UTA / UTA2 アダプタが搭載されている場合は、で設定します <<ノード 4 の UTA / UTA2 ポートを確認して設定してください>>。


IMPORTANT: システムにストレージディスクがある場合は、クラスタプロンプトでこのセクションのコマンドを入力する必要があります。V シリーズシステムまたは FlexArray 仮想化ソフトウェアがストレージアレイに接続されたシステムの場合は、このセクションのメンテナンスモードでコマンドを入力します。

.手順
. 次のいずれかを実行します。
+
[cols="30,70"]
|===
| アップグレードするシステム | 次に、 


| ストレージディスクがあります | 「 system node hardware unified-connect show 」を参照してください 


| は、 V シリーズシステムまたは FlexArray 仮想化ソフトウェアを搭載し、ストレージアレイに接続されています | ucadmin show 
|===
+
システムには、システム上のすべての FC アダプタと統合ネットワークアダプタに関する情報が表示されます。

. ノード 4 の FC 設定とノード 1 から前に取得した設定を比較します。
. 次のいずれかを実行します。
+
[cols="30,70"]
|===
| アップグレードするシステム | 次に、 


| ストレージディスクがあります  a| 
必要に応じて、ノード 4 の FC ポートを変更します。

** ターゲットポートをプログラムする場合：
+
ucadmin modify -m fc -t target_adapter_`

** イニシエータポートをプログラミングする場合：
+
ucadmin modify -m fc -t initiator_adapter_`



`-t` は FC4 のタイプで ' ターゲットまたはイニシエータです



| は、 V シリーズシステムまたは FlexArray 仮想化ソフトウェアを搭載し、ストレージアレイに接続されています  a| 
必要に応じて、ノード 4 の FC ポートを変更します。

`ucadmin modify -m fc -t initiator -f _adapter_port_name_`

`-t` は、FC4タイプ、ターゲット、イニシエータです。


NOTE: FCポートはイニシエータとしてプログラムする必要があります。

|===
. メンテナンスモードを終了します。
+
「 halt 」

. LOADERプロンプトからシステムをブートします。
+
「 boot_ontap menu

. コマンドを入力したら、ブート環境のプロンプトでシステムが停止するまで待ちます。
. 保守モードのブート・メニューからオプション「 5 」を選択します。

