= 
:allow-uri-read: 


. FC イニシエータポートをストレージアレイに新しいホストとして追加し、アレイ LUN を新しいホストにマッピングします。
+
手順については、ストレージアレイおよびゾーニングに関するドキュメントを参照してください。

. ストレージアレイ上のアレイ LUN に関連付けられたホストまたはボリュームグループの World Wide Port Name （ WWPN ；ワールドワイドポート名）値を変更する。
+
新しいコントローラモジュールを設置すると、各オンボード FC ポートに関連付けられている WWPN の値が変更されます。

. スイッチベースのゾーニングを使用している場合は、新しい WWPN 値が反映されるようにゾーニングを調整します。
. [[step27]]を設定します `bootarg.storageencryption.support` および `kmip.init.maxwait` node2構成のロード後にブートループが発生しないようにするための変数。
+
手順 でこれまでに行ったことがない場合は、Knowledge Baseの記事を参照してください https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Systems/FAS_Systems/How_to_tell_I_have_FIPS_drives_installed["FIPSドライブが取り付けられていることを確認する方法"^] 使用している自己暗号化ドライブのタイプを確認するため。

+
[cols="35,65"]
|===
| 次のドライブが使用中の場合 | 次に、 


| FIPS 140-2レベル2の自己暗号化要件に準拠したNetApp Storage Encryption（NSE）ドライブ  a| 
** `setenv bootarg.storageencryption.support *true*`
** 'etenv kmip.init.maxwait off




| ネットアップの非FIPS SED  a| 
** `setenv bootarg.storageencryption.support *false*`
** 'etenv kmip.init.maxwait off


|===
+
[NOTE]
====
** FIPSドライブは、同じノードまたはHAペアで他のタイプのドライブと混在させることはできません。
** SEDと非暗号化ドライブを同じノードまたはHAペアで混在させることができます。
** を設定したあとに停電が発生した場合は `kmip.init.maxwait` 変数をに設定します `off`を参照し、データ損失の可能性を回避するための支援をテクニカルサポートに依頼してください。
** HAペアのコントローラのアップグレードが完了したら、の設定を解除する必要があります `kmip.init.maxwait` 変数（Variable）：を参照してください link:ensure_new_controllers_are_set_up_correctly.html["新しいコントローラが正しくセットアップされていることを確認します"]。


====
. ノードをブートメニューに追加します。
+
「 boot_ontap menu

+
FC または UTA / UTA2 設定がない場合は、を実行します link:set_fc_or_uta_uta2_config_node4.html#auto_check_node4_step15["ノード 4 の UTA / UTA2 ポートの確認と設定、手順 15"] ノード 4 が node2 のディスクを認識できるようにします。


