= ノード 3 の FC ポートを設定
:allow-uri-read: 




== ノード 3 の FC ポートを設定

node3 にオンボードまたはアドオン FC アダプタ上の FC ポートがある場合、システムの出荷時にポートが事前構成されていないため、ノードをサービスに投入する前にノード上でポート構成を設定する必要があります。ポートを設定しないと、サービスが中断される可能性があります。

.作業を開始する前に
セクションに保存した FC ポート設定の値を node1 で確認しておく必要があります link:prepare_nodes_for_upgrade.html["ノードをアップグレードする準備をします"]。

.このタスクについて
システムに FC 構成がない場合は、このセクションをスキップしてかまいません。システムにオンボード UTA / UTA2 ポートまたは UTA / UTA2 カードがある場合は、で設定します <<ノード 3 の UTA / UTA2 ポートを確認して設定してください>>。


IMPORTANT: このセクションのコマンドをメンテナンス モードのシェル プロンプトで入力します。

.手順
. ノード 3 の FC 設定を、先ほどノード 1 からキャプチャした設定と比較します。
. 必要に応じて、次のいずれかのアクションを実行して、ノード 3 の FC ポートを変更します。
+
メンテナンス モードの場合 (ブート メニューのオプション 5):

+
** ターゲット ポートとしてプログラムするには:
+
`ucadmin modify -m fc -t target <adapter>`

+
例えば： `ucadmin modify -m fc -t target 2a`

** イニシエータポートをプログラミングする場合：
+
`ucadmin modify -m fc -t initiator <adapter>`

+
例えば： `ucadmin modify -m fc -t initator 2b`



. 次のコマンドを使用して出力を調べ、新しい設定を確認します。
+
ucadmin show

. ノードを停止します。
+
「 halt 」

. LOADERプロンプトからシステムをブートします。
+
「 boot_ontap menu

. コマンドを入力したら、ブート環境のプロンプトでシステムが停止するまで待ちます。
. 保守モードのブート・メニューからオプション「 5 」を選択します。

