= アグリゲートは、アップグレードの完了後、ノード 1 にもともと存在していたものとノード 4 によって所有されます
:allow-uri-read: 




== アグリゲートは、アップグレードの完了後、ノード 1 にもともと存在していたものとノード 4 によって所有されます

アップグレード手順の最後に、 node3 は、元々ホームノードとしてノード 1 を使用していたアグリゲートの新しいホームノードである必要があります。このパスはアップグレード後に再配置できます。

次の状況で、アグリゲートを正しく再配置できず、ノード 1 がノード 3 ではなくホームノードになっている可能性があります。

* ステージ 3 で、アグリゲートが node2 から node3 に再配置されている場合。再配置する一部のアグリゲートのホームノードが node1 に含まれている。たとえば、このようなアグリゲートのことを aggr_node_A_1 と呼びます。ステージ 3 で aggr_node_A_1 の再配置が失敗し、強制的に再配置を実行できない場合、アグリゲートは node2 で残ります。
* ステージ 4 のあとで、 node2 を node4 に置き換える場合。node2 を交換すると、 aggr_node_A_1 が、 node3 ではなく node4 にあるホームノードとしてオンラインになります。


ストレージフェイルオーバーを有効にしたあとに、ステージ 6 に続けて誤った所有権の問題を修正するには、次の手順を実行します。

.手順
. 次のコマンドを入力して、アグリゲートのリストを表示します。
+
storage aggregate show -nodes_node4 --is-home true

+
正しく再配置されていないアグリゲートを特定するには、セクションで取得した node1 のホーム所有者を含むアグリゲートのリストを参照してください link:prepare_nodes_for_upgrade.html["ノードをアップグレードする準備をします"] コマンドの出力と比較してください。

. 手順 1 の出力と、セクションで確認した node1 用の出力を比較します link:prepare_nodes_for_upgrade.html["ノードをアップグレードする準備をします"] 再配置されていないアグリゲートがあることを確認します。
. [[auto_aggr_relocate_fail_Step3] ノード 4 の背後にあるアグリゲートの再配置：
+
「storage aggregate relocation start -NODE_node4」-aggr_aggr_node_A_1 -destination_node3 _」を入力します

+
この再配置中は '-nd-controller-upgrade パラメータを使用しないでください

. node3 がアグリゲートのホームの所有者になったことを確認します。
+
storage aggregate show -aggregate aggr1、aggr2、aggr3_-fields home-name

+
「_aggr1、aggr2、aggr3__」は、node1が元のホーム所有者であるアグリゲートのリストです。

+
ノード 3 をホーム所有者としないアグリゲートは、の同じ再配置コマンドを使用してノード 3 に再配置できます ,手順 3。


