= 
:allow-uri-read: 


. [[auto_check3_step17]] autoboot 中に Ctrl + C を押して 'loader>` プロンプトでノードを停止します
. [[step18]] LOADER プロンプトで、メンテナンスモードに切り替えます。
+
「 boot_ontap maint 」を使用してください

. [[step19]] メンテナンスモードで、現在ターゲットモードになっている以前に設定されたすべてのイニシエータポートを表示します。
+
ucadmin show

+
ポートをイニシエータモードに戻します。

+
ucadmin modify -m fc -t initiator -f adapter name_`

. [[step20]] ポートがイニシエータモードに変更されていることを確認します。
+
ucadmin show

. [[step2]] メンテナンスモードを終了します。
+
「 halt 」

+
[NOTE]
====
外付けディスクをサポートするシステムから、外付けディスクもサポートするシステムにアップグレードする場合は、に進みます <<auto_check3_step22,手順 22>>。

外付けディスクをサポートするシステムから、AFF A800システムなどの内蔵ディスクと外付けディスクの両方をサポートするシステムにアップグレードする場合は、に進みます <<auto_check3_step23,手順 23>>。

====
. [[auto_check3_step22]] LOADERプロンプトで、次を起動します。
+
「 boot_ontap menu

+
これで、ブート時に以前に割り当てられていたすべてのディスクをノードで検出できるようになり、想定どおりにブートできるようになります。

+
交換するクラスタノードがルートボリューム暗号化を使用している場合、ONTAP ソフトウェアはディスクからボリューム情報を読み取ることができません。ルートボリュームのキーをリストアします。

+
.. 特別なブートメニューに戻ります。
`LOADER> boot_ontap menu`
+
[listing]
----
Please choose one of the following:
(1) Normal Boot.
(2) Boot without /etc/rc.
(3) Change password.
(4) Clean configuration and initialize all disks.
(5) Maintenance mode boot.
(6) Update flash from backup config.
(7) Install new software first.
(8) Reboot node.
(9) Configure Advanced Drive Partitioning.
(10) Set Onboard Key Manager recovery secrets.
(11) Configure node for external key management.

Selection (1-11)? 10
----
.. （10）Set Onboard Key Manager Recovery secrets（オンボードキーマネージャリカバリシークレットの設定）*を選択します
.. 入力するコマンド `y` 次のプロンプトが表示されます。
+
`This option must be used only in disaster recovery procedures. Are you sure? (y or n): y`

.. プロンプトで、キー管理ツールのパスフレーズを入力します。
.. プロンプトが表示されたら、バックアップデータを入力します。
+

NOTE: でパスフレーズとバックアップデータを入手しておく必要があります link:prepare_nodes_for_upgrade.html["ノードをアップグレードする準備をします"] この手順のセクション。

.. システムが再度特別な起動メニューを起動したら、オプション*（1）Normal Boot *を実行します
+

NOTE: この段階でエラーが発生する場合があります。エラーが発生した場合は、の手順を繰り返します <<auto_check3_step22,手順 22>> システムが正常に起動するまで。



. [[auto_check3_step23]] 外付けディスクがあるシステムから、内蔵ディスクと外付けディスクをサポートするシステム（ AFF A800 システムなど）にアップグレードする場合は、 node1 アグリゲートをルートアグリゲートとして設定し、ノード 1 のルートアグリゲートからノード 3 がブートすることを確認します。ルート・アグリゲートを設定するには ' ブート・メニューからオプション 5 を選択して ' 保守モードに切り替えます
+

CAUTION: * ここに示す順序で以下の手順を実行する必要があります。正しく実行しないと、原因が停止したり、データが失われたりする可能性があります。 *

+
次の手順は、 node3 を node1 のルートアグリゲートからブートするように設定します。

+
.. メンテナンスモードに切り替えます。
+
「 boot_ontap maint 」を使用してください

.. node1 アグリゲートの RAID 、プレックス、およびチェックサムの情報を確認します。
+
「 aggr status -r 」

.. node1 アグリゲートのステータスを確認します。
+
「 aggr status 」を入力します

.. 必要に応じて、 node1 アグリゲートをオンラインにします。
+
「aggr_online root_aggr_from__」を参照してください

.. node3 を元のルートアグリゲートからブートできないようにします。
+
「aggr offline_root_aggr_on_node3」を参照してください

.. node1 ルートアグリゲートを、 node3 の新しいルートアグリゲートとして設定します。
+
'aggr options aggr_from__ node1 __ root

.. ノード 3 のルートアグリゲートがオフラインになっていること、およびノード 1 からテイクオーバーされたディスクのルートアグリゲートがオンラインになっていて root に設定されていることを確認します。
+
「 aggr status 」を入力します

+

NOTE: 前の手順を実行しないと、原因 node3 を内部ルートアグリゲートからブートするか、原因システムで新しいクラスタ構成が存在すると想定するか、あるいはクラスタ構成を特定するように求められる可能性があります。

+
次の例は、コマンドの出力を示しています。

+
[listing]
----
 -----------------------------------------------------------------
 Aggr                 State    Status             Options

 aggr0_nst_fas8080_15 online   raid_dp, aggr      root, nosnap=on
                               fast zeroed
                               64-bit

 aggr0                offline  raid_dp, aggr      diskroot
                               fast zeroed
                               64-bit
 -----------------------------------------------------------------
----



