= ノード 3 の UTA / UTA2 ポートを確認して設定してください
:allow-uri-read: 




== ノード 3 の UTA / UTA2 ポートを確認して設定してください

ノード 3 にオンボード UTA / UTA2 ポートまたは UTA / UTA2 カードが搭載されている場合は、アップグレードしたシステムの使用方法によって、ポートの設定を確認し、場合によっては再設定する必要があります。

.作業を開始する前に
UTA / UTA2 ポートに対応する正しい SFP+ モジュールが必要です。

.このタスクについて
FC にユニファイドターゲットアダプタ（ UTA / UTA2 ）ポートを使用する場合は、まずポートの設定を確認する必要があります。


NOTE: ネットアップのマーケティング資料では、 UTA2 という用語を CNA アダプタとポートという意味で使用している場合があります。ただし、 CLI では CNA という用語が使用されます。

使用することができます `ucadmin show`次の出力例に示すように、現在のポート構成を表示または確認するには、コマンドを使用します。

....
*> ucadmin show
         Current  Current    Pending   Pending      Admin
Adapter  Mode     Type       Mode      Type         Status
-------  -------  -------    --------  ----------   --------
0e      fc        target     -         initiator    offline
0f      fc        target     -         initiator    offline
0g      fc        target     -         initiator    offline
0h      fc        target     -         initiator    offline
1a      fc        target     -         -            online
1b      fc        target     -         -            online
6 entries were displayed.
....
UTA / UTA2 ポートは、ネイティブの FC モードまたは UTA / UTA2 モードに設定できます。FC モードでは FC イニシエータと FC ターゲットがサポートされます。 UTA / UTA2 モードを使用すると、同じ 10GbE SFP+ インターフェイスを共有する NIC と FCoE のトラフィックを同時に処理でき、 FC ターゲットをサポートできます。

アドオン アダプタまたはコントローラ マザーボード上に UTA/UTA2 ポートがあり、次の構成になっている場合がありますが、ノード 3 の UTA/UTA2 ポートの構成を確認し、必要に応じて変更する必要があります。

* コントローラを注文した UTA / UTA2 カードは、注文したパーソナリティを指定するために出荷前に設定されます。
* コントローラとは別に発注した UTA / UTA2 カードは、デフォルトの FC ターゲットパーソナリティとして出荷されます。
* 新しいコントローラのオンボード UTA / UTA2 ポートは、希望するパーソナリティを持つように出荷する前に設定されます。
+

WARNING: UTA/UTA2 ポートを構成するには、メンテナンス モードになっている必要があります。このセクションのコマンドをメンテナンス モードのシェル プロンプトで入力します。



.手順
. 現在の SFP+ モジュールが目的の用途と一致しない場合は、正しい SFP+ モジュールに交換します。
+
ネットアップの担当者に連絡して、正しい SFP+ モジュールを入手します。

. UTA/UTA2 ポート設定を確認します。
+
ucadmin show

+
出力を調べて、UTA/UTA2 ポートに必要な特性があるかどうかを判断します。

+
次の例の出力は、アダプタ「1b」のタイプがイニシエーターに変更され、アダプタ「2a」と「2b」のモードが「cna」に変更されていることを示しています。  CNA モードでは、カードをネットワーク アダプタとして使用できます。

+
[listing]
----
*> ucadmin show
         Current    Current     Pending  Pending     Admin
Adapter  Mode       Type        Mode     Type        Status
-------  --------   ----------  -------  --------    --------
1a       fc         initiator   -        -           online
1b       fc         target      -        initiator   online
2a       fc         target      cna      -           online
2b       fc         target      cna      -           online
*>
----
. 次のいずれかを実行します。
+
[cols="30,70"]
|===
| UTA / UTA2 ポート | 次に、 


| 希望するパーソナリティがない | 行きます <<auto_check3_step4,手順 4>>。 


| あなたがほしい人格を持っている | ステップ4からステップ8をスキップして、<<auto_check3_step9,手順 9>> 。 
|===
. [[auto_check3_step4]]次のいずれかのアクションを実行します。
+
[cols="30,70"]
|===
| を設定する場合 | 次に、 


| UTA / UTA2 カードのポート | へ移動<<auto_check3_step5,手順 5>> 


| オンボードの UTA/UTA2 ポート | ステップ5をスキップして<<auto_check3_step6,手順 6>>。 
|===
. [[auto_check3_step5]]アダプタがイニシエーターモードであり、UTA/UTA2 ポートがオンラインの場合は、UTA/UTA2 ポートをオフラインにします。
+
`storage disable adapter <adapter_name>`

+
ターゲットモードのアダプタは、メンテナンスモードで自動的にオフラインになります。

. [[auto_check3_step6]]現在の構成が目的の用途と一致しない場合は、必要に応じて構成を変更します。
+
`ucadmin modify -m fc|cna -t initiator|target <adapter_name>`

+
** 「 -m 」はパーソナリティ・モードで、「 fc 」または「 cna 」です。
** `-t` は FC4 のタイプ、「 target 」または「 initiator 」です。
+

NOTE: テープ ドライブおよびMetroCluster構成には FC イニシエーターを使用する必要があります。  SAN クライアントには FC ターゲットを使用する必要があります。



. 各ポートに対して次のコマンドを 1 回ずつ入力して、ターゲット ポートをオンラインにします。
+
`storage enable adapter <adapter_name>`

. ポートをケーブル接続します。

