= 



NOTE: アグリゲートおよび LIF のホーム所有者は変更されず、現在の所有者のみが変更されます。

.手順
. アグリゲートの再配置処理と NAS データ LIF の移動処理を再開します。
+
「システムコントローラの交換が再開」

+
ルート以外のアグリゲートと NAS データ LIF はすべて、 node1 から node2 に移行されます。

+
処理が一時停止することで、ノード 1 のルート以外のアグリゲートと SAN 以外のデータ LIF がすべて node2 に移行されているかどうかを確認できます。

. アグリゲートの再配置処理と NAS データ LIF の移動処理のステータスを確認します。
+
「 system controller replace show-sdetails 」というエラーが表示されます

. 処理が一時停止したまま、ルート以外のすべてのアグリゲートが node2 でそれぞれの状態でオンラインになっていることを確認します。
+
「 storage aggregate show -node <node2> -state online -root false 」のように表示されます

+
次の例は、 node2 のルート以外のアグリゲートがオンラインになっていることを示しています。

+
[listing]
----
cluster::> storage aggregate show -node node2 state online -root false

Aggregate  Size     Available  Used%  State  #Vols  Nodes  RAID Status
---------  -------  ---------  -----  ------ -----  ------ --------------
aggr_1     744.9GB  744.8GB    0%     online     5  node2  raid_dp,normal
aggr_2     825.0GB  825.0GB    0%     online     1  node2  raid_dp,normal
2 entries were displayed.
----
+
アグリゲートがオフラインになった場合、または node2 で外部になった場合は、各アグリゲートに対して 1 回、 node2 で次のコマンドを使用してアグリゲートをオンラインにします。

+
「 storage aggregate online -aggregate <aggr_name>` 」という名前になります

. node2 で次のコマンドを使用し、出力を調べて、すべてのボリュームがオンラインであることを確認します。
+
volume show -node <node2> -state offline`

+
node2 上にオフラインのボリュームがある場合は、各ボリュームに対して 1 回、 node2 で次のコマンドを使用してオンラインにします。

+
'volume online -vserver <vserver-name> -volume <volume-name>`

+
このコマンドで使用する '<vserver-name> は ' 前の volume show コマンドの出力にあります


