= ノード 3 の FC ポートを設定




== ノード 3 の FC ポートを設定

node3 にオンボードまたは FC アダプタの FC ポートがある場合は、ポートが事前に設定されていないため、ノードを稼働状態にする前にポート設定を設定する必要があります。ポートが設定されていないと、サービスが停止する可能性があります。

セクションに保存した FC ポート設定の値を node1 で確認しておく必要があります link:prepare_nodes_for_upgrade.html["ノードをアップグレードする準備をします"]。

システムに FC 構成がない場合は、このセクションをスキップしてかまいません。システムにオンボード UTA / UTA2 ポートまたは UTA / UTA2 カードがある場合は、で設定します <<Check and configure UTA/UTA2 ports on node3>>。

* 重要 * ：ご使用のシステムにストレージ・ディスクがある場合は、クラスタ・プロンプトでこのセクションにコマンドを入力してください。「 V シリーズシステム」または FlexArray 仮想化ソフトウェアを使用していて、ストレージアレイに接続している場合は、このセクションにメンテナンスモードでコマンドを入力します。

. [[step1] ノード 3 の FC 設定を、ノード 1 から前に取得した設定と比較します。
. [[step2]] 次のいずれかの操作を実行します。
+
[cols="30,70"]
|===
| アップグレードするシステム | 次に、 


| ストレージディスクがあります  a| 
メンテナンスモード（ブートメニューのオプション 5 ）で、必要に応じてノード 3 の FC ポートを変更します。

** ターゲットポートをプログラムする場合：


ucadmin modify -m fc -t target <adapter>`

** イニシエータポートをプログラミングする場合：


ucadmin modify -m fc -t initiator <adapter>`

`-t` は FC4 のタイプで ' ターゲットまたはイニシエータです



| は、 V シリーズシステムまたは FlexArray 仮想化ソフトウェアを搭載し、ストレージアレイに接続されています | 保守モード（ブートメニューのオプション 5 ）で、必要に応じて node3 の FC ポートを変更します。 ucadmin modify -m fc -t initiator -f <adapter_port_name> `-t` は、 fc4 タイプ、ターゲット、またはイニシエータです。* 注： FC ポートはイニシエータとしてプログラムする必要があります。 
|===
. [[step3]] 次のいずれかの操作を実行します。
+
[cols="30,70"]
|===
| アップグレードするシステム | 次に、 


| ストレージディスクがあります | 次のコマンドを使用して、新しい設定を確認します。 ucadmin show 


| は、 V シリーズシステムまたは FlexArray 仮想化ソフトウェアを搭載し、ストレージアレイに接続されています | 次のコマンドを使用して、新しい設定を確認します。 ucadmin show 
|===
. [[step4]] メンテナンスモードを終了します。
+
「 halt 」

. LOADER プロンプトからシステムをブートします。
+
「 boot_ontap menu

. [[step6] コマンドを入力したら、ブート環境のプロンプトでシステムが停止するまで待ちます。
. 保守モードのブート・メニューからオプション「 5 」を選択します。

