= ノード 3 の FC ポートを設定
:allow-uri-read: 




== ノード 3 の FC ポートを設定

node3 にオンボードまたはアドオン FC アダプタ上の FC ポートがある場合、システムの出荷時にポートが事前構成されていないため、ノードをサービスに投入する前にノード上でポート構成を設定する必要があります。ポートを設定しないと、サービスが中断される可能性があります。

.作業を開始する前に
に保存した FC ポート設定の値を node1 で確認しておく必要があります link:prepare_nodes_for_upgrade.html["ノードをアップグレードする準備をします"]。

.このタスクについて
システムに FC 構成がない場合は、このセクションをスキップしてかまいません。システムにオンボード UTA / UTA2 ポートまたは UTA / UTA2 カードがある場合は、で設定します <<ノード 3 の UTA / UTA2 ポートを確認して設定してください>>。


IMPORTANT: このセクションのコマンドをクラスタープロンプトに入力します。

.手順
. システム上のすべての FC および統合ネットワーク アダプタに関する情報を表示します。
+
「 system node hardware unified-connect show 」を参照してください

. ノード 3 の FC 設定を、先ほどノード 1 からキャプチャした設定と比較します。
. [[man_config_3_step3]]次のいずれかのアクションを実行します。
+
[cols="35,65"]
|===
| 新しいノードのデフォルトの FC 設定 | 作業 


| ノード 1 で取得したものと同じです | 行きます <<man_config_3_step9,手順 9>>。 


| ノード 1 で取得したものとは異なります | 行きます <<man_config_3_step4,手順 4>>。 
|===
. [[man_config_3_step4]]必要に応じて、次のいずれかのコマンドを入力して、ノード3 の FC ポートを変更します。
+
** ターゲットポートをプログラムする場合：
+
`system node hardware unified-connect modify -type \| -t target -adapter _port_name_`

** イニシエータポートをプログラミングする場合：
+
`system node hardware unified-connect modify -type \| -t initiator -adapter _port_name_`

+
`-t` は FC4 のタイプで ' ターゲットまたはイニシエータです



. 次のコマンドを入力して出力を調べ、新しい設定を確認します。
+
「 system node hardware unified-connect show 」を参照してください

. メンテナンスモードを終了します。
+
「 halt 」

. コマンドを入力したら、ブート環境のプロンプトでシステムが停止するまで待ちます。
. ブート環境プロンプトで node3 をブートします。
+
「 boot_ontap 」

. [[man_config_3_step9]]次のいずれかのアクションを実行します。
+
** ノード 3 に UTA / UTA2 カードまたは UTA / UTA2 オンボードポートがある場合は、に進みます <<ノード 3 の UTA / UTA2 ポートを確認して設定してください>>。
** ノード 3 に UTA / UTA2 カードまたは UTA / UTA2 オンボードポートがない場合は、この手順を省略してください <<ノード 3 の UTA / UTA2 ポートを確認して設定してください>> にアクセスします link:map_ports_node1_node3.html["ポートを node1 から node3 にマッピングします"]。



