= 
:allow-uri-read: 


ノード 4 をラックに設置し、ノード 2 の接続をノード 4 に転送し、ノード 4 をブートする必要があります。ノード 2 のスペア、ルートに属するディスク、および node3 でそれよりも前に再配置されなかったルート以外のアグリゲートも再割り当てする必要があります。

.このタスクについて
node2 に同じバージョンの ONTAP 9 がインストールされていない場合は、 node4 をネットブートする必要があります。node4 のインストールが完了したら、 Web サーバに格納されている ONTAP 9 イメージからブートします。その後、の手順に従って、後続のシステムのブートに使用する正しいファイルをブートメディアデバイスにダウンロードできます link:prepare_for_netboot.html["ネットブートを準備"]

ただし、ノード2に同じバージョンまたはそれ以降のバージョンのONTAP 9がインストールされている場合は、ノード4をネットブートする必要はありません。

* 重要な情報： *

* V シリーズシステム、またはストレージアレイに接続された FlexArray 仮想化ソフトウェアを使用するシステムをアップグレードする場合は、を完了する必要があります <<man_install4_Step1,手順 1.>> から <<man_install4_Step7,手順 7>>をクリックします <<man_install4_Step8,手順 8>> およびの手順に従ってください link:set_fc_uta_uta2_config_node4.html["ノード 4 で FC または UTA / UTA2 設定を設定します"] 必要に応じて、メンテナンスモードでコマンドを入力します。その後、このセクションに戻り、で手順 を再開する必要があります <<man_install4_Step9,手順 9>>。
* ただし、ストレージディスクを搭載したシステムをアップグレードする場合は、このセクション全体を完了してからセクションに進む必要があります link:set_fc_uta_uta2_config_node4.html["ノード 4 で FC または UTA / UTA2 設定を設定します"]クラスタ・プロンプトでコマンドを入力します。


.手順
. [[man_install4_Step1] 次のいずれかの操作を行います。
+
[cols="35,65"]
|===
| ノード 4 の配置先 | 作業 


| ノード 3 とは別のシャーシ | に進みます <<man_install4_Step2,手順 2>>。 


| 同じシャーシを node3 と一緒に配置する | 手順 2 と 3 を省略して、に進みます <<man_install4_Step4,手順 4>>。 
|===
. [[man_install4_Step2]] ノード 4 に十分なラックスペースがあることを確認します。
+
node4 と node3 が別々のシャーシにある場合は、 node4 を node2 と同じ場所に配置できます。node3 と node4 が同じシャーシにある場合は、 node4 が適切なラックの場所にすでに存在しているとします。

. ノードモデルの _Installation and Setup Instructions _ の手順に従って、ノード 4 をラックに設置します。
. [[man_install4_Step4]] ケーブルノード 4 を接続し、ノード 2 からノード 4 に接続を移動します。
+
次の参考資料は、適切なケーブル接続を行う場合に役立ちます。に進みます link:other_references.html["参考資料"] をクリックしてリンクします。

+
** _ インストールおよびセットアップ手順 _ または _ FlexArray 仮想化インストール要件およびリファレンス _ （ノード 4 プラットフォーム用）
** 該当するディスクシェルフの手順を選択します
** HAペア管理のドキュメント
+
次の配線を行います。

** コンソール（リモート管理ポート）
** クラスタポート
** データポート
** クラスタポートとノード管理ポート
** ストレージ
** SAN 構成： iSCSI イーサネットおよび FC スイッチポート


+

NOTE: ほとんどのプラットフォームモデルには一意のインターコネクトカードモデルがあるため、インターコネクトカード / FC-VI カードまたはインターコネクト / FC-VI ケーブルの接続を node2 から node4 に移動する必要はありません。

. 次のいずれかを実行します。
+
[cols="35,65"]
|===
| ノード 4 の構成 | 作業 


| ノード 3 と同じシャーシ | に進みます <<man_install4_Step8,手順 8>>。 


| ノード 3 とは別のシャーシ | に進みます <<man_install4_Step6,手順 6>>。 
|===
. [[man_install4_step6]]ノード4の電源をオンにし、Ctrl+Cキーを押してブートを中断してブート環境プロンプトにアクセスします。
+

NOTE: node4 をブートすると、次のメッセージが表示される場合があります。

+
[listing]
----
WARNING: The battery is unfit to retain data during a power
         outage. This is likely because the battery is
         discharged but could be due to other temporary
         conditions.
         When the battery is ready, the boot process will
         complete and services will be engaged.
         To override this delay, press 'c' followed by 'Enter'
----
. [[man_install4_Step7] ステップ 6 で警告メッセージが表示された場合は、次の操作を実行します。
+
.. NVRAM バッテリ低下以外の問題を示すコンソールメッセージがないか確認し、必要に応じて対処します。
.. バッテリの充電と起動プロセスが完了するまで待ちます。
+

WARNING: * 警告 : 遅延を上書きしないでください。バッテリーの充電に失敗すると、データが失われる可能性があります。 *



. [[man_install4_Step8] 次のいずれかの操作を行います。
+
[cols="35,65"]
|===
| システムの状態 | 作業 


| ディスクがあり、バックエンドストレージがない | 手順 9 から 14 を省略して、に進みます <<man_install4_Step15,手順 15>>。 


| は、 V シリーズシステムまたは FlexArray 仮想化ソフトウェアを搭載し、ストレージアレイに接続されています  a| 
.. node4 の FC または UTA / UTA2 設定のセクションに移動し、セクションの作業を行います link:set_fc_uta_uta2_config_node4.html#configure-fc-ports-on-node4["ノード 4 の FC ポートを設定します"] および link:set_fc_uta_uta2_config_node4.html#check-and-configure-utauta2-ports-on-node4["ノード 4 の UTA / UTA2 ポートを確認して設定してください"]必要に応じて、システムに適用されます。
.. このセクションに戻って、から始めて残りの手順を実行します <<man_install4_Step9,手順 9>>。



IMPORTANT: VシリーズシステムでONTAP をブートする前に、FCオンボードポート、UTA / UTA2オンボードポート、およびUTA / UTA2カードを再設定する必要があります。

|===
. [[man_install4_Step9] 新しいノードの FC イニシエータポートをスイッチゾーンに追加します。
+
手順については、ストレージアレイおよびゾーニングに関するドキュメントを参照してください。

. FC イニシエータポートをストレージアレイに新しいホストとして追加し、アレイ LUN を新しいホストにマッピングします。
+
手順については、ストレージアレイおよびゾーニングに関するドキュメントを参照してください。

. ストレージアレイ上のアレイ LUN に関連付けられたホストまたはボリュームグループの World Wide Port Name （ WWPN ；ワールドワイドポート名）値を変更する。
+
新しいコントローラモジュールを設置すると、各オンボード FC ポートに関連付けられている WWPN の値が変更されます。

. スイッチベースのゾーニングを使用している場合は、新しい WWPN 値が反映されるようにゾーニングを調整します。
. 次のコマンドを入力し、出力を調べて、アレイ LUN が node4 に認識されていることを確認します。
+
「 sysconfig -v 」を使用します

+
各 FC イニシエータポートで認識されるすべてのアレイ LUN が表示されます。アレイ LUN が表示されない場合は、このセクションの後半で node2 から node4 にディスクを再割り当てすることはできません。

. Ctrl+Cキーを押してブートメニューを表示し、メンテナンスモードを選択します。
. [[man_install4_Step15]] メンテナンスモードのプロンプトで、次のコマンドを入力します。
+
「 halt 」

+
ブート環境プロンプトが表示されます。

. ONTAP のノード 4 を設定します。
+
「デフォルト設定」


