= 
:allow-uri-read: 


. 両方のノードのモデル、システム ID 、シリアル番号を記録します。
+
system node show -node-node1、node2 _-instanceです

+

NOTE: この情報を使用して、ディスクの再割り当てと元のノードの運用を停止します。

. ノード 1 とノード 2 の両方で次のコマンドを入力し、シェルフ、各シェルフ内のディスク数、フラッシュストレージの詳細、メモリ、 NVRAM 、ネットワークカードに関する情報を出力に記録します。
+
'run-node_node_name sysconfig '

+

NOTE: この情報を使用して、 node3 または node4 に転送するパーツやアクセサリを特定できます。ノードが V シリーズシステムであるか、 FlexArray 仮想化ソフトウェアがインストールされているかがわからない場合は、の出力からも確認できます。

. ノード 1 とノード 2 の両方で次のコマンドを入力し、両方のノードでオンラインになっているアグリゲートを記録します。
+
storage aggregate show -node _node_name --state online `

+

NOTE: この情報と次の手順の情報を使用して、再配置時にオフラインになった短時間のアグリゲートとボリュームが手順全体でオンラインのままになっていることを確認できます。

. [[man_prepare_nodes_step19]] ノード 1 とノード 2 の両方で次のコマンドを入力し、両方のノードでオフラインになっているボリュームを記録します。
+
volume show -node node_name --state offline`

+

NOTE: アップグレード後にもう一度コマンドを実行し、この手順の出力と比較して、他のボリュームがオフラインになったかどうかを確認します。

+
.. 次のコマンドを入力して、 node1 または node2 にインターフェイスグループまたは VLAN が設定されているかどうかを確認します。
+
「 network port ifgrp show 」のように表示されます

+
「 network port vlan show 」と表示されます

+
インターフェイスグループまたは VLAN がノード 1 とノード 2 のどちらで設定されているかを確認します。手順の次の手順以降で、その情報を確認する必要があります。

.. ノード 1 とノード 2 の両方で次の手順を実行して、手順 の後半で物理ポートを正しくマッピングできることを確認します。


. 次のコマンドを入力して 'clusterwide 以外のノードにフェイルオーバー・グループがあるかどうかを確認します
+
「 network interface failover-groups show 」と表示されます

+
フェイルオーバーグループは、システムに存在するネットワークポートのセットです。コントローラハードウェアをアップグレードすると物理ポートの場所が変わる可能性があるため、アップグレード中にフェイルオーバーグループを誤って変更する可能性があります。

+
次の例に示すように、ノード上のフェイルオーバーグループが表示されます。

+
....
cluster::> network interface failover-groups show

Vserver             Group             Targets
------------------- ----------------- ----------
Cluster             Cluster           node1:e0a, node1:e0b
                                      node2:e0a, node2:e0b

fg_6210_e0c         Default           node1:e0c, node1:e0d
                                      node1:e0e, node2:e0c
                                      node2:e0d, node2:e0e

2 entries were displayed.
....
. clusterwide 以外のフェイルオーバー・グループがある場合は ' フェイルオーバー・グループ名と ' そのフェイルオーバー・グループに属するポートを記録します
. 次のコマンドを入力して、ノードに VLAN が設定されているかどうかを確認します。
+
「network port vlan show -node _node_name _」のように入力します

+
VLAN は物理ポートを介して設定されます。物理ポートが変わった場合は、あとで手順で VLAN を再作成する必要があります。

+
次の例に示すように、ノードに設定されている VLAN が表示されます。

+
....
cluster::> network port vlan show

Network Network
Node    VLAN Name Port    VLAN ID MAC Address
------  --------- ------- ------- ------------------
node1   e1b-70    e1b     70      00:15:17:76:7b:69
....
. ノードに VLAN が設定されている場合は、各ネットワークポートと VLAN ID のペアをメモします。
+
.. 次のいずれかを実行します。
+
[cols="35,65"]
|===
| インターフェイスグループまたは VLAN の状態 | 作業 


| ノード 1 またはノード 2 | - 完了しました <<man_prepare_nodes_step23,手順 23>> および <<man_prepare_nodes_step24,手順 24>>。 


| ノード 1 とノード 2 ではありません | に進みます <<man_prepare_nodes_step24,手順 24>>。 
|===
.. [[man_prepare_nodes_step23]] SAN 環境または SAN 以外の環境で node1 と node2 が存在するかどうかが不明な場合は、次のコマンドを入力して出力を確認します。
+
「network interface show -vserver _vserver_name --data-protocol iscsi | fcp」というメッセージが表示されます

+
SVM に iSCSI も FC も設定されていない場合、次の例のようなメッセージが表示されます。

+
....
cluster::> network interface show -vserver Vserver8970 -data-protocol iscsi|fcp
There are no entries matching your query.
....
+
ノードが NAS 環境にあることを確認するには '-data-protocol nfs|cifs パラメータを指定した network interface show コマンドを使用します

+
SVM に iSCSI または FC が設定されている場合、次の例のようなメッセージが表示されます。

+
....
cluster::> network interface show -vserver vs1 -data-protocol iscsi|fcp

         Logical    Status     Network            Current  Current Is
Vserver  Interface  Admin/Oper Address/Mask       Node     Port    Home
-------- ---------- ---------- ------------------ -------- ------- ----
vs1      vs1_lif1   up/down    172.17.176.20/24   node1    0d      true
....
.. [man_prepare-to-downgrade 24]] 次の手順を実行して、クラスタ内のすべてのノードがクォーラムにあることを確認します。


. advanced 権限レベルに切り替えます。
+
「 advanced 」の権限が必要です

+
次のメッセージが表示されます。

+
....
Warning: These advanced commands are potentially dangerous; use them only when directed to do so by NetApp personnel.
Do you wish to continue? (y or n):
....
. 「 y 」と入力します。
. カーネル内のクラスタサービスの状態をノードごとに 1 回確認します。
+
「 cluster kernel-service show 」のように表示されます

+
次の例のようなメッセージが表示されます。

+
....
cluster::*> cluster kernel-service show

Master        Cluster       Quorum        Availability  Operational
Node          Node          Status        Status        Status
------------- ------------- ------------- ------------- -------------
node1         node1         in-quorum     true          operational
              node2         in-quorum     true          operational

2 entries were displayed.
....
+
過半数のノードが正常で相互に通信可能な場合に、クラスタ内のノードがクォーラムを構成している。詳細については、を参照してください link:other_references.html["参考資料"] をクリックして、 _System Administration Reference_( システム管理リファレンス ) にリンクします。

. admin 権限レベルに戻ります。
+
「特権管理者」

+
.. 次のいずれかを実行します。
+
[cols="35,65"]
|===
| クラスタの状況 | 作業 


| SAN が設定されている | に進みます <<man_prepare_nodes_step26,手順 26>>。 


| SAN が設定されていません | に進みます <<man_prepare_nodes_step29,手順 29>>。 
|===
.. [man_prepare-to-downgrade 26]] 次のコマンドを入力して、 SAN iSCSI または FC サービスが有効になっている各 SVM で、ノード 1 とノード 2 に SAN LIF があることを確認します。
+
network interface show -data-protocol iscsi|fcp-home-node_node_name _

+
コマンドは、ノード 1 とノード 2 の SAN LIF 情報を表示します。次の例は、 Status Admin/Oper 列に up/up と表示されているステータスを示しています。これは、 SAN iSCSI サービスと FC サービスが有効になっていることを示しています。

+
....
cluster::> network interface show -data-protocol iscsi|fcp
            Logical    Status     Network                  Current   Current Is
Vserver     Interface  Admin/Oper Address/Mask             Node      Port    Home
----------- ---------- ---------- ------------------       --------- ------- ----
a_vs_iscsi  data1      up/up      10.228.32.190/21         node1     e0a     true
            data2      up/up      10.228.32.192/21         node2     e0a     true

b_vs_fcp    data1      up/up      20:09:00:a0:98:19:9f:b0  node1     0c      true
            data2      up/up      20:0a:00:a0:98:19:9f:b0  node2     0c      true

c_vs_iscsi_fcp data1   up/up      20:0d:00:a0:98:19:9f:b0  node2     0c      true
            data2      up/up      20:0e:00:a0:98:19:9f:b0  node2     0c      true
            data3      up/up      10.228.34.190/21         node2     e0b     true
            data4      up/up      10.228.34.192/21         node2     e0b     true
....
+
また、次のコマンドを入力して、 LIF の詳細情報を確認することもできます。

+
'network interface show -instance -data-protocol iscsi|fcp

.. 次のコマンドを入力してシステムの出力を記録し、元のノードの FC ポートのデフォルト設定を取得します。
+
ucadmin show

+
コマンドは、次の例に示すように、クラスタ内のすべての FC ポートに関する情報を表示します。

+
....
cluster::> ucadmin show

                Current Current   Pending Pending   Admin
Node    Adapter Mode    Type      Mode    Type      Status
------- ------- ------- --------- ------- --------- -----------
node1   0a      fc      initiator -       -         online
node1   0b      fc      initiator -       -         online
node1   0c      fc      initiator -       -         online
node1   0d      fc      initiator -       -         online
node2   0a      fc      initiator -       -         online
node2   0b      fc      initiator -       -         online
node2   0c      fc      initiator -       -         online
node2   0d      fc      initiator -       -         online
8 entries were displayed.
....
+
アップグレード後の情報を使用して、新しいノードに FC ポートを設定できます。

.. V シリーズシステムまたは FlexArray 仮想化ソフトウェアがインストールされたシステムをアップグレードする場合は、次のコマンドを入力して出力を記録し、元のノードのトポロジに関する情報を取得します。
+
「 storage array config show -switch 」です

+
次の例に示すようにトポロジ情報が表示されます。

+
....
cluster::> storage array config show -switch

      LUN LUN                                  Target Side Initiator Side Initi-
Node  Grp Cnt Array Name    Array Target Port  Switch Port Switch Port    ator
----- --- --- ------------- ------------------ ----------- -------------- ------
node1 0   50  I_1818FAStT_1
                            205700a0b84772da   vgbr6510a:5  vgbr6510s164:3  0d
                            206700a0b84772da   vgbr6510a:6  vgbr6510s164:4  2b
                            207600a0b84772da   vgbr6510b:6  vgbr6510s163:1  0c
node2 0   50  I_1818FAStT_1
                            205700a0b84772da   vgbr6510a:5  vgbr6510s164:1  0d
                            206700a0b84772da   vgbr6510a:6  vgbr6510s164:2  2b
                            207600a0b84772da   vgbr6510b:6  vgbr6510s163:3  0c
                            208600a0b84772da   vgbr6510b:5  vgbr6510s163:4  2a
7 entries were displayed.
....
.. [man_prepare-to-downgrade 29]] 次の手順を実行します。


. 元のいずれかのノードで次のコマンドを入力し、出力を記録します。
+
「 service-processor show -node * -instance 」のように表示されます

+
両方のノードの SP に関する詳細情報が表示されます。

. SP のステータスがオンラインであることを確認します
. SP ネットワークが設定されていることを確認する。
. SP の IP アドレスやその他の情報を記録します。
+
リモート管理デバイスのネットワーク・パラメータ（この場合は SP ）を ' 新しいノードの SP の元のシステムから再利用することができますSP の詳細については ' を参照してください link:other_references.html["参考資料"] 『 _System Administration Reference_and the ONTAP 9 Commands ： Manual Page Reference_』 にリンクするには、次の手順を実行します。

+
.. [man_prepare-to-downgrade 30]] 新しいノードに元のノードと同じライセンス機能を設定する場合は、次のコマンドを入力して元のシステムのクラスタライセンスを表示します。
+
「 system license show -owner * 」と表示されます

+
次の例では、 cluster1 のサイトライセンスを表示しています。

+
....
system license show -owner *
Serial Number: 1-80-000013
Owner: cluster1

Package           Type    Description           Expiration
----------------- ------- --------------------- -----------
Base              site    Cluster Base License  -
NFS               site    NFS License           -
CIFS              site    CIFS License          -
SnapMirror        site    SnapMirror License    -
FlexClone         site    FlexClone License     -
SnapVault         site    SnapVault License     -
6 entries were displayed.
....
.. 新しいノードの新しいライセンスキーを the _NetApp Support Site_. に取得します。を参照してください link:other_references.html["参考資料"] からネットアップサポートサイトにリンクしてください。
+
必要なライセンスキーがサイトにない場合は、ネットアップの営業担当者にお問い合わせください。

.. 元のシステムで AutoSupport が有効になっているかどうかを確認するには、各ノードで次のコマンドを入力し、出力を調べます。
+
system node AutoSupport show -node-node1、node2 _

+
次の例に示すように、コマンド出力には AutoSupport が有効になっているかどうかが表示されます。

+
....
cluster::> system node autosupport show -node node1,node2

Node             State     From          To                Mail Hosts
---------------- --------- ------------- ----------------  ----------
node1            enable    Postmaster    admin@netapp.com  mailhost

node2            enable    Postmaster    -                 mailhost
2 entries were displayed.
....
.. 次のいずれかを実行します。
+
[cols="35,65"]
|===
| 元のシステム | 作業 


| AutoSupport が有効になっています ...  a| 
に進みます <<man_prepare_nodes_step34,手順 34>>。



| AutoSupport が有効になっていません ...  a| 
AutoSupport を有効にするには、 _System Administration Reference_. の手順に従ってください。を参照してください link:other_references.html["参考資料"] をクリックして、 _System Administration Reference_. にリンクします。）

* 注： AutoSupport は、ストレージ・システムを初めて設定したときに、デフォルトで有効になっています。AutoSupport はいつでも無効にできますが、常に有効にしておく必要があります。AutoSupport を有効にすると、ストレージシステムに問題が発生したときに、その問題や解決策を特定するのに非常に役立ちます。

|===
.. [man_prepare_nodes _step34]] 元のノードの両方で次のコマンドを入力し、 AutoSupport が正しいメールホストの詳細および受信者の E メール ID で設定されていることを確認します。
+
「 system node AutoSupport show -node node_name -instance 」の略

+
AutoSupport の詳細については、を参照してください link:other_references.html["参考資料"] 『 _System Administration Reference_and the ONTAP 9 Commands ： Manual Page Reference_』 にリンクするには、次の手順を実行します。

.. [[man_prepare-to-downgrade 35 、 Step 35]] 次のコマンドを入力して、 node1 のネットアップに AutoSupport メッセージを送信します。
+
「 system node AutoSupport invoke -node node1 -type all -message 」「 Upgrading node1 from platform_old to platform_new 」というメッセージが表示されます

+

NOTE: この時点では node2 の AutoSupport メッセージはネットアップに送信しないでください。これはあとで手順で送信します。

.. [man_prepare-to-downgrade 36 、 Step 36]] 次のコマンドを入力して、 AutoSupport メッセージが送信されたことを確認します。
+
'system node AutoSupport show -node1_-instance `

+
「 Last Subject Sent ：」フィールドと「 Last Time Sent ：」フィールドには、最後に送信されたメッセージのメッセージタイトルと、メッセージが送信された時刻が含まれています。

.. システムで自己暗号化ドライブを使用している場合は、Knowledge Baseの文書を参照してください https://kb.netapp.com/onprem/ontap/Hardware/How_to_tell_if_a_drive_is_FIPS_certified["ドライブがFIPS認定かどうかを確認する方法"^] アップグレード対象のHAペアで使用されている自己暗号化ドライブのタイプを確認する。ONTAP ソフトウェアは、次の2種類の自己暗号化ドライブをサポートしています。
+
--
*** FIPS認定のNetApp Storage Encryption（NSE）SASドライブまたはNVMeドライブ
*** FIPS非対応の自己暗号化NVMeドライブ（SED）


[NOTE]
====
FIPSドライブは、同じノードまたはHAペアで他のタイプのドライブと混在させることはできません。

SEDと非暗号化ドライブを同じノードまたはHAペアで混在させることができます。

====
https://docs.netapp.com/us-en/ontap/encryption-at-rest/support-storage-encryption-concept.html#supported-self-encrypting-drive-types["サポートされている自己暗号化ドライブの詳細を確認できます"^]。

--



