= 
:allow-uri-read: 


アップグレード手順の実行中、リモート LIF は SAN LUN へのトラフィックを処理します。アップグレード時にクラスタやサービスの健全性を維持するために、 SAN LIF を移動する必要はありません。SAN LIF は、新しいポートにマッピングする必要がないかぎり移動されません。ノード 3 をオンラインにしたあと、 LIF が正常に機能しており、適切なポートに配置されていることを確認します。

.手順
. [[step1] ノードごとに次のコマンドを入力し、出力をキャプチャして、 node2 が所有していないすべての NAS データ LIF を一覧表示します。
+
'network interface show -role data -curr-node _node2 __-is-home false -home-node node3_node3_’

. [[worksheet _step2] クラスタが SAN LIF 用に構成されている場合は、 SAN LIF 「 adapter 」および「 switch-port 」の構成情報をこのに記録します link:worksheet_information_before_moving_san_lifs_node3.html["ワークシート"] 手順 の後半で使用します。
+
.. node2 の SAN LIF を一覧表示し、出力を確認します。
+
「 network interface show -data-protocol fc * 」を参照してください

+
次の例のような出力が返されます。

+
[listing]
----
cluster1::> net int show -data-protocol fc*
  (network interface show)
             Logical     Status     Network            Current        Current Is
Vserver      Interface   Admin/Oper Address/Mask       Node           Port    Home
-----------  ----------  ---------- ------------------ -------------  ------- ----
svm2_cluster1
             lif_svm2_cluster1_340
                         up/up      20:02:00:50:56:b0:39:99
                                                       cluster1-01    1b      true
             lif_svm2_cluster1_398
                         up/up      20:03:00:50:56:b0:39:99
                                                       cluster1-02    1a      true
             lif_svm2_cluster1_691
                         up/up      20:01:00:50:56:b0:39:99
                                                       cluster1-01    1a      true
             lif_svm2_cluster1_925
                         up/up      20:04:00:50:56:b0:39:99
                                                       cluster1-02    1b      true
4 entries were displayed.
----
.. 既存の設定を表示し、出力を確認します。
+
「 fcp adapter show -fields switch-port 、 fc-wwpn 」と入力します

+
次の例のような出力が返されます。

+
[listing]
----
cluster1::> fcp adapter show -fields switch-port,fc-wwpn
  (network fcp adapter show)
node         adapter  fc-wwpn                  switch-port
-----------  -------  -----------------------  -------------
cluster1-01  0a       50:0a:09:82:9c:13:38:00  ACME Switch:0
cluster1-01  0b       50:0a:09:82:9c:13:38:01  ACME Switch:1
cluster1-01  0c       50:0a:09:82:9c:13:38:02  ACME Switch:2
cluster1-01  0d       50:0a:09:82:9c:13:38:03  ACME Switch:3
cluster1-01  0e       50:0a:09:82:9c:13:38:04  ACME Switch:4
cluster1-01  0f       50:0a:09:82:9c:13:38:05  ACME Switch:5
cluster1-01  1a       50:0a:09:82:9c:13:38:06  ACME Switch:6
cluster1-01  1b       50:0a:09:82:9c:13:38:07  ACME Switch:7
cluster1-02  0a       50:0a:09:82:9c:6c:36:00  ACME Switch:0
cluster1-02  0b       50:0a:09:82:9c:6c:36:01  ACME Switch:1
cluster1-02  0c       50:0a:09:82:9c:6c:36:02  ACME Switch:2
cluster1-02  0d       50:0a:09:82:9c:6c:36:03  ACME Switch:3
cluster1-02  0e       50:0a:09:82:9c:6c:36:04  ACME Switch:4
cluster1-02  0f       50:0a:09:82:9c:6c:36:05  ACME Switch:5
cluster1-02  1a       50:0a:09:82:9c:6c:36:06  ACME Switch:6
cluster1-02  1b       50:0a:09:82:9c:6c:36:07  ACME Switch:7
16 entries were displayed
----


. [[step3]] 次のいずれかの操作を実行します。
+
[cols="35,65"]
|===
| ノード 1 の状況 | 作業 


| インターフェイスグループまたは VLAN が設定されている | に進みます ,手順 4。 


| インターフェイスグループまたは VLAN が設定されていません | 手順 4 を省略して、に進みます ,手順 5。 
|===
. [[man_lif_verify_3_step3]] 次の手順を実行して、インターフェイスグループおよび VLAN でホストされていた NAS データ LIF を、ノード 2 からノード 3 に移行します。
+
.. [[man_lif_verify_3_substpa]] インターフェイスグループ上の node1 に属していた node2 でホストされているデータ LIF を、同じネットワーク上の LIF をホストできる node3 のポートに移行するには、各 LIF に対して 1 回、次のコマンドを入力します。
+
「network interface migrate -vserver vserver_name -lif_lif_name_-destination -node _node3 _–destination-port_netport | ifgrp_`」の形式で指定します

.. LIF のホームポートとホームノードを変更します ,手順 a LIF をホストしているポートとノードに対して次のコマンドを 1 回入力します。
+
「network interface modify -vserver _vserver_name __ lif_lif_name__-home-node _node3」-home-port_netport | ifgrp_`

.. [man_lif_verify_3_substpc ]] VLAN ポートでノード 1 に属していた node2 でホストされているすべてのデータ LIF を、同じネットワーク上の LIF をホストできるポート node3 に移行するには、各 LIF に対して 1 回、次のコマンドを入力します。
+
「network interface migrate -vserver vserver_name -lif_lif_name_-destination -node _node3 _–destination-port_netport | ifgrp_`」の形式で指定します

.. LIF のホームポートとホームノードを変更します ,サブステップ c LIF をホストしているポートとノードに対して次のコマンドを 1 回入力します。
+
「network interface modify -vserver _vserver_name __ lif_lif_name__-home-node _node3」-home-port_netport | ifgrp_`



. [man_lif_verify_3_step4] 次のいずれかの操作を実行します
+
[cols="25,75"]
|===
| クラスタの設定対象 | 作業 


| NAS | - 完了しました ,手順 6 および ,手順 7をクリックして、手順 8 をスキップして完了します ,手順 9 から ,手順 12。 


| SAN | ノード上のすべてのSAN LIFを無効にしてアップグレード用にダウンにします。「network interface modify -vserver _vserver_name -lif_lif_name__-home-node _port_to _upgrade_-home-port port | ifgrp-status-admin down 
|===

