= 
:allow-uri-read: 


. [man_lif_verify_3_step6] それぞれの LIF に対して次のコマンドを 1 回入力して、各 NAS データ LIF を node3 に移行します。
+
「network interface migrate -vserver vserver_name -lif_lif_name_-destination -node _node3 __ destination-port_netport | ifgrp_`」の形式で指定します

. [man_lif_verify_3_step7] データ移行が永続的であることを確認します。
+
「network interface modify -vserver _vserver_name __ lif_lif_name_-home-port_netport | ifgrp _-home-node _node3 _

. [man_lif_verify_3_step8] SAN LIF が node3 の正しいポートにあることを確認します。
+
.. 次のコマンドを入力し、出力を確認します。
+
network interface show -data-protocol iscsi|fcp-home-node3_`

+
次の例のような出力が返されます。

+
[listing]
----
cluster::> net int show -data-protocol iscsi|fcp -home-node node3
              Logical     Status      Network             Current        Current  Is
 Vserver      Interface   Admin/Oper  Address/Mask        Node           Port     Home
 -----------  ----------  ----------  ------------------  -------------  -------  ----
 vs0
              a0a         up/down     10.63.0.53/24       node3          a0a      true
              data1       up/up       10.63.0.50/18       node3          e0c      true
              rads1       up/up       10.63.0.51/18       node3          e1a      true
              rads2       up/down     10.63.0.52/24       node3          e1b      true
 vs1
              lif1        up/up       172.17.176.120/24   node3          e0c      true
              lif2        up/up       172.17.176.121/24   node3          e1a      true
----
.. 「 fcp adapter show 」コマンドの出力と、のワークシートに記録した設定情報を比較して、新しい「 adapter 」および「 switch-port 」の設定が正しいことを確認します <<worksheet_step2,手順 2>>。
+
ノード 3 に新しい SAN LIF の設定を表示します。

+
「 fcp adapter show -fields switch-port 、 fc-wwpn 」と入力します

+
次の例のような出力が返されます。

+
[listing]
----
cluster1::> fcp adapter show -fields switch-port,fc-wwpn
  (network fcp adapter show)
node        adapter fc-wwpn                 switch-port
----------- ------- ----------------------- -------------
cluster1-01 0a      50:0a:09:82:9c:13:38:00 ACME Switch:0
cluster1-01 0b      50:0a:09:82:9c:13:38:01 ACME Switch:1
cluster1-01 0c      50:0a:09:82:9c:13:38:02 ACME Switch:2
cluster1-01 0d      50:0a:09:82:9c:13:38:03 ACME Switch:3
cluster1-01 0e      50:0a:09:82:9c:13:38:04 ACME Switch:4
cluster1-01 0f      50:0a:09:82:9c:13:38:05 ACME Switch:5
cluster1-01 1a      50:0a:09:82:9c:13:38:06 ACME Switch:6
cluster1-01 1b      50:0a:09:82:9c:13:38:07 ACME Switch:7
cluster1-02 0a      50:0a:09:82:9c:6c:36:00 ACME Switch:0
cluster1-02 0b      50:0a:09:82:9c:6c:36:01 ACME Switch:1
cluster1-02 0c      50:0a:09:82:9c:6c:36:02 ACME Switch:2
cluster1-02 0d      50:0a:09:82:9c:6c:36:03 ACME Switch:3
cluster1-02 0e      50:0a:09:82:9c:6c:36:04 ACME Switch:4
cluster1-02 0f      50:0a:09:82:9c:6c:36:05 ACME Switch:5
cluster1-02 1a      50:0a:09:82:9c:6c:36:06 ACME Switch:6
cluster1-02 1b      50:0a:09:82:9c:6c:36:07 ACME Switch:7
16 entries were displayed
----
+

NOTE: 新しい構成の SAN LIF が同じ「 switch-port 」に接続されたアダプタ上にない場合、ノードをリブートすると原因 がシステム停止状態になる可能性があります。

.. ノード 3 に、ノード 1 に存在しないポート上にある SAN LIF または SAN LIF のグループがある場合、または別のポートにマッピングする必要がある場合は、次の手順を実行して、ノード 3 の該当するポートにそれらの SAN LIF またはグループを移動します。
+
... LIF のステータスを「 down 」に設定します。
+
「 network interface modify -vserver _vserver_name __ -lif lif_name --status-admin down 」を参照してください

... ポートセットから LIF を削除します。
+
`portset remove -vserver_name_-portset_portset_name__-port-name _port_name_`

... 次のいずれかのコマンドを入力します。
+
**** 1 つの LIF を移動します。
+
「network interface modify -vserver _vserver_name __ lif_lif_name_-home-port_'」を指定します

**** 存在しない、または間違ったポート上のすべての LIF を新しいポートに移動します。
+
'network interface modify｛-home-node port_port_on_node1_-role data｝-home-node _new_home_port_on_node3 _`

**** LIF をポートセットに再度追加します。
+
`portset add -vserver_name_-portset_portset_name__-port-name _port_name_`

+

NOTE: SAN LIF は、元のポートとリンク速度が同じポートに移動する必要があります。







. ノードでトラフィックを許可して送信できるように、すべての LIF のステータスを「 up 」に変更します。
+
network interface modify -home-node port_name_--home-node3_life-status-admin upです

. いずれかのノードで次のコマンドを入力し、その出力を調べて、 LIF が正しいポートに移動されていること、およびいずれかのノードで次のコマンドを入力して LIF のステータスが「 up 」になっていることを確認します。
+
'network interface show -home-node node_node3 -- role data `

. [[man_lif_verify_3_step11]] いずれかの LIF が停止している場合は、次のコマンドを 1 回入力して、各 LIF について LIF の管理ステータスを「 up 」に設定します。
+
「 network interface modify -vserver vserver_name __ -lif LIF_name -status-admin up

. アップグレード後に行う AutoSupport メッセージを node1 のネットアップに送信します。
+
'system node AutoSupport invoke -node _node3_type all -message "node1 successfully upgraded from _platform_old_to _platform_new_"


