= 
:allow-uri-read: 


ノード 4 をラックに設置し、ノード 2 の接続をノード 4 に転送し、ノード 4 をブートする必要があります。ノード 2 のスペア、ルートに属するディスク、および node3 でそれよりも前に再配置されなかったルート以外のアグリゲートも再割り当てする必要があります。

.このタスクについて
ノード4にノード2にインストールされているONTAP 9と同じバージョンがインストールされていない場合は、ノード4をネットブートする必要があります。node4 のインストールが完了したら、 Web サーバに保存されている ONTAP 9 イメージからブートします。その後、以下の手順に従って、以降のシステムブートに必要なファイルをブートメディアデバイスにダウンロードしてください。 link:prepare_for_netboot.html["ネットブートを準備"] 。

ただし、node2 にインストールされている ONTAP 9 と同じバージョンまたはそれ以降のバージョンが node4 にインストールされている場合は、node4 をネットブートする必要はありません。

[IMPORTANT]
====
* AFF A800またはAFF C800コントローラのアップグレードの場合、ノード 2 を取り外す前に、シャーシ内のすべてのドライブがミッドプレーンにしっかりと固定されていることを確認する必要があります。詳細については、 link:../upgrade-arl-auto-in-chassis/replace-node1-affa800.html["AFF A800またはAFF C800コントローラモジュールを交換"]。
* ストレージディスクを備えたシステムをアップグレードする場合は、このセクション全体を完了してから、セクションに進む必要があります。 link:set_fc_uta_uta2_config_node4.html["ノード 4 で FC または UTA / UTA2 設定を設定します"]クラスタープロンプトでコマンドを入力します。


====
.手順
. [[man_install4_Step1] 次のいずれかの操作を行います。
+
[cols="35,65"]
|===
| ノード 4 の配置先 | 作業 


| ノード 3 とは別のシャーシ | に進みます <<man_install4_Step2,手順 2>>。 


| 同じシャーシを node3 と一緒に配置する | 手順 2 と 3 を省略して、に進みます <<man_install4_Step4,手順 4>>。 
|===
. [[man_install4_Step2]] ノード 4 に十分なラックスペースがあることを確認します。
+
node4 と node3 が別々のシャーシにある場合は、 node4 を node2 と同じ場所に配置できます。node3 と node4 が同じシャーシにある場合は、 node4 が適切なラックの場所にすでに存在しているとします。

. ノードモデルの _Installation and Setup Instructions _ の手順に従って、ノード 4 をラックに設置します。
. [[man_install4_Step4]] ケーブルノード 4 を接続し、ノード 2 からノード 4 に接続を移動します。
+
次の参考資料は、適切なケーブル接続を行う場合に役立ちます。に進みます link:other_references.html["参考資料"] をクリックしてリンクします。

+
** node4プラットフォームのインストールとセットアップ手順
** 該当するディスクシェルフの手順を選択します
** HAペア管理のドキュメント
+
次の配線を行います。

** コンソール（リモート管理ポート）
** クラスタポート
** データポート
** クラスタポートとノード管理ポート
** ストレージ
** SAN 構成： iSCSI イーサネットおよび FC スイッチポート


+

NOTE: ほとんどのプラットフォームモデルには一意のインターコネクトカードモデルがあるため、インターコネクトカード / FC-VI カードまたはインターコネクト / FC-VI ケーブルの接続を node2 から node4 に移動する必要はありません。

. 次のいずれかを実行します。
+
[cols="35,65"]
|===
| ノード 4 の構成 | 作業 


| ノード 3 と同じシャーシ | に進みます <<man_install4_Step8,手順 8>>。 


| ノード 3 とは別のシャーシ | に進みます <<man_install4_Step6,手順 6>>。 
|===
. [[man_install4_step6]]ノード4の電源をオンにし、Ctrl+Cキーを押してブートを中断してブート環境プロンプトにアクセスします。
+

NOTE: node4 をブートすると、次のメッセージが表示される場合があります。

+
[listing]
----
WARNING: The battery is unfit to retain data during a power
         outage. This is likely because the battery is
         discharged but could be due to other temporary
         conditions.
         When the battery is ready, the boot process will
         complete and services will be engaged.
         To override this delay, press 'c' followed by 'Enter'
----
. [[man_install4_Step7] ステップ 6 で警告メッセージが表示された場合は、次の操作を実行します。
+
.. NVRAM バッテリ低下以外の問題を示すコンソールメッセージがないか確認し、必要に応じて対処します。
.. バッテリの充電と起動プロセスが完了するまで待ちます。
+

WARNING: *遅延を無効にしないでください。バッテリーを充電しないと、データが失われる可能性があります。*



. [[man_install4_Step8]]メンテナンス モード プロンプトで、次のコマンドを入力します。
+
「 halt 」

+
ブート環境プロンプトが表示されます。

. ONTAP のノード 4 を設定します。
+
「デフォルト設定」


