= ステージ 2 でリブート、パニック、または電源の再投入が発生した場合
:allow-uri-read: 


アップグレードの各段階で、システムがクラッシュする（リブート、パニック状態、または電源の再投入）場合があります。これらの問題の解決策は、状況によって異なります。



== ステージ 2 でリブート、パニック、または電源の再投入が発生した場合

クラッシュは、ステージ 2 の前後、またはステージ 2 のアグリゲートをノード 1 からノード 2 に再配置し、ノード 1 が所有するデータ LIF と SAN LIF をノード 2 に移動し、ノード 1 の情報を記録し、ノード 1 を廃棄する前、実行中、またはただちに発生します。



=== HA を有効にして第 2 段階の前にノード 1 またはノード 2 がクラッシュする

ステージ 2 の前にノード 1 またはノード 2 がクラッシュした場合は、再配置されたアグリゲートがなく、 HA 構成が有効なままになります。

.このタスクについて
テイクオーバーとギブバックは正常に実行されます。

.手順
. コンソールで、システムで発行された EMS メッセージを確認し、推奨される対処方法を実行します。
. ノードペアのアップグレード用手順に進みます。




=== HA を有効にして第 2 段階の実行中または直後にノード 1 がクラッシュする

一部またはすべてのアグリゲートがノード 1 からノード 2 に再配置されており、 HA が有効なままです。node2 は、 node1 のルートボリュームと再配置されていないルート以外のアグリゲートをテイクオーバーします。

.このタスクについて
再配置されたアグリゲートの所有権は、ホーム所有者が変更されていないためにテイクオーバーされたルート以外のアグリゲートの所有権と同じように見えます。node1 の状態が「 waiting for giveback state 」になると、 node2 はノード 1 のルート以外のすべてのアグリゲートをギブバックします。

.手順
. - 完了しました link:relocate_non_root_aggr_node1_node2.html#step1["手順 1."] セクションの _root 以外のアグリゲートをノード 1 から node2 _ に再配置する
. ノードペアのアップグレード用手順に進みます。




=== HA を無効にすると、ステージ 2 のあとにノード 1 がクラッシュします

node2 はテイクオーバーしませんが、ルート以外のすべてのアグリゲートから引き続きデータを提供しています。

.手順
. ノード 1 を起動します。
. ノードペアのアップグレード用手順に進みます。
+
「 storage failover show 」コマンドの出力には変更が表示されることがありますが、これは通常の動作であり、手順には影響しません。トラブルシューティングのセクションを参照してください link:issues_multiple_stages_of_procedure.html#Unexpected-storage-failover-show-command-output["予期しない「 storage failover show 」コマンドの出力が表示されます"]。





=== ステージ 2 の実行中または実行後に、 HA を有効にして node2 に障害が発生する

ノード 1 の一部またはすべてのアグリゲートが node2 に再配置されています。HA が有効になっている。

.このタスクについて
ノード 1 は、ノード 2 のすべてのアグリゲートと、ノード 2 に再配置された独自のアグリゲートをテイクオーバーします。node2 が Waiting for giveback' 状態になると、 node1 は node2 のすべてのアグリゲートをギブバックします。

.手順
. - 完了しました link:relocate_non_root_aggr_node1_node2.html#step1["手順 1."] セクションの _root 以外のアグリゲートをノード 1 から node2 _ に再配置する
. ノードペアのアップグレード用手順に進みます。




=== ステージ 2 で HA を無効にすると、ノード 2 がクラッシュする

ノード 1 ではテイクオーバーされません。

.手順
. node2 を起動します。
+
node2 のブート中にすべてのアグリゲートでクライアントが停止します。

. 残りのノードペアのアップグレード手順に進みます。




== ステージ 3 でリブート、パニック、電源の再投入が発生した場合

ステージ 3 の実行中または実行直後に障害が発生し、ステージ 3 ではノード 1 からノード 3 へのポートのマッピング、ノード 1 とノード 2 に属するデータ LIF と SAN LIF のノード 3 への移動、ノード 2 からノード 3 へのすべてのアグリゲートの再配置が行われます。



=== HA を無効にした状態でステージ 3 が実行され、アグリゲートを再配置する前にノード 2 がクラッシュする

HA がすでに無効になっているため、ノード 2 のクラッシュ後はノード 3 はテイクオーバーしません。

.手順
. node2 を起動します。
+
node2 のブート中にすべてのアグリゲートでクライアントが停止します。

. ノードペアのアップグレード用手順に進みます。




=== 一部またはすべてのアグリゲートの再配置後、ステージ 3 でノード 2 がクラッシュする

node2 の一部またはすべてのアグリゲートが node3 に再配置され、再配置されたアグリゲートからデータが提供されます。HA が無効になっています。

.このタスクについて
再配置されなかったアグリゲートのクライアントが停止します。

.手順
. node2 を起動します。
. 残りのアグリゲートの再配置は完了して実行します link:relocate_non_root_aggr_node2_node3.html#step1["手順 1."] から link:relocate_non_root_aggr_node2_node3.html#step3["手順 3"] セクションの _root 以外のアグリゲートを node2 から node3 _ に移動する
. ノードペアのアップグレード用手順に進みます。




=== ステージ 3 でノード 2 からアグリゲートが再配置される前に、ノード 3 がクラッシュした場合

node2 はテイクオーバーしませんが、ルート以外のすべてのアグリゲートから引き続きデータを提供しています。

.手順
. ノード 3 を起動します。
. ノードペアのアップグレード用手順に進みます。




=== アグリゲートの再配置中に、ステージ 3 でノード 3 がクラッシュした場合

node2 によるアグリゲートのノード 3 への再配置中にノード 3 がクラッシュした場合、 node2 を使用すると残りのアグリゲートの再配置が中止されます。

.このタスクについて
node2 では残りのアグリゲートの処理が続行されますが、 node3 のブート中にすでに node3 に再配置されたアグリゲートでクライアントが停止する可能性があります。

.手順
. ノード 3 を起動します。
. - 完了しました link:relocate_non_root_aggr_node2_node3.html#step3["手順 3"] セクションの「ルート以外のアグリゲートを node2 から node3 _ に再配置する」を再度実行します。
. ノードペアのアップグレード用手順に進みます。




=== ステージ 3 でクラッシュすると、ノード 3 がブートしない

重大な障害が原因で、ステージ 3 のクラッシュ後に node3 をブートすることはできません。

.ステップ
. テクニカルサポートにお問い合わせください。




=== ステージ 3 のあと、ステージ 5 の前に node2 がクラッシュします

ノード 3 では、すべてのアグリゲートのデータの提供が続行されます。HA ペアが無効になります。

.手順
. node2 を起動します。
. ノードペアのアップグレード用手順に進みます。




=== ステージ 3 の完了後、ステージ 5 の前にノード 3 がクラッシュした場合

ステージ 3 の完了後、ステージ 5 の前にノード 3 がクラッシュした場合。HA ペアが無効になります。

.手順
. ノード 3 を起動します。
+
すべてのアグリゲートがクライアントで停止します。

. ノードペアのアップグレード用手順に進みます。




== ステージ 5 でリブート、パニック、または電源の再投入が発生した場合

クラッシュは、ステージ 5 、ノード 4 のインストールとブートのステージ、ノード 2 からノード 4 へのポートのマッピング、ノード 2 に属するデータ LIF と SAN LIF のノード 2 からノード 4 への移動、ノード 2 のすべてのアグリゲートのノード 3 からノード 4 への再配置の実行中に発生する可能性があります。



=== ステージ 5 でノード 3 がクラッシュする

ノード 3 の一部またはすべてのアグリゲートが node4 に再配置されている。node4 にはテイクオーバーは行われず、 node3 がすでに再配置されたルート以外のアグリゲートは引き続き提供されます。HA ペアが無効になります。

.このタスクについて
node3 が再度ブートするまでは、残りのアグリゲートが停止している必要があります。

.手順
. ノード 3 を起動します。
. node2 に属していた残りのアグリゲートを再配置します link:relocate_node2_non_root_aggr_node3_node4.html#Step1["手順 1."] から link:relocate_node2_non_root_aggr_node3_node4.html#step3["手順 3"] セクションの _Relocate node2 のルート以外のアグリゲートを node3 から node4 に再配置する例を次に示します。
. ノードペアのアップグレード用手順に進みます。




=== ステージ 5 でノード 4 がクラッシュした場合

ノード 3 の一部またはすべてのアグリゲートが node4 に再配置されている。node3 は、自身が所有しているルート以外のアグリゲートおよび再配置されていないアグリゲートを引き続き提供します。HA が無効になっています。

.このタスクについて
ノード 4 が再びブートするまで再配置されたルート以外のアグリゲートは停止します。

.手順
. ノード 4 を起動します。
. 再度完了して、 node2 に属していた残りのアグリゲートを再配置します link:relocate_node2_non_root_aggr_node3_node4.html#Step1["手順 1."] から link:relocate_node2_non_root_aggr_node3_node4.html#step3["手順 3"] In _Relocate node2 のルート以外のアグリゲートを node3 から node4 に再配置します。
. ノードペアのアップグレード用手順に進みます。

