= アグリゲートの再配置に失敗していないかどうか
:allow-uri-read: 


アグリゲートの再配置（ ARL ）がアップグレード中に別のポイントで失敗することがあります。



== アグリゲートの再配置に失敗していないかどうか

手順の処理中に、ステージ 2 、ステージ 3 、またはステージ 5 で ARL が失敗することがあります。

.手順
. 次のコマンドを入力し、出力を確認します。
+
「 storage aggregate relocation show 」を参照してください

+
「 storage aggregate relocation show 」コマンドを実行すると、正常に再配置されたアグリゲートと再配置されなかったアグリゲート、および障害の原因が表示されます。

. コンソールで EMS メッセージを確認します。
. 次のいずれかを実行します。
+
** 「 storage aggregate relocation show 」コマンドの出力と EMS メッセージの出力に応じて、適切な方法を実行します。
** 「 storage aggregate relocation start 」コマンドの「 override-vetoes 」オプションまたは「 override-vetoes destination-checks 」オプションを使用して、アグリゲートまたはアグリゲートの強制的な再配置を実行します。


+
 `storage aggregate relocation start`、 `override-vetoes`、 `override-destination-checks`オプションの詳細については、link:other_references.html["参考資料"]を参照して_ONTAP 9 Command reference_にリンクしてください。





== アグリゲートは、アップグレードの完了後、ノード 1 にもともと存在していたものとノード 4 によって所有されます

アップグレード手順 の最後に、 node3 は、元々ホームノードとしてノード 1 を使用していたアグリゲートの新しいホームノードである必要があります。このパスはアップグレード後に再配置できます。

.このタスクについて
次の状況で、アグリゲートを正しく再配置できず、ノード 1 がノード 3 ではなくホームノードになっている可能性があります。

* ステージ3では、アグリゲートがnode2からnode3に再配置されます。再配置されるアグリゲートの中には、node1をホームノードとしているものがあります。たとえば、そのようなアグリゲートはaggr_node_1と呼ばれることがあります。ステージ3でaggr_node_1の再配置が失敗し、再配置を強制できない場合、アグリゲートはnode2上に残されます。
* ステージ4の後、node2がnode4に置き換えられます。node2が交換されると、aggr_node_1はnode3ではなくnode4をホームノードとしてオンラインになります。


ストレージフェイルオーバーを有効にしたあとに、ステージ 6 に続けて誤った所有権の問題を修正するには、次の手順を実行します。

.手順
. [man_aggr_ffail _step1] 次のコマンドを入力して、アグリゲートのリストを表示します。
+
storage aggregate show -nodes_node4 --is-home true

+
正しく再配置されていないアグリゲートを特定するには、セクションで取得した node1 のホーム所有者を含むアグリゲートのリストを参照してください link:prepare_nodes_for_upgrade.html["ノードをアップグレードする準備をします"] コマンドの出力と比較してください。

. [[step2] の出力を比較します <<man_aggr_fail_step1,手順 1.>> セクションで node1 用に取得した出力を確認します link:prepare_nodes_for_upgrade.html["ノードをアップグレードする準備をします"] 再配置されていないアグリゲートがあることを確認します。
. [man_aggr_fil_Step3] ノード 4 の背後にあるアグリゲートの再配置を行います。
+
「storage aggregate relocation start -NODE_node4」-aggr_aggr_node_A_1 -destination_node3 _」を入力します

+
この再配置中は '-nd-controller-upgrade パラメータを使用しないでください

. 次のコマンドを入力して、 node3 がアグリゲートのホームの所有者になっていることを確認します。
+
storage aggregate show -aggregate aggr1、aggr2、aggr3_-fields home-name

+
「_aggr1、aggr2、aggr3__」は、node1が元のホーム所有者であるアグリゲートのリストです。

+
ノード 3 をホーム所有者としないアグリゲートは、の同じ再配置コマンドを使用してノード 3 に再配置できます <<man_aggr_fail_Step3,手順 3>>。


