= 
:allow-uri-read: 


ノード 3 をラックに設置し、ノード 1 の接続をノード 3 に転送し、ノード 3 をブートして、 ONTAP をインストールする必要があります。また、ノード 1 のスペアディスク、ルートボリュームに属するディスク、およびルート以外のアグリゲートのうち、ノード 2 に再配置されていないディスクも再割り当てする必要があります。

.このタスクについて
ノード 1 にインストールされている ONTAP 9 のバージョンが異なる場合は、ノード 3 をネットブートする必要があります。node3 のインストールが完了したら、 Web サーバに保存されている ONTAP 9 イメージからブートします。その後、以降のシステムブートで使用するブートメディアデバイスに正しいファイルをダウンロードできます。を参照してください link:prepare_for_netboot.html["ネットブートを準備"]。

ただし、ノード 1 にインストールされている ONTAP 9 のバージョンが同じかそれ以降である場合は、ノード 3 をネットブートする必要はありません。

[IMPORTANT]
====
ストレージアレイに接続されている V シリーズシステム、またはストレージアレイに接続されている FlexArray 仮想化ソフトウェアを使用するシステムをアップグレードする場合は、これで完了です <<man_install3_step1,手順 1.>> から <<man_install3_step5,手順 5>>をクリックします <<man_install3_step6,手順 6>> およびの手順に従ってください link:set_fc_uta_uta2_config_node3.html#configure-fc-ports-on-node3["ノード 3 の FC ポートを設定"] および link:set_fc_uta_uta2_config_node3.html#uta-ports-node3["ノード 3 の UTA / UTA2 ポートを確認して設定してください"] 必要に応じて、保守モードでコマンドを入力します。その後、このセクションに戻ってからを使用して再開する必要があります <<man_install3_step7,手順 7>>。

ただし、ストレージディスクを搭載したシステムをアップグレードする場合は、このセクション全体を完了してからに進む必要があります link:set_fc_uta_uta2_config_node3.html#configure-fc-ports-on-node3["ノード 3 の FC ポートを設定"] および link:set_fc_uta_uta2_config_node3.html#uta-ports-node3["ノード 3 の UTA / UTA2 ポートを確認して設定してください"]クラスタ・プロンプトでコマンドを入力します。

====
.手順
. [[man_install3_step1] ノード 3 のラックスペースがあることを確認します。
+
ノード 1 とノード 2 が別々のシャーシに搭載されている場合は、ノード 3 をノード 1 と同じラックの場所に設置できます。ただし、ノード1がノード2と同じシャーシに搭載されていた場合は、ノード3をノード1の場所に近い独自のラックスペースに配置する必要があります。

. [[step2] ノードモデルの _ インストールおよびセットアップ手順 _ に従って、ラックにノード 3 をインストールします。
+

NOTE: 両方のノードを同じシャーシに搭載したシステムにアップグレードする場合は、 node4 と node3 をシャーシに設置します。そうしないと、ノードをブートしたときにノードがデュアルシャーシ構成と同じように動作し、 node4 をブートした場合、ノード間のインターコネクトは稼働しません。

. [[step3]] ケーブルノード 3 を接続し、ノード 1 からノード 3 に接続を移動します。
+
次の参考資料は、適切なケーブル接続を行う場合に役立ちます。に進みます link:other_references.html["参考資料"] をクリックしてリンクします。

+
** _ インストールおよびセットアップ手順 _ または _ FlexArray 仮想化インストール要件およびリファレンス _ （ node3 プラットフォーム用）
** 該当するディスクシェルフの手順を選択します
** 高可用性管理に関するドキュメント（ _High Availability MANAGEMENT


+
次の配線を行います。

+
** コンソール（リモート管理ポート）
** クラスタポート
** データポート
** クラスタポートとノード管理ポート
** ストレージ
** SAN 構成： iSCSI イーサネットおよび FC スイッチポート
+

NOTE: ほとんどのプラットフォームモデルには一意のインターコネクトカードモデルがあるため、インターコネクトカードまたはクラスタインターコネクトケーブルの接続を node1 から node3 に移動する必要はない場合があります。MetroCluster 構成の場合は、FC-VIケーブルの接続をノード1からノード3に移行する必要があります。新しいホストに FC-VI カードがない場合は、 FC-VI カードの移動が必要になることがあります。



. [[man_install3_step4]] ノード 3 の電源をオンにしてから、コンソール端末で Ctrl+C キーを押してブートプロセスを中断し、ブート環境プロンプトにアクセスします。
+
両方のノードを同じシャーシに搭載したシステムにアップグレードする場合は、 node4 もリブートします。ただし、 node4 のブートはあとで破棄することができます。

+

NOTE: node3 をブートすると、次の警告メッセージが表示される場合があります。

+
[listing]
----
WARNING: The battery is unfit to retain data during a power outage. This is likely because the battery is discharged but could be due to other temporary conditions.
When the battery is ready, the boot process will complete and services will be engaged.
To override this delay, press 'c' followed by 'Enter'
----
. [[man_install3_step5]] で警告メッセージが表示される場合 <<man_install3_step4,手順 4>>を使用して、次の操作を実行します。
+
.. NVRAM バッテリ低下以外の問題を示すコンソールメッセージがないか確認し、必要に応じて対処します。
.. バッテリの充電と起動プロセスが完了するまで待ちます。
+

NOTE: * 注意 * ：遅延は無視しないでください。バッテリーの充電に失敗すると、データが失われるおそれがあります。



. [[man_install3_step6] 次のいずれかの操作を実行します。
+
[cols="35,65"]
|===
| システムの状態 | 作業 


| ディスクがあり、バックエンドストレージがない | 手順 7 から 12 を省略して、に進みます <<man_install3_step13,手順 13>>。 


| は、 V シリーズシステム、または FlexArray 仮想化ソフトウェアがストレージアレイに接続されたシステムです  a| 
.. に進みます link:set_fc_uta_uta2_config_node3.html["ノード 3 で FC または UTA / UTA2 設定を設定します"] をクリックし、サブセクションを完了します link:set_fc_uta_uta2_config_node3.html#configure-fc-ports-on-node3["ノード 3 の FC ポートを設定"] および link:set_fc_uta_uta2_config_node3.html#uta-ports-node3["ノード 3 の UTA / UTA2 ポートを確認して設定してください"]必要に応じて、システムに適用されます。
.. このセクションに戻って、から始めて残りの手順を実行します <<man_install3_step7,手順 7>>。



IMPORTANT: VシリーズまたはFlexArray 仮想化ソフトウェアを使用してONTAP をブートする前に、FCオンボードポート、CNAオンボードポート、およびCNAカードを再設定する必要があります。

|===
. [man_install3_step7] 新しいノードの FC イニシエータポートをスイッチゾーンに追加します。
+
システムにテープ SAN がある場合は、イニシエータをゾーニングする必要があります。手順については、ストレージアレイおよびゾーニングに関するドキュメントを参照してください。

. [man_install3_step8] FC イニシエータポートをストレージアレイに新しいホストとして追加し、アレイ LUN を新しいホストにマッピングします。
+
手順については、ストレージアレイおよびゾーニングに関するドキュメントを参照してください。

. [[man_install3_step9] ストレージアレイのアレイ LUN に関連付けられたホストまたはボリュームグループでの World Wide Port Name （ WWPN ；ワールドワイドポート名）の値を変更します。
+
新しいコントローラモジュールを設置すると、各オンボード FC ポートに関連付けられている WWPN の値が変更されます。

. [man_install3_step10] ：構成でスイッチベースのゾーニングを使用している場合は、ゾーニングを調整して新しい WWPN 値を反映させます。
. [[man_install3_step11]] アレイ LUN が node3 に表示されることを確認します。
+
「 sysconfig -v 」を使用します

+
各 FC イニシエータポートで認識されるすべてのアレイ LUN が表示されます。アレイ LUN が表示されない場合は、このセクションで後述する node1 から node3 にディスクを再割り当てすることはできません。

. [[man_install3_step12]] Ctrl+C キーを押してブートメニューを表示し、メンテナンスモードを選択します。
. [[man_install3_step13]] メンテナンスモードのプロンプトで、次のコマンドを入力します。
+
「 halt 」

+
ブート環境プロンプトが表示されます。

. [[man_install3_step14]] 次のいずれかの操作を実行します
+
[cols="35,65"]
|===
| アップグレード後のシステムの構成 | 作業 


| デュアルシャーシ構成（コントローラが別々のシャーシに搭載されている場合） | に進みます <<man_install3_step15,手順 15>>。 


| シングルシャーシ構成（コントローラが同じシャーシに搭載されている場合）  a| 
.. コンソールケーブルを node3 から node4 に切り替えます。
.. ノード 4 の電源をオンにしてから、コンソール端末で Ctrl+C キーを押してブートプロセスを中断し、ブート環境プロンプトにアクセスします。
+
両方のコントローラが同じシャーシ内にある場合は、電源はすでにオンになっているはずです。

+

NOTE: node4にはブート環境のプロンプトが表示されたままにします。node4には戻ります link:install_boot_node4.html["ノード 4 をインストールしてブートします"]。

.. に警告メッセージが表示される場合は <<man_install3_step4,手順 4>>の手順に従ってください <<man_install3_step5,手順 5>>
.. コンソールケーブルを node4 から node3 に戻します。
.. に進みます <<man_install3_step15,手順 15>>。


|===
. [[man_install3_step15]] ONTAP の node3 の設定：
+
「デフォルト設定」


