= 
:allow-uri-read: 


. ノード 4 にインストールされている ONTAP のバージョンが node2 にインストールされている ONTAP 9 と同じかそれ以降の場合は、次のコマンドを入力します。
+
「 boot_ontap menu

. 次のいずれかを実行します。
+
[cols="35,65"]
|===
| アップグレードするシステム | 作業 


| ノード 4 に正しい ONTAP バージョンまたは現在の バージョンがない | に進みます <<man_install4_Step20,手順 20>>。 


| ノード 4 の ONTAP のバージョンが正しいか、最新のバージョンであることが必要です | に進みます <<man_install4_Step25,手順 25>>。 
|===
. [[man_install4_Step20]] 次のいずれかの操作を選択して、ネットブート接続を設定します。
+

NOTE: ネットブート接続として管理ポートおよび IP アドレスを使用する必要があります。アップグレードの実行中にデータ LIF の IP アドレスを使用しないでください。データ LIF が停止する可能性があります。

+
[cols="35,75"]
|===
| 動的ホスト構成プロトコル（ DHCP ）の状態 | 作業 


| 実行中です  a| 
ブート環境プロンプトで「 ifconfig e0M -auto 」コマンドを入力すると、接続が自動的に設定されます



| 実行されていません  a| 
ブート環境プロンプトで次のコマンドを入力して、接続を手動で設定します。
`ifconfig e0M -addr=_filer_addr_ mask=_netmask_ -gw=_gateway_ dns=_dns_addr_ domain=_dns_domain_`

`_filer_addr_` は、ストレージシステムのIPアドレスです（必須）。
`_netmask_` は、ストレージシステムのネットワークマスクです（必須）。
`_gateway_` は、ストレージシステムのゲートウェイです（必須）。
`_dns_addr_` は、ネットワーク上のネームサーバのIPアドレスです（オプション）。
`_dns_domain_` は、ドメインネームサービス（DNS）ドメイン名です。このオプションパラメータを使用する場合は、ネットブートサーバの URL に完全修飾ドメイン名を指定する必要はなく、サーバのホスト名だけを指定します。


NOTE: インターフェイスによっては、その他のパラメータが必要になる場合もあります。ファームウェア・プロンプトで「 help ifconfig 」と入力すると、詳細が表示されます。

|===
. ノード 4 でネットブートを実行します。
+
[cols="30,70"]
|===
| 用途 | 作業 


| FAS/AFF8000 シリーズシステム | netboot\http://web_server_ip/path_to_webaccessible_directory/netboot/kernel` 


| その他すべてのシステム | netboot\http://web_server_ip/path_to_webaccessible_directory/ontap_version_image.tgz` 
|===
+
「 path_to_the_web-accessible_directory 」は、「 ONTAP_version_image.tgz 」をダウンロードした場所を指します link:prepare_for_netboot.html#man_netboot_Step1["手順 1."] の項で、 netboot_ の準備を参照してください。

+

NOTE: トランクを中断しないでください。

. 起動メニューから 'option(7) Install new software first ’を選択します
+
このメニューオプションを選択すると、新しい Data ONTAP イメージがブートデバイスにダウンロードおよびインストールされます。

+
次のメッセージは無視してください。

+
`This procedure is not supported for Non-Disruptive Upgrade on an HA pair`

+
コントローラのアップグレードではなく、 Data ONTAP による環境の無停止アップグレードも記録されています。

+

NOTE: 新しいノードを希望するイメージに更新する場合は、必ずネットブートを使用してください。別の方法で新しいコントローラにイメージをインストールした場合、正しいイメージがインストールされないことがあります。この問題環境はすべての ONTAP リリースに対応しています。オプションを指定してネットブート手順 を実行する `(7) Install new software` ブートメディアを消去して、両方のイメージパーティションに同じONTAP バージョンを配置します。

. [man_install4_step23]] 手順を続行するかどうかを確認するメッセージが表示されたら、 y を入力します。パッケージの入力を求められたら、次の URL を入力します。
+
http://web_server_ip/path_to_web-accessible_directory/ontap_version_image.tgz` にアクセスします

. 次の手順を実行します。
+
.. 次のプロンプトが表示されたら 'n' を入力してバックアップ・リカバリをスキップします
+
[listing]
----
Do you want to restore the backup configuration now? {y|n}
----
.. 次のプロンプトが表示されたら 'y' と入力して再起動します
+
[listing]
----
The node must be rebooted to start using the newly installed software. Do you want to reboot now? {y|n}
----
+
コントローラモジュールはリブートしますが、ブートメニューで停止します。これは、ブートデバイスが再フォーマットされたことにより、構成データのリストアが必要なためです。



. [man_install4_Step25]] ブートメニューからメンテナンスモード「 5 」を選択し ' ブートを続行するように求められたら 'y' を入力します
. [[man_install4_Step26]] 続行する前に、に進みます link:set_fc_uta_uta2_config_node4.html["ノード 4 で FC または UTA / UTA2 設定を設定します"] ノードの FC ポートまたは UTA / UTA2 ポートに必要な変更を加えるため。これらのセクションで推奨される変更を行ってからノードをリブートし、メンテナンスモードに切り替えます。
. 次のコマンドを入力し、出力を調べて node4 のシステム ID を特定します。
+
「ディスクショー - A` 」

+
次の例に示すように、ノードのシステム ID 、およびそのディスクに関する情報が表示されます。

+
[listing]
----
*> disk show -a
Local System ID: 536881109
DISK         OWNER                       POOL   SERIAL NUMBER   HOME
------------ -------------               -----  -------------   -------------
0b.02.23     nst-fas2520-2(536880939)    Pool0  KPG2RK6F        nst-fas2520-2(536880939)
0b.02.13     nst-fas2520-2(536880939)    Pool0  KPG3DE4F        nst-fas2520-2(536880939)
0b.01.13     nst-fas2520-2(536880939)    Pool0  PPG4KLAA        nst-fas2520-2(536880939)
......
0a.00.0                   (536881109)    Pool0  YFKSX6JG                     (536881109)
......
----
. ノード 2 のスペア、ルートに属するディスク、および前のセクションでノード 3 に再配置されなかったルート以外のアグリゲートを再割り当てします link:relocate_non_root_aggr_node2_node3.html["ルート以外のアグリゲートを node2 から node3 に再配置します。"]：
+

NOTE: システムに共有ディスク、ハイブリッドアグリゲート、またはその両方がある場合は、適切なを使用する必要があります `disk reassign` コマンドを次の表に示します。

+
[cols="35,65"]
|===
| ディスクタイプ | 実行するコマンド 


| 共有ディスクの場合 | `disk reassign -s `_node2 _sysid_-d _node4 _sysid_-p _node3 _sysid_` 


| 共有なし | disk disk reassign -s `_node2 _sysid_-d_node4 _sysid_` 
|===
+
をクリックします `<node2_sysid>` で取得した情報を使用します。 link:record_node2_information.html#man_record_2_step10["手順 10"] をクリックします。の場合 `_node4_sysid_`で取得した情報を使用します。 <<man_install4_step23,手順 23>>。

+

NOTE: -p オプションは ' 共有ディスクが存在する場合にのみ保守モードで必要です

+
disk reassignコマンドは'_node2 _sysid_'が現在の所有者であるディスクだけを再割り当てします

+
次のメッセージが表示されます。

+
[listing]
----
Partner node must not be in Takeover mode during disk reassignment from maintenance mode.
Serious problems could result!!
Do not proceed with reassignment if the partner is in takeover mode. Abort reassignment (y/n)? n
----
+
ディスクの再割り当てを中止するかどうかを尋ねられたら 'n' を入力します

+
ディスクの再割り当てを中止するように求められた場合は、次の手順に従って一連のプロンプトを回答に出力する必要があります。

+
.. 次のメッセージが表示されます。
+
[listing]
----
After the node becomes operational, you must perform a takeover and giveback of the HA partner node to ensure disk reassignment is successful.
Do you want to continue (y/n)? y
----
.. 「 y 」と入力して続行します。
+
次のメッセージが表示されます。

+
[listing]
----
Disk ownership will be updated on all disks previously belonging to Filer with sysid <sysid>.
Do you want to continue (y/n)? y
----
.. ディスク所有権の更新を許可するには 'y' を入力します


. 外付けディスクが搭載されたシステムから、内蔵ディスクと外付けディスクをサポートするシステム（ A800 システムなど）にアップグレードする場合は、 node4 を root として設定し、 node2 のルートアグリゲートからブートすることを確認します。
+

WARNING: * 警告：次の手順を記載された順序で実行する必要があります。正しく実行しないと、原因が停止したり、データが失われたりする可能性があります。 *

+
次の手順では、 node4 に node2 のルートアグリゲートからブートするよう設定しています。

+
.. node2 アグリゲートの RAID 、プレックス、およびチェックサムの情報を確認します。
+
「 aggr status -r 」

.. node2 アグリゲートの全体的なステータスを確認します。
+
「 aggr status 」を入力します

.. 必要に応じて、 node2 アグリゲートをオンラインにします。
+
「aggr_online root_aggr_from__」に設定します

.. ノード 4 が元のルートアグリゲートからブートしないようにします。
+
'aggr offline_root_aggr_on_node4

.. node2 のルートアグリゲートを node4 の新しいルートアグリゲートとして設定します。
+
'aggr options aggr_from__ node2 _root



. 次のコマンドを入力し、出力を確認して、コントローラとシャーシが「 ha 」として設定されていることを確認します。
+
「 ha-config show 」

+
次に 'ha-config show コマンドの出力例を示します

+
[listing]
----
*> ha-config show
   Chassis HA configuration: ha
   Controller HA configuration: ha
----
+
システムは、 HA ペア構成かスタンドアロン構成かを PROM に記録します。状態は、スタンドアロンシステムまたは HA ペア内のすべてのコンポーネントで同じである必要があります。

+
コントローラとシャーシが「 ha 」として設定されていない場合は、次のコマンドを使用して設定を修正します。

+
「 ha-config modify controller ha 」を参照してください

+
「 ha-config modify chassis ha 」を参照してください。

+
MetroCluster 構成を使用している場合は、次のコマンドを使用して設定を修正します。

+
「 ha-config modify controller mcc 」

+
「 ha-config modify chassis mcc 」

. node4 にあるメールボックスを破棄します。
+
「マイボックス破壊ローカル」

. メンテナンスモードを終了します。
+
「 halt 」

+
ブート環境プロンプトが表示されます。

. ノード 3 で、システムの日付、時刻、およびタイムゾーンを確認します。
+
「食事」

. ノード 4 で、ブート環境プロンプトの日付を確認します。
+
「日付」

. 必要に応じて、 node4 に日付を設定します。
+
'set date_mm/dd/yyyy_`

. ノード 4 で、ブート環境プロンプトの時刻を確認します。
+
「時間」

. 必要に応じて、 node4 に時間を設定します。
+
'set time_hh:mm:ss_`

. パートナーシステム ID が、に示すように正しく設定されていることを確認します <<man_install4_Step26,手順 26>> オプション（ Option ）の下。
+
printenv partner-sysid

. 必要に応じて、 node4 にパートナーシステム ID を設定します。
+
setsetenv partner-sysid_node3 _sysid_`

+
.. 設定を保存します。
+
'aveenv



. ブート環境プロンプトでブートメニューを入力します。
+
「 boot_ontap menu

. ブート・メニューで ' プロンプトに「 6 」と入力して 'Option *(6) Update flash from backup config * を選択します
+
次のメッセージが表示されます。

+
[listing]
----
This will replace all flash-based configuration with the last backup to disks. Are you sure you want to continue?:
----
. プロンプトで「 y 」と入力します。
+
ブートが正常に続行され、システム ID の不一致を確認するように求められます。

+

NOTE: 不一致の警告が表示される前にシステムが 2 回リブートする可能性があります。

. 不一致を確認します。正常にブートする前に、ノードの 1 回のリブートが完了することがあります。
. ノード 4 にログインします。

