= ノード 3 の UTA / UTA2 ポートを確認して設定してください
:allow-uri-read: 




== ノード 3 の UTA / UTA2 ポートを確認して設定してください

ノード 3 にオンボード UTA / UTA2 ポートまたは UTA / UTA2 カードが搭載されている場合は、アップグレードしたシステムの使用方法によって、ポートの設定を確認し、場合によっては再設定する必要があります。

.作業を開始する前に
UTA / UTA2 ポートに対応する正しい SFP+ モジュールが必要です。

.このタスクについて
FC にユニファイドターゲットアダプタ（ UTA / UTA2 ）ポートを使用する場合は、まずポートの設定を確認する必要があります。


NOTE: ネットアップのマーケティング資料では、 UTA2 という用語を CNA アダプタとポートという意味で使用している場合があります。ただし、 CLI では CNA という用語が使用されます。

現在のポート設定を確認するには、「 ucadmin show 」コマンドを使用します。

[listing]
----
*> ucadmin show
          Current  Current    Pending  Pending    Admin
 Adapter  Mode     Type       Mode     Type       Status
 -------  -------  ---------  -------  ---------  -----------
 0e       fc       target     -        initiator  offline
 0f       fc       target     -        initiator  offline
 0g       fc       target     -        initiator  offline
 0h       fc       target     -        initiator  offline
 1a       fc       target     -        -          online
 1b       fc       target     -        -          online
6 entries were displayed.
----
UTA / UTA2 ポートは、ネイティブの FC モードまたは UTA / UTA2 モードに設定できます。FC モードは FC イニシエータと FC ターゲットをサポートします。 UTA / UTA2 モードは、同じ 10GbE SFP+ インターフェイスを共有する NIC と FCoE のトラフィックの同時処理を可能にし、 FC ターゲットをサポートします。

UTA / UTA2 ポートはアダプタまたはコントローラに搭載されている場合がありますが、次の構成になっています。ノード 3 の UTA / UTA2 ポートの設定を確認し、必要に応じて変更してください。

* コントローラを注文した UTA / UTA2 カードは、注文したパーソナリティを指定するために出荷前に設定されます。
* コントローラとは別に発注した UTA / UTA2 カードは、デフォルトの FC ターゲットパーソナリティとして出荷されます。
* 新しいコントローラのオンボード UTA / UTA2 ポートは、希望するパーソナリティを持つように出荷する前に設定されます。
+

NOTE: メンテナンス モードに入るように指示されない限り、このセクションのコマンドをクラスター プロンプトに入力します。



.手順
. node3 で次のコマンドを入力して、現在のポート構成を確認します。
+
「 system node hardware unified-connect show 」を参照してください

+
次の例のような出力が表示されます。

+
[listing]
----
 cluster1::> system node hardware unified-connect show

                Current  Current    Pending  Pending  Admin
 Node  Adapter  Mode     Type       Mode     Type     Status
 ----  -------  -------  ---------  -------  -------  ------
 f-a   0e       fc       initiator  -        -        online
 f-a   0f       fc       initiator  -        -        online
 f-a   0g       cna      target     -        -        online
 f-a   0h       cna      target     -        -        online
 f-b   0e       fc       initiator  -        -        online
 f-b   0f       fc       initiator  -        -        online
 f-b   0g       cna      target     -        -        online
 f-b   0h       cna      target     -        -        online
 12 entries were displayed.
----
. [[step2] 現在の SFP+ モジュールが目的の用途と一致しない場合は、正しい SFP+ モジュールと交換します。
+
ネットアップの担当者に連絡して、正しい SFP+ モジュールを入手します。

. [[step3]] 「 system node hardware unified-connect show 」コマンドまたは「 ucadmin show 」コマンドの出力を調べて、 UTA / UTA2 ポートに希望するパーソナリティがあるかどうかを確認します。
. [[step4]] 次のいずれかの操作を実行します。
+
[cols="35,65"]
|===
| UTA / UTA2 ポート | 作業 


| 希望するパーソナリティがない | に進みます <<man_check_3_step5,手順 5>>。 


| あなたがほしい人格を持っている | ステップ5からステップ13をスキップして、<<man_check_3_step14,手順 14>> 。 
|===
. [[man_check_3_step5]]システムにストレージディスクがあり、clustered Data ONTAP 8.3 を実行している場合は、ノード 3 を起動してメンテナンス モードに入ります。
+
「 boot_ontap maint 」を使用してください

. 設定を確認します。
+
ucadmin show

. 次のいずれかを実行します。
+
[cols="35,65"]
|===
| を設定する場合 | 作業 


| UTA / UTA2 カードのポート | 行きます <<man_check_3_step8,手順 8>>。 


| オンボードの UTA/UTA2 ポート | ステップ8をスキップして<<man_check_3_step9,手順 9>>。 
|===
. [[man_check_3_step8]]アダプタがイニシエーターモードであり、UTA/UTA2 ポートがオンラインの場合は、UTA/UTA2 ポートをオフラインにします。
+
storage disable adapter_adapter_adapter_adapter_name_`

+
ターゲットモードのアダプタは、メンテナンスモードで自動的にオフラインになります。

. [[man_check_3_step9]]現在の構成が目的の用途と一致しない場合は、必要に応じて構成を変更します。
+
ucadmin modify -m fc | cna-t initiator | target_adapter_name_`

+
** 「 -m 」はパーソナリティ・モードで、「 fc 」または「 cna 」です。
** `-t` は FC4 のタイプ、「 target 」または「 initiator 」です。
+

NOTE: テープ ドライブおよびMetroCluster構成には FC イニシエーターを使用する必要があります。  SAN クライアントには FC ターゲットを使用する必要があります。



. システムを停止します。
+
「 halt 」

+
ブート環境プロンプトが表示されます。

. 次のコマンドを入力します。
+
「 boot_ontap 」

. [[step11]] 設定を確認します。
+
「 system node hardware unified-connect show 」を参照してください

+
次の例の出力は ' アダプタ「 1b 」の FC4 タイプがイニシエータに変更されており ' アダプタ「 2a 」および「 2b 」のモードが「 cna' 」に変更されていることを示しています

+
[listing]
----
 cluster1::> system node hardware unified-connect show

                Current  Current    Pending  Pending      Admin
 Node  Adapter  Mode     Type       Mode     Type         Status
 ----  -------  -------  ---------  -------  -----------  ------
 f-a   1a       fc       initiator  -        -            online
 f-a   1b       fc       target     -        initiator    online
 f-a   2a       fc       target     cna      -            online
 f-a   2b       fc       target     cna      -            online

 4 entries were displayed.
----
. [[step12a]]各ポートごとに次のコマンドを入力して、ターゲット ポートをオンラインにします。
+
「network fcp adapter modify -node node_name --adapter_adapter_adapter_adapter_name_-state up」の形式で指定します

. [[man_check_3_step14]]ポートにケーブルを接続します。

