= ノード 4 の FC ポートを設定します
:allow-uri-read: 




== ノード 4 の FC ポートを設定します

ノード 4 にオンボードまたは FC アダプタのいずれかの FC ポートがある場合は、ポートが事前に構成されていないため、ノードを稼働状態にする前にポートの設定を行う必要があります。ポートが設定されていないと、サービスが停止する可能性があります。

.作業を開始する前に
セクションに保存した node2 の FC ポート設定の値を確認しておく必要があります link:prepare_nodes_for_upgrade.html["ノードをアップグレードする準備をします"]。

.このタスクについて
システムに FC 構成がない場合は、このセクションをスキップしてかまいません。システムにオンボード UTA / UTA2 ポートまたは UTA / UTA2 アダプタが搭載されている場合は、で設定します <<ノード 4 の UTA / UTA2 ポートを確認して設定してください>>。


IMPORTANT: このセクションのコマンドをクラスタープロンプトに入力します。

.手順
. システム上のすべての FC および統合ネットワーク アダプタに関する情報を表示します。
+
「 system node hardware unified-connect show 」を参照してください

. 新しいノードの FC 設定を、元のノードで取り込んだ設定と比較します。
. 必要に応じて、ノード 4 の FC ポートを変更します。
+
** ターゲットポートをプログラムする場合：
+
`system node hardware unified-connect modify -type \| -t target -adapter _port_name_`

** イニシエータポートをプログラミングする場合：
+
`system node unified-connect modify type \| -t initiator -adapter _port_name_`

+
`-type ` は FC4 のタイプ、ターゲットまたはイニシエータである。



. 次のコマンドを入力して出力を調べ、新しい設定を確認します。
+
`system node unified-connect show`

. 次のいずれかを実行します。
+
[cols="35,65"]
|===
| 新しいノードのデフォルトの FC 設定 | 次に、 


| 元のノードでキャプチャしたのと同じです | 行きます <<man_config_4_Step9,手順 9>>。 


| 元のノードでキャプチャしたものとは異なります | 行きます <<man_config_4_Step6,ステップ6>>。 
|===
. [[man_config_4_Step6]]メンテナンスモードを終了します。
+
「 halt 」

. コマンドを入力したら、ブート環境のプロンプトでシステムが停止するまで待ちます。
. ブート環境プロンプトで次のコマンドを入力して、node4 をブートします。
+
「 boot_ontap 」

. [[man_config_4_Step9]]次のいずれかのアクションを実行します。
+
** に進みます <<ノード 4 の UTA / UTA2 ポートを確認して設定してください>> ノード 4 に UTA / UTA2A カードまたは UTA / UTA2 オンボードポートがある場合
** セクションをスキップして、に進みます link:map_ports_node2_node4.html["node2 のポートを node4 にマッピングします"] ノード 4 に UTA / UTA2 カードまたは UTA / UTA2 オンボードポートがない場合



