---
sidebar: sidebar 
permalink: upgrade-arl-manual/determine_aggregates_on_internal_drives.html 
keywords: determine, aggregate, disk, drive, controller 
summary: ONTAP 9.7 以前を実行しているコントローラでは、 ARL を手動でアップグレードする際に、内蔵ディスクドライブにルートアグリゲートまたはデータアグリゲートが含まれていないことを確認します。 
---
= コントローラの内蔵ディスクドライブにアグリゲートがあるかどうかを確認します
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
内蔵ディスクドライブを搭載したコントローラをアップグレードする場合は、いくつかのコマンドを実行し、その出力を調べて、ルートアグリゲートやデータアグリゲートが含まれている内蔵ディスクドライブがないことを確認する必要があります。

.このタスクについて
内蔵ディスクドライブにアグリゲートがあるコントローラをアップグレードしない場合は、このセクションをスキップし、セクションに進みます link:prepare_nodes_for_upgrade.html["ノードをアップグレードする準備をします"]。

.手順
. 元のノードごとに 1 回、ノードシェルを入力します。
+
'system node run -node _node_name _`

. 内蔵ドライブを表示します。
+
「 sysconfig -av 」

+
次の例に示すように、ストレージを含む、ノードの構成に関する詳細情報が出力に表示されます。

+
....

node> sysconfig -av
slot 0: SAS Host Adapter 0a (PMC-Sierra PM8001 rev. C, SAS, UP)
                Firmware rev: 01.11.06.00
                 Base WWN: 5:00a098:0008a3b:b0
                 Phy State: [0] Enabled, 6.0 Gb/s
                            [1] Enabled, 6.0 Gb/s
                            [2] Enabled, 6.0 Gb/s
                            [3] Enabled, 6.0 Gb/s
                ID Vendor Model FW Size
                00.0 : NETAPP X306_HMARK02TSSM NA04 1695.4GB (3907029168 512B/sect)
                00.1 : NETAPP X306_HMARK02TSSM NA04 1695.4GB (3907029168 512B/sect)
                00.2 : NETAPP X306_HMARK02TSSM NA04 1695.4GB (3907029168 512B/sect)
                00.3 : NETAPP X306_HMARK02TSSM NA04 1695.4GB (3907029168 512B/sect)
                00.4 : NETAPP X306_HMARK02TSSM NA04 1695.4GB (3907029168 512B/sect)
                00.5 : NETAPP X306_HMARK02TSSM NA04 1695.4GB (3907029168 512B/sect)
                00.6 : NETAPP X306_HMARK02TSSM NA04 1695.4GB (3907029168 512B/sect)
                00.7 : NETAPP X306_HMARK02TSSM NA04 1695.4GB (3907029168 512B/sect)
                00.8 : NETAPP X306_HMARK02TSSM NA04 1695.4GB (3907029168 512B/sect)
                00.9 : NETAPP X306_HMARK02TSSM NA04 1695.4GB (3907029168 512B/sect)
                00.10: NETAPP X306_HMARK02TSSM NA04 1695.4GB (3907029168 512B/sect)
                00.11: NETAPP X306_HMARK02TSSM NA04 1695.4GB (3907029168 512B/sect)
...
....
. 「 sysconfig -av 」コマンドのストレージ出力を調べて内蔵ディスク・ドライブを特定し、その情報を記録します。
+
内蔵ドライブの ID は先頭に「 00 」と表示されます。「 00 」は内蔵ディスクシェルフを示し、小数点以下の数字は個々のディスクドライブを示します。

. [[man_aggr_step4]] 両方のコントローラで次のコマンドを入力します。
+
「 aggr status -r 」

+
次の例の出力の一部に示すように、ノードのアグリゲートステータスが表示されます。

+
[listing]
----
node> aggr status -r
Aggregate aggr2 (online, raid_dp, parity uninit'd!) (block checksums)
Plex /aggr2/plex0 (online, normal, active)
RAID group /aggr2/plex0/rg0 (normal, block checksums)

RAID Disk Device    HA SHELF BAY CHAN Pool Type RPM  Used (MB/blks)     Phys (MB/blks)
--------- --------- -- ----- --- ---- ---- ---- ---- ------------------ ------------------
dparity   0a.00.1   0a   0    1  SA:B  0   BSAS 7200 1695466/3472315904 1695759/3472914816
parity    0a.00.3   0a   0    3  SA:B  0   BSAS 7200 1695466/3472315904 1695759/3472914816
data      0a.00.9   0a   0    9  SA:B  0   BSAS 7200 1695466/3472315904 1695759/3472914816
...
----
+

NOTE: アグリゲートの作成に使用されるデバイスは物理ディスクではなく、パーティションの場合もあります。

. aggr status -r コマンドの出力を調べて、内蔵ディスク・ドライブを使用しているアグリゲートを特定し、その情報を記録します。
+
前の手順の例では、シェルフ ID が「 0 」の場合、「 aggr2 」は内蔵ドライブを使用します。

. 両方のコントローラで次のコマンドを入力します。
+
「 aggr status -y 」を入力します

+
次の例の出力の一部に示すように、アグリゲート上のボリュームに関する情報が表示されます。

+
....
node> aggr status -v
...
 aggr2   online   raid_dp, aggr    nosnap=off, raidtype=raid_dp, raidsize=14,
                  64-bit           raid_lost_write=on, ignore_inconsistent=off,
                  rlw_on           snapmirrored=off, resyncsnaptime=60,
                                   fs_size_fixed=off, lost_write_protect=on,
                                   ha_policy=cfo, hybrid_enabled=off, percent_snapshot_space=0%,
                                   free_space_realloc=off, raid_cv=on, thorough_scrub=off
         Volumes: vol6, vol5, vol14
...
 aggr0   online   raid_dp, aggr    root, diskroot, nosnap=off, raidtype=raid_dp,
                  64-bit           raidsize=14, raid_lost_write=on, ignore_inconsistent=off,
                  rlw_on           snapmirrored=off,  resyncsnaptime=60, fs_size_fixed=off,
                                   lost_write_protect=on, ha_policy=cfo, hybrid_enabled=off,
                                   percent_snapshot_space=0%, free_space_realloc=off, raid_cv=on
         Volumes: vol0
....
+
の出力に基づきます <<man_aggr_step4,手順 4>> 手順 6 では、 aggr2 は 3 つの内蔵ドライブ「 0a.00.1 」、「 0a.00.3 」、「 0a.00.9 」を使用します。「 aggr2 」のボリュームは「 vol6 」、「 vol5 」、「 vol14 」です。また、手順 6 の出力では、「 aggr0 」の読み出しには、アグリゲートの情報の先頭に「 root 」という単語が含まれています。ルートボリュームが含まれていることを示します。

. 「 aggr status -v 」コマンドの出力を調べ、内部ドライブ上のアグリゲートに属するボリュームと、それらのボリュームにルート・ボリュームが含まれているかどうかを確認します。
. 各コントローラで次のコマンドを入力して、ノードシェルを終了します。
+
「 exit

. 次のいずれかを実行します。
+
[cols="35,65"]
|===
| コントローラの状況 | 作業 


| 内蔵ディスクドライブにアグリゲートを含めないでください | この手順に進みます。 


| 内蔵ディスクドライブにはアグリゲートは含まれますが、ボリュームは含まれません  a| 
この手順に進みます。


NOTE: 続行する前に、アグリゲートをオフラインにしてから、内蔵ディスクドライブ上のアグリゲートを削除する必要があります。を参照してください link:other_references.html["参考資料"] アグリゲートの管理に関する情報を取得するには、 CLI の _content を使用して _Disk およびアグリゲートの管理にリンクします。



| 内蔵ドライブにルート以外のボリュームを格納します  a| 
この手順に進みます。


NOTE: 続行する前に、ボリュームを外付けディスクシェルフに移動し、アグリゲートをオフラインにして、内蔵ディスクドライブ上のアグリゲートを削除する必要があります。を参照してください link:other_references.html["参考資料"] ボリュームの移動に関する情報を取得するには、 CLI の _CONTENT を使用して、 _Disk およびアグリゲートの管理にリンクしてください。



| 内部ドライブ上のルートボリュームが含まれます | この手順を続行しないでください。コントローラをアップグレードする方法について、を参照してください link:other_references.html["参考資料"] 手順を実行しているノードペアで、ボリュームを移動して Data ONTAP を実行しているコントローラハードウェアのアップグレードを実行し、 _NetApp Support Site_and へのリンク。 


| 内蔵ドライブにルート以外のボリュームを格納し、外付けストレージにボリュームを移動することはできません | この手順を続行しないでください。clustered Data ONTAP を実行しているノードのペアで手順 _ ボリュームを移動してコントローラハードウェアをアップグレードする方法を説明します。を参照してください link:other_references.html["参考資料"] からネットアップサポートサイトにリンクして、この手順にアクセスできます。 
|===

