---
sidebar: sidebar 
permalink: upgrade-arl-manual/ensure_controllers_set_up_correctly.html 
keywords: set up, controllers, correctly, ha pair, lif, aggregate, node, failover 
summary: HA ペアを有効にし、 node3 と node4 にあるストレージアクセスを確認し、 ONTAP 9.7 以前を実行しているコントローラで ARL を手動でアップグレードしたあとにアグリゲートの所有権を確認します。 
---
= 新しいコントローラが正しくセットアップされていることを確認します
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
セットアップが正しいことを確認するには、HAペアを有効にします。また、ノード3とノード4が相互にストレージにアクセスできること、およびクラスタの他のノードに属するデータLIFをどちらも所有していないことを確認します。さらに、ノード3がノード1のアグリゲートを所有し、ノード4がノード2のアグリゲートを所有していること、および両方のノードのボリュームがオンラインであることを確認します。

.手順
. いずれかのノードで次のコマンドを入力して、ストレージフェイルオーバーを有効にします。
+
`storage failover modify -enabled true -node <node3>`

. ストレージフェイルオーバーが有効になっていることを確認します。
+
「 storage failover show 」をクリックします

+
次の例は、ストレージフェイルオーバーが有効になっている場合のコマンドの出力例を示しています。

+
[listing]
----
cluster::> storage failover show
                              Takeover
Node           Partner        Possible State Description
-------------- -------------- -------- ------------------
node3          node4          true     Connected to node4
node4          node3          true     Connected to node3
----
. 次のいずれかを実行します。
+
|===
| クラスタの種類 | 説明 


| 2 ノードクラスタ | どちらかのノードで cluster ha modify -configured true コマンドを入力して ' クラスタの高可用性を有効にします 


| 3 ノード以上のクラスタ | に進みます <<man_ensure_setup_Step4,手順 4>>。 
|===
. [[man_ver_setup_Step4]] 次のコマンドを入力して、 node3 と node4 が同じクラスタに属していることを確認します。
+
「 cluster show 」を参照してください

. 次のコマンドを入力し、出力を調べて、 node3 と node4 が相互のストレージにアクセスできることを確認します。
+
「 storage failover show -fields local-missing-disks 、 partner-missing-disks 」というメッセージが表示されます

. 次のコマンドを入力し、出力を調べて、 node3 と node4 がクラスタ内の他のノードによってホーム所有されているデータ LIF を所有していないことを確認します。
+
「 network interface show 」を参照してください

+
node3 または node4 に、クラスタ内の他のノードがホーム所有するデータ LIF がある場合は、「 network interface revert 」コマンドを使用して、データ LIF をホーム所有者にリバートします。

. ノード 3 がノード 1 のアグリゲートを所有していること、およびノード 4 がノード 2 のアグリゲートを所有していることを確認します。
+
`storage aggregate show -owner-name <node3>`
`storage aggregate show -owner-name <node4>`

. オフラインになっているボリュームがないかを確認します。
+
`volume show -node <node3> -state offline`
`volume show -node <node4> -state offline`

. オフラインのボリュームがある場合は、で取得したオフラインボリュームのリストと比較します  link:prepare_nodes_for_upgrade.html#man_prepare_nodes_step19["手順 19 （ d ）"] で、各ボリュームに対して次のコマンドを 1 回入力して、アップグレードの準備をし、必要に応じてオフラインのボリュームをオンラインにします。
+
`volume online -vserver <vserver_name> -volume <volume_name>`

. ノードごとに次のコマンドを入力して、新しいノード用の新しいライセンスをインストールします。
+
`system license add -license-code <license_code,license_code,license_code...>`

+
license-code パラメータには、アルファベットの文字キーをアルファベットの大文字 28 個まで入力できます。ライセンスは一度に 1 つずつ追加することも、ライセンスキーごとにカンマで区切って複数ずつ追加することもできます。

. [[unset_maxwait_manual]]構成で自己暗号化ドライブを使用している場合は、を設定します `kmip.init.maxwait` 変数をに設定します `off` （例：で） link:install_boot_node3.html#man_install3_step16["手順 16"] of _ Install and boot node3 _）では、変数の設定を解除する必要があります。
+
`set diag; systemshell -node-node_name --コマンドsudo kenv -u -p kmip.init.maxwait`

. 元のノードから古いライセンスをすべて削除するには、次のいずれかのコマンドを入力します。
+
`system license clean-up -unused -expired`
`system license delete -serial-number <node_serial_number> -package <licensable_package>`

+
** 期限切れのライセンスをすべて削除するには、次のように入力します
+
「システムライセンスのクリーンアップ - 期限切れ」

** 未使用のライセンスをすべて削除するには、次のように入力し
+
'System license clean-up-unused （システムライセンスのクリーンアップ - 未使用） '

** クラスタから特定のライセンスを削除するには、ノードで次のコマンドを入力します。
+
`system license delete -serial-number <node1_serial_number> -package *`
`system license delete -serial-number <node2_serial_number> -package *`

+
次の出力が表示されます。

+
[listing]
----
Warning: The following licenses will be removed:
<list of each installed package>
Do you want to continue? {y|n}: y
----
+
すべてのパッケージを削除するには 'y' を入力します



. 次のコマンドを入力し、出力を調べて、ライセンスが正しくインストールされていることを確認します。
+
「 system license show 」を参照してください

+
出力をキャプチャした出力と比較することができますlink:prepare_nodes_for_upgrade.html#man_prepare_nodes_step29["手順 29"]_アップグレード用にノードを準備する_。

. 両方のノードで次のコマンドを実行して、 SP を設定します。
+
`system service-processor network modify -node <node_name>`

+
に進みます link:other_references.html["参考資料"] SP の詳細については ' システム管理リファレンスにリンクし '_System ONTAP 9 コマンド：マニュアルページリファレンスにリンクし 'system service-processor network modify コマンドの詳細については ' を参照してください

. 新しいノードにスイッチレスクラスタをセットアップする場合は、に進みます link:other_references.html["参考資料"] ネットワークサポートサイトへのリンクをクリックし、 2 ノードスイッチレスクラスタへの移行の手順に従ってください。


.完了後
ノード 3 とノード 4 でストレージ暗号化が有効になっている場合は、の手順を実行します link:set_up_storage_encryption_new_controller.html["新しいコントローラモジュールで Storage Encryption をセットアップします"]。それ以外の場合は、の手順を実行します link:decommission_old_system.html["古いシステムの運用を停止"]。
