---
sidebar: sidebar 
permalink: upgrade-arl-manual/guidelines_upgrade_with_arl.html 
keywords: guidelines, upgrade, controllers, arl, aggregate, relocation 
summary: ONTAP 9.7 以前を実行するコントローラのペアに手動 ARL 手順 を使用できるかどうかを確認します。 
---
= ARL を使用したコントローラのアップグレードに関するガイドライン
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
アグリゲートの再配置（ ARL ）を使用して ONTAP 9.0 を実行するコントローラのペアをアップグレードできるかどうかは、プラットフォームおよび元のコントローラと交換用コントローラの両方の構成によって異なります。



== ARL のアップグレードがサポートされます

ARL を使用してノードのペアをアップグレードできる状況は次のとおりです。

* アップグレード前に、元のコントローラと交換用コントローラの両方で同じバージョンの ONTAP 9.x が実行されている必要があります。
* 交換用コントローラの容量は元のコントローラと同じかそれ以上である必要があります。容量が等しいかそれよりも大きい場合は、 NVRAM サイズ、ボリューム、 LUN 、アグリゲート数の上限などの属性を表し、新しいノードのボリュームまたはアグリゲートの最大サイズも表します。
* 次の種類のシステムをアップグレードできます。
+
** FAS システムから FAS システムへの移動。
** FlexArray 仮想化ソフトウェアまたは V シリーズシステムを搭載したシステムへの FAS システムの追加。
** AFF システムへの AFF システム。
** FlexArray 仮想化ソフトウェアまたは V シリーズシステムを FAS システムに移行するシステム。ただし、 FlexArray 仮想化ソフトウェアまたは V シリーズシステムにアレイ LUN がない場合に限ります。
** V シリーズシステムから、 FlexArray 仮想化ソフトウェアまたは V シリーズシステムを搭載したシステムへのアップグレード。





NOTE: AFF システムのアップグレードを実行する前に、 ONTAP をリリースバージョン 9.3P12 、 9.4P6 、または 9.5P1 以降にアップグレードする必要があります。これらのリリースレベルは、アップグレードを成功させるために必要です。

* 一部の ARL コントローラアップグレードでは、交換用コントローラの一時的なクラスタポートをアップグレードに使用できます。たとえば、 AFF A300 から AFF A400 システムにアップグレードする場合、 AFF A400 構成に応じて、 2 つのメザニンポートのいずれかを使用するか、 4 ポート 10GbE ネットワークインターフェイスカードを追加して一時的なクラスタポートを提供できます。一時的なクラスタポートを使用してコントローラのアップグレードを完了したら、交換用コントローラの 100GbE ポートにクラスタを無停止で移行できます。
* ONTAP 9.6P11 、 9.7P8 、またはそれ以降のリリースを使用している場合は、 Connectivity 、 live, and Availability Monitor （ CLAM ）のテイクオーバーを有効にして、特定のノード障害が発生したときにクラスタをクォーラムに戻すことを推奨します。「 kernel-service 」コマンドには、 advanced 権限レベルのアクセスが必要です。詳細については、を参照してください https://kb.netapp.com/Support_Bulletins/Customer_Bulletins/SU436["ネットアップの技術情報アーティクル SU436 ：「 clam takeover default configuration changed"^]。
* ARL を使用したコントローラのアップグレードは、 SnapLock Enterprise ボリュームおよび SnapLock Compliance ボリュームが設定されたシステムでサポートされます。


ARL を元のコントローラおよび交換用コントローラで実行できるかどうかを確認する必要があります。元のシステムでサポートされるすべての定義済みアグリゲートのサイズとディスク数を確認する必要があります。新しいシステムでサポートされるアグリゲートのサイズとディスク数を比較します。この情報にアクセスするには、を参照してください link:other_references.html["参考資料"] Hardware Universe にリンクするには、次の手順を実行します。新しいシステムでサポートされるアグリゲートサイズとディスク数は、元のシステムでサポートされるアグリゲートサイズとディスク数以上であることが必要です。

元のコントローラを交換したときに、新しいノードが既存のノードとクラスタの一部になることができるかどうかは、クラスタ混在ルールで検証する必要があります。クラスタ混在ルールの詳細については、を参照してください link:other_references.html["参考資料"] Hardware Universe にリンクするには、次の手順を実行します。


NOTE: どちらのシステムもハイアベイラビリティ（ HA ）と非 HA のどちらかです。両方のノードがこの機能を有効または無効にする必要があります。オールフラッシュで最適化されたノードと同じ HA ペアで最適化が有効になっていないノードを組み合わせることはできません。パーソナリティが異なる場合は、テクニカルサポートに連絡してください。


NOTE: 新しいシステムのスロット数が元のシステムのスロット数より少ない場合、またはポートの数が少ないか異なる場合は、新しいシステムにアダプタを追加しなければならないことがあります。を参照してください link:other_references.html["参考資料"] 特定のプラットフォームの詳細については、ネットアップサポートサイトの Hardware Universe にリンクしてください。



== ARL のアップグレードはサポートされていません

次のアップグレードは実行できません。

* ONTAP 9.0 から ONTAP 9.7 への ONTAP のバージョンを実行できないコントローラとの間。
+
Data ONTAP 7-Mode を実行するシステムでのコントローラのアップグレードについては、を参照してください link:other_references.html["参考資料"] からネットアップサポートサイトにリンクできます。

* 元のコントローラに接続されたディスクシェルフをサポートしない交換用コントローラへの接続
+
ディスクサポート情報については、を参照してください link:other_references.html["参考資料"] Hardware Universe にリンクするには、次の手順を実行します。

* ルートアグリゲートまたは内蔵ドライブ上のデータアグリゲートを含むコントローラからのアクセス。
+
ルートアグリゲートまたはデータアグリゲートが含まれるコントローラを内蔵ディスクドライブにアップグレードする場合は、を参照してください link:other_references.html["参考資料"] ボリュームまたは storage を移動して _Upgrade にリンクし、 Data ONTAP に移動して、 clustered 手順を実行するノードのペアをアップグレードする _ に進みます。

+

NOTE: クラスタ内のノードの ONTAP をアップグレードする場合は、を参照してください link:other_references.html["参考資料"] リンク先： ONTAP のアップグレード _ 。





== 前提条件と用語

このマニュアルの記述は次の前提に基づいています。

* 交換用コントローラハードウェアは新しく購入され、使用されていません。
+

WARNING: * 注意 * ：この手順は、交換用コントローラハードウェアが新しく、使用されていないと想定しているため、使用済みコントローラを「 wipeconfig 」コマンドで準備するために必要な手順は、この手順には含まれていません。交換用コントローラハードウェアを以前に使用していた場合は、テクニカルサポートに問い合わせる必要があります。特に、コントローラが Data ONTAP 7-Mode を実行していた場合は、テクニカルサポートにお問い合わせください。

* ノードのペアをアップグレードする際のガイドラインを確認し、理解しておきます。
+

WARNING: * 注意 * NVRAM の内容は消去しないでください。NVRAM の内容をクリアする必要がある場合は、ネットアップテクニカルサポートにお問い合わせください。

* 「 mody 」コマンドの前後に適切なコマンドを実行し、両方の「 show 」コマンドの出力を比較して、「 mody 」コマンドが成功したことを確認しています。
* SAN 構成の場合、 HA ペア上の各 Storage Virtual Machine （ SVM ）にローカル LIF とパートナー LIF があります。各 SVM にローカル LIF とパートナー LIF がない場合は、アップグレードを開始する前に、その SVM のリモートノードとローカルノードに SAN データ LIF を追加します。
* SAN 構成でポートセットを使用する場合は、バインドされた各ポートセットに HA ペアの各ノードの LIF が少なくとも 1 つ含まれていることを確認しておく必要があります。


この手順では、ノードのリブートや環境変数の出力や設定など、特定のタスクを実行できるノード上のプロンプトを「 _boot environment prompt_ 」で参照します。このプロンプトは、 _boot loader prompt_ と非公式に呼ばれることがあります。

ブート環境のプロンプトの例を次に示します。

[listing]
----
LOADER>
----


== ONTAP 9.7 以前のライセンス

クラスタをセットアップする際、セットアップウィザードでクラスタベースのライセンスキーを入力するように求められます。ただし、一部の機能には追加のライセンスが必要です。このライセンスは、 1 つ以上の機能を含む _ パッケージ _ として発行されます。クラスタで使用する各機能のキーは、クラスタ内の各ノードに独自に設定する必要があります。

新しいライセンスキーがない場合は、クラスタで現在ライセンスされている機能を新しいコントローラで使用でき、引き続き使用できます。ただし、ライセンスされていない機能をコントローラで使用するとライセンス契約に違反する可能性があるため、アップグレードの完了後に新しいコントローラの新しいライセンスキーをインストールする必要があります。

すべてのライセンスキーは、 28 文字の大文字のアルファベットです。を参照してください link:other_references.html["参考資料"] ONTAP 9.7 の新しい 28 文字のライセンスキーを取得する方法については、 _NetApp サポートサイト _ にリンクしてください。またはそれ以前のバージョン。キーは、 _ ソフトウェアライセンス _ の _ マイサポート _ セクションにあります。必要なライセンスキーがサイトにない場合は、ネットアップの営業担当者にお問い合わせください。

ライセンスの詳細については、を参照してください link:other_references.html["参考資料"] をクリックして、 _System Administration Reference_( システム管理リファレンス ) にリンクします。



== ストレージ暗号化

元のノードまたは新しいノードでストレージ暗号化が有効になっている場合があります。その場合は、この手順 で追加の手順を実行して、ストレージ暗号化が正しく設定されていることを確認する必要があります。

ストレージ暗号化を使用する場合は、ノードに関連付けられているすべてのディスクドライブに自己暗号化ディスクドライブが必要です。



== 2 ノードスイッチレスクラスタ

2 ノードスイッチレスクラスタのノードをアップグレードする場合は、アップグレードの実行中もスイッチレスクラスタのノードをそのまま使用できます。スイッチクラスタに変換する必要はありません。



== トラブルシューティング

この手順にはトラブルシューティングの提案が含まれてい

コントローラのアップグレード中に問題が発生した場合は、を参照してください link:troubleshoot.html["トラブルシューティングを行う"] 詳細および解決策については、手順の末尾にあるセクションを参照してください。

発生した問題に対する解決策 が見つからない場合は、テクニカルサポートにお問い合わせください。
