---
sidebar: sidebar 
permalink: upgrade-arl-manual/install_boot_node3.html 
keywords: install, boot, node3, rack, transfer connections, v-series, storage disks 
summary: ONTAP 9.7 以前を実行しているコントローラでは、 ARL を手動でアップグレードする際に、 node3 をインストールして ONTAP ソフトウェアをインストールします。 
---
= node3 をインストールしてブートします
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
ノード 3 をラックに設置し、ノード 1 の接続をノード 3 に転送し、ノード 3 をブートして、 ONTAP をインストールする必要があります。また、ノード 1 のスペアディスク、ルートボリュームに属するディスク、およびルート以外のアグリゲートのうち、ノード 2 に再配置されていないディスクも再割り当てする必要があります。

.このタスクについて
ノード 1 にインストールされている ONTAP 9 と同じバージョンがノード 3 にインストールされていない場合は、ノード 3 をネットブートする必要があります。node3 のインストールが完了したら、 Web サーバに保存されている ONTAP 9 イメージからブートします。その後、以降のシステムブートで使用するブートメディアデバイスに正しいファイルをダウンロードできます。を参照して link:prepare_for_netboot.html["ネットブートを準備"]

ただし、node3 に node1 にインストールされている ONTAP 9 と同じバージョンまたはそれ以降のバージョンがインストールされている場合は、node3 をネットブートする必要はありません。

[IMPORTANT]
====
* AFF A800 または AFF C800 コントローラのアップグレードでは、ノード 1 を取り外す前に、シャーシ内のすべてのドライブがミッドプレーンにしっかりと固定されていることを確認する必要があります。詳細については、を参照してください link:../upgrade-arl-auto-affa900/replace-node1-affa800.html["AFF A800またはAFF C800コントローラモジュールを交換"]。
* ストレージディスクを備えたシステムをアップグレードする場合は、このセクション全体を完了してから、 link:set_fc_uta_uta2_config_node3.html#configure-fc-ports-on-node3["ノード 3 の FC ポートを設定"]そしてlink:set_fc_uta_uta2_config_node3.html#uta-ports-node3["ノード 3 の UTA / UTA2 ポートを確認して設定してください"]クラスタープロンプトでコマンドを入力します。


====
.手順
. [[man_install3_step1] ノード 3 のラックスペースがあることを確認します。
+
ノード 1 とノード 2 が別々のシャーシに搭載されている場合は、ノード 3 をノード 1 と同じラックの場所に設置できます。ただし、ノード1がノード2と同じシャーシに搭載されていた場合は、ノード3をノード1の場所に近い独自のラックスペースに配置する必要があります。

. [[step2] ノードモデルの _ インストールおよびセットアップ手順 _ に従って、ラックにノード 3 をインストールします。
+

NOTE: 両方のノードを同じシャーシに搭載したシステムにアップグレードする場合は、 node4 と node3 をシャーシに設置します。そうしないと、ノードをブートしたときにノードがデュアルシャーシ構成と同じように動作し、 node4 をブートした場合、ノード間のインターコネクトは稼働しません。

. [[step3]] ケーブルノード 3 を接続し、ノード 1 からノード 3 に接続を移動します。
+
次の参考資料は、適切なケーブル接続を行う場合に役立ちます。に進みます link:other_references.html["参考資料"] をクリックしてリンクします。

+
** node3 プラットフォームのインストールとセットアップ手順
** 該当するディスクシェルフの手順を選択します
** HAペア管理のドキュメント


+
次の配線を行います。

+
** コンソール（リモート管理ポート）
** クラスタポート
** データポート
** クラスタポートとノード管理ポート
** ストレージ
** SAN 構成： iSCSI イーサネットおよび FC スイッチポート
+

NOTE: ほとんどのプラットフォームモデルには一意のインターコネクトカードモデルがあるため、インターコネクトカードまたはクラスタインターコネクトケーブルの接続を node1 から node3 に移動する必要はない場合があります。MetroCluster 構成の場合は、FC-VIケーブルの接続をノード1からノード3に移行する必要があります。新しいホストに FC-VI カードがない場合は、 FC-VI カードの移動が必要になることがあります。



. [[man_install3_step4]] ノード 3 の電源をオンにしてから、コンソール端末で Ctrl+C キーを押してブートプロセスを中断し、ブート環境プロンプトにアクセスします。
+
両方のノードを同じシャーシに搭載したシステムにアップグレードする場合は、 node4 もリブートします。ただし、 node4 のブートはあとで破棄することができます。

+

NOTE: node3 をブートすると、次の警告メッセージが表示される場合があります。

+
[listing]
----
WARNING: The battery is unfit to retain data during a power outage. This is likely because the battery is discharged but could be due to other temporary conditions.
When the battery is ready, the boot process will complete and services will be engaged.
To override this delay, press 'c' followed by 'Enter'
----
. [[man_install3_step5]] で警告メッセージが表示される場合 <<man_install3_step4,手順 4>>を使用して、次の操作を実行します。
+
.. NVRAM バッテリ低下以外の問題を示すコンソールメッセージがないか確認し、必要に応じて対処します。
.. バッテリの充電と起動プロセスが完了するまで待ちます。
+

WARNING: *遅延を無視しないでください。バッテリーの充電が不十分だと、データが失われる可能性があります。*



. メンテナンス モード プロンプトで、次のコマンドを入力します。
+
「 halt 」

+
ブート環境プロンプトが表示されます。

. 次のいずれかを実行します。
+
[cols="35,65"]
|===
| アップグレード後のシステムの構成 | 作業 


| デュアルシャーシ構成（コントローラが別々のシャーシに搭載されている場合） | 行きます <<man_install3_step8,手順 8>>。 


| シングルシャーシ構成（コントローラが同じシャーシに搭載されている場合）  a| 
.. コンソールケーブルを node3 から node4 に切り替えます。
.. ノード 4 の電源をオンにしてから、コンソール端末で Ctrl+C キーを押してブートプロセスを中断し、ブート環境プロンプトにアクセスします。
+
両方のコントローラが同じシャーシ内にある場合は、電源はすでにオンになっているはずです。

+

NOTE: node4にはブート環境のプロンプトが表示されたままにします。node4には戻ります link:install_boot_node4.html["ノード 4 をインストールしてブートします"]。

.. に警告メッセージが表示される場合は <<man_install3_step4,手順 4>>の手順に従ってください <<man_install3_step5,手順 5>>
.. コンソールケーブルを node4 から node3 に戻します。
.. 行きます <<man_install3_step8,手順 8>>。


|===
. [[man_install3_step8]] ONTAP用にノード3を設定します。
+
「デフォルト設定」

. [[man_install3_step16]]NetApp Storage Encryption (NSE) ドライブがインストールされている場合は、次の手順を実行します。
+

NOTE: 手順 でこれまでに行ったことがない場合は、Knowledge Baseの記事を参照してください https://kb.netapp.com/onprem/ontap/Hardware/How_to_tell_if_a_drive_is_FIPS_certified["ドライブがFIPS認定かどうかを確認する方法"^] 使用している自己暗号化ドライブのタイプを確認するため。

+
.. 設定 `bootarg.storageencryption.support` 終了： `true` または `false`：
+
[cols="35,65"]
|===
| 次のドライブが使用中の場合 | 次に、 


| FIPS 140-2レベル2の自己暗号化要件に準拠したNSEドライブ | `setenv bootarg.storageencryption.support *true*` 


| ネットアップの非FIPS SED | `setenv bootarg.storageencryption.support *false*` 
|===
+
[NOTE]
====
FIPSドライブは、同じノードまたはHAペアで他のタイプのドライブと混在させることはできません。

SEDと非暗号化ドライブを同じノードまたはHAペアで混在させることができます。

====
.. オンボードキー管理情報のリストアについては、ネットアップサポートにお問い合わせください。


. [[man_install3_step17]] node3 にインストールされている ONTAP のバージョンが、 node1 にインストールされている ONTAP 9 のバージョンと同じかそれ以降である場合は、ディスクをリストして新しい node3 に再割り当てします。
+
「 boot_ontap 」

+

WARNING: 他のクラスタまたはHAペアでこの新しいノードを使用したことがある場合は、を実行する必要があります `wipeconfig` 次に進む前に、これを行わないと、サービスの停止やデータの損失が発生する可能性があります。交換用コントローラを以前に使用したことがある場合、特にコントローラが ONTAP 7-Mode を実行していた場合は、テクニカルサポートにお問い合わせください。

. CTRL-C を押してブート メニューを表示します。
. [[man_install3_step19]] 次のいずれかの操作を実行します
+
[cols="35,65"]
|===
| アップグレードするシステム | 作業 


| Does _ not_ have the correct or current ONTAP version on node3 （ノード 3 に正しい バージョンまたは現在の バージョンがありません | 行きます <<man_install3_step13,手順 13>>。 


| ノード 3 に正しいバージョンまたは最新バージョンの ONTAP があること | 行きます <<man_install3_step18,ステップ18>>。 
|===
. [[man_install3_step13]]次のいずれかのアクションを選択して、ネットブート接続を構成します。
+

NOTE: ネットブート接続として管理ポートおよび IP を使用する必要があります。データ LIF IP を使用しないでください。使用していると、アップグレードの実行中にデータが停止する可能性があります。

+
[cols="35,65"]
|===
| 動的ホスト構成プロトコル（ DHCP ）の状態 | 作業 


| 実行中です | ブート環境プロンプトで「 ifconfig e0M -auto 」コマンドを入力すると、接続が自動的に設定されます 


| 実行されていません  a| 
ブート環境プロンプトで次のコマンドを入力して、接続を手動で設定します。
`ifconfig e0M -addr=_filer_addr_ -mask=_netmask_ -gw=_gateway_ -dns=_dns_addr_ -domain=_dns_domain_`

`_filer_addr_` は、ストレージシステムのIPアドレスです（必須）。
`_netmask_` は、ストレージシステムのネットワークマスクです（必須）。
`_gateway_` は、ストレージシステムのゲートウェイです（必須）。
`_dns_addr_` は、ネットワーク上のネームサーバのIPアドレスです（オプション）。
`_dns_domain_` は、ドメインネームサービス（DNS）ドメイン名です。このオプションパラメータを使用する場合は、ネットブートサーバの URL に完全修飾ドメイン名を指定する必要はなく、サーバのホスト名だけを指定します。


NOTE: インターフェイスによっては、その他のパラメータが必要になる場合もあります。ファームウェア・プロンプトで「 help ifconfig 」と入力すると、詳細が表示されます。

|===
. ノード3でネットブートを実行します。
+
[cols="35,65"]
|===
| 用途 | 作業 


| FAS/AFF8000 シリーズシステム | netboot\http://web_server_ip/path_to_webaccessible_directory/netboot/kernel` 


| その他すべてのシステム | netboot\http://web_server_ip/path_to_webaccessible_directory/ontap_version_image.tgz` 
|===
+
「 path_to_the_web-accessible_directory 」は、の「 ONTAP_version_image.tgz 」をダウンロードした場所を指します link:prepare_for_netboot.html#man_netboot_Step1["手順 1."] の項で、 netboot_ の準備を参照してください。

+

NOTE: トランクを中断しないでください。

. ブートメニューから、まずオプション*(7) 新しいソフトウェアをインストールする*を選択します。
+
このメニューオプションを選択すると、新しい ONTAP イメージがブートデバイスにダウンロードおよびインストールされます。

+
次のメッセージは無視してください。

+
`This procedure is not supported for Non-Disruptive Upgrade on an HA pair`

+
コントローラのアップグレードではなく、 ONTAP による環境の無停止アップグレードも記録されています。

+

NOTE: 新しいノードを希望するイメージに更新する場合は、必ずネットブートを使用してください。別の方法で新しいコントローラにイメージをインストールすると、正しいイメージがインストールされない場合があります。この問題環境はすべての ONTAP リリースに対応しています。オプションを指定してネットブート手順 を実行する `(7) Install new software` ブートメディアを消去して、同じONTAP バージョンのONTAP を両方のイメージパーティションに配置します。

. 手順を続行するように求められた場合は、 `y`パッケージの入力を求められた場合は、次の URL を入力します。
+
http://web_server_ip/path_to_web-accessible_directory/ontap_version_image.tgz` にアクセスします

. 次の手順を実行します。
+
.. 次のプロンプトが表示されたら 'n' を入力してバックアップ・リカバリをスキップします
+
[listing]
----
Do you want to restore the backup configuration now? {y|n}
----
.. 次のプロンプトが表示されたら 'y' と入力して再起動します
+
[listing]
----
The node must be rebooted to start using the newly installed software. Do you want to reboot now? {y|n}
----
+
コントローラモジュールはリブートしますが、ブートメニューで停止します。これは、ブートデバイスが再フォーマットされたことにより、構成データのリストアが必要なためです。



. [[man_install3_step18]]*(5)メンテナンスモードブート*を選択して、 `5`を入力し、 `y`起動を続行するかどうかを尋ねるプロンプトが表示されたら。
. [[man_install3_step26]] 続行する前に、に進みます link:set_fc_uta_uta2_config_node3.html["ノード 3 で FC または UTA / UTA2 設定を設定します"] ノードの FC ポートまたは UTA / UTA2 ポートに必要な変更を加えるため。
+
これらのセクションで推奨される変更を行ってからノードをリブートし、メンテナンスモードに切り替えます。

. node3 のシステム ID を見つけます。
+
「ディスクショー - A` 」

+
次の例に示すように、ノードのシステム ID 、およびそのディスクに関する情報が表示されます。

+
[listing]
----
 *> disk show -a
 Local System ID: 536881109
 DISK     OWNER                    POOL  SERIAL   HOME          DR
 HOME                                    NUMBER
 -------- -------------            ----- -------- ------------- -------------
 0b.02.23 nst-fas2520-2(536880939) Pool0 KPG2RK6F nst-fas2520-2(536880939)
 0b.02.13 nst-fas2520-2(536880939) Pool0 KPG3DE4F nst-fas2520-2(536880939)
 0b.01.13 nst-fas2520-2(536880939) Pool0 PPG4KLAA nst-fas2520-2(536880939)
 ......
 0a.00.0               (536881109) Pool0 YFKSX6JG              (536881109)
 ......
----
+

NOTE: コマンドを入力すると、「ディスクはありません」というメッセージが表示される場合があります。これはエラーメッセージではないため、手順を続行できます。

. [[man_install3_step21]]ノード1のスペアディスク、ルートに属するディスク、および以前にノード2に再配置されなかったルート以外のアグリゲートを再割り当てします。link:relocate_non_root_aggr_node1_node2.html["ルート以外のアグリゲートを node1 から node2 に再配置します。"] 。
+
システムに共有ディスクがあるかどうかに応じて、適切な形式の「 disk reassign 」コマンドを入力します。

+

NOTE: システムに共有ディスク、ハイブリッドアグリゲート、またはその両方がある場合は、適切なを使用する必要があります `disk reassign` コマンドを次の表に示します。

+
[cols="35,65"]
|===
| ディスクタイプ | 実行するコマンド 


| 共有ディスクの場合 | 'disk reassign -s _node1 _sysid_-d_node3 _sysid_-p _node2 _sysid_` 


| ディスクを共有しない | 'disk reassign -s _node1 _sysid_-d_node3 _sysid_` 
|===
+
`_node1_sysid_`の値には'で取得した情報を使用します link:record_node1_information.html["ノード 1 の情報を記録します"]。`_node3_sysid_`の値を取得するには'sysconfigコマンドを使用します

+

NOTE: -p オプションは ' 共有ディスクが存在する場合にのみ保守モードで必要です

+
disk reassignコマンドは'_node1_sysid_'が現在の所有者であるディスクのみを再割り当てします

+
次のメッセージが表示されます。

+
[listing]
----
Partner node must not be in Takeover mode during disk reassignment from maintenance mode.
Serious problems could result!!
Do not proceed with reassignment if the partner is in takeover mode. Abort reassignment (y/n)?
----
. [man_install3_step29]] 「 n` 」と入力します。
+
次のメッセージが表示されます。

+
[listing]
----
After the node becomes operational, you must perform a takeover and giveback of the HA partner node to ensure disk reassignment is successful.
Do you want to continue (y/n)?
----
. [man_install3_step30]] 「 y 」と入力します
+
次のメッセージが表示されます。

+
[listing]
----
Disk ownership will be updated on all disks previously belonging to Filer with sysid <sysid>.
Do you want to continue (y/n)?
----
. [man_install3_step31]] 「 y 」と入力します。
. [[man_install3_step32]] 外付けディスクがあるシステムから、内蔵ディスクと外付けディスクをサポートするシステム（ AFF A800 システムなど）にアップグレードする場合は、 node1 アグリゲートを root として設定し、 node3 が node1 のルートアグリゲートからブートすることを確認します。
+

WARNING: * 警告 * ：次の手順を記載された順序で実行する必要があります。正しく実行しないと、原因が停止したり、データが失われたりする可能性があります。

+
次の手順は、 node3 を node1 のルートアグリゲートからブートするように設定します。

+
.. node1 アグリゲートの RAID 、プレックス、およびチェックサムの情報を確認します。
+
「 aggr status -r 」

.. node1 アグリゲートのステータスを確認します。
+
「 aggr status 」を入力します

.. 必要に応じて、 node1 アグリゲートをオンラインにします。
+
'aggr_online _root_aggr_from_node1_`

.. node3が元のルートアグリゲートからブートしないようにします。「aggr offline_root_aggr_on_node3」を参照してください
.. node1 ルートアグリゲートを、 node3 の新しいルートアグリゲートとして設定します。
+
「aggr options _aggr_from_node1_root」と入力します

.. ノード 3 のルートアグリゲートがオフラインになっていること、およびノード 1 からテイクオーバーされたディスクのルートアグリゲートがオンラインになっていて root に設定されていることを確認します。
+
「 aggr status 」を入力します

+

NOTE: 前の手順を実行しないと、原因 node3 を内部ルートアグリゲートからブートするか、原因システムで新しいクラスタ構成が存在すると想定するか、あるいはクラスタ構成を特定するように求められる可能性があります。

+
次の例は、コマンドの出力を示しています。



+
[listing]
----
 ---------------------------------------------------------------
      Aggr State               Status          Options
 aggr0_nst_fas8080_15 online   raid_dp, aggr   root, nosnap=on
                               fast zeroed
                               64-bit

   aggr0 offline               raid_dp, aggr   diskroot
                               fast zeroed
                               64-bit
 ----------------------------------------------------------------------
----
. [man_install3_step33]] コントローラとシャーシが 'ha' として構成されていることを確認します
+
「 ha-config show 」

+
次に、 ha-config show コマンドの出力例を示します。

+
[listing]
----
 *> ha-config show
    Chassis HA configuration: ha
    Controller HA configuration: ha
----
+
システムは、 HA ペア構成かスタンドアロン構成かにかかわらず、プログラム可能 ROM （ PROM ）に記録されます。状態は、スタンドアロンシステムまたは HA ペア内のすべてのコンポーネントで同じである必要があります。

+
コントローラとシャーシが「 HA 」として構成されていない場合は、次のコマンドを使用して構成を修正します。

+
「 ha-config modify controller ha 」を参照してください

+
「 ha-config modify chassis ha 」を参照してください

+
MetroCluster 構成の場合は、次のコマンドを使用してコントローラとシャーシを変更します。

+
「 ha-config modify controller mcc 」

+
「 ha-config modify chassis mcc 」

. [man_install3_step34]] ノード 3 のメールボックスを破棄します
+
「マイボックス破壊ローカル」

+
コンソールに次のメッセージが表示されます。

+
[listing]
----
Destroying mailboxes forces a node to create new empty mailboxes, which clears any takeover state, removes all knowledge of out-of-date plexes of mirrored volumes, and will prevent management services from going online in 2-node cluster HA configurations. Are you sure you want to destroy the local mailboxes?
----
. [man_install3_step35]] ローカルメールボックスを破棄することを確認するプロンプトで 'y' を入力します
. [[man_install3_step36]] メンテナンスモードを終了します。
+
「 halt 」

+
ブート環境プロンプトが表示されます。

. [man_install3_step37]] node2 で、システムの日付、時刻、およびタイムゾーンを確認します。
+
「食事」

. [man_install3_step38]] ノード 3 で、ブート環境プロンプトで日付を確認します。
+
「日付」

. [[man_install3_step39]] 必要に応じて、 node3 の日付を設定します。
+
'set date_mm/dd/yyyy_`

. [man_install3_step40]] ノード 3 で、ブート環境のプロンプトで時刻を確認します。
+
「時間」

. [[man_install3_step41] 必要に応じて、 node3 に時間を設定します。
+
'set time_hh:mm:ss_`

. [[man_install3_step42]]パートナーシステムIDが、<<man_install3_step21,手順 21>> -p スイッチの場合:
+
printenv partner-sysid

. [[man_install3_step43] 必要に応じて、 node3 にパートナーシステム ID を設定します。
+
setsetenv partner-sysid_node2 _sysid_`

+
設定を保存します。

+
'aveenv

. [man_install3_step44]] ブート環境プロンプトでブートメニューにアクセスします
+
「 boot_ontap menu

. [man_install3_step45]] ブートメニューで ' プロンプトで '6` を入力して 'option *(6) Update flash from backup config* を選択します
+
次のメッセージが表示されます。

+
[listing]
----
This will replace all flash-based configuration with the last backup to disks. Are you sure you want to continue?:
----
. [[man_install3_step46]] プロンプトで「 y 」と入力します。
+
ブートが正常に続行され、システム ID の不一致を確認するよう求められます。

+

NOTE: 不一致の警告が表示される前にシステムが 2 回リブートする可能性があります。

. [[man_install3_step47]] 次の例に示すように、不一致を確認します。
+
[listing]
----
WARNING: System id mismatch. This usually occurs when replacing CF or NVRAM cards!
Override system id (y|n) ? [n] y
----
+
正常にブートする前に、ノードが 1 回限りのリブートを実行する可能性があります。

. [[man_install3_step48]] node3 にログインします。

