---
sidebar: sidebar 
permalink: upgrade-arl-manual/reboots_panics_power_cycles.html 
keywords: crash, reboot, node1, node2, node3, node4, upgrade 
summary: ONTAP 9.7 以前を実行しているコントローラで ARL を手動でアップグレードする場合、システムがクラッシュするか、パニック状態になるか、電源の再投入が行われる可能性があります。 
---
= リブート、パニック、電源再投入
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
アップグレードの各段階で、システムがクラッシュする（リブート、パニック状態、または電源の再投入）場合があります。これらの問題の解決策は、状況によって異なります。



== ステージ 2 でリブート、パニック、または電源の再投入が発生した場合

クラッシュは、ステージ 2 の前後、またはステージ 2 のアグリゲートをノード 1 からノード 2 に再配置し、ノード 1 が所有するデータ LIF と SAN LIF をノード 2 に移動し、ノード 1 の情報を記録し、ノード 1 を廃棄する前、実行中、またはただちに発生します。



=== HA を有効にして第 2 段階の前にノード 1 またはノード 2 がクラッシュする

ステージ 2 の前にノード 1 またはノード 2 がクラッシュした場合は、再配置されたアグリゲートがなく、 HA 構成が有効なままになります。

.このタスクについて
テイクオーバーとギブバックは正常に実行されます。

.手順
. コンソールで、システムで発行された EMS メッセージを確認し、推奨される対処方法を実行します。
. ノードペアのアップグレード用手順に進みます。




=== HA を有効にして第 2 段階の実行中または直後にノード 1 がクラッシュする

一部または全てのアグリゲートがnode1からnode2に再配置され、HAは引き続き有効になっています。node2は、node1のルートボリュームと、再配置されなかった非ルートアグリゲートをテイクオーバーします。

.このタスクについて
再配置されたアグリゲートの所有権は、ホーム所有者が変更されていないため、テイクオーバーされた非ルートアグリゲートの所有権と同じように見えます。node1 が `waiting for giveback state`に入ると、node2 は node1 の非ルートアグリゲートをすべて返します。

.手順
. 完了link:relocate_non_root_aggr_node1_node2.html#relocate-step1["手順 1."]_非ルート アグリゲートをノード 1 からノード 2 に再配置_ のセクションで再度実行します。
. ノードペアのアップグレード用手順に進みます。




=== HA を無効にすると、ステージ 2 のあとにノード 1 がクラッシュします

node2 はテイクオーバーしませんが、ルート以外のすべてのアグリゲートから引き続きデータを提供しています。

.手順
. ノード 1 を起動します。
. ノードペアのアップグレード用手順に進みます。
+
の出力にいくつかの変更が表示される場合があります。 `storage failover show` コマンドですが、これは一般的なコマンドであり、手順には影響しません。トラブルシューティングのセクションを参照してください link:issues_multiple_stages_of_procedure.html#storage-failover-command["予期しない「 storage failover show 」コマンドの出力が表示されます"]。





=== ステージ 2 の実行中または実行後に、 HA を有効にして node2 に障害が発生する

ノード 1 の一部またはすべてのアグリゲートが node2 に再配置されています。HA が有効になっている。

.このタスクについて
Node1は、node2のすべてのアグリゲートと、node2に再配置していた自身のアグリゲートを引き継ぎます。node2が `Waiting for Giveback`状態になると、node1はnode2のすべてのアグリゲートを返します。

.手順
. 完了link:relocate_non_root_aggr_node1_node2.html#relocate-step1["手順 1."]_非ルート アグリゲートをノード 1 からノード 2 に再配置_ のセクションで再度実行します。
. ノードペアのアップグレード用手順に進みます。




=== ステージ 2 で HA を無効にすると、ノード 2 がクラッシュする

ノード 1 ではテイクオーバーが実行されません。

.手順
. node2 を起動します。
+
node2の起動中に、すべてのアグリゲートでクライアント障害が発生します。

. 残りのノードペアのアップグレード手順に進みます。




== ステージ 3 でリブート、パニック、電源の再投入が発生した場合

ステージ 3 の実行中または実行直後に障害が発生し、ステージ 3 ではノード 1 からノード 3 へのポートのマッピング、ノード 1 とノード 2 に属するデータ LIF と SAN LIF のノード 3 への移動、ノード 2 からノード 3 へのすべてのアグリゲートの再配置が行われます。



=== HA を無効にした状態でステージ 3 が実行され、アグリゲートを再配置する前にノード 2 がクラッシュする

HAが既に無効になっているため、node2がクラッシュしてもnode3は引き継ぎません。

.手順
. node2 を起動します。
+
node2の起動中に、すべてのアグリゲートでクライアント障害が発生します。

. ノードペアのアップグレード用手順に進みます。




=== 一部またはすべてのアグリゲートの再配置後、ステージ 3 でノード 2 がクラッシュする

Node2は、その集約データの一部または全部をNode3に移動しました。Node3は、移動された集約データからデータを提供します。HAは無効になっています。

.このタスクについて
再配置されなかったアグリゲートでクライアントの停止が発生します。

.手順
. node2 を起動します。
. 残りの骨材を再配置するには、link:relocate_non_root_aggr_node2_node3.html#verify-partner-sys-id["手順 1."]を通してlink:relocate_non_root_aggr_node2_node3.html#relocate-step5["手順 5"]「_非ルート アグリゲートをノード 2 からノード 3 に再配置する_」セクション。
. ノードペアのアップグレード用手順に進みます。




=== ステージ 3 でノード 2 からアグリゲートが再配置される前に、ノード 3 がクラッシュした場合

node2 はテイクオーバーしませんが、ルート以外のすべてのアグリゲートから引き続きデータを提供しています。

.手順
. ノード 3 を起動します。
. ノードペアのアップグレード用手順に進みます。




=== アグリゲートの再配置中に、ステージ 3 でノード 3 がクラッシュした場合

node2がアグリゲートをnode3に再配置している最中にnode3がクラッシュした場合、node2は残りのアグリゲートの再配置を中止します。

.このタスクについて
node2 では残りのアグリゲートの処理が続行されますが、 node3 のブート中にすでに node3 に再配置されたアグリゲートでクライアントが停止する可能性があります。

.手順
. ノード 3 を起動します。
. 完了link:relocate_non_root_aggr_node2_node3.html#relocate-step5["手順 5"]_非ルート アグリゲートをノード 2 からノード 3 に再配置する_ セクションで再度実行します。
. ノードペアのアップグレード用手順に進みます。




=== ステージ 3 でクラッシュすると、ノード 3 がブートしない

重大な障害が原因で、ステージ 3 のクラッシュ後に node3 をブートすることはできません。

.ステップ
. テクニカルサポートにお問い合わせください。




=== ステージ 3 のあと、ステージ 5 の前に node2 がクラッシュします

ノード 3 では、すべてのアグリゲートのデータの提供が続行されます。HA ペアが無効になります。

.手順
. node2 を起動します。
. ノードペアのアップグレード用手順に進みます。




=== ステージ 3 の完了後、ステージ 5 の前にノード 3 がクラッシュした場合

ステージ 3 の完了後、ステージ 5 の前にノード 3 がクラッシュした場合。HA ペアが無効になります。

.手順
. ノード 3 を起動します。
+
すべてのアグリゲートでクライアントの停止が発生しています。

. ノードペアのアップグレード用手順に進みます。




== ステージ 5 でリブート、パニック、または電源の再投入が発生した場合

クラッシュは、ステージ 5 、ノード 4 のインストールとブートのステージ、ノード 2 からノード 4 へのポートのマッピング、ノード 2 に属するデータ LIF と SAN LIF のノード 2 からノード 4 への移動、ノード 2 のすべてのアグリゲートのノード 3 からノード 4 への再配置の実行中に発生する可能性があります。



=== ステージ 5 でノード 3 がクラッシュする

ノード 3 の一部またはすべてのアグリゲートが node4 に再配置されている。node4 にはテイクオーバーは行われず、 node3 がすでに再配置されたルート以外のアグリゲートは引き続き提供されます。HA ペアが無効になります。

.このタスクについて
node3 が再度ブートするまでは、残りのアグリゲートが停止している必要があります。

.手順
. ノード 3 を起動します。
. node2 に属していた残りのアグリゲートを再配置します link:relocate_node2_non_root_aggr_node3_node4.html#man_relocate_3_4_Step1["手順 1."] から link:relocate_node2_non_root_aggr_node3_node4.html#step3["手順 3"] セクションの _Relocate node2 のルート以外のアグリゲートを node3 から node4 に再配置する例を次に示します。
. ノードペアのアップグレード用手順に進みます。




=== ステージ 5 でノード 4 がクラッシュした場合

ノード 3 の一部またはすべてのアグリゲートが node4 に再配置されている。node3 は、自身が所有しているルート以外のアグリゲートおよび再配置されていないアグリゲートを引き続き提供します。HA が無効になっています。

.このタスクについて
ノード 4 が再びブートするまで再配置されたルート以外のアグリゲートは停止します。

.手順
. ノード 4 を起動します。
. ノード2に属していた残りのアグリゲートを再度実行して再配置します。link:relocate_node2_non_root_aggr_node3_node4.html#man_relocate_3_4_Step1["手順 1."]を通してlink:relocate_node2_non_root_aggr_node3_node4.html#step3["手順 3"]_node2 の非ルート アグリゲートを node3 から node4 に再配置_。
. ノードペアのアップグレード用手順に進みます。

