---
sidebar: sidebar 
permalink: upgrade-arl-manual/reconfig_index.html 
keywords: reconfigure, fc, switch, layout, RCF, metrocluster 
summary: ONTAP 9.1 以降の場合は、ポートレイアウトを再設定し、 ONTAP 9.7 以前を実行しているコントローラで ARL を手動アップグレードする際に最新の RCF を適用します。 
---
= ONTAP 9.1 以降の FC スイッチレイアウトを再設定します
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
既存の FC スイッチレイアウトが ONTAP 9.1 より前に構成されていた場合は、ポートレイアウトを再構成して、最新のリファレンス構成ファイル（ RCF ）を適用する必要があります。この手順は、 MetroCluster FC 構成にのみ適用されます。

.作業を開始する前に
ファブリックドメイン内の FC スイッチを特定する必要があります。

管理パスワードと FTP サーバまたは SCP サーバへのアクセスが必要です。

.このタスクについて
既存の FC スイッチレイアウトが ONTAP 9.1 より前に構成されたもので、 ONTAP 9.1 以降でサポートされるプラットフォームモデルにアップグレードする場合は、このタスクを実行する必要があります。ONTAP 9.1 以降用に設定された既存のスイッチレイアウトからアップグレードする場合は、 _not_required です。

この手順はシステムを停止せずに実行でき、ディスクが初期化されている場合は約 4 時間で完了します（ラックとスタックは除く）。

.手順
. link:send_custom_asup_message_prior_reconfig_switches.html["カスタム AutoSupport メッセージは、スイッチの再設定前に送信します"]
. link:verify_health_mcc_config.html["MetroCluster 構成の健全性を確認"]
. link:check_mcc_config_errors.html["MetroCluster 構成エラーがないかどうかを確認します"]
. link:persist_disable_switches.html["スイッチを永続的に無効にします"]
. link:determine_new_cabling_layout.html["新しいケーブルレイアウトを決定します"]
. link:apply_RCF_files_recable_switches.html["RCF ファイルを適用し、スイッチを再接続します"]
. link:persist_enable_switches.html["スイッチを永続的に有効にします"]
. link:verify_swtichover_healing_switchback.html["スイッチオーバー、修復、スイッチバックを検証"]

