---
sidebar: sidebar 
permalink: upgrade-arl-manual/relocate_non_root_aggr_node2_node3.html 
keywords: node2, node3, node2, aggregates, autosupport 
summary: node2 の AutoSupport メッセージを送信し、 ONTAP 9.7 以前を実行しているコントローラで node2 の非ルートアグリゲートを手動で ARL アップグレード時にノード 2 に再配置します。 
---
= ルート以外のアグリゲートを node2 から node3 に再配置します。
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
ノード2をノード4に交換する前に、ノード2に関するAutoSupportメッセージを送信し、ノード2で所有されているルート以外のアグリゲートをノード3に再配置する必要があります。


CAUTION: この手順では、アグリゲートをノード3からノード2に再配置しないでください。その結果、アグリゲートがオフラインになり、再配置されたアグリゲートのデータが利用できなくなります。

[[verify-partner-sys-id]]
.手順
. ノード 3 でパートナー システム ID が正しく設定されていることを確認します。
+
.. advanced 権限レベルに切り替えます。
+
「 advanced 」の権限が必要です

.. ノード3のパートナーシステムIDを表示します。
+
`ha interconnect config show -node <node3-node1>`

+
次の例のような出力が表示されます。

+
.例を示します
[%collapsible]
====
[listing]
----
cluster::*> ha interconnect config show -node <node>
  (system ha interconnect config show)

                       Node: node3-node1
          Interconnect Type: RoCE
            Local System ID: <node3-system-id>
          Partner System ID: <node2-system-id>
       Connection Initiator: local
                  Interface: external

Port   IP Address
----   -----------------
e4a-17   0.0.0.0
e4b-18   0.0.0.0
----
====


. ノード3の「パートナーシステムID」が正しくない場合は、次の手順を実行します。
+
.. ノード3を停止します。
+
「 halt 」

.. Loaderプロンプトで、正しい「partner-sysid」の値を設定します。
+
ノード3の「partner-sysid」はノード2のシステムIDで、の出力で確認できます `ha interconnect config show`<<verify-partner-sys-id,手順 1.>>。

.. 設定を保存します。
+
'aveenv

.. Loaderプロンプトで、ノード3をブートメニューでブートします。
+
「 boot_ontap menu

.. ノード3にログインします。


. ノード2のAutoSupportメッセージをNetAppに送信します。
+
`system node autosupport invoke -node <node2> -type all -message "Upgrading <node2> from <platform_old> to <platform_new>"`

. AutoSupport メッセージが送信されたことを確認します。
+
`system node autosupport show -node <node2> -instance`

+
「 Last Subject Sent ：」および「 Last Time Sent ：」のフィールドには、最後に送信されたメッセージのメッセージタイトルと、メッセージが送信された時刻が含まれています。

. [[relocate-step5]]ルート以外のアグリゲートを再配置します。
+
.. 権限レベルを advanced に設定します。
+
「 advanced 」の権限が必要です

.. node2 が所有するアグリゲートを表示します。
+
`storage aggregate show -owner-name <node2>`

.. アグリゲートの再配置を開始する：
+
`storage aggregate relocation start -node <node2> -destination <node3> -aggregate-list * -ndo-controller-upgrade true`

+

NOTE: コマンドは、ルート以外のアグリゲートのみを特定します。

.. プロンプトが表示されたら、「 y 」と入力します。
+
再配置はバックグラウンドで実行されます。アグリゲートの再配置には数秒から数分かかる場合があります。この時間には、クライアントの停止部分と停止部分の両方が含まれます。コマンドでは、オフラインまたは制限されたアグリゲートは再配置されません。

.. admin 権限レベルに戻ります。
+
「特権管理者」



. node2 の再配置のステータスを確認します。
+
`storage aggregate relocation show -node <node2>`

+
再配置後のアグリゲートについては、出力に「done」と表示されます。

+

NOTE: node2 に所有されているすべてのアグリゲートが node3 に再配置されてから次の手順に進む必要があります。

. 次のいずれかを実行します。
+
[cols="35,65"]
|===
| 再配置する対象 | 作業 


| すべてのアグリゲートが完了しました | にアクセスします。 


| アグリゲートに障害が発生したか、拒否された  a| 
.. 詳細なステータスメッセージを表示します。
+
「 storage aggregate show -instance 」のように表示されます

+
EMS ログで必要な対処方法を確認することもできます。

+

NOTE: event log showコマンドを実行すると'発生したエラーが表示されます

.. 対処方法を実行します。
.. 権限レベルを advanced に設定します。
+
「 advanced 」の権限が必要です

.. 障害が発生したアグリゲートまたは拒否されたアグリゲートを
+
`storage aggregate relocation start -node <node2> -destination <node3> -aggregate-list * -ndo-controllerupgrade true`

.. プロンプトが表示されたら、「 y 」と入力します。
.. admin 権限レベルに戻ります。
+
「特権管理者」



必要に応じて、次のいずれかの方法で強制的に再配置を実行できます。

** 拒否のチェックを無視する：
+
「 storage aggregate relocation start -override-vetoes true -nd-controller-upgrade

** 送信先チェックを無効にする：
+
「 storage aggregate relocation start -override-destination-checks true -ndocontroller -upgrade 」を実行します



storage aggregate relocation コマンドの詳細については、を参照してください link:other_references.html["参考資料"] CLI_ および ONTAP 9 コマンド：マニュアルページリファレンス _ を使用してディスクおよびアグリゲートの管理にリンクするには、次の手順を実行します。

|===
. [man_relocate_2_3_step8] ルート以外のアグリゲートがすべてノード 3 でオンラインになっていることを確認します。
+
`storage aggregate show -node <node3> -state offline -root false`

+
オフラインになったアグリゲートや外部になったアグリゲートがある場合は、各アグリゲートを 1 つずつオンラインにする必要があります。

+
`storage aggregate online -aggregate <aggregate_name>`

. ノード 3 ですべてのボリュームがオンラインになっていることを確認します。
+
`volume show -node <node3> -state offline`

+
ノード 3 でオフラインになっているボリュームがある場合は、各ボリュームについて 1 回、オンラインにする必要があります。

+
`volume online -vserver <Vserver-name> -volume <volume-name>`

. node2がルート以外のオンラインのアグリゲートを所有していないことを確認します。
+
`storage aggregate show -owner-name <node2> -ha-policy sfo -state online`

+
ルート以外のオンラインアグリゲートがすべて node3 にすでに再配置されているため、コマンドの出力にルート以外のオンラインアグリゲートが表示されないようにする必要があります。


