---
sidebar: sidebar 
permalink: upgrade-arl-manual/set_fc_uta_uta2_config_node4.html 
keywords: fc configuration, uta configuration, uta2 configuration, configure FC ports, uta/uta2 card, node4, target, adapter, ports 
summary: ONTAP 9.7 以前を実行しているコントローラで ARL を手動でアップグレードする際に、ノード 4 のオンボード FC ポート、 UTA / UTA2 ポート、または UTA / UTA2 カードを設定します。 
---
= ノード 4 で FC または UTA / UTA2 設定を設定します
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
ノード 4 でオンボードの FC ポート、オンボードのユニファイドターゲットアダプタ（ UTA / UTA2 ）ポート、または UTA / UTA2 カードが使用されている場合は、残りの手順を完了する前に設定する必要があります。

.このタスクについて
完了する必要がある場合があります <<ノード 4 の FC ポートを設定します>>、 <<ノード 4 の UTA / UTA2 ポートを確認して設定してください>>、または両方のセクション。

ノード 4 にオンボードの FC ポート、オンボード UTA / UTA2 ポート、または UTA / UTA2 カードがなく、ストレージディスクが搭載されたシステムをアップグレードする場合は、に進みます link:map_ports_node2_node4.html["node2 のポートを node4 にマッピングします"]。

ただし、 V シリーズシステムまたは FlexArray 仮想化ソフトウェアがインストールされていて、ストレージアレイに接続されている場合に、ノード 4 にオンボードの FC ポート、オンボード UTA / UTA2 ポート、 UTA / UTA2 カードがないときは、 _Install and boot node4 セクションに戻って再開する必要があります link:install_boot_node4.html#man_install4_Step9["手順 9"]。ノード 4 に十分なラックスペースがあることを確認してください。node4 が node2 とは別のシャーシにある場合は、 node3 と同じ場所に node4 を配置できます。node2 と node4 が同じシャーシにある場合は、 node4 が適切なラックの場所にすでに存在しているとします。

.選択肢
* <<ノード 4 の FC ポートを設定します>>
* <<ノード 4 の UTA / UTA2 ポートを確認して設定してください>>




== ノード 4 の FC ポートを設定します

ノード 4 にオンボードまたは FC アダプタのいずれかの FC ポートがある場合は、ポートが事前に構成されていないため、ノードを稼働状態にする前にポートの設定を行う必要があります。ポートが設定されていないと、サービスが停止する可能性があります。

.作業を開始する前に
セクションに保存した node2 の FC ポート設定の値を確認しておく必要があります link:prepare_nodes_for_upgrade.html["ノードをアップグレードする準備をします"]。

.このタスクについて
システムに FC 構成がない場合は、このセクションをスキップしてかまいません。システムにオンボード UTA / UTA2 ポートまたは UTA / UTA2 アダプタが搭載されている場合は、で設定します <<ノード 4 の UTA / UTA2 ポートを確認して設定してください>>。


IMPORTANT: システムにストレージディスクがある場合は、クラスタプロンプトでこのセクションのコマンドを入力する必要があります。V シリーズシステムまたは FlexArray 仮想化ソフトウェアがストレージアレイに接続されたシステムの場合は、このセクションのメンテナンスモードでコマンドを入力します。

.手順
. 次のいずれかを実行します。
+
[cols="35,65"]
|===
| アップグレードするシステム | 次に、 


| ストレージディスクがあります | に進みます <<man_config_4_Step5,手順 5>>。 


| は、 V シリーズシステムまたは FlexArray 仮想化ソフトウェアを搭載し、ストレージアレイに接続されています | に進みます <<man_config_4_Step2,手順 2>>。 
|===
. [[man_config_4_Step2]] メンテナンスモードにアクセスします。
+
「 boot_ontap maint 」を使用してください

. 次のいずれかを実行します。
+
[cols="35,65"]
|===
| アップグレードするシステム | 次に、 


| ストレージディスクがあります | 「 system node hardware unified-connect show 」を参照してください 


| は、 V シリーズシステムまたは FlexArray 仮想化ソフトウェアを搭載し、ストレージアレイに接続されています | ucadmin show 
|===
+
システムには、システム上のすべての FC アダプタと統合ネットワークアダプタに関する情報が表示されます。

. 新しいノードの FC 設定を、元のノードで取り込んだ設定と比較します。
. [[man_config_4_Step5]] 次のいずれかの操作を行います。
+
[cols="35,65"]
|===
| アップグレードするシステム | 次に、 


| ストレージディスクがあります  a| 
必要に応じて、ノード 4 の FC ポートを変更します。

** ターゲットポートをプログラムする場合：


system node hardware unified-connect modify-type |-t target-adapter_port_name_`

** イニシエータポートをプログラミングする場合：


'system node unified-connect modify type|-t initiator-adapter_port_name_`

`-type ` は FC4 のタイプ、ターゲットまたはイニシエータである。



| は、 V シリーズシステムまたは FlexArray 仮想化ソフトウェアを搭載し、ストレージアレイに接続されています  a| 
必要に応じて、ノード 4 の FC ポートを変更します。

`ucadmin modify -m fc -t initiator -f _adapter_port_name_`

`-t` は、FC4タイプ、ターゲット、イニシエータです。


NOTE: FCポートはイニシエータとしてプログラムする必要があります。

|===
. 次のいずれかを実行します。
+
[cols="35,65"]
|===
| アップグレードするシステム | 次に、 


| ストレージディスクがあります | 次のコマンドを入力し、出力を調べて、新しい設定を確認します。 'system node unified-connect show' 


| は、 V シリーズシステムまたは FlexArray 仮想化ソフトウェアを搭載し、ストレージアレイに接続されています | 次のコマンドを入力し、出力を確認して、新しい設定を確認します。 ucadmin show 
|===
. 次のいずれかを実行します。
+
[cols="35,65"]
|===
| 新しいノードのデフォルトの FC 設定 | 次に、 


| 元のノードでキャプチャしたのと同じです | に進みます <<man_config_4_Step11,手順 11>>。 


| 元のノードでキャプチャしたものとは異なります | に進みます <<man_config_4_Step8,手順 8.>>。 
|===
. [[man_config_4_Step8] メンテナンスモードを終了します：
+
「 halt 」

. コマンドを入力したら、ブート環境のプロンプトでシステムが停止するまで待ちます。
. 次のいずれかを実行します。
+
[cols="35,65"]
|===
| アップグレードするシステム | 次に、 


| は、 V シリーズシステムであるか、 Data ONTAP 8.3.0 以降を実行する FlexArray 仮想化ソフトウェアがインストールされています | ブート環境プロンプトで「 boot_ontap maint 」というコマンドを入力し、保守モードにアクセスします 


| は、 V シリーズシステムではなく、 FlexArray 仮想化ソフトウェアもありません | ブート環境プロンプトで「 boot_ontap 」と入力し、 node4 をブートします 
|===
. [[man_config_4_Step11]] 次のいずれかの操作を行います。
+
[cols="35,65"]
|===
| アップグレードするシステム | 次に、 


| ストレージディスクがあります  a| 
** に進みます <<ノード 4 の UTA / UTA2 ポートを確認して設定してください>> ノード 4 に UTA / UTA2A カードまたは UTA / UTA2 オンボードポートがある場合
** セクションをスキップして、に進みます link:map_ports_node2_node4.html["node2 のポートを node4 にマッピングします"] ノード 4 に UTA / UTA2 カードまたは UTA / UTA2 オンボードポートがない場合




| は、 V シリーズシステムまたは FlexArray 仮想化ソフトウェアを搭載し、ストレージアレイに接続されています  a| 
** に進みます <<ノード 4 の UTA / UTA2 ポートを確認して設定してください>> ノード 4 に UTA / UTA2 カードまたは UTA / UTA2 オンボードポートがある場合
** node4 に UTA / UTA2 カードまたは UTA / UTA2 オンボードポートがない場合は、 section_Check をスキップして UTA / UTA2 ポートを設定し、 node4 に戻ってブートノードを再開します link:install_boot_node4.html#man_install4_Step9["手順 9"]。


|===




== ノード 4 の UTA / UTA2 ポートを確認して設定してください

ノード 4 でオンボード UTA / UTA2 ポートまたは UTA / UTA2A カードが使用されている場合は、アップグレードしたシステムの使用方法に応じて、ポートの設定を確認して設定する必要があります。

.作業を開始する前に
UTA / UTA2 ポートに対応する正しい SFP+ モジュールが必要です。

.このタスクについて
UTA / UTA2 ポートは、ネイティブの FC モードまたは UTA / UT2A モードに設定できます。FC モードは FC イニシエータと FC ターゲットをサポートします。 UTA / UTA2 モードを使用すると、 NIC と FCoE の同時トラフィックで同じ 10GbE SFP+ インターフェイスを共有し、 FC ターゲットをサポートすることができます。


NOTE: ネットアップのマーケティング資料では、 UTA2 という用語を CNA アダプタとポートという意味で使用している場合があります。ただし、 CLI では CNA という用語が使用されます。

UTA / UTA2 ポートはアダプタまたはコントローラ上に次の構成で配置されます。

* UTA / UTA2 カードは、コントローラと同時に注文しても、希望するパーソナリティを持つ未設定の状態で出荷されます。
* コントローラとは別に発注した UTA / UTA2 カードは、デフォルトの FC ターゲットパーソナリティとして出荷されます。
* 新しいコントローラのオンボード UTA / UTA2 ポートは、要求したパーソナリティを持つように（出荷前に）設定されています。


ただし、ノード 4 の UTA / UTA2 ポートの設定を確認し、必要に応じて変更することができます。

* 注意 * ：ストレージディスクがある場合は、メンテナンスモードに指示されていないかぎり、クラスタプロンプトでこのセクションのコマンドを入力します。ストレージアレイに接続された MetroCluster FC システム、 V シリーズシステム、または FlexArray 仮想化ソフトウェアを搭載したシステムがある場合、 UTA / UTA2 ポートを設定するにはメンテナンスモードにする必要があります。

.手順
. ノード 4 で次のいずれかのコマンドを使用して、ポートが現在どのように設定されているかを確認します。
+
[cols="35,65"]
|===
| システムの状態 | 次に、 


| ストレージディスクがあります | 「 system node hardware unified-connect show 」を参照してください 


| は、 V シリーズシステムまたは FlexArray 仮想化ソフトウェアを搭載し、ストレージアレイに接続されています | ucadmin show 
|===
+
次の例のような出力が表示されます。

+
....
*> ucadmin show
                Current  Current    Pending   Pending   Admin
Node   Adapter  Mode     Type       Mode      Type      Status
----   -------  ---      ---------  -------   --------  -------
f-a    0e       fc       initiator  -          -        online
f-a    0f       fc       initiator  -          -        online
f-a    0g       cna      target     -          -        online
f-a    0h       cna      target     -          -        online
f-a    0e       fc       initiator  -          -        online
f-a    0f       fc       initiator  -          -        online
f-a    0g       cna      target     -          -        online
f-a    0h       cna      target     -          -        online
*>
....
. 現在の SFP+ モジュールが目的の用途と一致しない場合は、正しい SFP+ モジュールに交換します。
+
ネットアップの担当者に連絡して、正しい SFP+ モジュールを入手します。

. 「 system node hardware unified-connect show 」コマンドと「 ucadmin show 」コマンドの出力を調べ、 UTA / UTA2 ポートに希望するパーソナリティが設定されているかどうかを確認します。
. 次のいずれかを実行します。
+
[cols="35,65"]
|===
| CNA ポートの状況 | 作業 


| 希望するパーソナリティがない | に進みます <<man_check_4_Step5,手順 5>>。 


| あなたがほしい人格を持っている | 手順 5 から 12 を省略して、に進みます <<man_check_4_Step13,手順 13>>。 
|===
. [[man_check_4_Step5]] 次のいずれかの操作を行います。
+
[cols="35,65"]
|===
| システムの状態 | 作業 


| ストレージディスクがあり、 Data ONTAP 8.3 を実行している | node4 をブートし、メンテナンスモードに入ります。「 boot_ontap maint 」と入力します 


| は、 V シリーズシステムまたは FlexArray 仮想化ソフトウェアを搭載し、ストレージアレイに接続されています | に進みます <<man_check_4_Step6,手順 6>>。すでにメンテナンスモードになっている必要があります。 
|===
. [[man_check_4_Step6]] 次のいずれかの操作を行います。
+
[cols="35,65"]
|===
| を設定する場合 | 作業 


| UTA / UTA2A カードのポート | に進みます <<man_check_4_Step7,手順 7>>。 


| オンボードの UTA/UTA2 ポート | 手順 7 を省略して、に進みます <<man_check_4_Step8,手順 8>>。 
|===
. [[man_check_4_Step7] アダプタがイニシエータモードの場合、 UTA / UTA2 ポートがオンラインの場合は、 UTA / UTA2 ポートをオフラインにします。
+
storage disable adapter_adapter_adapter_adapter_name_`

+
ターゲットモードのアダプタは、メンテナンスモードで自動的にオフラインになります。

. [[man_check_4_Step8] 現在の設定が目的の使用方法と一致しない場合は、次のコマンドを入力して必要に応じて設定を変更します。
+
ucadmin modify -m fc | cna-t initiator | target_adapter_name_`

+
** 「 -m' 」はパーソナリティ・モードである FC または 10 GbE UTA です。
** `-t` は FC4 のタイプで ' ターゲットまたはイニシエータです


+

NOTE: テープドライブおよび FlexArray 仮想化システムには、 FC イニシエータを使用する必要があります。SAN クライアントには FC ターゲットを使用する必要があります。

. 次のコマンドを入力し、出力を確認して、設定を確認します。
+
ucadmin show

. 次のいずれかを実行します。
+
[cols="35,65"]
|===
| システムの状態 | 作業 


| ストレージディスクがあります  a| 
.. 次のコマンドを入力します。
+
「 halt 」

+
ブート環境プロンプトが表示されます。

.. 次のコマンドを入力します。
+
「 boot_ontap 」





| は、 V シリーズシステムまたは FlexArray 仮想化ソフトウェアを搭載したストレージアレイに接続され、 Data ONTAP 8.3 を実行しているシステムです | 保守モードで再起動します（「 boot_ontap maint 」） 
|===
. 設定を確認します。
+
[cols="35,65"]
|===
| システムの状態 | 作業 


| ストレージディスクがあります | 次のコマンドを入力します。 'system node hardware unified-connect show' 


| は、 V シリーズシステムまたは FlexArray 仮想化ソフトウェアを搭載し、ストレージアレイに接続されています | 次のコマンドを入力します。 ucadmin show 
|===
+
次の例の出力では ' アダプタ「 1b 」の FC4 タイプがイニシエータに変更されており ' アダプタ「 2a 」と「 2b 」のモードが CNA に変更されています

+
[listing]
----
cluster1::> system node hardware unified-connect show
               Current  Current   Pending  Pending    Admin
Node  Adapter  Mode     Type      Mode     Type       Status
----  -------  -------  --------- -------  -------    -----
f-a    1a      fc       initiator -        -          online
f-a    1b      fc       target    -        initiator  online
f-a    2a      fc       target    cna      -          online
f-a    2b      fc       target    cna      -          online
4 entries were displayed.
----
+
[listing]
----
*> ucadmin show
               Current Current   Pending  Pending    Admin
Node  Adapter  Mode    Type      Mode     Type       Status
----  -------  ------- --------- -------  -------    -----
f-a    1a      fc      initiator -        -          online
f-a    1b      fc      target    -        initiator  online
f-a    2a      fc      target    cna      -          online
f-a    2b      fc      target    cna      -          online
4 entries were displayed.
*>
----
. 次のいずれかのコマンドをポートごとに 1 回入力して、ターゲットポートをオンラインにします。
+
[cols="35,65"]
|===
| システムの状態 | 作業 


| ストレージディスクがあります | 「network fcp adapter modify -node node_name --adapter_adapter_adapter_adapter_name_-state up」の形式で指定します 


| は、 V シリーズシステムまたは FlexArray 仮想化ソフトウェアを搭載し、ストレージアレイに接続されています | 'fcp config_adapter_name_up' 
|===
. [[man_check_4_Step13]] ポートをケーブル接続します。
. 次のいずれかを実行します。
+
[cols="35,65"]
|===
| システムの状態 | 作業 


| ストレージディスクがあります | に進みます link:map_ports_node2_node4.html["node2 のポートを node4 にマッピングします"]。 


| は、 V シリーズシステムまたは FlexArray 仮想化ソフトウェアを搭載し、ストレージアレイに接続されています | section_Install および boot node4 _ に戻り、のセクションを再開します link:install_boot_node4.html#man_install4_Step9["手順 9"]。 
|===

