---
sidebar: sidebar 
permalink: upgrade-arl-manual/set_up_storage_encryption_new_controller.html 
keywords: set up, setup, storage encryption, new, controller, module 
summary: 必要に応じて、 ONTAP 9.7 以前を実行しているコントローラでストレージ暗号化を設定し、 SSL 証明書をインストールし、 ARL を手動でアップグレードする際にキー管理サーバをセットアップします。 
---
= 新しいコントローラモジュールで Storage Encryption をセットアップします
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
交換したコントローラまたは新しいコントローラの HA パートナーで Storage Encryption が使用されている場合は、 SSL 証明書のインストールやキー管理サーバのセットアップなど、新しいコントローラモジュールを Storage Encryption 用に設定する必要があります。

この手順には、新しいコントローラモジュールで実行する手順が含まれています。コマンドは正しいノードで入力する必要があります。

.手順
. キー管理サーバがまだ使用可能であり、ステータスと認証キー情報が正しいことを確認します。
+
「 securitykey-manager show -status 」

+
「セキュリティキーマネージャクエリー」

. 前の手順で確認したキー管理サーバを、新しいコントローラのキー管理サーバのリストに追加します。
+
.. キー管理サーバを追加します。
+
「 securitykey-manager-add <key_manager_server_ip_address >` 」

.. リストされている各キー管理サーバについて、同じ手順を繰り返します。
+
最大 4 台のキー管理サーバをリンクできます。

.. キー管理サーバが正常に追加されたことを確認します。
+
「 securitykey -manager show 」を参照してください



. 新しいコントローラモジュールで、キー管理セットアップウィザードを実行して、キー管理サーバをセットアップしてインストールします。
+
既存のコントローラモジュールと同じキー管理サーバをインストールする必要があります。

+
.. 新しいノードでキー管理サーバセットアップウィザードを起動します。
+
「 securitykey-manager setup -node <new_controller_name>` 」のように指定します

.. ウィザードの手順に従って、キー管理サーバを設定します。


. リンクされたすべてのキー管理サーバから新しいノードに認証キーをリストアします。
+
「 securitykey-manager restore -node <new_controller_name>` 」のように指定します


