---
sidebar: sidebar 
permalink: upgrade-arl-manual/set_up_netapp_encryption_on_new_controller.html 
keywords: set up, netapp volume encryption, encryption, controller, module 
summary: 必要に応じて、 ONTAP 9.7 以前を実行しているコントローラで ARL を手動でアップグレードする際に、 NVE 用の新しいコントローラモジュールを設定します。 
---
= 新しいコントローラモジュールで NetApp Volume Encryption をセットアップします
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
交換したコントローラまたは新しいコントローラの HA パートナーが NetApp Volume Encryption （ NVE ）を使用している場合は、新しいコントローラモジュールを NVE 用に設定する必要があります。

この手順には、新しいコントローラモジュールで実行する手順が含まれています。コマンドは正しいノードで入力する必要があります。

.手順
. キー管理サーバがまだ使用可能であり、ステータスと認証キー情報が正しいことを確認します。
+
[cols="35,65"]
|===
| この ONTAP バージョンの場合 ... | 使用するコマンド 


| ONTAP 9.6 または 9.7 | 「 securitykey manager key query -node node 」を参照してください 


| ONTAP 9.5 以前 | 「 securitykey -manager key show 」を参照してください 
|===
. 前の手順で確認したキー管理サーバを新しいコントローラのキー管理サーバリストに追加します。
+
.. 次のコマンドを使用して、キー管理サーバを追加します。
+
「 securitykey-manager-add <key_manager_server_ip_address >` 」

.. リストされている各キー管理サーバについて、同じ手順を繰り返します。最大 4 台のキー管理サーバをリンクできます。
.. 次のコマンドを使用して、キー管理サーバが正常に追加されたことを確認します。
+
「 securitykey -manager show 」を参照してください



. 新しいコントローラモジュールで、キー管理セットアップウィザードを実行して、キー管理サーバをセットアップしてインストールします。
+
既存のコントローラモジュールと同じキー管理サーバをインストールする必要があります。

+
.. 次のコマンドを使用して、新しいノードでキー管理サーバセットアップウィザードを起動します。
+
「 securitykey-manager setup -node <new_controller_name>` 」のように指定します

.. ウィザードの手順に従って、キー管理サーバを設定します。


. リンクされたすべてのキー管理サーバから新しいノードに認証キーをリストアします。
+
** 外部キーマネージャ（ EKD ）の認証を復元します。
+
「セキュリティキーマネージャの外部リストア」

+
このコマンドには、オンボードキーマネージャ（ OKM ）のパスフレーズが必要です

** OKM の認証をリストアします：
+
[cols="35,65"]
|===
| この ONTAP バージョンの場合 ... | 使用するコマンド 


| その他すべての ONTAP バージョン | 「セキュリティキーマネージャオンボード同期」 


| ONTAP 9.5 | 「 securitykey-manager setup -node <node_name >` 」のように指定します 
|===




認証キーを使用できなかったか、外部キー管理サーバにアクセスできなかったためにボリュームがオフラインになっていないかを確認します。次のコマンドを使用して、ボリュームをオンラインに戻します。

「 volume online 」と入力します
