---
sidebar: sidebar 
permalink: upgrade-arl-auto-app/decide_to_use_the_aggregate_relocation_guide.html 
keywords: deciding, aggregate, relocation, content, storage, controllers, administrators, ontap, ha, high, availability 
summary: 'ONTAP 9.8 以降を実行するコントローラをアップグレードするために ARL を使用するかどうかを決定するには "system controller replace" コマンドを使用します' 
---
= アグリゲートの再配置手順を使用するかどうかを決定します
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
このコンテンツでは、既存のデータとディスクを残したまま、HAペアのストレージコントローラを新しいコントローラにアップグレードする方法について説明します。これは複雑な手順であり、経験豊富な管理者のみが使用する必要があります。

このコンテンツは、次のような状況で使用できます。

* ONTAP 9.8 以降を実行している。
* 新しいコントローラを新しい HA ペアとしてクラスタに追加し、ボリューム移動を使用してデータを移行する必要はありません。
* ONTAP の管理経験があり、 diagnostic 権限モードで作業する場合のリスクが十分にあります。
* MetroCluster 構成をアップグレードする場合は、 4 ノード以上の FC 構成になり、すべてのノードで ONTAP 9.8 以降が実行されている必要があります。
+
MetroCluster IP 構成のアップグレードについては、を参照してください link:other_references.html["参考資料"] MetroCluster アップグレードおよび Expansion コンテンツにリンクするには、次の手順を実行します。




NOTE: この手順 では、NetApp Storage Encryption（NSE）、NetApp Volume Encryption（NVE）、およびNetApp Aggregate Encryption（NAE）を使用できます。

[[sys_commands _98_supported_systems]] 次の表は、コントローラのアップグレードでサポートされるモデルマトリックスを示しています。

|===
| 古いコントローラ | 交換用コントローラ 


| FAS8020 ^3^、FAS8040 ^3^、FAS8060、FAS8080 | FAS8200 、 FAS8300 、 FAS8700 、 FAS9000 


| FAS8060 ^4^、FAS8080 ^4^ | FAS9500 


| AFF8020^3^、AFF8040^3^、AFF8060、AFF8080を参照してください | AFF A300 、 AFF A400 、 AFF A700 、 AFF A800^1 


| AFF8060 ^4^、AFF8080 ^4^ | AFF A900 の略 


| FAS8200 | FAS8300 ^2^、FAS8700、FAS9000、FAS9500 


| FAS8300、FAS8700、FAS9000 | FAS9500 


| AFF A300 | AFF A400 ^2^、AFF A700、AFF A800^1 ^、AFF A900 


| AFF A320 ^4^ | AFF A400 


| AFF A400 、 AFF A700 | AFF A900 の略 
|===

NOTE: コントローラのアップグレードモデルの組み合わせが上記の表にない場合は、テクニカルサポートにお問い合わせください。

^1 AFF A800 システムに必要な追加手順については、セクションの「 A800 」を参照する手順に進んでください link:set_fc_or_uta_uta2_config_on_node3.html#auto_check3_step23["ノード 3 の UTA / UTA2 ポートを確認して設定し、手順 23 を実行します"]または link:set_fc_or_uta_uta2_config_node4.html#auto_check_4_step23["ノード 4 の UTA / UTA2 ポートの確認と設定、手順 23"]。

^2^ AFF A300からAFF A400またはFAS8200を2ノードスイッチレスクラスタ構成でFAS8300システムにアップグレードする場合は、コントローラのアップグレード用の一時的なクラスタポートを選択する必要があります。AFF A400 および FAS8300 システムは、イーサネットバンドルとして、メザニンカードポートはイーサネットタイプ、 FC タイプの FC バンドルとして、 2 種類の構成で提供されます。

* AFF A400 または FAS8300 では、イーサネットタイプの構成の場合、 2 つのメザニンポートのいずれかを一時的なクラスタポートとして使用できます。
* AFF A400 または FC タイプの構成で FAS8300 を使用する場合は、 4 ポートの 10GbE ネットワークインターフェイスカード（パーツ番号 X1147A ）を追加して一時的なクラスタポートを提供する必要があります。
* 一時的なクラスタポートを使用したコントローラのアップグレードが完了したら、クラスタ LIF を無停止で e3a および e3b 、 AFF A400 システムの 100GbE ポート、 FAS8300 システムの e0c および e0d 、 100GbE ポートに移行できます。


^3FAS8020、FAS8040、AFF8020、およびAFF8040のシステムを上記の表のターゲット交換コントローラにアップグレードする場合、交換用コントローラが古いコントローラと同じONTAP バージョンを実行している必要があります。FAS8020、FAS8040、AFF8020、およびAFF8040のシステムは、ONTAP 9.8以降のONTAP バージョンをサポートしていません。

^4^次の表に、これらのコントローラアップグレードの組み合わせでサポートされる最小ONTAP バージョンとそれ以降のバージョンを示します。

[cols="20,30,20,30"]
|===
2+| 古いコントローラ 2+| 交換用コントローラ 


| システム | ONTAP バージョン | システム | ONTAP バージョン 


| AFF A320 | 9.9.1以降 | AFF A400 | 9.9.1以降 


| AFF8060の場合 | 9.8P13以降のパッチ | AFF A900 の略 | 9.10.1から9.12.1 


| AFF8080 | 9.8P10以降のパッチ | AFF A900 の略 | 9.10.1から9.12.1 


| FAS8060 | 9.8P13以降のパッチ | FAS9500 | 9.10.1P3～9.12.1 


| FAS8080 | 9.8P12以降のパッチ | FAS9500 | 9.10.1P3～9.12.1 
|===
[NOTE]
====
上記の表にあるアップグレードの組み合わせについては、次の点に注意してください。

* 既存のコントローラと交換用コントローラで同じバージョンのONTAP を使用する必要はありません。ONTAP ソフトウェアのアップグレードは、コントローラのアップグレード時に実行されます。
* アップグレードするときは、サポートされているONTAP バージョンとパッチレベルで交換用コントローラを取り付ける必要があります。
* 手順 を起動して最初のノードをアップグレードしたあとに、コントローラのアップグレードをキャンセルまたは取り消すことはできません。


====
コントローラハードウェアを別の方法でアップグレードして、ボリュームの移動を希望する場合は、を参照してください link:other_references.html["参考資料"] をクリックして、ボリュームまたは storage _ を移動して _ Upgrade にリンクします。

を参照してください link:other_references.html["参考資料"] から ONTAP 9 ドキュメントセンターにリンクして、 ONTAP 9 製品ドキュメントにアクセスできます。
