---
sidebar: sidebar 
permalink: upgrade-arl-auto-app/decide_to_use_the_aggregate_relocation_guide.html 
keywords: deciding, aggregate, relocation, content, storage, controllers, administrators, ontap, ha, high, availability 
summary: 'ONTAP 9.8 以降を実行するコントローラをアップグレードするために ARL を使用するかどうかを決定するには "system controller replace" コマンドを使用します' 
---
= この集約再配置手順を使用するかどうかを決定します
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
コントローラハードウェアをアップグレードするには、アグリゲート再配置（ARL）の方法が複数あります。この手順では、ONTAP 9.8以降を実行しているシステムで、「システムコントローラ置換コマンド」を使用してアグリゲート再配置（ARL）を行い、コントローラハードウェアをアップグレードする方法について説明します。この複雑な手順は、経験豊富なONTAP管理者のみが実行できます。

この ARL 手順がコントローラ ハードウェアのアップグレードに適しているかどうかを判断するには、サポートされているアップグレードについて次の状況をすべて確認する必要があります。

* ONTAP 9.8以降を実行している。
* 新しいコントローラを新しいHAペアとしてクラスタに追加したり、ボリューム移動を使用してデータを移行したりすることはありません。
* ONTAPの管理経験があり、diagnostic権限モードで作業する場合のリスクを十分に理解していること。
* MetroCluster構成をアップグレードする場合は、4ノード以上のFC構成で、すべてのノードでONTAP 9.8以降が実行されています。
+
MetroCluster IP構成のアップグレードについては、MetroCluster Upgrade and Expansion_へのリンクを参照してくださいlink:other_references.html["参考資料"]。



[NOTE]
====
* AFF A800やAFF C800など、同じシャーシ内のコントローラモジュールを交換してシステムをアップグレードする場合、 NetApp、link:../upgrade-arl-auto-in-chassis/index.html["ARLを使用してコントローラモデルをアップグレードし、既存のシステムシャーシとディスクを維持します。"] 。この ARL 手順には、アップグレード手順中にコントローラを取り外したり取り付けたりするときに、内部ディスクがシャーシ内で安全な状態を保つための手順が含まれています。
+
link:../upgrade-arl-auto-in-chassis/decide-to-use-the-aggregate-relocation-guide.html#supported-systems-in-chassis["既存のシステムシャーシとディスクを維持しながら、ARLを使用してサポートされているシステムアップグレードの組み合わせについて学習します。"]。

* この手順 では、NetApp Storage Encryption（NSE）、NetApp Volume Encryption（NVE）、およびNetApp Aggregate Encryption（NAE）を使用できます。


====


== サポートされているシステムアップグレードの組み合わせ

次の表は、この ARL 手順を使用してコントローラのアップグレードを実行する場合にサポートされるシステム マトリックスを示しています。

|===
| 古いコントローラ | 交換用コントローラ 


| FAS8020 ^3^、FAS8040 ^3^、FAS8060、FAS8080 | FAS8200 、 FAS8300 、 FAS8700 、 FAS9000 


| FAS8060 ^4^、FAS8080 ^4^ | FAS9500 


| AFF8020^3^、AFF8040^3^、AFF8060、AFF8080を参照してください | AFF A300 、 AFF A400 、 AFF A700 、 AFF A800^1 


| AFF8060 ^4^、AFF8080 ^4^ | AFF A900 の略 


| FAS8200 | FAS8300 ^2^、FAS8700、FAS9000、FAS9500 


| FAS8300、FAS8700、FAS9000 | FAS9500 


| AFF A300 | AFF A400 ^2^、AFF A700、AFF A800^1 ^、AFF A900 


| AFF A320 ^4^ | AFF A400 


| AFF A400 、 AFF A700 | AFF A900 の略 
|===

NOTE: コントローラのアップグレードモデルの組み合わせが上記の表にない場合は、テクニカルサポートにお問い合わせください。

^1^ AFF A800システムに必要なその他の手順については、セクションlink:reassign-node1-disks-to-node3.html#reassign-node1-node3-app-step9["ノード1のディスクをノード3に再割り当て（手順9）"]、またはのA800に関する説明に記載されている手順に進みますlink:reassign-node2-disks-to-node4.html#reassign-node2-node4-app-step9["ノード2のディスクをノード4に再割り当て（手順9）"]。

^2^2ノードスイッチレスクラスタ構成でAFF A300からAFF A400、またはFAS8200からFAS8300システムにアップグレードする場合は、コントローラのアップグレード用に一時的なクラスタポートを選択する必要があります。AFF A400 および FAS8300 システムは、イーサネットバンドルとして、メザニンカードポートはイーサネットタイプ、 FC タイプの FC バンドルとして、 2 種類の構成で提供されます。

* AFF A400 または FAS8300 では、イーサネットタイプの構成の場合、 2 つのメザニンポートのいずれかを一時的なクラスタポートとして使用できます。
* AFF A400 または FC タイプの構成で FAS8300 を使用する場合は、 4 ポートの 10GbE ネットワークインターフェイスカード（パーツ番号 X1147A ）を追加して一時的なクラスタポートを提供する必要があります。
* 一時的なクラスタポートを使用したコントローラのアップグレードが完了したら、クラスタ LIF を無停止で e3a および e3b 、 AFF A400 システムの 100GbE ポート、 FAS8300 システムの e0c および e0d 、 100GbE ポートに移行できます。


^3FAS8020、FAS8040、AFF8020、およびAFF8040のシステムを上記の表のターゲット交換コントローラにアップグレードする場合、交換用コントローラが古いコントローラと同じONTAP バージョンを実行している必要があります。FAS8020、FAS8040、AFF8020、およびAFF8040のシステムは、ONTAP 9.8以降のONTAP バージョンをサポートしていません。

^4^次の表に、これらのコントローラアップグレードの組み合わせでサポートされる最小ONTAP バージョンとそれ以降のバージョンを示します。

[cols="20,30,20,30"]
|===
2+| 古いコントローラ 2+| 交換用コントローラ 


| システム | ONTAP バージョン | システム | ONTAP バージョン 


| AFF A320 | 9.9.1以降 | AFF A400 | 9.9.1以降 


| AFF8060の場合 | 9.8P13以降のパッチ | AFF A900 の略 | 9.10.1から9.12.1 


| AFF8080 | 9.8P10以降のパッチ | AFF A900 の略 | 9.10.1から9.12.1 


| FAS8060 | 9.8P13以降のパッチ | FAS9500 | 9.10.1P3～9.12.1 


| FAS8080 | 9.8P12以降のパッチ | FAS9500 | 9.10.1P3～9.12.1 
|===
[NOTE]
====
上記の表にあるアップグレードの組み合わせについては、次の点に注意してください。

* 既存のコントローラと交換用コントローラで同じバージョンのONTAPを使用する必要はありません。ONTAP ソフトウェアのアップグレードは、コントローラのアップグレード時に実行されます。
* アップグレードするときは、サポートされているONTAP バージョンとパッチレベルで交換用コントローラを取り付ける必要があります。
* 手順を開始して最初のノードをアップグレードすると、コントローラのアップグレードをキャンセルしたり元に戻したりすることはできません。


====


== 別のハードウェアアップグレード手順を選択する

* link:../upgrade-arl/index.html["コントローラハードウェアのアップグレードに使用できる代替ARL方法を確認します"]です。
* コントローラハードウェアを別の方法でアップグレードして、ボリュームの移動を希望する場合は、を参照してください link:other_references.html["参考資料"] をクリックして、ボリュームまたは storage _ を移動して _ Upgrade にリンクします。


.関連情報
参照link:other_references.html["参考資料"] _ONTAP 9 ドキュメント_にリンクします。
