---
sidebar: sidebar 
permalink: upgrade-arl-auto-app/ensure_new_controllers_are_set_up_correctly.html 
keywords: confirm, controllers, set up, ha, node3, node4, node2, lif, cluster, high, availability 
summary: 'ONTAP 9.8 以降を実行しているコントローラをアップグレードした後で "system controller replace" コマンドを使用して HA ペアを有効にし " ノード 3 とノード 4 のストレージアクセスを確認し " アグリゲートの所有権を確認します' 
---
= 新しいコントローラが正しくセットアップされていることを確認します
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
正しいセットアップを確認するには、 HA ペアを有効にする必要があります。さらに、 node3 と node4 が相互のストレージにアクセスできること、およびクラスタ内の他のノードに属するデータ LIF を所有していないことを確認する必要があります。また、 node3 が node1 のアグリゲートを所有しており、 node4 が node2 のアグリゲートを所有していること、および両方のノードのボリュームがオンラインであることを確認する必要があります。

.手順
. node2 のチェック後、 node2 クラスタのストレージフェイルオーバーとクラスタ HA ペアが有効になります。処理が完了すると、両方のノードに「 Completed 」と表示され、クリーンアップ処理が実行されます。
. ストレージフェイルオーバーが有効になっていることを確認します。
+
「 storage failover show 」をクリックします

+
次の例は、ストレージフェイルオーバーが有効になっている場合のコマンドの出力例を示しています。

+
....
cluster::> storage failover show
                  Takeover
Node     Partner  Possible   State Description
-------- -----    -------    ------------------
node3    node4    true       Connected to node4
node4    node3    true       Connected to node3
....
. 次のコマンドを使用して、 node3 と node4 が同じクラスタに属していることを確認します。出力を確認します。
+
「 cluster show 」を参照してください

. 次のコマンドを使用して、 node3 と node4 が相互のストレージにアクセスできることを確認します。出力を確認します。
+
「storage failover show -fields local-missing-disks、partner-missing-disks」

. 次のコマンドを使用して、 node3 と node4 がクラスタ内の他のノードによってホーム所有されているデータ LIF を所有していないことを確認します。
+
「 network interface show 」を参照してください

+
node3 と node4 がクラスタ内の他のノードによってホーム所有されているデータ LIF を所有していない場合は、データ LIF をホーム所有者にリバートします。

+
「 network interface revert 」の略

. ノード 3 がノード 1 のアグリゲートを所有していること、およびノード 4 がノード 2 のアグリゲートを所有していることを確認します。
+
storage aggregate show-owner-name_node3_`

+
storage aggregate show-owner-name_node4

. オフラインになっているボリュームがないかを確認します。
+
volume show -node _node3 --state offline`

+
volume show -node-node4 --state offline`

. オフラインになっているボリュームがある場合は、セクションで取得したオフラインボリュームのリストと比較します link:prepare_nodes_for_upgrade.html["ノードをアップグレードする準備をします"]必要に応じて、次のコマンドを使用して、ボリュームごとに 1 回、オフラインボリュームをオンラインにします。
+
'volume online -vserver_name_-volume_name_`

. ノードごとに次のコマンドを使用して、新しいノードの新しいライセンスをインストールします。
+
'system license add -license-code_license_code'license_code'license_code..._`

+
license-code パラメータには、アルファベットの文字キーをアルファベットの大文字 28 個まで入力できます。ライセンスは一度に 1 つずつ追加することも、複数追加することもできます。各ライセンスキーをカンマで区切って指定することもできます。

. 次のいずれかのコマンドを使用して、元のノードから古いライセンスをすべて削除します。
+
「システムライセンスのクリーンアップ - 未使用 - 期限切れ」

+
'system license delete -serial-number_node_name --package_license_package_`

+
--
** 期限切れのライセンスをすべて削除します。
+
「システムライセンスのクリーンアップ - 期限切れ」

** 未使用のライセンスをすべて削除します。
+
'System license clean-up-unused （システムライセンスのクリーンアップ - 未使用） '

** クラスタから特定のライセンスを削除するには、ノードで次のコマンドを使用します。
+
'system license delete -serial-number_node1_serial_number'-package *

+
'system license delete -serial-number_node2 _serial_number'-package *



--
+
次の出力が表示されます。

+
....
Warning: The following licenses will be removed:
<list of each installed package>
Do you want to continue? {y|n}: y
....
+
すべてのパッケージを削除するには 'y' を入力します

. 次のコマンドを使用して出力を調べ、ライセンスが正しくインストールされていることを確認します。
+
「 system license show 」を参照してください

+
出力を、セクションでキャプチャした出力と比較できます link:prepare_nodes_for_upgrade.html["ノードをアップグレードする準備をします"]。

. NetApp Storage Encryption（NSE）が構成で使用されていた場合、「setenv bootarg.storageencryption.support」コマンドを「_kmip.init.maxwait_` variable」off」（の）で「true」に設定します link:install_boot_node4.html#step27["Node4 をインストールしてブートします（手順 27 ）"]）を使用している場合は、変数をリセットする必要があります。
+
`set diag; systemshell -node-node_name --コマンドsudo kenv -u -p kmip.init.maxwait`



. [[Step13]] 両方のノードで次のコマンドを使用して、 SP を設定します。
+
system service-processor network modify -node _node_name _`

+
を参照してください link:other_references.html["参考資料"] SP および _SP ONTAP 9.8 コマンドの詳細については ' システム管理リファレンスにリンクするには ' マニュアルページリファレンスを参照してください system の service-processor network modify コマンドの詳細については ' を参照してください

. 新しいノードにスイッチレスクラスタをセットアップする場合は、を参照してください link:other_references.html["参考資料"] ネットアップサポートサイトへのリンクを設定するには、 _ 2 ノードスイッチレスクラスタへの移行の手順に従ってください。


.完了後
ノード 3 とノード 4 でストレージ暗号化が有効になっている場合は、セクションを完了します link:set_up_storage_encryption_new_module.html["新しいコントローラモジュールで Storage Encryption をセットアップします"]。それ以外の場合は、の項を実行します link:decommission_old_system.html["古いシステムの運用を停止"]。
