---
sidebar: sidebar 
permalink: upgrade-arl-auto-app/guidelines_for_upgrading_controllers_with_arl.html 
keywords: guidelines, upgrading, controllers, ARL 
summary: 'ONTAP 9.8 以降を実行しているコントローラをアップグレードできるかどうかを確認するには "system controller replace" コマンドを使用します' 
---
= ARL を使用したコントローラのアップグレードに関するガイドライン
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ARL を使用して ONTAP 9.8 以降を実行するコントローラのペアをアップグレードできるかどうかは、プラットフォームおよび元のコントローラと交換用コントローラの両方の構成によって異なります。



== ARL のアップグレードがサポートされます

ARL 手順 for ONTAP 9.8 以降を使用してノードのペアをアップグレードする場合は、 ARL が元のコントローラおよび交換用コントローラで実行されていることを確認する必要があります。

元のシステムでサポートされるすべての定義済みアグリゲートのサイズとディスク数を確認する必要があります。次に、サポートされるアグリゲートサイズとディスク数を、新しいシステムでサポートされるアグリゲートサイズとディスク数と比較する必要があります。を参照してください link:other_references.html["参考資料"] この情報がある Hardware Universe にリンクするには、次の手順を実行します。新しいシステムでサポートされるアグリゲートサイズとディスク数は、元のシステムでサポートされるアグリゲートサイズとディスク数以上であることが必要です。

元のコントローラを交換したときに、新しいノードが既存のノードとクラスタの一部になることができるかどうかは、クラスタ混在ルールで検証する必要があります。クラスタ混在ルールの詳細については、を参照してください link:other_references.html["参考資料"] Hardware Universe にリンクするには、次の手順を実行します。


NOTE: 内蔵ドライブをサポートするシステム（ FAS2700 または AFF A250 など）をアップグレードする場合でも内蔵ドライブがないときは、を参照してください link:other_references.html["参考資料"] および、 _ アグリゲートの再配置に含まれる手順を使用して、使用している ONTAP のバージョンに適したコントローラ Hardware_content を手動でアップグレードします。

FAS8080 や AFF8080 システムなど、ノードあたり 3 つ以上のクラスタポートを備えたシステムは、アップグレードを開始する前に、ノードあたり 2 つのクラスタポートにクラスタ LIF を移行してホームに戻す必要があります。ノードごとに 3 つ以上のクラスタポートを使用してコントローラのアップグレードを実行すると、アップグレード後に新しいコントローラのクラスタ LIF がなくなる可能性があります。

ARL を使用したコントローラのアップグレードは、 SnapLock Enterprise ボリュームおよび SnapLock Compliance ボリュームが設定されたシステムでサポートされます。



== 2 ノードスイッチレスクラスタ

2 ノードスイッチレスクラスタのノードをアップグレードする場合は、アップグレードの実行中もスイッチレスクラスタのノードをそのまま使用できます。スイッチクラスタに変換する必要はありません。



== ARL のアップグレードはサポートされていません

次のアップグレードは実行できません。

* 元のコントローラに接続されたディスクシェルフをサポートしない交換用コントローラへの接続
+
を参照してください link:other_references.html["参考資料"] ディスクサポート情報の Hardware Universe にリンクするには、次の手順を実行します。

* 内蔵ドライブを搭載したエントリレベルのコントローラ。たとえば、 FAS 2500 などです。
+
内蔵ドライブを搭載したエントリレベルのコントローラをアップグレードする場合は、を参照してください link:other_references.html["参考資料"] ボリュームまたは storage を移動して _Upgrade にリンクし、 Data ONTAP に移動して、 clustered 手順を実行するノードのペアをアップグレードする _ に進みます。





== トラブルシューティング

コントローラのアップグレード中に問題が発生した場合は、を参照してください link:troubleshoot.html["トラブルシューティングを行う"] 詳細および解決策については、手順の末尾にあるセクションを参照してください。

発生した問題に対する解決策 が見つからない場合は、テクニカルサポートにお問い合わせください。
