---
sidebar: sidebar 
permalink: upgrade-arl-auto-app/guidelines_for_upgrading_controllers_with_arl.html 
keywords: guidelines, upgrading, controllers, ARL 
summary: 'ONTAP 9.8 以降を実行しているコントローラをアップグレードできるかどうかを確認するには "system controller replace" コマンドを使用します' 
---
= ARL を使用したコントローラのアップグレードに関するガイドライン
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
ARL を使用して ONTAP 9.8 以降を実行するコントローラのペアをアップグレードできるかどうかは、プラットフォームおよび元のコントローラと交換用コントローラの両方の構成によって異なります。



[[supported-upgrades-for-arl]]
== ARL のアップグレードがサポートされます

ARL 手順 for ONTAP 9.8 以降を使用してノードのペアをアップグレードする場合は、 ARL が元のコントローラおよび交換用コントローラで実行されていることを確認する必要があります。

定義済みのすべてのアグリゲートのサイズと、元のシステムでサポートされているディスクの数を確認する必要があります。次に、アグリゲート サイズとサポートされているディスクの数を、新しいシステムでサポートされているアグリゲート サイズおよびディスクの数と比較する必要があります。link:other-references.html["参考資料"]を参照して、この情報が掲載されている _Hardware Universe_ にリンクしてください。新しいシステムでサポートされるアグリゲート サイズおよびディスクの数は、元のシステムでサポートされているアグリゲート サイズおよびディスクの数以上である必要があります。

クラスタ混合ルールにおいて、元のコントローラが交換された際に、新しいノードが既存のノードと共にクラスタの一部となることができるかどうかを検証する必要があります。クラスタ混合ルールの詳細については、link:other-references.html["参考資料"]を参照して _Hardware Universe_ にアクセスしてください。


NOTE: 内蔵ドライブをサポートするシステム（例：FAS2700 または AFF A250）をアップグレードする場合で、内蔵ドライブが搭載されていない場合は、link:other-references.html["参考資料"]を参照し、お使いの ONTAP バージョンに適した _Aggregate Relocation to Manually Upgrade Controller Hardware_ コンテンツの手順を使用してください。

FAS8080 や AFF8080 システムなど、ノードあたり 3 つ以上のクラスタポートを備えたシステムは、アップグレードを開始する前に、ノードあたり 2 つのクラスタポートにクラスタ LIF を移行してホームに戻す必要があります。ノードごとに 3 つ以上のクラスタポートを使用してコントローラのアップグレードを実行すると、アップグレード後に新しいコントローラのクラスタ LIF がなくなる可能性があります。

ARL を使用したコントローラのアップグレードは、 SnapLock Enterprise ボリュームおよび SnapLock Compliance ボリュームが設定されたシステムでサポートされます。



[[two-node-switchless-clusters]]
== 2 ノードスイッチレスクラスタ

2 ノードスイッチレスクラスタのノードをアップグレードする場合は、アップグレードの実行中もスイッチレスクラスタのノードをそのまま使用できます。スイッチクラスタに変換する必要はありません。



[[upgrades-not-supported-for-arl]]
== ARL のアップグレードはサポートされていません

次のアップグレードは実行できません。

* 元のコントローラに接続されたディスクシェルフをサポートしない交換用コントローラへの接続
+
link:other-references.html["参考資料"]を参照して、ディスクサポート情報の _Hardware Universe_ にリンクしてください。

* 内部ドライブを備えたエントリーレベルのコントローラ（例：FAS2750）。
+
内部ドライブを搭載したエントリーレベルのコントローラーをアップグレードする場合は、link:other-references.html["参考資料"] を参照して「ボリュームまたはストレージの移動によるアップグレード」にリンクし、「ボリュームを移動することによるクラスタ化された Data ONTAP を実行するノードペアのアップグレード」の手順に進んでください。





[[metrocluster-fc-configuration]]
== MetroCluster FC 構成

MetroCluster FC構成では、できるだけ早くディザスタリカバリ/フェイルオーバーサイトのノードを交換する必要があります。コントローラモデルの不一致が原因で原因ディザスタリカバリのミラーリングがオフラインになる可能性があるため、 MetroCluster 内のコントローラモデルの不一致はサポートされません。2つ目のサイトでノードを交換する場合は、コマンドを使用し `-skip-metrocluster-check true` てMetroClusterチェックをバイパスします。



[[troubleshoot]]
== トラブルシューティングを行う

ノードペアのアップグレード中に障害が発生する可能性があります。ノードがクラッシュする、アグリゲートが再配置されない、または LIF が移行されない可能性があります。障害の原因とその解決策は、アップグレード手順の実行中に障害が発生したタイミングによって異なります。

問題が発生した場合は、 link:aggregate_relocation_failures.html["トラブルシューティングを行う"]詳細情報と可能な解決策については、手順の最後にあるセクションをご覧ください。発生する可能性のある障害に関する情報は、手順のフェーズごとに記載されています。 link:overview_of_the_arl_upgrade.html["ARLアップグレードシーケンス"] 。

発生した問題に対する解決策 が見つからない場合は、テクニカルサポートにお問い合わせください。

.次の手順
ARLを使用してコントローラーをアップグレードするためのガイドラインを確認した後、link:verify_health_of_metrocluster_config.html["MetroCluster構成の健全性を確認する"]。
