---
sidebar: sidebar 
permalink: upgrade-arl-auto-app/index.html 
keywords: aggregate, relocation, controller, hardware, aggregates, flexarray, metrocluster, terminology 
summary: 'ONTAP 9.8 以降を実行しているコントローラ・ハードウェアをアップグレードするには "system controller replace コマンドを使用して " ルート以外のアグリゲートの所有権を切り替えます' 
---
= 概要
:allow-uri-read: 


[role="lead"]
この手順 では、次のシステム構成で Aggregate Relocation （ ARL ；アグリゲートの再配置）を使用してコントローラハードウェアをアップグレードする方法について説明します。

[cols="40,20,40"]
|===
| メソッド | ONTAP バージョン | サポートされるシステム 


| 「 system controller replace 」コマンドを使用します | 9.8 以降 | link:decide_to_use_the_aggregate_relocation_guide.html#sys_commands_98_supported_systems["サポートされているシステムマトリックスへのリンク"] 
|===
手順の実行中に、交換用コントローラハードウェアを使用して元のコントローラハードウェアをアップグレードし、ルート以外のアグリゲートの所有権を切り替えます。アグリゲートをノードからノードに複数回移行して、アップグレード手順 全体を通じて、少なくとも 1 つのノードがアグリゲートからデータを提供していることを確認します。また、処理を続行する前に、データ論理インターフェイス（ LIF ）を移行し、新しいコントローラのネットワークポートをインターフェイスグループに割り当てます。

.この情報で使用される用語
この情報では、元のノードの名前は「 node1 」と「 node2 」になり、新しいノードの名前は「 node3 」と「 node4 」になります。説明されている手順では、 node1 は node3 に置き換えられ、 node2 は node4 に置き換えられます。「 node1 」、「 node2 」、「 node3 」、および「 node4 」は、元のノードと新しいノードを区別するためだけに使用されます。手順を使用するときは、元のノードと新しいノードの実際の名前を置き換える必要があります。ただし実際には、ノードの名前は変更されません。 node3 には node1 という名前が付けられ、 node4 にはコントローラハードウェアのアップグレード後に node2 という名前が付けられます。

この情報の中で、「 FlexArray 仮想化ソフトウェアを搭載したシステム」とは、これらの新しいプラットフォームに属するシステムを指します。「 V シリーズシステム」という用語は、ストレージアレイに接続可能な独立したハードウェアシステムを指します。

.重要な情報：
* この手順は複雑で、 ONTAP の高度な管理スキルがあることを前提としています。また、を読んで理解する必要があります link:guidelines_for_upgrading_controllers_with_arl.html["ARL を使用したコントローラのアップグレードに関するガイドライン"] および link:overview_of_the_arl_upgrade.html["ARL アップグレードの概要"] アップグレード開始前のセクション。
* この手順は、交換用コントローラハードウェアが新しく購入され、使用されていないことを前提としています。使用済みのコントローラを「 wipeconfig 」コマンドで準備するために必要な手順は、この手順には含まれていません。交換用コントローラハードウェアを以前に使用していた場合は、テクニカルサポートに問い合わせる必要があります。特に、コントローラが Data ONTAP 7-Mode を実行していた場合は、テクニカルサポートにお問い合わせください。
* ARL を使用すると、システムを停止することなく、アップグレードするクラスタよりも新しいバージョンの ONTAP を実行する新しいコントローラへのアップグレードを実行できます。古いコントローラと新しいコントローラの ONTAP バージョンの組み合わせは、 ONTAP ソフトウェアリリースの NDU モデルによって決まります。たとえば、 ONTAP 9.8 を実行しているコントローラがあり、そのコントローラで最後にサポートされていたバージョンである場合は、 ONTAP 9.8 より後のバージョンの ONTAP を実行している新しいコントローラにアップグレードできます。
+
このアップグレード手順では、交換するコントローラモデルで ONTAP の新しいバージョンがサポートされておらず、新しいコントローラで以前のバージョンの ONTAP がサポートされていない主な環境アップグレードシナリオを使用します。

* この手順を使用して、ノードが 3 つ以上あるクラスタでコントローラハードウェアをアップグレードできます。ただし、クラスタ内のハイアベイラビリティ（ HA ）ペアごとに手順を個別に実行する必要があります。
* この FlexArray システム、 V シリーズシステム、 AFF システム、および手順環境 FAS 仮想化ソフトウェアを搭載したシステムです。必要なライセンスがインストールされていれば、 ONTAP 9.5 以降にリリースされた FAS システムをストレージアレイに接続できます。ストレージアレイと V シリーズのモデルの詳細については、を参照してください link:other_references.html["参考資料"] Hardware Universe にリンクして、 V シリーズサポートマトリックスにアクセスしてください。
* この手順環境システムは、 4 ノードの NetApp MetroCluster 構成以上を実行しています。MetroCluster 構成サイトは物理的に異なる場所に設置できるため、 HA ペアの場合は各 MetroCluster サイトでコントローラの自動アップグレードを個別に実行する必要があります。
* HA クラスタなどの MetroCluster 以外手順のシステムでは、 ARL アップグレードのみがサポートされます。
* AFF A320 システムからアップグレードする場合は、ボリューム移動を使用してコントローラハードウェアをアップグレードするか、テクニカルサポートにお問い合わせください。を参照してください link:other_references.html["参考資料"] をクリックして、ボリュームまたは storage _ を移動して _ Upgrade にリンクします。

