---
sidebar: sidebar 
permalink: upgrade-arl-auto-app/move_non_root_aggr_and_nas_data_lifs_node2_from_node3_to_node4.html 
keywords: move, non-root, aggregates, nas, lif, node2, node3, node4 
summary: 'ONTAP 9.8 以降を実行しているコントローラをアップグレードするときに "system controller replace" コマンドを使用して "node3 にある node2 の NAS データ LIF が node3 から node4 に再配置されていることを確認します' 
---
= node2 によって所有されているルート以外のアグリゲートと NAS データ LIF を、 node3 から node4 に移動します
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
ノード 4 のネットワーク構成を確認した後、ノード 2 が所有する NAS データ LIF をノード 3 からノード 4 に再配置し、SAN LIF がノード 4 に存在することを確認する必要があります。

.このタスクについて
リモート LIF は、アップグレード手順中に SAN LUN へのトラフィックを処理します。アップグレード中のクラスタまたはサービスの健全性のために、SAN LIF を移動する必要はありません。SAN LIF は、新しいポートにマッピングする必要がある場合を除き、移動されません。

node4 をオンラインにした後、LIF が正常であり、正しいポートに配置されていることを確認します。


NOTE: T6ベースのイーサネットネットワークインターフェイスカードまたはマザーボードポートのポート速度を変更すると、速度変換後に不正な形式のパケットが受信されることがあります。を参照してください https://mysupport.netapp.com/site/bugs-online/product/ONTAP/BURT/1570339["NetApp Bugs OnlineのバグID1570339"^] ナレッジベースの記事 https://kb.netapp.com/onprem/ontap/hardware/CRC_errors_on_T6_ports_after_converting_from_40GbE_to_100GbE["40GbEから100GbEへの変換後のT6ポートのCRCエラー"^] を参照してください。

.手順
. 再配置処理を再開します。
+
[source, cli]
----
system controller replace resume
----
+
システムは次のタスクを実行します。

+
** クラスタクォーラムチェック
** システム ID の確認
** イメージのバージョンチェック
** ターゲットプラットフォームのチェック
** ネットワーク到達可能性チェック


+
ネットワーク到達可能性チェックのこの段階で、システムは操作を一時停止します。

. 再配置処理を再開します。
+
[source, cli]
----
system controller replace resume
----
+
システムは次のチェックを実行します。

+
** クラスタの健全性チェック
** クラスタ LIF のステータスを確認します


+
これらのチェックの実行後、システムによって、 node2 によって所有されているルート以外のアグリゲートと NAS データ LIF が新しいコントローラ node4 に再配置されます。リソースの再配置が完了すると、コントローラの交換処理が一時停止します。

. アグリゲートの再配置処理と NAS データ LIF の移動処理のステータスを確認します。
+
[source, cli]
----
system controller replace show-details
----
+
コントローラ交換用手順が一時停止している場合は、エラーがある場合はチェックして修正し、次に「問題 re sume 」をクリックして操作を続行します。

. 必要に応じて、移動された LIF を復元して元に戻すか、自動的に再配置できなかったノード 2 LIF をノード 4 に手動で移行して変更します。
+
[role="tabbed-block"]
====
.移動したLIFを復元して元に戻す
--
.. 移動した LIF をリストします。
+
[source, cli]
----
cluster controller-replacement network displaced-interface show
----
.. LIF が取り外された場合は、ホームノードをノード 4 にリストアします。
+
[source, cli]
----
cluster controller-replacement network displaced-interface restore-home-node -node <node4_nodename> -vserver <vserver name> -lif-name <lif_name>
----


--
.LIFを手動で移行および変更する
--
.. 自動的に再配置できなかった LIF をノード 4 に移行します。
+
[source, cli]
----
network interface migrate -vserver <vserver name> -lif <lif_name> -destination-node <node4_nodename> -destination-port <port_on_node4>
----
.. 移行された LIF のホーム ノードとホーム ポートを変更します。
+
[source, cli]
----
network interface modify -vserver <vserver_name> -lif <data_lif_name> -home-node <node4_nodename> -home-port <home_port>
----


--
====
. この処理を再開すると、必要なポストチェックの実行をシステムに求めるプロンプトが表示されます。
+
[source, cli]
----
system controller replace resume
----
+
次のポストチェックが実行されます。

+
** クラスタクォーラムチェック
** クラスタの健全性チェック
** アグリゲートの再構築チェック
** アグリゲートのステータスを確認します
** ディスクのステータスを確認します
** クラスタ LIF のステータスを確認します
** ボリュームチェック




.次の手順
node2が所有する非ルート集約とNASデータLIFをnode3からnode4に移動した後、link:manage-authentication-using-kmip-servers.html["KMIPサーバを使用して認証を管理する"]。
