---
sidebar: sidebar 
permalink: upgrade-arl-auto-app/move_non-root_aggr_and_nas_data_lifs_node1_from_node2_to_node3.html 
keywords: moving, non-root, aggregates, nas, lif, node1, node2, node3 
summary: 'を使用して、ONTAP 9.8以降を実行しているコントローラをアップグレードするときに、node2のnode1 NASデータLIFがnode2からnode3に再配置されていることを確認します `system controller replace` コマンド' 
---
= ノード 1 で所有されているルート以外のアグリゲートと NAS データ LIF を、ノード 2 からノード 3 に移動します
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
ノード 3 のネットワーク設定を確認し、ノード 2 からノード 3 にアグリゲートを再配置する前に、ノード 2 に現在あるノード 1 に属する NAS データ LIF が node2 からノード 3 に再配置されたことを確認する必要があります。また、ノード 3 に SAN LIF が存在することも確認する必要があります。

.このタスクについて
リモートLIFは、アップグレード手順中にSAN LUNへのトラフィックを処理します。アップグレード中にSAN LIFを移動することは、クラスタやサービスの健全性を維持するために必要ではありません。SAN LIFは、新しいポートにマッピングする必要がない限り、移動されません。node3をオンラインにした後、LIFが正常に動作し、適切なポートに配置されていることを確認します。


NOTE: T6ベースのイーサネットネットワークインターフェイスカードまたはマザーボードポートのポート速度を変更すると、速度変換後に不正な形式のパケットが受信されることがあります。を参照してください https://mysupport.netapp.com/site/bugs-online/product/ONTAP/BURT/1570339["NetApp Bugs OnlineのバグID1570339"^] ナレッジベースの記事 https://kb.netapp.com/onprem/ontap/hardware/CRC_errors_on_T6_ports_after_converting_from_40GbE_to_100GbE["40GbEから100GbEへの変換後のT6ポートのCRCエラー"^] を参照してください。

.手順
. 再配置処理を再開します。
+
[source, cli]
----
system controller replace resume
----
+
システムは次のタスクを実行します。

+
** クラスタクォーラムチェック
** システム ID の確認
** イメージのバージョンチェック
** ターゲットプラットフォームのチェック
** ネットワーク到達可能性チェック


+
ネットワーク到達可能性チェックのこの段階で処理が一時停止します。

. 再配置処理を再開します。
+
[source, cli]
----
system controller replace resume
----
+
システムは次のチェックを実行します。

+
** クラスタの健全性チェック
** クラスタ LIF のステータスを確認します


+
これらのチェックの実行後、 node1 で所有されているルート以外のアグリゲートと NAS データ LIF が新しいコントローラ node3 に再配置されます。リソースの再配置が完了すると、コントローラの交換処理が一時停止します。

. アグリゲートの再配置処理と NAS データ LIF の移動処理のステータスを確認します。
+
[source, cli]
----
system controller replace show-details
----
+
コントローラ交換用手順が一時停止している場合は、エラーがある場合はチェックして修正し、次に「問題 re sume 」をクリックして操作を続行します。

. 必要に応じて、移動された LIF を復元して元に戻すか、自動的に再配置できなかったノード 1 LIF をノード 3 に手動で移行して変更します。
+
[role="tabbed-block"]
====
.移動したLIFを復元して元に戻す
--
.. 移動した LIF をリストします。
+
[source, cli]
----
cluster controller-replacement network displaced-interface show
----
.. LIF が表示されなくなった場合は、ホームノードをノード 3 にリストアします。
+
[source, cli]
----
cluster controller-replacement network displaced-interface restore-home-node -node <node3_nodename> -vserver <vserver name> -lif-name <lif_name>
----


--
.LIFを手動で移行および変更する
--
.. 自動的に再配置できなかった LIF をノード 3 に移行します。
+
[source, cli]
----
network interface migrate -vserver <vserver name> -lif <lif_name> -destination-node <node3_nodename> -destination-port <port_on_node3>
----
.. 移行された LIF のホーム ノードとホーム ポートを変更します。
+
[source, cli]
----
network interface modify -vserver <vserver_name> -lif <data_lif_name> -home-node <node3_nodename> -home-port <home_port>
----


--
====
. この処理を再開すると、必要なポストチェックの実行をシステムに求めるプロンプトが表示されます。
+
[source, cli]
----
system controller replace resume
----
+
次のポストチェックが実行されます。

+
** クラスタクォーラムチェック
** クラスタの健全性チェック
** アグリゲートの再構築チェック
** アグリゲートのステータスを確認します
** ディスクのステータスを確認します
** クラスタ LIF のステータスを確認します
** ボリュームチェック




.次の手順
node1が所有する非ルート集約とNASデータLIFをnode2からnode3に移動した後、link:relocate_non_root_aggr_nas_lifs_from_node2_to_node3.html["非ルート・アグリゲートとNASデータLIFをnode2からnode3に再配置する"]。
