---
sidebar: sidebar 
permalink: upgrade-arl-auto-app/prepare_nodes_for_upgrade.html 
keywords: preparing, nodes, upgrade 
summary: 'ONTAP 9.8 以降を実行しているコントローラをアップグレードするときは、 system controller replace" コマンドを使用してノードを準備し、一連の事前チェックを実行します。' 
---
= ノードをアップグレードする準備をします
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ノードをアップグレードする準備として、次の手順を実行する必要があります。

.手順
. ONTAP コマンドラインで次のコマンドを入力して、コントローラの交換プロセスを開始します。
+
'system controller replace start-nodes_node_name _`

+
[NOTE]
====
** ONTAP 9.10.1 以降では、 4 ノードの MetroCluster FC 構成のデフォルトの自動ネゴシエートスイッチオーバー（ NSO ）ベースのアップグレード手順が使用されます。4 ノード MetroCluster FC 構成をアップグレードする場合、「 system controller replace start 」コマンドを問題するときに、「 -nso 」パラメータを「 false 」に設定して、 NSO ベースの手順の起動を禁止する必要があります。
+
'system controller replace start-nodes _node_name --nso false

** 「 system controller replace start 」コマンドは、 advanced 権限レベルでのみ実行できます。
+
「 advanced 」の権限が必要です



====
+
次の出力が表示されます。

+
....
Warning:
1. Current ONTAP version is 9.x
Before starting controller replacement operation, ensure that the new controllers are running the version 9.x

2. Verify that NVMEM or NVRAM batteries of the new nodes are charged, and charge them if they are not. You need to physically check the new nodes to see if the NVMEM or NVRAM  batteries are charged. You can check the battery status either by connecting to a serial console or using SSH, logging into the Service Processor (SP) or Baseboard Management Controller (BMC) for your system, and use the system sensors to see if the battery has a sufficient charge.

Attention: Do not try to clear the NVRAM contents. If there is a need to clear the contents of NVRAM, contact NetApp technical support.

3. If a controller was previously part of a different cluster, run wipeconfig before using it as the replacement controller.

Do you want to continue? {y|n}: y
....
. 「 y 」キーを押すと、次の出力が表示されます。
+
....
Controller replacement operation: Prechecks in progress.
Controller replacement operation has been paused for user intervention.
....
+
システムでは次の事前確認が実行され、あとで手順で使用するために各事前確認の出力が記録されます。

+
[cols="35,65"]
|===
| 事前チェック | 説明 


| クラスタの健常性チェック | クラスタ内のすべてのノードが正常であることを確認します。 


| MCC クラスタチェック | システムが MetroCluster 構成かどうかを確認します。MetroCluster 構成かどうかが自動的に検出され、特定の事前確認と検証チェックが実行されます。4 ノードの MetroCluster FC 構成のみがサポートされます。2 ノード MetroCluster 構成と 4 ノード MetroCluster の IP 構成では、チェックが失敗します。MetroCluster 構成がスイッチオーバーされている場合、チェックは失敗します。 


| アグリゲートの再配置ステータスチェック | アグリゲートの再配置がすでに実行中であるかどうかを確認します。別のアグリゲートの再配置を実行中の場合、チェックは失敗します。 


| モデル名のチェック（ Model Name Check | この手順でコントローラモデルがサポートされているかどうかを確認します。モデルがサポートされていない場合、タスクは失敗します。 


| クラスタクォーラムチェック | 交換するノードがクォーラムにあることを確認します。ノードがクォーラムを構成していない場合は、タスクが失敗します。 


| イメージのバージョンチェック | 交換するノードで同じバージョンの ONTAP が実行されていることを確認します。ONTAP イメージのバージョンが異なると、タスクは失敗します。新しいノードには、元のノードと同じバージョンの ONTAP 9.x がインストールされている必要があります。新しいノードに別のバージョンの ONTAP がインストールされている場合は、設置後に新しいコントローラをネットブートする必要があります。ONTAP のアップグレード方法については、を参照してください link:other_references.html["参考資料"] リンク先： ONTAP のアップグレード _ 。 


| HA ステータスチェック | 交換する両方のノードがハイアベイラビリティ（ HA ）ペア構成になっているかどうかを確認します。コントローラでストレージフェイルオーバーが有効になっていない場合、タスクは失敗します。 


| アグリゲートステータスチェック | ホーム所有者でないアグリゲートを交換するノードが所有している場合、そのタスクは失敗します。ローカル以外のアグリゲートを所有するノードは使用しないでください。 


| ディスクステータスチェック | 交換するノードに不足しているディスクまたは障害が発生しているディスクがある場合、タスクは失敗します。足りないディスクがある場合は、を参照してください link:other_references.html["参考資料"] CLI でディスクおよびアグリゲートの管理にリンクするには、 CLI_ 、 _ で論理ストレージの管理に使用します。 HA ペアのストレージを構成するには、 _ 、 _ ハイアベイラビリティ管理 _ を使用します。 


| データ LIF ステータスチェック | 交換するノードにローカル以外のデータ LIF があるかどうかを確認します。ホーム所有者でないデータ LIF がノードに含まれないようにしてください。ローカル以外のデータ LIF がいずれかのノードに含まれている場合、タスクは失敗します。 


| クラスタ LIF ステータス | 両方のノードでクラスタ LIF が動作しているかどうかを確認します。クラスタ LIF が停止している場合は、タスクは失敗します。 


| ASUP ステータスチェック | ASUP 通知が設定されていないと、タスクは失敗します。コントローラの交換用手順を開始する前に ASUP を有効にする必要があります。 


| CPU 利用率チェック | 交換するノードの CPU 利用率が 50% を超えていないかどうかを確認します。CPU 使用率がかなりの時間にわたって 50% を超えると、タスクは失敗します。 


| アグリゲートの再構築チェック | いずれかのデータアグリゲートで再構築が実行されているかどうかを確認しますアグリゲートの再構築を実行中の場合、タスクは失敗します。 


| ノードアフィニティジョブチェック | ノードアフィニティジョブが実行されているかどうかを確認します。ノードアフィニティジョブが実行中の場合、チェックは失敗します。 
|===
. コントローラの交換処理が開始されて事前確認が完了すると、処理が一時停止するため、ノード 3 の設定時にあとで必要になる可能性がある出力情報を収集できます。
+

NOTE: FAS8080 や AFF8080 システムなど、ノードあたり 3 つ以上のクラスタポートを備えたシステムは、アップグレードを開始する前に、ノードあたり 2 つのクラスタポートにクラスタ LIF を移行してホームに戻す必要があります。ノードごとに 3 つ以上のクラスタポートを使用してコントローラのアップグレードを実行すると、アップグレード後に新しいコントローラのクラスタ LIF がなくなる可能性があります。

. システムコンソールで、コントローラの交換用手順の指示に従って、次のコマンドセットを実行します。
+
各ノードに接続されているシリアルポートで、次のコマンドの出力を個別に実行して保存します。

+
** vserver services name-service dns show
** `network interface show -curr-node _local_ -role _cluster,intercluster,node-mgmt,cluster-mgmt,data_`
** `network port show -node _local_ -type physical`
** `service-processor show -local -instance`
** `network fcp adapter show -node _local_`
** 「 network port ifgrp show 」のように表示されます
** `system node show -instance -node _local_`
** `run -node _local_ sysconfig`
** `storage aggregate show -node _local_`
** `volume show -node _local_`
** storage array config show -switch_switch_name_`
** `system license show -owner _local_`
** 「 storage encryption disk show 」のように表示されます
** 「 securitykey manager onboard show-backup 」を参照してください
** 「 security key-manager external show 」と入力します
** 「 security key-manager external show-status 」
** 「 network port reachability show-detail` 」と表示されます


+

NOTE: オンボードキーマネージャ（OKM）を使用するNetApp Volume Encryption（NVE）またはNetApp Aggregate Encryption（NAE）を使用している場合は、あとで手順 でキー管理ツールのパスフレーズを使用してキー管理ツールの再同期を完了できます。

. システムで自己暗号化ドライブを使用している場合は、Knowledge Baseの文書を参照してください https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Systems/FAS_Systems/How_to_tell_I_have_FIPS_drives_installed["FIPSドライブが取り付けられていることを確認する方法"^] アップグレード対象のHAペアで使用されている自己暗号化ドライブのタイプを確認する。ONTAP ソフトウェアは、次の2種類の自己暗号化ドライブをサポートしています。
+
--
** FIPS認定のNetApp Storage Encryption（NSE）SASドライブまたはNVMeドライブ
** FIPS非対応の自己暗号化NVMeドライブ（SED）


[NOTE]
====
FIPSドライブは、同じノードまたはHAペアで他のタイプのドライブと混在させることはできません。

SEDと非暗号化ドライブを同じノードまたはHAペアで混在させることができます。

====
https://docs.netapp.com/us-en/ontap/encryption-at-rest/support-storage-encryption-concept.html#supported-self-encrypting-drive-types["サポートされている自己暗号化ドライブの詳細を確認できます"^]。

--




== ARL の事前確認に失敗した場合は、アグリゲートの所有権を修正

アグリゲートステータスチェックに失敗した場合は、パートナーノードが所有するアグリゲートをホーム所有者ノードに戻し、事前確認プロセスを再度開始する必要があります。

.手順
. パートナーノードが現在所有しているアグリゲートをホーム所有者ノードに戻します。
+
storage aggregate relocation start -node-source_node__ destination_destination-node-aggregate-list *

. node1 と node2 のどちらも現在の所有者（ホーム所有者ではない）アグリゲートを所有していないことを確認します。
+
storage aggregate show -nodes_node_name -is-home false -fields owner-name、home-name、stateを指定します

+
次の例は、アグリゲートの現在の所有者とホーム所有者の両方がノードにある場合のコマンドの出力例を示しています。

+
[listing]
----
cluster::> storage aggregate show -nodes node1 -is-home true -fields owner-name,home-name,state
aggregate   home-name  owner-name  state
---------   ---------  ----------  ------
aggr1       node1      node1       online
aggr2       node1      node1       online
aggr3       node1      node1       online
aggr4       node1      node1       online

4 entries were displayed.
----




=== 完了後

コントローラの交換プロセスを再開する必要があります。

'system controller replace start-nodes_node_name _`



== 使用許諾

クラスタをセットアップする際、セットアップウィザードでクラスタベースのライセンスキーを入力するように求められます。ただし、一部の機能には追加のライセンスが必要です。このライセンスは、 1 つ以上の機能を含む _ パッケージ _ として発行されます。クラスタで使用する各機能のキーは、クラスタ内の各ノードに独自に設定する必要があります。

新しいライセンスキーがない場合は、クラスタで現在ライセンスされている機能を新しいコントローラで使用できます。ただし、ライセンスされていない機能をコントローラで使用するとライセンス契約に違反する可能性があるため、アップグレードの完了後に新しいコントローラのライセンスキーをインストールする必要があります。

を参照してください link:other_references.html["参考資料"] からネットアップサポートサイトにリンクして、 ONTAP 用の新しい 2 文字のライセンスキーを取得できます。キーは、 _ ソフトウェアライセンス _ の _ マイサポート _ セクションにあります。必要なライセンスキーがサイトにない場合は、ネットアップの営業担当者にお問い合わせください。

ライセンスの詳細については、を参照してください link:other_references.html["参考資料"] をクリックして、 _System Administration Reference_( システム管理リファレンス ) にリンクします。
