---
sidebar: sidebar 
permalink: upgrade-arl-auto-app/prepare_for_netboot.html 
keywords: preparing, netboot, ndac, ontap 
summary: 'ONTAP 9.8 以降を実行しているコントローラをアップグレードするときに "system controller replace" コマンドを使用して "node3 と node4 をネットブートする準備をします' 
---
= ネットブートを準備
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ノード 3 とノード 4 を手順の後半で物理的にラックに設置したあと、ネットブートが必要になることがあります。ネットブートという用語は、リモート・サーバに保存された ONTAP イメージからブートすることを意味します。ネットブートの準備を行うときは、システムがアクセスできる Web サーバに、 ONTAP 9 ブート・イメージのコピーを配置する必要があります。

.作業を開始する前に
* システムから HTTP サーバにアクセスできることを確認します。
* を参照してください link:other_references.html["参考資料"] からネットアップサポートサイトにリンクして、使用しているプラットフォームに必要なシステムファイルと、適切なバージョンの ONTAP をダウンロードします。


元のコントローラと同じバージョンの ONTAP 9 がインストールされていない場合は、新しいコントローラをネットブートする必要があります。新しいコントローラをそれぞれ取り付けたら、 Web サーバに保存されている ONTAP 9 イメージからシステムをブートします。その後、以降のシステムブートで使用するブートメディアデバイスに正しいファイルをダウンロードできます。

.手順
. ネットアップサポートサイトにアクセスして、システムのネットブートの実行に使用するファイルをダウンロードします。
. ネットアップサポートサイトのソフトウェアダウンロードセクションから適切な ONTAP ソフトウェアをダウンロードし、「 <ONTAP_version>_image.tgz 」ファイルを Web にアクセスできるディレクトリに保存します。
. Web にアクセスできるディレクトリに移動し、必要なファイルが利用可能であることを確認します。
+
[cols="30,70"]
|===
| 用途 | 作業 


| FAS/AFF8000 シリーズシステム | 「 <ONTAP_version>_image.tgz 」ファイルの内容をターゲットディレクトリに展開します。 tar -zxvf <ONTAP_version>_image.tgz * Note * ： Windows で内容を展開する場合は、 7-Zip または WinRAR を使用してネットブートイメージを展開します。ディレクトリの一覧には、カーネル・ファイル「 netboot/ kernel 」を含むネットブート・フォルダが含まれている必要があります 


| その他すべてのシステム | ディレクトリの一覧に次のファイルが含まれている必要があります。 `<ONTAP_version>_image.tgz *Note*: 「 <ONTAP_version>_image.tgz 」ファイルの内容を抽出する必要はありません。 
|===
+
のディレクトリの情報を使用します link:stage_3_install_boot_node3_overview.html["ステージ 3"]。


