---
sidebar: sidebar 
permalink: upgrade-arl-auto-app/set_fc_or_uta_uta2_config_on_node3.html 
keywords: setting, fc, uta, uta2 configuration, node 
summary: 'ONTAP 9.8 以降を実行しているコントローラをアップグレードするときに "system controller replace" コマンドを使用して " オンボード FC ポート "UTA/UTA2 ポート " または UTA/UTA2 カードをノード 3 に設定します' 
---
= ノード 3 で FC または UTA / UTA2 設定を設定します
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
ノード 3 にオンボードの FC ポート、オンボードのユニファイドターゲットアダプタ（ UTA / UTA2 ）ポート、または UTA / UTA2 カードがある場合は、残りの手順を完了する前に設定を行う必要があります。

.このタスクについて
セクションの完了が必要な場合があります <<ノード 3 の FC ポートを設定>>、を参照してください <<ノード 3 の UTA / UTA2 ポートを確認して設定してください>>、または両方のセクション。


NOTE: ネットアップのマーケティング資料では、 Converged Network Adapter （ CNA ；統合ネットワークアダプタ）アダプタおよびポートを UTA2 と呼ぶ場合があります。ただし、 CLI では CNA という用語が使用されます。

ノード3にオンボードFCポート、オンボードUTA/UTA2ポート、またはUTA/UTA2カード（たとえば、 ONTAP 9.15.1以降に導入されたAFFおよびFASシステム）がなく、ストレージディスクを備えたシステムをアップグレードする場合は、link:reassign-node1-disks-to-node3.html["ノード1のディスクをノード3に再割り当て"] 。



== ノード 3 の FC ポートを設定

node3 にオンボードまたはアドオン FC アダプタ上の FC ポートがある場合、システムの出荷時にポートが事前構成されていないため、ノードをサービスに投入する前にノード上でポート構成を設定する必要があります。ポートを設定しないと、サービスが中断される可能性があります。

.作業を開始する前に
セクションに保存した FC ポート設定の値を node1 で確認しておく必要があります link:prepare_nodes_for_upgrade.html["ノードをアップグレードする準備をします"]。

.このタスクについて
システムに FC 構成がない場合は、このセクションをスキップしてかまいません。システムにオンボード UTA / UTA2 ポートまたは UTA / UTA2 カードがある場合は、で設定します <<ノード 3 の UTA / UTA2 ポートを確認して設定してください>>。


IMPORTANT: このセクションのコマンドをメンテナンス モードのシェル プロンプトで入力します。

.手順
. ノード 3 の FC 設定を、先ほどノード 1 からキャプチャした設定と比較します。
. 必要に応じて、次のいずれかのアクションを実行して、ノード 3 の FC ポートを変更します。
+
メンテナンス モードの場合 (ブート メニューのオプション 5):

+
** ターゲット ポートとしてプログラムするには:
+
`ucadmin modify -m fc -t target <adapter>`

+
例えば： `ucadmin modify -m fc -t target 2a`

** イニシエータポートをプログラミングする場合：
+
`ucadmin modify -m fc -t initiator <adapter>`

+
例えば： `ucadmin modify -m fc -t initator 2b`



. 次のコマンドを使用して出力を調べ、新しい設定を確認します。
+
ucadmin show

. ノードを停止します。
+
「 halt 」

. LOADERプロンプトからシステムをブートします。
+
「 boot_ontap menu

. コマンドを入力したら、ブート環境のプロンプトでシステムが停止するまで待ちます。
. 保守モードのブート・メニューからオプション「 5 」を選択します。


. [[auto_check3_step8] 次のいずれかの操作を実行します
+
[cols="30,70"]
|===
| ノード 3 の場合... | 作業 


| UTA/UTA2 カードまたは UTA/UTA2 オンボード ポートを搭載 | へ移動<<ノード 3 の UTA / UTA2 ポートを確認して設定してください>> 


| UTA/UTA2 カードまたは UTA/UTA2 オンボード ポートがありません | _ノード3のUTA/UTA2ポートの確認と設定_をスキップして、link:reassign-node1-disks-to-node3.html["ノード1のディスクをノード3に再割り当て"] 。 
|===




== ノード 3 の UTA / UTA2 ポートを確認して設定してください

ノード 3 にオンボード UTA / UTA2 ポートまたは UTA / UTA2 カードが搭載されている場合は、アップグレードしたシステムの使用方法によって、ポートの設定を確認し、場合によっては再設定する必要があります。

.作業を開始する前に
UTA / UTA2 ポートに対応する正しい SFP+ モジュールが必要です。

.このタスクについて
FC にユニファイドターゲットアダプタ（ UTA / UTA2 ）ポートを使用する場合は、まずポートの設定を確認する必要があります。


NOTE: ネットアップのマーケティング資料では、 UTA2 という用語を CNA アダプタとポートという意味で使用している場合があります。ただし、 CLI では CNA という用語が使用されます。

使用することができます `ucadmin show`次の出力例に示すように、現在のポート構成を表示または確認するには、コマンドを使用します。

....
*> ucadmin show
         Current  Current    Pending   Pending      Admin
Adapter  Mode     Type       Mode      Type         Status
-------  -------  -------    --------  ----------   --------
0e      fc        target     -         initiator    offline
0f      fc        target     -         initiator    offline
0g      fc        target     -         initiator    offline
0h      fc        target     -         initiator    offline
1a      fc        target     -         -            online
1b      fc        target     -         -            online
6 entries were displayed.
....
UTA / UTA2 ポートは、ネイティブの FC モードまたは UTA / UTA2 モードに設定できます。FC モードでは FC イニシエータと FC ターゲットがサポートされます。 UTA / UTA2 モードを使用すると、同じ 10GbE SFP+ インターフェイスを共有する NIC と FCoE のトラフィックを同時に処理でき、 FC ターゲットをサポートできます。

アドオン アダプタまたはコントローラ マザーボード上に UTA/UTA2 ポートがあり、次の構成になっている場合がありますが、ノード 3 の UTA/UTA2 ポートの構成を確認し、必要に応じて変更する必要があります。

* コントローラを注文した UTA / UTA2 カードは、注文したパーソナリティを指定するために出荷前に設定されます。
* コントローラとは別に発注した UTA / UTA2 カードは、デフォルトの FC ターゲットパーソナリティとして出荷されます。
* 新しいコントローラのオンボード UTA / UTA2 ポートは、希望するパーソナリティを持つように出荷する前に設定されます。
+

WARNING: UTA/UTA2 ポートを構成するには、メンテナンス モードになっている必要があります。このセクションのコマンドをメンテナンス モードのシェル プロンプトで入力します。



.手順
. 現在の SFP+ モジュールが目的の用途と一致しない場合は、正しい SFP+ モジュールに交換します。
+
ネットアップの担当者に連絡して、正しい SFP+ モジュールを入手します。

. UTA/UTA2 ポート設定を確認します。
+
ucadmin show

+
出力を調べて、UTA/UTA2 ポートに必要な特性があるかどうかを判断します。

+
次の例の出力は、アダプタ「1b」のタイプがイニシエーターに変更され、アダプタ「2a」と「2b」のモードが「cna」に変更されていることを示しています。  CNA モードでは、カードをネットワーク アダプタとして使用できます。

+
[listing]
----
*> ucadmin show
         Current    Current     Pending  Pending     Admin
Adapter  Mode       Type        Mode     Type        Status
-------  --------   ----------  -------  --------    --------
1a       fc         initiator   -        -           online
1b       fc         target      -        initiator   online
2a       fc         target      cna      -           online
2b       fc         target      cna      -           online
*>
----
. 次のいずれかを実行します。
+
[cols="30,70"]
|===
| UTA / UTA2 ポート | 次に、 


| 希望するパーソナリティがない | 行きます <<auto_check3_step4,手順 4>>。 


| あなたがほしい人格を持っている | ステップ4からステップ8をスキップして、<<auto_check3_step9,手順 9>> 。 
|===
. [[auto_check3_step4]]次のいずれかのアクションを実行します。
+
[cols="30,70"]
|===
| を設定する場合 | 次に、 


| UTA / UTA2 カードのポート | へ移動<<auto_check3_step5,手順 5>> 


| オンボードの UTA/UTA2 ポート | ステップ5をスキップして<<auto_check3_step6,手順 6>>。 
|===
. [[auto_check3_step5]]アダプタがイニシエーターモードであり、UTA/UTA2 ポートがオンラインの場合は、UTA/UTA2 ポートをオフラインにします。
+
`storage disable adapter <adapter_name>`

+
ターゲットモードのアダプタは、メンテナンスモードで自動的にオフラインになります。

. [[auto_check3_step6]]現在の構成が目的の用途と一致しない場合は、必要に応じて構成を変更します。
+
`ucadmin modify -m fc|cna -t initiator|target <adapter_name>`

+
** 「 -m 」はパーソナリティ・モードで、「 fc 」または「 cna 」です。
** `-t` は FC4 のタイプ、「 target 」または「 initiator 」です。
+

NOTE: テープ ドライブおよびMetroCluster構成には FC イニシエーターを使用する必要があります。  SAN クライアントには FC ターゲットを使用する必要があります。



. 各ポートに対して次のコマンドを 1 回ずつ入力して、ターゲット ポートをオンラインにします。
+
`storage enable adapter <adapter_name>`

. ポートをケーブル接続します。


[[auto_check3_step9]]
. メンテナンスモードを終了します。
+
「 halt 」

. [[step14]]ノードをブートメニューでブートします。
+
「 boot_ontap menu



.次の手順
* AFF A800システムにアップグレードする場合は、link:reassign-node1-disks-to-node3.html#reassign-node1-node3-app-step9["ノード1のディスクをノード3に再割り当て（手順9）"] 。
* その他のシステムアップグレードについては、link:reassign-node1-disks-to-node3.html["ノード1のディスクをノード3に再割り当て（手順1）"] 。

