---
sidebar: sidebar 
permalink: upgrade-arl-auto-app/set_fc_or_uta_uta2_config_on_node3.html 
keywords: setting, fc, uta, uta2 configuration, node 
summary: 'ONTAP 9.8 以降を実行しているコントローラをアップグレードするときに "system controller replace" コマンドを使用して " オンボード FC ポート "UTA/UTA2 ポート " または UTA/UTA2 カードをノード 3 に設定します' 
---
= ノード 3 で FC または UTA / UTA2 設定を設定します
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
ノード 3 にオンボードの FC ポート、オンボードのユニファイドターゲットアダプタ（ UTA / UTA2 ）ポート、または UTA / UTA2 カードがある場合は、残りの手順を完了する前に設定を行う必要があります。

.このタスクについて
セクションの完了が必要な場合があります <<ノード 3 の FC ポートを設定>>、を参照してください <<ノード 3 の UTA / UTA2 ポートを確認して設定してください>>、または両方のセクション。


NOTE: ネットアップのマーケティング資料では、 Converged Network Adapter （ CNA ；統合ネットワークアダプタ）アダプタおよびポートを UTA2 と呼ぶ場合があります。ただし、 CLI では CNA という用語が使用されます。

* ストレージディスクを搭載したシステムをアップグレードする場合、ノード3にオンボードFCポート、オンボードUTA / UTA2ポート、またはUTA / UTA2カードがない場合は、に進みます。link:reassign-node1-disks-to-node3.html["ノード1のディスクをノード3に再割り当て"]
* ただし、Vシリーズシステムまたはストレージアレイを搭載したFlexArray仮想化ソフトウェアを搭載したシステムで、node3にオンボードFCポート、オンボードUTA / UTAポート、またはUTA / UTA2カードがない場合は、_Installに戻り、node3_をブートしてから手順を再開します。link:install_boot_node3.html#auto_install3_step23["手順 23"]




== ノード 3 の FC ポートを設定

node3 にオンボードまたは FC アダプタの FC ポートがある場合は、ポートが事前に設定されていないため、ノードを稼働状態にする前にポート設定を設定する必要があります。ポートが設定されていないと、サービスが停止する可能性があります。

.作業を開始する前に
セクションに保存した FC ポート設定の値を node1 で確認しておく必要があります link:prepare_nodes_for_upgrade.html["ノードをアップグレードする準備をします"]。

.このタスクについて
システムに FC 構成がない場合は、このセクションをスキップしてかまいません。システムにオンボード UTA / UTA2 ポートまたは UTA / UTA2 カードがある場合は、で設定します <<ノード 3 の UTA / UTA2 ポートを確認して設定してください>>。


IMPORTANT: システムにストレージディスクがある場合は、クラスタプロンプトでこのセクションのコマンドを入力します。「 V シリーズシステム」または FlexArray 仮想化ソフトウェアを使用していて、ストレージアレイに接続している場合は、このセクションにメンテナンスモードでコマンドを入力します。

. [[step1] ノード 3 の FC 設定を、ノード 1 から前に取得した設定と比較します。
. [[step2]] 次のいずれかの操作を実行します。
+
[cols="30,70"]
|===
| アップグレードするシステム | 次に、 


| ストレージディスクがあります  a| 
メンテナンスモード（ブートメニューのオプション 5 ）で、必要に応じてノード 3 の FC ポートを変更します。

** ターゲットポートをプログラムする場合：


ucadmin modify -m fc -t target_adapter_`

** イニシエータポートをプログラミングする場合：


ucadmin modify -m fc -t initiator_adapter_`

`-t` は FC4 のタイプで ' ターゲットまたはイニシエータです



| は、 V シリーズシステムまたは FlexArray 仮想化ソフトウェアを搭載し、ストレージアレイに接続されています  a| 
メンテナンスモード（ブートメニューのオプション 5 ）で、必要に応じてノード 3 の FC ポートを変更します。

`ucadmin modify -m fc -t initiator -f _adapter_port_name_`

`-t` は、FC4タイプ、ターゲット、イニシエータです。


NOTE: FCポートはイニシエータとしてプログラムする必要があります。

|===
. [[step3]] 次のいずれかの操作を実行します。
+
[cols="30,70"]
|===
| アップグレードするシステム | 次に、 


| ストレージディスクがあります | 次のコマンドを使用して、新しい設定を確認します。 ucadmin show 


| は、 V シリーズシステムまたは FlexArray 仮想化ソフトウェアを搭載し、ストレージアレイに接続されています | 次のコマンドを使用して、新しい設定を確認します。 ucadmin show 
|===
. [[step4]] メンテナンスモードを終了します。
+
「 halt 」

. LOADERプロンプトからシステムをブートします。
+
「 boot_ontap menu

. [[step6] コマンドを入力したら、ブート環境のプロンプトでシステムが停止するまで待ちます。
. 保守モードのブート・メニューからオプション「 5 」を選択します。


. [[auto_check3_step8] 次のいずれかの操作を実行します
+
|===
| アップグレードするシステム | 次に、 


| ストレージディスクがあります  a| 
** ノード 3 に UTA / UTA2 カードまたは UTA / UTA2 オンボードポートがある場合は、に進みます <<ノード 3 の UTA / UTA2 ポートを確認して設定してください>>。
** ノード3にUTA / UTA2カードまたはUTA / UTA2オンボードポートがない場合は、ノード3_のUTA / UTA2ポートを設定してに進みます。link:reassign-node1-disks-to-node3.html["ノード1のディスクをノード3に再割り当て"]




| は、 V シリーズシステムまたは FlexArray 仮想化ソフトウェアを搭載し、ストレージアレイに接続されています  a| 
** ノード 3 に UTA / UTA2 カードまたは UTA / UTA2 オンボードポートがある場合は、に進みます <<ノード 3 の UTA / UTA2 ポートを確認して設定してください>>。
** ノード3にUTA / UTA2カードまたはUTA / UTA2オンボードポートがない場合は、ノード3_のUTA / UTA2ポートを設定してから_に戻ってノード3_のインストールとブートを行ってから、の手順を再開します。link:install_boot_node3.html#auto_install3_step23["手順 23"]


|===




== ノード 3 の UTA / UTA2 ポートを確認して設定してください

ノード 3 にオンボード UTA / UTA2 ポートまたは UTA / UTA2 カードが搭載されている場合は、アップグレードしたシステムの使用方法によって、ポートの設定を確認し、場合によっては再設定する必要があります。

.作業を開始する前に
UTA / UTA2 ポートに対応する正しい SFP+ モジュールが必要です。

.このタスクについて
FC にユニファイドターゲットアダプタ（ UTA / UTA2 ）ポートを使用する場合は、まずポートの設定を確認する必要があります。


NOTE: ネットアップのマーケティング資料では、 UTA2 という用語を CNA アダプタとポートという意味で使用している場合があります。ただし、 CLI では CNA という用語が使用されます。

現在のポート設定を確認するには、「 ucadmin show 」コマンドを使用します。

....
*> ucadmin show
         Current  Current    Pending   Pending      Admin
Adapter  Mode     Type       Mode      Type         Status
-------  -------  -------    --------  ----------   --------
0e      fc        target     -         initiator    offline
0f      fc        target     -         initiator    offline
0g      fc        target     -         initiator    offline
0h      fc        target     -         initiator    offline
1a      fc        target     -         -            online
1b      fc        target     -         -            online
6 entries were displayed.
....
UTA / UTA2 ポートは、ネイティブの FC モードまたは UTA / UTA2 モードに設定できます。FC モードでは FC イニシエータと FC ターゲットがサポートされます。 UTA / UTA2 モードを使用すると、同じ 10GbE SFP+ インターフェイスを共有する NIC と FCoE のトラフィックを同時に処理でき、 FC ターゲットをサポートできます。

UTA / UTA2 ポートはアダプタまたはコントローラに搭載されている場合がありますが、次の構成になっています。ノード 3 の UTA / UTA2 ポートの設定を確認し、必要に応じて変更してください。

* コントローラを注文した UTA / UTA2 カードは、注文したパーソナリティを指定するために出荷前に設定されます。
* コントローラとは別に発注した UTA / UTA2 カードは、デフォルトの FC ターゲットパーソナリティとして出荷されます。
* 新しいコントローラのオンボード UTA / UTA2 ポートは、希望するパーソナリティを持つように出荷する前に設定されます。
+

WARNING: * 注意 * ：ストレージディスクがある場合は、メンテナンスモードに指示されていないかぎり、クラスタプロンプトでこのセクションのコマンドを入力します。V シリーズシステムまたは FlexArray 仮想化ソフトウェアがインストールされていて、ストレージアレイに接続されている場合は、このセクションのメンテナンスモードプロンプトでコマンドを入力します。UTA / UTA2 ポートを設定する場合は、メンテナンスモードにする必要があります。



.手順
. [[step1] node3 で次のコマンドを入力して、ポートが現在どのように設定されているかを確認します。
+
[cols="30,70"]
|===
| システムの状態 | 次に、 


| ストレージディスクがあります | 対処は不要です。 


| は、 V シリーズシステムまたは FlexArray 仮想化ソフトウェアを搭載し、ストレージアレイに接続されています | ucadmin show 
|===
+
次の例のような出力が表示されます。

+
....
*> ucadmin show
         Current  Current     Pending   Pending    Admin
Adapter  Mode     Type        Mode      Type       Status
-------  -------  ---------   -------   --------   ---------
0e      fc        initiator   -         -          online
0f      fc        initiator   -         -          online
0g      cna       target      -         -          online
0h      cna       target      -         -          online
0e      fc        initiator   -         -          online
0f      fc        initiator   -         -          online
0g      cna       target      -         -          online
0h      cna       target      -         -          online
*>
....
. [[step2] 現在の SFP+ モジュールが目的の用途と一致しない場合は、正しい SFP+ モジュールと交換します。
+
ネットアップの担当者に連絡して、正しい SFP+ モジュールを入手します。

. [[step3]] 「 ucadmin show 」コマンドの出力を調べ、 UTA / UTA2 ポートに希望するパーソナリティがあるかどうかを確認します。
. [[step4]] 次のいずれかの操作を実行します。
+
[cols="30,70"]
|===
| UTA / UTA2 ポート | 次に、 


| 希望するパーソナリティがない | に進みます <<auto_check3_step5,手順 5>>。 


| あなたがほしい人格を持っている | 手順 5 から 12 を省略して、に進みます <<auto_check3_step13,手順 13>>。 
|===
. [[auto_check3_step5] 次のいずれかの操作を実行します。
+
[cols="30,70"]
|===
| を設定する場合 | 次に、 


| UTA / UTA2 カードのポート | に進みます <<auto_check3_step7,手順 7>> 


| オンボードの UTA/UTA2 ポート | 手順 7 を省略して、に進みます <<auto_check3_step8,手順 8>>。 
|===
. [[step6] アダプタがイニシエータモードの場合、および UTA / UTA2 ポートがオンラインの場合は、 UTA / UTA2 ポートをオフラインにします。
+
storage disable adapter_adapter_adapter_adapter_name_`

+
ターゲットモードのアダプタは、メンテナンスモードで自動的にオフラインになります。

. [[auto_check3_step7] 現在の構成が目的の用途に一致しない場合は、必要に応じて構成を変更します。
+
ucadmin modify -m fc | cna-t initiator | target_adapter_name_`

+
** 「 -m 」はパーソナリティ・モードで、「 fc 」または「 cna 」です。
** `-t` は FC4 のタイプ、「 target 」または「 initiator 」です。
+

NOTE: テープドライブ、 FlexArray 仮想化システム、および MetroCluster 構成には、 FC イニシエータを使用する必要があります。SAN クライアントには FC ターゲットを使用する必要があります。



. [[auto_check3_step8] 設定を確認します。
+
ucadmin show

. [[step9] 設定を確認します。
+
[cols="30,70"]
|===
| システムの状態 | 次に、 


| ストレージディスクがあります | ucadmin show 


| は、 V シリーズシステムまたは FlexArray 仮想化ソフトウェアを搭載し、ストレージアレイに接続されています | ucadmin show 
|===
+
次の例の出力は ' アダプタ「 1b 」の FC4 タイプがイニシエータに変更され ' アダプタ「 2a 」および「 2b 」のモードが「 cna' 」に変更されていることを示しています

+
....
*> ucadmin show
         Current    Current     Pending  Pending     Admin
Adapter  Mode       Type        Mode     Type        Status
-------  --------   ----------  -------  --------    --------
1a       fc         initiator   -        -           online
1b       fc         target      -        initiator   online
2a       fc         target      cna      -           online
2b       fc         target      cna      -           online
*>
....
. [[step10]] 次のいずれかのコマンドを入力して、各ポートに 1 回ずつターゲットポートをオンラインにします。
+
[cols="30,70"]
|===
| システムの状態 | 次に、 


| ストレージディスクがあります | 「network fcp adapter modify -node node_name --adapter_adapter_adapter_adapter_name_-state up」の形式で指定します 


| は、 V シリーズシステムまたは FlexArray 仮想化ソフトウェアを搭載し、ストレージアレイに接続されています | 'fcp config_adapter_name_up' 
|===
. [[step11]] ポートをケーブル接続します。


. [[auto_check3_step12]] 次のいずれかの操作を実行します。
+
|===
| システムの状態 | 次に、 


| ストレージディスクがあります | にアクセスします。 


| は、 V シリーズシステムまたは FlexArray 仮想化ソフトウェアを搭載し、ストレージアレイに接続されています | _Installに戻ってnode3_をブートし、手順を再開しlink:install_boot_node3.html#auto_install3_step23["手順 23"]ます。 
|===
. [[auto_check3_step13]] メンテナンスモードを終了します。
+
「 halt 」

. [[step14]]を実行してノードをブートメニューにブートし `boot_ontap menu`ます。A800にアップグレードする場合は、に進みますlink:reassign-node1-disks-to-node3.html#reassign-node1-node3-app-step9["ノード1のディスクをノード3に再割り当て（手順9）"]。

