---
sidebar: sidebar 
permalink: upgrade-arl-auto-app/set_fc_or_uta_uta2_config_node4.html 
keywords: fc configuration, uta configuration, UTA2 configuration, configure FC ports, UTA/UTA2 card, node4, target, adapter, ports 
summary: 'ONTAP 9.8 以降を実行しているコントローラをアップグレードするときに "system controller replace" コマンドを使用して "node4 のオンボード FC ポート "UTA/UTA2 ポート " または UTA/UTA2 カードを設定します' 
---
= ノード 4 で FC または UTA / UTA2 設定を設定します
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
ノード 4 でオンボードの FC ポート、オンボードのユニファイドターゲットアダプタ（ UTA / UTA2 ）ポート、または UTA / UTA2 カードが使用されている場合は、残りの手順を完了する前に設定する必要があります。

.このタスクについて
セクションまたはその両方を完了する必要がある場合があります <<ノード 4 の FC ポートを設定します>> <<ノード 4 の UTA / UTA2 ポートを確認して設定してください>> 。

[NOTE]
====
ストレージディスクを搭載したシステムをアップグレードする場合、ノード4にオンボードFCポート、オンボードUTA / UTA2ポート、またはUTA / UTA2カードがない場合は、に進みます。link:reassign-node2-disks-to-node4.html["ノード2のディスクをノード4に再割り当てします。"]

ただし、Vシリーズシステムを使用しているかFlexArray仮想化ソフトウェアを使用していて、ストレージアレイに接続されていて、ノード4にオンボードFCポート、オンボードUTA / UTA2ポート、またはUTA / UTA2カードが搭載されてlink:install_boot_node4.html#step22["手順 22"]いない場合は、_のインストールとブートに戻って、node4_の手順を再開する必要があります。

ノード 4 に十分なラックスペースがあることを確認してください。node4 と node2 が別々のシャーシにある場合は、 node4 を node3 と同じ場所に配置できます。node2 と node4 が同じシャーシにある場合は、 node4 が適切なラックの場所にすでに存在しているとします。

====


== ノード 4 の FC ポートを設定します

ノード 4 にオンボードまたは FC アダプタのいずれかの FC ポートがある場合は、ポートが事前に構成されていないため、ノードを稼働状態にする前にポートの設定を行う必要があります。ポートが設定されていないと、サービスが停止する可能性があります。

.作業を開始する前に
セクションに保存した node2 の FC ポート設定の値を確認しておく必要があります link:prepare_nodes_for_upgrade.html["ノードをアップグレードする準備をします"]。

.このタスクについて
システムに FC 構成がない場合は、このセクションをスキップしてかまいません。システムにオンボード UTA / UTA2 ポートまたは UTA / UTA2 アダプタが搭載されている場合は、で設定します <<ノード 4 の UTA / UTA2 ポートを確認して設定してください>>。


IMPORTANT: システムにストレージディスクがある場合は、クラスタプロンプトでこのセクションのコマンドを入力する必要があります。V シリーズシステムまたは FlexArray 仮想化ソフトウェアがストレージアレイに接続されたシステムの場合は、このセクションのメンテナンスモードでコマンドを入力します。

.手順
. 次のいずれかを実行します。
+
[cols="30,70"]
|===
| アップグレードするシステム | 次に、 


| ストレージディスクがあります | 「 system node hardware unified-connect show 」を参照してください 


| は、 V シリーズシステムまたは FlexArray 仮想化ソフトウェアを搭載し、ストレージアレイに接続されています | ucadmin show 
|===
+
システムには、システム上のすべての FC アダプタと統合ネットワークアダプタに関する情報が表示されます。

. ノード 4 の FC 設定とノード 1 から前に取得した設定を比較します。
. 次のいずれかを実行します。
+
[cols="30,70"]
|===
| アップグレードするシステム | 次に、 


| ストレージディスクがあります  a| 
必要に応じて、ノード 4 の FC ポートを変更します。

** ターゲットポートをプログラムする場合：
+
ucadmin modify -m fc -t target_adapter_`

** イニシエータポートをプログラミングする場合：
+
ucadmin modify -m fc -t initiator_adapter_`



`-t` は FC4 のタイプで ' ターゲットまたはイニシエータです



| は、 V シリーズシステムまたは FlexArray 仮想化ソフトウェアを搭載し、ストレージアレイに接続されています  a| 
必要に応じて、ノード 4 の FC ポートを変更します。

`ucadmin modify -m fc -t initiator -f _adapter_port_name_`

`-t` は、FC4タイプ、ターゲット、イニシエータです。


NOTE: FCポートはイニシエータとしてプログラムする必要があります。

|===
. メンテナンスモードを終了します。
+
「 halt 」

. LOADERプロンプトからシステムをブートします。
+
「 boot_ontap menu

. コマンドを入力したら、ブート環境のプロンプトでシステムが停止するまで待ちます。
. 保守モードのブート・メニューからオプション「 5 」を選択します。


. [[step8]] 次のいずれかの操作を実行します。
+
[cols="30,70"]
|===
| アップグレードするシステム | 次に、 


| ストレージディスクがあります  a| 
** ノード4にUTA / UTA2カードまたはUTA / UTA2オンボードポートがない場合は、このセクションをスキップしてに進みますlink:reassign-node2-disks-to-node4.html["ノード2のディスクをノード4に再割り当てします。"]。




| は、 V シリーズシステムまたは FlexArray 仮想化ソフトウェアを搭載し、ストレージアレイに接続されています  a| 
** に進みます <<ノード 4 の UTA / UTA2 ポートを確認して設定してください>> ノード 4 に UTA / UTA2 カードまたは UTA / UTA2 オンボードポートがある場合
** スキップ_ノード4のUTA / UTA2ポートを確認して設定します。ノード4にUTA / UTA2カードまたはUTA / UTA2オンボードポートがない場合は、_に戻ってnode4_をインストールしてブートし、の手順を再開しますlink:install_boot_node4.html#auto_install4_step23["手順 23"]。


|===




== ノード 4 の UTA / UTA2 ポートを確認して設定してください

ノード 4 でオンボード UTA / UTA2 ポートまたは UTA / UTA2A カードが使用されている場合は、アップグレードしたシステムの使用方法に応じて、ポートの設定を確認して設定する必要があります。

.作業を開始する前に
UTA / UTA2 ポートに対応する正しい SFP+ モジュールが必要です。

.このタスクについて
UTA / UTA2 ポートは、ネイティブの FC モードまたは UTA / UT2A モードに設定できます。FC モードでは FC イニシエータと FC ターゲットがサポートされます。 UTA / UTA2 モードを使用すると、 NIC と FCoE の同時トラフィックで同じ 10GbE SFP+ インターフェイスを共有し、 FC ターゲットをサポートすることができます。


NOTE: ネットアップのマーケティング資料では、 UTA2 という用語を CNA アダプタとポートという意味で使用している場合があります。ただし、 CLI では CNA という用語が使用されます。

UTA / UTA2 ポートはアダプタまたはコントローラ上に次の構成で配置されます。

* UTA / UTA2 カードは、コントローラと同時に注文しても、希望するパーソナリティを持つ未設定の状態で出荷されます。
* コントローラとは別に発注した UTA / UTA2 カードは、デフォルトの FC ターゲットパーソナリティとして出荷されます。
* 新しいコントローラのオンボード UTA / UTA2 ポートは、要求したパーソナリティを持つように（出荷前に）設定されています。


ただし、ノード 4 の UTA / UTA2 ポートの設定を確認し、必要に応じて変更してください。


WARNING: * 注意 * ：ストレージディスクがある場合は、メンテナンスモードに指示されていないかぎり、クラスタプロンプトでこのセクションのコマンドを入力します。ストレージアレイに接続された MetroCluster FC システム、 V シリーズシステム、または FlexArray 仮想化ソフトウェアを搭載したシステムがある場合、 UTA / UTA2 ポートを設定するにはメンテナンスモードにする必要があります。

.手順
. ノード 4 で次のいずれかのコマンドを使用して、ポートが現在どのように設定されているかを確認します。
+
[cols="30,70"]
|===
| システムの状態 | 次に、 


| ストレージディスクがあります | 「 system node hardware unified-connect show 」を参照してください 


| は、 V シリーズシステムまたは FlexArray 仮想化ソフトウェアを搭載し、ストレージアレイに接続されています | ucadmin show 
|===
+
次の例のような出力が表示されます。

+
....
*> ucadmin show
                Current  Current    Pending   Pending   Admin
Node   Adapter  Mode     Type       Mode      Type      Status
----   -------  ---      ---------  -------   --------  -------
f-a    0e       fc       initiator  -          -        online
f-a    0f       fc       initiator  -          -        online
f-a    0g       cna      target     -          -        online
f-a    0h       cna      target     -          -        online
f-a    0e       fc       initiator  -          -        online
f-a    0f       fc       initiator  -          -        online
f-a    0g       cna      target     -          -        online
f-a    0h       cna      target     -          -        online
*>
....
. 現在の SFP+ モジュールが目的の用途と一致しない場合は、正しい SFP+ モジュールに交換します。
+
ネットアップの担当者に連絡して、正しい SFP+ モジュールを入手します。

. ucadmin show コマンドの出力結果を調べ、 UTA / UTA2 ポートが希望するパーソナリティに対応しているかどうかを確認します。
. 次のいずれかを実行します。
+
[cols="30,70"]
|===
| CNA ポートの状況 | 次に、 


| 希望するパーソナリティがない | に進みます <<auto_check_4_step5,手順 5>>。 


| あなたがほしい人格を持っている | 手順 5 から 12 を省略して、に進みます <<auto_check_4_step13,手順 13>>。 
|===
. [[auto_check_4_step5] 次のいずれかの操作を実行します。
+
[cols="30,70"]
|===
| を設定する場合 | 次に、 


| UTA / UTA2 カードのポート | に進みます <<auto_check_4_step7,手順 7>> 


| オンボードの UTA/UTA2 ポート | 手順 7 を省略して、に進みます <<auto_check_4_step8,手順 8>>。 
|===
. アダプタがイニシエータモードで、 UTA / UTA2 ポートがオンラインの場合は、 UTA / UTA2 ポートをオフラインにします。
+
storage disable adapter_adapter_adapter_adapter_name_`

+
ターゲットモードのアダプタは、メンテナンスモードで自動的にオフラインになります。

. [[auto_check_4_step7] 現在の構成が目的の用途に一致しない場合は、必要に応じて構成を変更します。
+
ucadmin modify -m fc | cna-t initiator | target_adapter_name_`

+
** 「 -m 」はパーソナリティ・モード、 FC または 10GbE UTA です。
** `-t` は FC4 のタイプ、「 target 」または「 initiator 」です。
+

NOTE: テープドライブ、 FlexArray 仮想化システム、および MetroCluster 構成には、 FC イニシエータを使用する必要があります。SAN クライアントには FC ターゲットを使用する必要があります。



. [[auto_check_4_step8] 次のコマンドを使用して設定を確認し、出力を調べます。
+
ucadmin show

. 設定を確認します。
+
[cols="40,60"]
|===
| システムの状態 | 次に、 


| ストレージディスクがあります | ucadmin show 


| は、 V シリーズシステムまたは FlexArray 仮想化ソフトウェアを搭載し、ストレージアレイに接続されています | ucadmin show 
|===
+
次の例の出力は ' アダプタ「 1b 」の FC4 タイプがイニシエータに変更され ' アダプタ「 2a 」および「 2b 」のモードが「 cna' 」に変更されていることを示しています

+
....
*> ucadmin show
Node  Adapter  Current Mode  Current Type  Pending Mode  Pending Type  Admin Status
----  -------  ------------  ------------  ------------  ------------  ------------
f-a   1a       fc             initiator    -             -             online
f-a   1b       fc             target       -             initiator     online
f-a   2a       fc             target       cna           -             online
f-a   2b       fc             target       cna           -             online
4 entries were displayed.
*>
....
. 次のいずれかのコマンドをポートごとに 1 回入力して、ターゲットポートをオンラインにします。
+
[cols="30,70"]
|===
| システムの状態 | 次に、 


| ストレージディスクがあります | 「network fcp adapter modify -node node_name --adapter_adapter_adapter_adapter_name_-state up」の形式で指定します 


| は、 V シリーズシステムまたは FlexArray 仮想化ソフトウェアを搭載し、ストレージアレイに接続されています | 'fcp config_adapter_name_up' 
|===
. ポートをケーブル接続します。


. [[step12]] 次のいずれかの操作を実行します。
+
[cols="30,70"]
|===
| システムの状態 | 次に、 


| ストレージディスクがあります | にアクセスします。 


| は、 V シリーズシステムまたは FlexArray 仮想化ソフトウェアを搭載し、ストレージアレイに接続されています | _Installに戻り、node4_をブートし、で再開しますlink:install_boot_node4.html#auto_install4_step23["手順 23"]。 
|===
. [[auto_check_4_step13]] メンテナンスモードを終了します。
+
「 halt 」

. [[step14]] ブートメニューからのノードのブート :
+
「 boot_ontap menu

+
A800にアップグレードする場合は、に進みますlink:reassign-node2-disks-to-node4.html#reassign-node2-node4-app-step9["ノード2のディスクをノード4に再割り当て（手順9）"]。


