---
sidebar: sidebar 
permalink: upgrade-arl-auto-app/stage_3_index.html 
keywords: installing, booting, node3, install, cluster, stage 3 
summary: ONTAP 9.8 以降を実行しているコントローラ上で system controller replace コマンドを使用して、 ARL アップグレードのステージ 3 プロセスシーケンスを実行します。 
---
= ステージ3の概要
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
ステージ3では、ノード3をインストールしてブートし、ノード1のクラスタポートとノード管理ポートがノード3でオンラインになったことを確認し、ノード1のディスクをノード3に再割り当てして、ノード3のインストールを確認します。NetApp Volume Encryption（NVE）を使用している場合は、キー管理ツールの設定をリストアします。必要に応じて、ノード3にFCまたはUTA / UTA2設定を設定します。さらに、node1のNASデータLIFとルート以外のアグリゲートをnode2からnode3に再配置し、SAN LIFがnode3にあることを確認します。

.手順
. link:install_boot_node3.html["node3 をインストールしてブートします"]
. link:set_fc_or_uta_uta2_config_on_node3.html["ノード 3 で FC または UTA / UTA2 設定を設定します"]
. link:reassign-node1-disks-to-node3.html["ノード1のディスクをノード3に再割り当て"]
. link:verify_node3_installation.html["ノード 3 のインストールを確認します"]
. link:restore_key-manager_configuration_node3.html["ノード 3 でキー管理ツールの設定をリストアします"]
. link:move_non-root_aggr_and_nas_data_lifs_node1_from_node2_to_node3.html["ノード 1 で所有されているルート以外のアグリゲートと NAS データ LIF を、ノード 2 からノード 3 に移動します"]

