---
sidebar: sidebar 
permalink: upgrade-arl-auto-affa900/cable-node1-for-shared-cluster-HA-storage.html 
keywords: cluster, ha, aff, a800, shared, storage, data, management 
summary: AFF A800 node1に接続していたクラスタ接続、HA接続、ストレージ接続、およびデータ接続を、新しく設置したAFF A90またはAFF A70 node1に接続します。 
---
= 共有クラスタHAとストレージのノード1をケーブル接続（AFF A800のアップグレードのみ）
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
以前AFF A800 node1に接続していたクラスタ、HA、ストレージ、データ、および管理の接続を、新しく設置したAFF A90またはAFF A70 node1に接続します。



== e0MポートとBMCポートを接続

AFF A800には管理ポート（e0M）とBMCポートがあります。AFF A90およびAFF A70では、e0MポートとBMCポートが組み合わされ、「レンチ」ポート経由でアクセスされます。AFF A90またはAFF A70に接続する前に、e0MポートとBMCポートがAFF A800の同じスイッチとサブネットに接続されていることを確認する必要があります。

[cols="35,65"]
|===
| 状況 | 作業 


| e0MとBMCのIPアドレスが同じIPサブネット上にある | AFF A800のe0MポートまたはBMCポートを、AFF A90またはAFF A70の「レンチ」ポートに接続します。 


| e0MとBMCのIPアドレスが別 々 のサブネットにあります  a| 
. e0MとBMCのIPアドレスを1つのIPサブネットにマージします。
. AFF A800のe0MポートまたはBMCポートを、AFF A90またはAFF A70の「レンチ」ポートに接続します。


|===


== 2ノードスイッチレスクラスタに接続

次の表に、2ノードスイッチレスクラスタ構成でのスイッチポートの用途を示します。

|===
| ポート | AFF A800ノード | AFF A90ノード | AFF A70ノード 


| クラスタ | e0a | e1a | e1a 


| クラスタ | e1a | e7a（e7aがない場合はe1bを使用） | e1b 


| はあ | e0b | 接続しない | 接続しない 


| はあ | e1b | 接続しない | 接続しない 


| SASストレージポート（存在し、使用している場合） | 使用可能な任意のポート | 使用可能な任意のポート | 使用可能な任意のポート 


| NS224シェルフのイーサネットストレージポート | 使用可能な任意のポート | イーサネットストレージ接続のマッピングを参照 | イーサネットストレージ接続のマッピングを参照 
|===


== スイッチ接続クラスタへの接続

スイッチ接続クラスタの場合は、次の要件を満たしていることを確認します。

* AFF A90ノードまたはAFF A70ノード上の同一のクラスタポートが同じスイッチ上にあります。たとえば、アップグレードが完了したら、node1のe1aとnode2のe1aを1つのクラスタスイッチに接続する必要があります。同様に、両方のノードの2番目のクラスタポートを2番目のクラスタスイッチに接続する必要があります。共有クラスタHAポート（ノード1のe1aがスイッチAに接続され、ノード2のe1aがスイッチBに接続されている）をクロス接続すると、HA通信に障害が発生します。
* AFF A90およびAFF A70ノードは、共有クラスタHAイーサネットポートを使用します。共有クラスタHAポートをサポートするリファレンス構成ファイル（RCF）がクラスタスイッチにインストールされていることを確認します。

