---
sidebar: sidebar 
permalink: upgrade-arl-auto-affa900/cable-node1-for-shared-cluster-HA-storage.html 
keywords: cluster, ha, aff, a800, shared, storage, data, management 
summary: AFF A800 node1に接続していたクラスタ接続、HA接続、ストレージ接続、およびデータ接続を、新しく設置したAFF A90またはAFF A70 node1に接続します。 
---
= 共有クラスタHAとストレージのノード1をケーブル接続します。
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
次のいずれかのアップグレードを実行する場合は、以前に既存のシステムのnode1に接続していたクラスタ、HA、ストレージ、データ、および管理の接続を、交換用システムの新しくインストールしたnode1に接続する必要があります。

[cols="35,65"]
|===
| 既存のシステム | 交換用システム 


| AFF A250用 | AFF A30、AFF A50 


| AFF C250用 | AFF C30、AFF C60 


| AFF A800用 | AFF A70、AFF A90 


| AFF C800用 | C80 
|===


== e0MポートとBMCポートを接続

既存のシステムに管理ポート（e0M）とBMCポートがある場合。交換用システムでは、e0MポートとBMCポートが組み合わされ、「レンチ」ポート経由でアクセスされます。交換用システムに接続する前に、e0MポートとBMCポートが既存システムの同じスイッチとサブネットに接続されていることを確認する必要があります。

[cols="35,65"]
|===
| 状況 | 作業 


| e0MとBMCのIPアドレスが同じIPサブネット上にある | 既存システムのe0MポートまたはBMCポートを、交換用システムの「レンチ」ポートに接続します。 


| e0MとBMCのIPアドレスが別 々 のサブネットにあります  a| 
. e0MとBMCのIPアドレスを1つのIPサブネットにマージします。
. 既存システムのe0MポートまたはBMCポートを、交換用システムの「レンチ」ポートに接続します。


|===


== 2ノードスイッチレスクラスタに接続

次の表に、2ノードスイッチレスクラスタ構成でのスイッチポートの用途を示します。

|===
| ポート | AFF A800、AFF C800 | AFF A90用 | AFF A70、AFF C80 


| クラスタ | e0a | e1a | e1a 


| クラスタ | e1a | e7a（e7aがない場合はe1bを使用） | e1b 


| はあ | e0b | 接続しない | 接続しない 


| はあ | e1b | 接続しない | 接続しない 


| SASストレージポート（存在し、使用している場合） | 使用可能な任意のポート | 使用可能な任意のポート | 使用可能な任意のポート 


| NS224シェルフのイーサネットストレージポート | 使用可能な任意のポート | イーサネットストレージ接続のマッピングを参照 | イーサネットストレージ接続のマッピングを参照 
|===
|===
| ポート | AFF A250、AFF C250 | AFF A30、AFF C30、AFF C60 | AFF A50用 


| クラスタトHA | e0c | e4a | e4a 


| クラスタトHA | e0d | e2a（e2aがない場合はe4bを使用） | e2a（e2aがない場合はe4bを使用） 


| イーサネットストレージポート | 使用可能な任意のポート | e3a、e3b | e3a、e3b 


| SASストレージポート | 使用可能な任意のポート | 3a、3b | 3a、3b 
|===


== スイッチ接続クラスタへの接続

スイッチ接続クラスタの場合は、AFF A30、AFF A50、AFF A70、AFF A90、AFF C30、AFF C60、またはAFF C80（交換用）ノードの次の要件を満たしていることを確認します。

* 交換用ノードの同一のクラスタポートが同じスイッチ上にあります。たとえば、アップグレードが完了したら、node1のe1aとnode2のe1aを1つのクラスタスイッチに接続する必要があります。同様に、両方のノードの2番目のクラスタポートを2番目のクラスタスイッチに接続する必要があります。共有クラスタHAポート（ノード1のe1aがスイッチAに接続され、ノード2のe1aがスイッチBに接続されている）をクロス接続すると、HA通信に障害が発生します。
* 交換用ノードは、共有のクラスタHAイーサネットポートを使用します。クラスタスイッチに、共有クラスタHAポートをサポートするリファレンス構成ファイル（RCF）がインストールされていることを確認します。

