---
sidebar: sidebar 
permalink: upgrade-arl-auto-affa900/decide_to_use_the_aggregate_relocation_guide.html 
keywords: deciding, aggregate, relocation, content, storage, controllers, administrators, ontap, ha, high, availability 
summary: 同じシャーシ内のコントローラモデルをアップグレードするARL手順を使用するかどうかを決定します。 
---
= アグリゲートの再配置手順を使用するかどうかを決定します
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
このコンテンツでは、既存のデータとディスクをすべて残したまま、HAペアのストレージコントローラをアップグレードする方法について説明します。これは複雑な手順であり、経験豊富な管理者のみが使用する必要があります。



== ARLのアップグレードでサポート

この手順は、次の状況で使用できます。

* コントローラのアップグレードがに表示されlink:index.html#supported-systems,["サポートされるシステムマトリックス"]ます。
* NetAppの営業担当者に、コントローラのアップグレードに必要なハードウェアが揃っていることを確認しておきます。
+
** AFF A90、AFF A70、またはAFF C80コントローラ×2、およびすべてのI/Oモジュール。100GbEケーブルに必要な長さ。
** AFF A50、AFF A30、AFF C30、またはAFF C60コントローラとI/Oモジュール×2必要なケーブル。
** ASA A150、AFF A150、またはFAS2820コントローラ
** ASA A900、AFF A900、またはFAS9500コントローラとNVRAMモジュールとそのパーツ


* アップグレードに必要な最小ONTAPバージョンを実行している。詳細については、を参照してください link:index.html["概要"]。
* 新しいコントローラを新しい HA ペアとしてクラスタに追加し、ボリューム移動を使用してデータを移行する必要はありません。
* ONTAP の管理経験があり、 diagnostic 権限モードで作業する場合のリスクが十分にあります。
* システムでONTAP 9.15.1以降が実行されており、イーサネットスイッチを使用してイーサネット接続ストレージに接続している。




== ARLのアップグレードではサポートされない

次の状況では、この手順を使用できません。

* アップグレードする既存のシステムでFlexArray仮想化ソフトウェアを使用している。
* MetroCluster IP設定をアップグレードしようとしています。
+
MetroCluster IP構成をアップグレードするには、MetroCluster Upgrade and Expansion_contentへのリンクを参照してくださいlink:other_references.html["参考資料"]。




NOTE: この手順 では、NetApp Storage Encryption（NSE）、NetApp Volume Encryption（NVE）、およびNetApp Aggregate Encryption（NAE）を使用できます。

コントローラハードウェアを別の方法でアップグレードして、ボリュームの移動を希望する場合は、を参照してください link:other_references.html["参考資料"] をクリックして、ボリュームまたは storage _ を移動して _ Upgrade にリンクします。

を参照してください link:other_references.html["参考資料"] から ONTAP 9 ドキュメントセンターにリンクして、 ONTAP 9 製品ドキュメントにアクセスできます。
