---
sidebar: sidebar 
permalink: upgrade-arl-auto-affa900/decide_to_use_the_aggregate_relocation_guide.html 
keywords: deciding, aggregate, relocation, content, storage, controllers, administrators, ontap, ha, high, availability, aff, a700, a900 
summary: ARL 手順 を使用して AFF A700 を AFF A900 にアップグレードするかどうかを決定します。 
---
= アグリゲートの再配置手順を使用するかどうかを決定します
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
このコンテンツでは、AFF A700 HAペアのストレージコントローラを、新しいAFF A900コントローラまたはFAS9000 HAペアのコントローラと新しいFAS9500コントローラとの間でアップグレードする方法について説明します。既存のデータとディスクはすべて維持されます。これは複雑な手順であり、経験豊富な管理者のみが使用する必要があります。

この手順 は、次の状況で使用します。

* AFF A900またはFAS9500コントローラ、NVRAMモジュール、およびアップグレードに必要な部品を受け取ったことを、ネットアップの営業担当者に確認しておきます。
* ONTAP 9.11.1P6または9.10.1P10（2月2023日を対象）を実行している。
* 新しいコントローラを新しい HA ペアとしてクラスタに追加し、ボリューム移動を使用してデータを移行する必要はありません。
* ONTAP の管理経験があり、 diagnostic 権限モードで作業する場合のリスクが十分にあります。


Do * not * この手順 は、次の状況で使用します。

* AFF A700またはFAS9000システムでFlexArray 仮想化ソフトウェアを使用している。
* クラスタインターコネクトストレージとイーサネット接続ストレージに共有スイッチを使用している。


Fabric MetroCluster または MetroCluster IP 設定のアップグレードについては、を参照してください link:other_references.html["参考資料"] MetroCluster アップグレードおよび Expansion コンテンツにリンクするには、次の手順を実行します。


NOTE: この手順 では、NetApp Storage Encryption（NSE）、NetApp Volume Encryption（NVE）、およびNetApp Aggregate Encryption（NAE）を使用できます。

コントローラハードウェアを別の方法でアップグレードして、ボリュームの移動を希望する場合は、を参照してください link:other_references.html["参考資料"] をクリックして、ボリュームまたは storage _ を移動して _ Upgrade にリンクします。

を参照してください link:other_references.html["参考資料"] から ONTAP 9 ドキュメントセンターにリンクして、 ONTAP 9 製品ドキュメントにアクセスできます。
