---
sidebar: sidebar 
permalink: upgrade-arl-auto-affa900/decide_to_use_the_aggregate_relocation_guide.html 
keywords: deciding, aggregate, relocation, content, storage, controllers, administrators, ontap, ha, high, availability 
summary: 同じシャーシ内のコントローラモデルをアップグレードするARL手順を使用するかどうかを決定します。 
---
= アグリゲートの再配置手順を使用するかどうかを決定します
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
このコンテンツでは、既存のデータとディスクをすべて残したまま、HAペアのストレージコントローラをアップグレードする方法について説明します。これは複雑な手順であり、経験豊富な管理者のみが使用する必要があります。

この手順は、次の状況で使用できます。

* 次のいずれかのコントローラのアップグレードを実行している。
+
[cols="50,50"]
|===
| 古いコントローラ | 交換用コントローラ 


| AFF A800用 | AFF A70およびAFF A90 


| AFF A220をASAとして構成 | ASA A150 


| AFF A220、AFF A200、またはAFF C190 | AFF A150 


| FAS2620またはFAS2720 | FAS2820 


| AFF A700をASAとして構成 | ASA A900 


| AFF A700の略 | AFF A900 の略 


| FAS9000 | FAS9500 
|===
* NetAppの営業担当者に、コントローラアップグレード用のハードウェアが届いていることを確認しておきます。
+
** アップグレードに必要なAFF A90コントローラ×2またはAFF A70コントローラ×2、およびすべてのI/Oモジュール。100GbEケーブルに必要な長さ。
** ASA A150、AFF A150、またはFAS2820コントローラ
** ASA A900、AFF A900、またはFAS9500コントローラおよびNVRAMモジュールとアップグレードに必要なパーツ


* アップグレードに必要な最小ONTAPバージョンを実行している。詳細については、を参照してください link:index.html["概要"]。
* 新しいコントローラを新しい HA ペアとしてクラスタに追加し、ボリューム移動を使用してデータを移行する必要はありません。
* ONTAP の管理経験があり、 diagnostic 権限モードで作業する場合のリスクが十分にあります。


次の状況では、この手順を使用できません。

* AFF A800、AFF A700、またはFAS9000システムでFlexArray仮想化ソフトウェアを使用している。
* クラスタインターコネクトストレージとイーサネット接続ストレージに共有スイッチを使用している。


AFF A800、AFF A700、またはFAS9000システムでMetroCluster IP構成をアップグレードする方法については、「_ MetroCluster Upgrade and Expansion_content」へのリンクを参照してください link:other_references.html["参考資料"] 。


NOTE: この手順 では、NetApp Storage Encryption（NSE）、NetApp Volume Encryption（NVE）、およびNetApp Aggregate Encryption（NAE）を使用できます。

コントローラハードウェアを別の方法でアップグレードして、ボリュームの移動を希望する場合は、を参照してください link:other_references.html["参考資料"] をクリックして、ボリュームまたは storage _ を移動して _ Upgrade にリンクします。

を参照してください link:other_references.html["参考資料"] から ONTAP 9 ドキュメントセンターにリンクして、 ONTAP 9 製品ドキュメントにアクセスできます。
