---
sidebar: sidebar 
permalink: upgrade-arl-auto-affa900/ensure_new_controllers_are_set_up_correctly.html 
keywords: ensure, controllers, new, setup, ha, pair, node1, node2, lif, cluster, high, availability 
summary: HA ペアが有効になっていることを確認し、ノード 1 とノード 2 のストレージアクセスと LIF を確認し、 AFF A700 を AFF A900 にアップグレードしたあとにアグリゲートの所有権を確認します。 
---
= 新しいコントローラが正しくセットアップされていることを確認します
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
正しいセットアップを確認するには、 HA ペアが有効になっていることを確認する必要があります。さらに、 node1 と node2 が相互のストレージにアクセスできること、およびクラスタ上の他のノードに属するデータ LIF を所有していないことを確認する必要があります。また、すべてのデータアグリゲートが正しいホームノードにあり、両方のノードのボリュームがオンラインであることを確認する必要があります。新しいノードの 1 つにユニファイドターゲットアダプタがある場合は、ポート設定をすべてリストアする必要があり、場合によってはアダプタの使用方法の変更が必要になることがあります。

.手順
. node2 のチェック後、 node2 クラスタのストレージフェイルオーバーとクラスタ HA ペアが有効になります。処理が完了すると、両方のノードに「 Completed 」と表示され、クリーンアップ処理が実行されます。
. ストレージフェイルオーバーが有効になっていることを確認します。
+
「 storage failover show 」をクリックします

+
次の例は、ストレージフェイルオーバーが有効になっている場合のコマンドの出力例を示しています。

+
[listing]
----
cluster::> storage failover show
                                Takeover
Node	         Partner	        Possible	      State Description
-------------  --------------   --------------  ------------------
node1	         node2            true	           Connected to node2
node2	         node1            true	           Connected to node1
----
. 次のコマンドを使用して出力を調べ、 node1 と node2 が同じクラスタに属していることを確認します。
+
「 cluster show 」を参照してください

. 次のコマンドを使用して、 node1 と node2 が相互のストレージにアクセスできることを確認します。
+
「 storage failover show -fields local-missing-disks 、 partner-missing-disks 」というメッセージが表示されます

. 次のコマンドを使用して、 node1 と node2 のどちらもクラスタ内の他のノードがホーム所有するデータ LIF を所有していないことを確認します。
+
「 network interface show 」を参照してください

+
クラスタ内の他のノードがホーム所有するデータ LIF をノード 1 とノード 2 のどちらも所有していない場合は、データ LIF をホーム所有者にリバートします。

+
「 network interface revert 」の略

. アグリゲートがそれぞれのホームノードで所有されていることを確認します。
+
storage aggregate show-owner-name_node1_`

+
storage aggregate show-owner-name_node2_`

. オフラインになっているボリュームがないかを確認します。
+
volume show -node node1 __-state offline`

+
volume show -node-node2 --状態オフライン

. オフラインになっているボリュームがある場合は、セクションで取得したオフラインボリュームのリストと比較します link:prepare_nodes_for_upgrade.html["ノードをアップグレードする準備をします"]必要に応じて、次のコマンドを使用して、ボリュームごとに 1 回、オフラインボリュームをオンラインにします。
+
'volume online -vserver_name_-volume_name_`

. ノードごとに次のコマンドを使用して、新しいノードの新しいライセンスをインストールします。
+
'system license add -license-code_license_code'license_code'license_code..._`

+
license-code パラメータには、アルファベットの文字キーをアルファベットの大文字 28 個まで入力できます。ライセンスは一度に 1 つずつ追加することも、複数追加することもできます。各ライセンスキーをカンマで区切って指定することもできます。

. 次のいずれかのコマンドを使用して、元のノードから古いライセンスをすべて削除します。
+
「システムライセンスのクリーンアップ - 未使用 - 期限切れ」

+
'system license delete -serial-number_node_name --package_license_package_`

+
--
** 期限切れのライセンスをすべて削除します。
+
「システムライセンスのクリーンアップ - 期限切れ」

** 未使用のライセンスをすべて削除します。
+
'System license clean-up-unused （システムライセンスのクリーンアップ - 未使用） '

** クラスタから特定のライセンスを削除するには、ノードで次のコマンドを使用します。
+
'system license delete -serial-number_node1_serial_number_-package *`system license delete -serial-number_node2 _serial_number_-package *`



--
+
次の出力が表示されます。

+
[listing]
----
Warning: The following licenses will be removed:
<list of each installed package>
Do you want to continue? {y|n}: y
----
+
すべてのパッケージを削除するには 'y' を入力します

. 次のコマンドを使用して出力を調べ、ライセンスが正しくインストールされていることを確認します。
+
「 system license show 」を参照してください

+
でキャプチャした出力と比較できます link:prepare_nodes_for_upgrade.html["ノードをアップグレードする準備をします"] セクション。

. 構成にNetApp Storage Encryption（NSE）を使用していた場合、「setenv bootarg.storageencryption.support」コマンドを「kmip.init.maxwait`」変数を「true」に設定します（AFF A900またはFAS9500コントローラとNVRAMモジュールを搭載したin_bootnode2）。 link:boot_node2_with_a900_controller_and_nvs.html#A900_boot_node2["手順 1."]）を使用している場合は、変数をリセットする必要があります
+
`set diag; systemshell -node-node_name --コマンドsudo kenv -u -p kmip.init.maxwait`

. 両方のノードで次のコマンドを使用して SP を設定します。
+
system service-processor network modify -node _node_name _`

+
を参照してください link:other_references.html["参考資料"] SP および _SP ONTAP 9 コマンドの詳細については ' システム管理リファレンスにリンクするには ' マニュアルページリファレンスを参照してください system の service-processor network modify コマンドの詳細については ' を参照してください

. 新しいノードの 1 つで次の操作を実行します。
+
.. advanced 権限レベルに切り替えます。
+
「 advanced 」の権限が必要です

.. 次のコマンドを入力します。
+
storage failover modify -node _node_name --CIFS-NDO -duration _default | medium | low_`

+
*** システムのワークロードが 50% ～ 75% の場合は、「 m edium 」と入力します。
*** システムのワークロードが 75% ～ 100% の場合は 'low' と入力します


.. admin レベルに戻ります。
+
「特権管理者」

.. システムをリブートして、変更が有効になっていることを確認します。


. 新しいノードにスイッチレスクラスタをセットアップする場合は、を参照してください link:other_references.html["参考資料"] ネットアップサポートサイトへのリンクを設定するには、 _ 2 ノードスイッチレスクラスタへの移行の手順に従ってください。


ノード 1 とノード 2 でストレージ暗号化が有効になっている場合は、セクションを完了します link:set_up_storage_encryption_new_module.html["新しいコントローラモジュールで Storage Encryption をセットアップします"]。それ以外の場合は、の項を実行します link:decommission_old_system.html["古いシステムの運用を停止"]。
