---
sidebar: sidebar 
permalink: upgrade-arl-auto-affa900/guidelines_for_upgrading_controllers_with_arl.html 
keywords: guidelines, upgrade, ontap, controllers, old, system, chassis, disk, disks 
summary: アップグレード構成にARLを使用できるかどうかを確認します。古いシステムシャーシとディスクはそのまま使用できます。 
---
= コントローラのアップグレードに関するガイドラインを参照してください
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
アグリゲートの再配置（ARL）を使用して古いシステムシャーシとディスクを維持できるかどうかを理解するには、システムのアップグレード構成とONTAPのバージョンによって異なります。



== ARL のアップグレードがサポートされます

特定のシステム構成では、コントローラのアップグレードがサポートされます。サポートされるシステムとONTAPの最小バージョンの一覧については、を参照してください link:index.html["概要"]。

新しいシャーシを含む完全なシステムとして新しいAFF A30、AFF A150 A50、AFF A70、AFF、AFF、AFF A900、AFF A90 C30、AFF C60、AFF C80、FAS2820、またはFAS9500を受け取った場合は、「system controller replace」コマンドを参照して、link:other_references.html["参考資料"]ONTAP 9.8以降を実行しているコントローラハードウェアをアップグレードしてください_。

ARL を使用したコントローラのアップグレードは、 SnapLock Enterprise ボリュームおよび SnapLock Compliance ボリュームが設定されたシステムでサポートされます。



== 2 ノードスイッチレスクラスタ

2 ノードスイッチレスクラスタのノードをアップグレードする場合は、アップグレードの実行中もスイッチレスクラスタのノードをそのまま使用できます。スイッチクラスタに変換する必要はありません。



== スイッチ接続のクラスタ

クラスタスイッチに接続されたクラスタ内のノードをアップグレードする場合は、スイッチで実行されているmake、model、ファームウェアバージョン、RCF、およびONTAPのバージョンが、アップグレード後に交換用コントローラで実行されているバージョンと同じになることを確認する必要があります。必要に応じて、このドキュメントに記載されているARL手順を使用してコントローラをアップグレードする前にスイッチのアップグレードを実行する必要があります。



== トラブルシューティングを行う

コントローラのアップグレード中に問題が発生した場合は、を参照してください link:troubleshoot_index.html["トラブルシューティングを行う"] 詳細および解決策については、手順の末尾にあるセクションを参照してください。

発生した問題に対する解決策 が見つからない場合は、テクニカルサポートにお問い合わせください。
