---
sidebar: sidebar 
permalink: upgrade-arl-auto-affa900/guidelines_for_upgrading_controllers_with_arl.html 
keywords: guidelines, upgrade, aff, a900, a700, ontap, controllers 
summary: ARL を使用して AFF A700 を AFF A900 にアップグレードできるかどうかを確認します。 
---
= コントローラのアップグレードに関するガイドラインを参照してください
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ARLを使用して、次のシステム構成のコントローラのペアをアップグレードします。

* ONTAP 9.10.1以降を実行しているAFF A900システムにAFF A700コントローラのペアをアップグレードします
* ONTAP 9.10.1P3以降を実行しているFAS9500システムにFAS9000コントローラのペアをアップグレードします




== ARL のアップグレードがサポートされます

AFF A700からAFF A900へのコントローラのアップグレード、またはARLを使用したFAS9000からFAS9500へのコントローラのアップグレードでは、NVRAMモジュールがサポートされています。新しいシャーシを含む完全なシステムとしてAFF A900またはFAS9500システムが新規に購入された場合は、を参照してください link:other_references.html["参考資料"] ONTAP 9.8 以降の _content を実行しているコントローラハードウェアをアップグレードするには、 "system controller replace" コマンドを使用してください。


WARNING: この手順 は、厳密に環境 ONTAP 9.10.1以降を実行するAFF A700からAFF A900へのアップグレード、および9.10.1P3以降を実行するFAS9000からFAS9500へのアップグレードです。他のシステムの組み合わせのアップグレードには、この手順 を使用しないでください。

ARL を使用したコントローラのアップグレードは、 SnapLock Enterprise ボリュームおよび SnapLock Compliance ボリュームが設定されたシステムでサポートされます。



== 2 ノードスイッチレスクラスタ

2 ノードスイッチレスクラスタのノードをアップグレードする場合は、アップグレードの実行中もスイッチレスクラスタのノードをそのまま使用できます。スイッチクラスタに変換する必要はありません。



== トラブルシューティングを行う

コントローラのアップグレード中に問題が発生した場合は、を参照してください link:troubleshoot_index.html["トラブルシューティングを行う"] 詳細および解決策については、手順の末尾にあるセクションを参照してください。

発生した問題に対する解決策 が見つからない場合は、テクニカルサポートにお問い合わせください。
