---
sidebar: sidebar 
permalink: upgrade-arl-auto-affa900/guidelines_for_upgrading_controllers_with_arl.html 
keywords: guidelines, upgrade, aff, a900, a700, ontap, controllers 
summary: ARL を使用して AFF A700 を AFF A900 にアップグレードできるかどうかを確認します。 
---
= ARL を使用した AFF A700 から AFF A900 へのアップグレードに関するガイドライン
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ARL を使用して、 ONTAP 9.10.1 以降を実行する AFF A700 コントローラのペアを AFF A900 システムにアップグレードするには、システムと、元のコントローラと交換用コントローラの両方の構成が必要です。



== ARL のアップグレードがサポートされます

ARL を使用して AFF A900 にアップグレードし、コントローラモジュールと NVRAM モジュールのみを交換する方法は、 ARL でサポートされる組み合わせです。 AFF新しいシャーシを含む、完全なシステムとして新しい AFF A900 システムを購入した場合は、を参照してください link:other_references.html["参考資料"] ONTAP 9.8 以降の _content を実行しているコントローラハードウェアをアップグレードするには、 "system controller replace" コマンドを使用してください。


WARNING: この手順 は、環境 ONTAP 9.10.1 以降を実行している AFF A900 への AFF A700 のアップグレードに限定して提供されます。他のシステムの組み合わせのアップグレードには、この手順 を使用しないでください。

ARL を使用したコントローラのアップグレードは、 SnapLock Enterprise ボリュームおよび SnapLock Compliance ボリュームが設定されたシステムでサポートされます。



== 2 ノードスイッチレスクラスタ

2 ノードスイッチレスクラスタのノードをアップグレードする場合は、アップグレードの実行中もスイッチレスクラスタのノードをそのまま使用できます。スイッチクラスタに変換する必要はありません。



== トラブルシューティングを行う

コントローラのアップグレード中に問題が発生した場合は、を参照してください link:troubleshoot_index.html["トラブルシューティングを行う"] 詳細および解決策については、手順の末尾にあるセクションを参照してください。

発生した問題に対する解決策 が見つからない場合は、テクニカルサポートにお問い合わせください。
