---
sidebar: sidebar 
permalink: upgrade-arl-auto-affa900/index.html 
keywords: aggregate, relocation, controller, hardware, aggregates, flexarray, metrocluster, terminology, old, system, chassis, disk, disks 
summary: コントローラハードウェアをアップグレードするには、古いシステムを交換用システムに変換し、古いシステムのシャーシとディスクを残します。 
---
= 概要
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
この手順では、次のシステム構成のアグリゲートの再配置（ARL）を使用してHAペアのコントローラハードウェアを無停止でアップグレードする方法について説明します。手順によって古いシステムが交換用システムに変換され、古いシステムシャーシとディスクは維持されます。


WARNING: この手順は、以下のアップグレード構成を厳密に環境します。他のシステムの組み合わせ間でアップグレードを実行する場合は、この手順を使用しないでください。

[cols="20,20,40"]
|===
| 古いシステム | 交換用システム | サポートされるONTAPのバージョン 


| AFF A220をオールSANアレイ（ASA）として構成 | ASA A150 | 9.13.1P1以降 


| AFF A220の略 | AFF A150 | 9.10.1P15、9.11.1P11、9.12.1P5以降 


| AFF A200 | AFF A150  a| 
9.10.1P15、9.11.1P11以降


NOTE: AFF A200では、9.11.1よりもあとのバージョンのONTAPはサポートされません。



| AFF C190の略 | AFF A150 | 9.10.1P15、9.11.1P11、9.12.1P5以降 


| FAS2620 | FAS2820  a| 
9.11.1P7（FAS2620）


NOTE: FAS2620では、9.11.1よりあとのバージョンのONTAPはサポートされません。

9.13.1以降（FAS2820）



| FAS2720 | FAS2820 | 9.13.1以降 


| AFF A700をASAとして構成 | ASA A900 | 9.13.1P1以降 


| AFF A700の略 | AFF A900 の略 | 9.10.1P10、9.11.1P6以降 


| FAS9000 | FAS9500 | 9.10.1P10、9.11.1P6以降 
|===
[NOTE]
====
NetAppでは、可能であれば、古いシステムと交換用システムで同じONTAPバージョンを使用することを推奨しています。

上記の表のONTAPの最小バージョンは必須です。これらのバージョンのONTAPにはサービスプロセッサまたはベースボード管理コントローラ（BMC）のファームウェアバージョンが適用されています。このファームウェアバージョンは、アップグレード時にシャーシ内に異なるコントローラタイプを混在させるために必要です。

====
手順では、ルート以外のアグリゲートを古いコントローラノード間で移行します。インストールが完了したら、ルート以外のアグリゲートを古いコントローラノードから交換用コントローラノードに移行します。アップグレードするノードでホストされているデータには、アップグレード手順の実行中にアクセスできます。

.このタスクについて
このコントローラのアップグレード手順では、次のいずれかのアップグレードを実行します。

* 古いコントローラの各ノードのコントローラモジュールを新しいモジュールと交換します。この環境an AFF A220、AFF A200、AFF C190、FAS2620、FAS2720システムへのアップグレードです。
* 古いコントローラの各ノードのコントローラモジュールとNVRAMモジュールを新しいモジュールと交換します。この環境an AFF A700またはFAS9000システムのアップグレード。



NOTE: I/O カード、データケーブル、ディスクシェルフ、およびディスクを移動、切断、再接続する必要はありません。

この手順では、 Aggregate Relocation （ ARL ；アグリゲートの再配置）と呼ばれる方法を使用します。 ARL を使用すると、 HA 構成を活用して、ルート以外のアグリゲートの所有権をノード間で移動できます（ルートが同じクラスタ内のストレージを共有している場合）。

手順の実行中に、交換用コントローラハードウェアを使用して元のコントローラハードウェアをアップグレードし、ルート以外のアグリゲートの所有権を切り替えます。アグリゲートをノードからノードに複数回移行して、アップグレード手順 全体を通じて、少なくとも 1 つのノードがアグリゲートからデータを提供していることを確認します。処理を続行する前に、クラスタ内のノード間でデータ LIF を移行することもできます。


NOTE: このドキュメントでは、ノード名の参照としてのみ * node1 * と * node2 * という用語が使用されています。手順のあとにノードの実際の名前を置き換える必要があります。

.重要な情報
* この手順は複雑で、 ONTAP の高度な管理スキルがあることを前提としています。また、を読んで理解する必要があります link:guidelines_for_upgrading_controllers_with_arl.html["コントローラのアップグレードに関するガイドラインを参照してください"] および link:overview_of_the_arl_upgrade.html["ARL アップグレードの概要"] アップグレード開始前のセクション。
* この手順は、交換用コントローラハードウェアが新しく購入されていて、他のシステムで使用されていないことを前提としています。使用済みのコントローラを「 wipeconfig 」コマンドで準備するために必要な手順は、この手順には含まれていません。交換用コントローラハードウェアが以前に別の ONTAP クラスタまたはスタンドアロンのシングルノードシステムとして使用されていた場合は、テクニカルサポートにお問い合わせください。
* この手順を使用して、ノードが 3 つ以上あるクラスタのコントローラハードウェアをアップグレードできますが、クラスタ内の HA ペアごとに手順を個別に実行する必要があります。
* ONTAPのバージョンでサポートされていないスイッチおよびアップグレード先の交換用システムがある場合は、を参照してください link:other_references.html["参考資料"] Hardware Universe にリンクするには、次の手順を実行します。
* この手順専用 環境 AFF A200、AFF A220、AFF C190、FAS2620、FAS2720、 AFF A700およびFAS9000システム：AFF A150、FAS2820、AFF A900、またはFAS9500システムへのアップグレードが必要なその他すべてのコントローラモデルについては、を参照してください link:other_references.html["参考資料"] 「system controller replace」コマンドを使用して、ONTAP 9.8以降を実行しているコントローラハードウェアをアップグレードする方法_およびアグリゲートの再配置を使用して、ONTAP 9.8以降を実行しているコントローラハードウェアを手動でアップグレードする方法_へのリンク。
* ASA A900、AFF A900、およびFAS9500システムは、ハイライン電源（200V~240V）のみをサポートします。AFF A700またはFAS9000システムをローライン電源（100~120V）で実行している場合、この手順 を使用する前に、AFF A700またはFAS9000の入力電源を変換する必要があります。
* AFF A200、AFF A220、AFF C190、FAS2620、FAS2720からアップグレードする場合 ダウンタイムが発生するAFF A700またはFAS9000システムでは、ストレージを移動することでコントローラハードウェアをアップグレードするか、テクニカルサポートにお問い合わせください。を参照してください link:other_references.html["参考資料"] をクリックして、ボリュームまたは storage _ を移動して _ Upgrade にリンクします。




== コントローラのアップグレードプロセスを自動化する

この手順には、手順を自動化するための手順が用意されています。この手順では、自動ディスク割り当てとネットワークポートの到達可能性チェックを使用して、コントローラのアップグレードを簡易化します。
