---
sidebar: sidebar 
permalink: upgrade-arl-auto-affa900/index.html 
keywords: aggregate, relocation, controller, hardware, aggregates, flexarray, metrocluster, terminology, aff, a700, a900 
summary: AFF A700 のコントローラハードウェアを AFF A900 にアップグレードするには、コントローラモジュールと NVS を交換します。 
---
= 概要
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
この手順 では、次のシステム構成で Aggregate Relocation （ ARL ；アグリゲートの再配置）を使用してコントローラハードウェアをアップグレードする方法について説明します。

[cols="30,20,20,30"]
|===
| メソッド | ONTAP バージョン | サポートされるシステム | 説明 


| を使用します `system contlroller replace` コマンド | 9.11.1P6または9.10.1P10（2023年2月を目標） | AFF A700 から AFF A900 へ | AFF A700システムをAFF A900システムに変換し、A700シャーシを保管します 


| 「 system controller replace 」コマンドを使用します | 9.11.1P6または9.10.1P10（2023年2月を目標） | FAS9000からFAS9500へ | FAS9000システムをFAS9500システムに変換して、FAS9000シャーシを維持します。 
|===
ハイアベイラビリティ（HA）ペアのコントローラハードウェアは、コントローラとNVRAMモジュールを交換することで、無停止でアップグレードできます。最初に、ルート以外のアグリゲートを古いコントローラノード間で移行します。インストールが完了したら、ルート以外のアグリゲートを古いコントローラノードから交換用コントローラノードに移行します。アップグレードするノードでホストされているデータには、アップグレード手順の実行中にアクセスできます。

.このタスクについて
このコントローラのアップグレード手順 時に、AFF A700またはFAS9000システムの各ノードの2つのフィールド交換可能ユニット（FRU）を新しいFRUと交換する必要があります。


NOTE: I/O カード、データケーブル、ディスクシェルフ、およびディスクを移動、切断、再接続する必要はありません。

この手順では、 Aggregate Relocation （ ARL ；アグリゲートの再配置）と呼ばれる方法を使用します。 ARL を使用すると、 HA 構成を活用して、ルート以外のアグリゲートの所有権をノード間で移動できます（ルートが同じクラスタ内のストレージを共有している場合）。

手順の実行中に、交換用コントローラハードウェアを使用して元のコントローラハードウェアをアップグレードし、ルート以外のアグリゲートの所有権を切り替えます。アグリゲートをノードからノードに複数回移行して、アップグレード手順全体を通じて少なくとも 1 つのノードがアグリゲートからデータを提供していることを確認します。処理を続行する前に、クラスタ内のノード間でデータ LIF を移行することもできます。


NOTE: このドキュメントでは、ノード名の参照としてのみ * node1 * と * node2 * という用語が使用されています。手順のあとにノードの実際の名前を置き換える必要があります。

.重要な情報
* この手順は複雑で、 ONTAP の高度な管理スキルがあることを前提としています。また、を読んで理解する必要があります link:guidelines_for_upgrading_controllers_with_arl.html["コントローラのアップグレードに関するガイドラインを参照してください"] および link:overview_of_the_arl_upgrade.html["ARL アップグレードの概要"] アップグレード開始前のセクション。
* この手順は、交換用コントローラハードウェアが新しく購入されていて、他のシステムで使用されていないことを前提としています。使用済みのコントローラを「 wipeconfig 」コマンドで準備するために必要な手順は、この手順には含まれていません。交換用コントローラハードウェアが以前に別の ONTAP クラスタまたはスタンドアロンのシングルノードシステムとして使用されていた場合は、テクニカルサポートにお問い合わせください。
* この手順を使用して、ノードが 3 つ以上あるクラスタのコントローラハードウェアをアップグレードできますが、クラスタ内の HA ペアごとに手順を個別に実行する必要があります。
* この手順 は、AFF A700システムとFAS9000システムにのみ適用されます。AFF A900またはFAS9500システムへのアップグレードが必要な他のすべてのコントローラモデルについては、を参照してください link:other_references.html["参考資料"] 「 system controller replace 」コマンドを使用して、 ONTAP 9.8 以降を実行するコントローラハードウェアと、 ONTAP 9.8 以降を実行するコントローラハードウェアを手動でアップグレードするには、「 _Using Aggregate Relocation 」コマンドを使用します。
* AFF A900およびFAS9500システムでは、高電圧（200~240V）のみがサポートされます。AFF A700またはFAS9000システムをローライン電源（100~120V）で実行している場合、この手順 を使用する前に、AFF A700またはFAS9000の入力電源を変換する必要があります。
* ダウンタイムを発生させずにAFF A700またはFAS9000システムからアップグレードする場合、ストレージを移動するか、テクニカルサポートにお問い合わせください。を参照してください link:other_references.html["参考資料"] をクリックして、ボリュームまたは storage _ を移動して _ Upgrade にリンクします。

