---
sidebar: sidebar 
permalink: upgrade-arl-auto-affa900/index.html 
keywords: aggregate, relocation, controller, hardware, aggregates, flexarray, metrocluster, terminology, aff, a700, a900 
summary: AFF A900 コントローラハードウェアを使用して AFF A700 コントローラハードウェアをアップグレードし、ルート以外のアグリゲートの所有権を切り替えます。 
---
= 概要
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
* このアグリゲート再配置手順を使用すると、「 system controller replace 」コマンドを使用して AAF A700 を AAF A900 システムにアップグレードできます。ONTAP 9.10.1 RC2 以降を実行する手順環境 AFF A700 および AFF A900 システム。 *

コントローラモジュールと不揮発性ストレージモジュール（ NVS ）を交換することで、 AFF A700 ノードの HA ペアのコントローラハードウェアを AFF A900 システムに無停止でアップグレードできます。AFF A700 ノード間でルート以外のアグリゲートを移行してから、 HA ペア内の AFF A900 ノードに移行します。アップグレードするノードでホストされているデータには、アップグレード手順の実行中にアクセスできます。

このコントローラの手順をアップグレードする際には、 AFF A700 システムを AFF A900 システムにアップグレードします。


NOTE: AFF A700 システムの各ノードの 2 つのフィールド交換可能ユニット（ FRU ）を新しい FRU と交換する必要があります。I/O カード、データケーブル、ディスクシェルフ、およびディスクを移動、切断、再接続する必要はありません。

この手順では、 Aggregate Relocation （ ARL ；アグリゲートの再配置）と呼ばれる方法を使用します。 ARL を使用すると、 HA 構成を活用して、ルート以外のアグリゲートの所有権をノード間で移動できます（ルートが同じクラスタ内のストレージを共有している場合）。

手順の実行中に、交換用コントローラハードウェアを使用して元のコントローラハードウェアをアップグレードし、ルート以外のアグリゲートの所有権を切り替えます。アグリゲートをノードからノードに複数回移行して、アップグレード手順全体を通じて少なくとも 1 つのノードがアグリゲートからデータを提供していることを確認します。処理を続行する前に、クラスタ内のノード間でデータ論理インターフェイス（ LIF ）を移行することもできます。


NOTE: このドキュメントでは、ノード名の参照としてのみ * node1 * と * node2 * という用語が使用されています。手順のあとにノードの実際の名前を置き換える必要があります。

.注意すべき重要な情報
* この手順は複雑で、 ONTAP の高度な管理スキルがあることを前提としています。また、を読んで理解する必要があります link:guidelines_for_upgrading_controllers_with_arl.html["ARL を使用した AFF A700 から AFF A900 へのアップグレードに関するガイドライン"] および  アップグレード開始前のセクション。
* この手順は、交換用コントローラハードウェアが新しく購入されていて、他のシステムで使用されていないことを前提としています。使用済みのコントローラを「 wipeconfig 」コマンドで準備するために必要な手順は、この手順には含まれていません。交換用コントローラハードウェアが以前に別の ONTAP クラスタまたはスタンドアロンのシングルノードシステムとして使用されていた場合は、テクニカルサポートにお問い合わせください。
* この手順を使用して、ノードが 3 つ以上あるクラスタでコントローラハードウェアをアップグレードできます。ただし、クラスタ内のハイアベイラビリティ（ HA ）ペアごとに手順を個別に実行する必要があります。
* この手順は、 AFF A700 システムにのみ適用されます。AFF A900 システムへのアップグレードが必要なその他すべてのコントローラモデルについては、を参照してください link:other_references.html["参考資料"] 「 system controller replace 」コマンドを使用して、 ONTAP 9.8 以降を実行するコントローラハードウェアと、 ONTAP 9.8 以降を実行するコントローラハードウェアを手動でアップグレードするには、「 _Using Aggregate Relocation 」コマンドを使用します。
* ダウンタイムを発生させずに AFF A700 システムからアップグレードする場合は、ストレージを移動するか、テクニカルサポートにお問い合わせください。を参照してください link:other_references.html["参考資料"] をクリックして、ボリュームまたは storage _ を移動して _ Upgrade にリンクします。

