---
sidebar: sidebar 
permalink: upgrade-arl-auto-affa900/index.html 
keywords: aggregate, relocation, controller, hardware, aggregates, flexarray, metrocluster, terminology, old, system, chassis, disk, disks 
summary: コントローラハードウェアをアップグレードするには、古いシステムを交換用システムに変換し、古いシステムのシャーシとディスクを残します。 
---
= 概要
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
アグリゲートの再配置（ARL）を使用して既存のシステムを交換用システムに変換し、既存のシステムのシャーシとディスクを残して、HAペアのコントローラハードウェアを無停止でアップグレードできます。


WARNING: この手順は、以下のアップグレード構成を厳密に環境します。他のシステムの組み合わせ間でアップグレードを実行する場合は、この手順を使用しないでください。

[cols="20,20,40"]
|===
| 既存のシステム | 交換用システム | サポートされるONTAPのバージョン 


| AFF A800^1^ | AFF A90またはAFF A70 | 9.15.1 


| AFF A220をオールSANアレイ（ASA）として構成 | ASA A150 | 9.13.1P1以降 


| AFF A220の略 | AFF A150 | 9.10.1P15、9.11.1P11、9.12.1P5以降 


| AFF A200 | AFF A150  a| 
9.10.1P15、9.11.1P11以降^2^



| AFF C190の略 | AFF A150 | 9.10.1P15、9.11.1P11、9.12.1P5以降 


| FAS2620 | FAS2820  a| 
9.11.1P7以降のパッチリリース（FAS2620）^2^

9.13.1以降（FAS2820）



| FAS2720 | FAS2820 | 9.13.1以降 


| AFF A700をASAとして構成 | ASA A900 | 9.13.1P1以降 


| AFF A700の略 | AFF A900 の略 | 9.10.1P10、9.11.1P6以降 


| FAS9000 | FAS9500 | 9.10.1P10、9.11.1P6以降 
|===
^1^ ONTAP 9.151で導入されたシステムにアップグレードすると、ONTAPは、Storage Efficiencyを使用していないボリュームも含めて、シンプロビジョニングされている既存のすべてのボリュームのストレージ効率を変換し、ハードウェアオフロード機能を使用する新しいStorage Efficiency機能を適用します。これは自動バックグラウンドプロセスであり、システムのパフォーマンスへの明らかな影響はありません。 https://docs.netapp.com/us-en/ontap/concepts/builtin-storage-efficiency-concept.html["詳細はこちら。"^]です。

^2^ AFF A200およびFAS2620システムでは、9.11.1よりも新しいバージョンのONTAPはサポートされていません。

[NOTE]
====
NetAppでは、可能であれば、古いシステムと交換用システムで同じONTAPバージョンを使用することを推奨しています。

上記の表のONTAPの最小バージョンは必須です。これらのバージョンのONTAPにはサービスプロセッサまたはベースボード管理コントローラ（BMC）のファームウェアバージョンが適用されています。このファームウェアバージョンは、アップグレード時にシャーシ内に異なるコントローラタイプを混在させるために必要です。

====
手順では、ルート以外のアグリゲートを古いコントローラノード間で移行します。インストールが完了したら、ルート以外のアグリゲートを古いコントローラノードから交換用コントローラノードに移行します。アップグレードするノードでホストされているデータには、アップグレード手順の実行中にアクセスできます。

.このタスクについて
このコントローラのアップグレード手順では、次のいずれかのアップグレードを実行します。

[cols="30,70"]
|===
| 既存のオブジェクト | 実行する操作 


| AFF A800用 | 2台のAFF A800コントローラ、NVRAM、およびすべてのI/Oモジュールを新しいコントローラおよびI/Oモジュールと交換します。 


| AFF A220、AFF A200、AFF C190、FAS2620、またはFAS2720 | 古いコントローラの各ノードのコントローラモジュールを新しいモジュールと交換します。^1 ^ 


| AFF A700またはFAS9000 | 古いコントローラの各ノードのコントローラモジュールとNVRAMモジュールを新しいモジュールと交換します。^1 ^ 
|===
^1^ I/Oカード、データケーブル、ディスクシェルフ、およびディスクを移動、切断、再接続する必要はありません。

この手順では、アグリゲートの再配置（ARL）と呼ばれる方法を使用します。ARLでは、HA構成とクラスタインターコネクト通信を利用しています。この機能を使用すると、ルート以外のアグリゲートが同じクラスタ内のストレージを共有している場合に、ノード間で所有権を移動できます。

手順の実行中に、交換用コントローラハードウェアを使用して元のコントローラハードウェアをアップグレードし、ルート以外のアグリゲートの所有権を切り替えます。アグリゲートをノードからノードに複数回移行して、アップグレード手順 全体を通じて、少なくとも 1 つのノードがアグリゲートからデータを提供していることを確認します。処理を続行する前に、クラスタ内のノード間でデータ LIF を移行することもできます。


NOTE: このドキュメントでは、ノード名の参照としてのみ * node1 * と * node2 * という用語が使用されています。この手順を実行する場合は、ノードの実際の名前に置き換える必要があります。

.重要な情報
* この手順は複雑で、 ONTAP の高度な管理スキルがあることを前提としています。また、を読んで理解する必要があります link:guidelines_for_upgrading_controllers_with_arl.html["コントローラのアップグレードに関するガイドラインを参照してください"] および link:overview_of_the_arl_upgrade.html["ARL アップグレードの概要"] アップグレード開始前のセクション。
* この手順は、交換用コントローラハードウェアが新しく購入されていて、他のシステムで使用されていないことを前提としています。使用済みのコントローラを「 wipeconfig 」コマンドで準備するために必要な手順は、この手順には含まれていません。交換用コントローラハードウェアが以前に別の ONTAP クラスタまたはスタンドアロンのシングルノードシステムとして使用されていた場合は、テクニカルサポートにお問い合わせください。
* この手順を使用して、ノードが 3 つ以上あるクラスタのコントローラハードウェアをアップグレードできますが、クラスタ内の HA ペアごとに手順を個別に実行する必要があります。
* ONTAPのバージョンでサポートされていないスイッチおよびアップグレード先の交換用システムがある場合は、を参照してください link:other_references.html["参考資料"] Hardware Universe にリンクするには、次の手順を実行します。
* AFF A70システムとAFF A90システムは、クラスタ接続とHA接続の両方で100GbEネットワークポートを共有します。これらのシステムでは、従来のクラスタスイッチとの10GbEまたは25GbEクラスタ接続をサポートできますが、NetApp 10GbEおよび25GbEスイッチが不要になった場合は、100GbEクラスタ速度に更新することを推奨します。詳細については、次のナレッジベースの記事を参照してください。
+
--
** link:https://kb.netapp.com/on-prem/ontap/OHW/OHW-KBs/How_to_configure_10G_or_25G_cluster_ports_on_a_new_cluster_setup_on_AFF_ASA_A1K_A90_A70_FAS90_FAS70["AFF / ASA A1K、A90、A70、FAS90、FAS70の新しいクラスタセットアップで10Gまたは25Gのクラスタポートを構成する方法"^]
** link:https://kb.netapp.com/on-prem/ontap/OHW/OHW-KBs/How_to_convert_an_existing_cluster_from_10G_or_25G_cluster_ports_to_40G_or_100G_cluster_ports_on_an_AFF_ASA_A1K_A90_A70_FAS90_FAS70["AFF / ASA A1K、A90、A70、FAS90、FAS70で既存のクラスタを10Gまたは25Gのクラスタポートから40Gまたは100Gのクラスタポートに変換する方法"^]


--
+
既存のノードのクラスタポートe0aまたはe0bを新しいノードのクラスタポートにリンクできない場合は、を参照してください link:https://mysupport.netapp.com/site/bugs-online/product/ONTAP/JiraNgage/CONTAP-166978["NetApp Bugs OnlineのバグIDCONTAP-166978"^]。

* この手順は、AFF A800、AFF A200、AFF A220、AFF C190、FAS2620、 FAS2720、AFF A700、FAS9000システム：AFF A90、AFF A70、AFF A150、FAS2820、AFF A900へのアップグレードが必要なその他すべてのコントローラモデル またはFAS9500システムの場合は、「system controller replace」コマンドを使用してONTAP 9.8以降を実行しているコントローラハードウェアをアップグレードする方法_およびアグリゲートの再配置を使用してONTAP 9.8以降を実行しているコントローラハードウェアを手動でアップグレードする方法_へのリンクを参照し link:other_references.html["参考資料"] てください。
* ASA A900、AFF A900、およびFAS9500システムは、ハイライン電源（200V~240V）のみをサポートします。AFF A700またはFAS9000システムをローライン電源（100~120V）で実行している場合、この手順 を使用する前に、AFF A700またはFAS9000の入力電源を変換する必要があります。
* AFF A800、AFF A200、AFF A220、AFF C190、FAS2620からアップグレードする場合 FAS2720、AFF A700、またはFAS9000システムでダウンタイムが発生した場合は、ストレージを移動することでコントローラハードウェアをアップグレードするか、テクニカルサポートにお問い合わせください。「ボリュームまたはストレージの移動によるアップグレード」へのリンクを参照してください link:other_references.html["参考資料"] 。




== コントローラのアップグレードプロセスを自動化する

この手順には、手順を自動化するための手順が用意されています。この手順では、自動ディスク割り当てとネットワークポートの到達可能性チェックを使用して、コントローラのアップグレードを簡易化します。
