---
sidebar: sidebar 
permalink: upgrade-arl-auto-affa900/install-aff-a30-a50-c30-c50-node2.html 
keywords: aff, fas, asa, install, NVRAM, node2, controller, module, modules, replacement 
summary: 同じシャーシのコントローラモデルをARLでアップグレードする際に、交換用システムモジュールをノード2に取り付けます。 
---
= AFF A30、AFF A50、AFF C30、またはAFF C60モジュールをノード2に取り付けます。
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
アップグレード用に受け取った交換用コントローラモジュールをノード2に取り付けます。Node2 は、システムの背面からコントローラを見たときにシャーシの下半分に配置されているコントローラ B です。

.手順
. キャビネットまたはTelcoラックの中央にあるレールにストレージシステムを配置し、ストレージシステムを下から支えて所定の位置にスライドさせます。
+

NOTE: 手順の後半で指示されるまで、コントローラモジュールをシャーシに完全に挿入しないでください。

. 管理ポートとコンソールポートを node2 コントローラモジュールにケーブル接続します。
+

NOTE: シャーシの電源はすでにオンになっているため、node2 は完全に装着されるとすぐに BIOS 初期化を開始し、続いて AUTOBOOT を開始します。ノード 2 のブートを中断するには、コントローラ モジュールをスロットに完全に挿入する前に、シリアル コンソールと管理ケーブルをノード 2 コントローラ モジュールに接続することをお勧めします。

. カムハンドルを開いた状態で、コントローラモジュールをミッドプレーンまでしっかりと押し込んで完全に装着します。コントローラモジュールが完全に装着されると、ロックラッチが上がります。カムハンドルをロック位置まで閉じます。
+

NOTE: コネクタの破損を防ぐため、コントローラモジュールをシャーシに挿入する際に力を入れすぎないように注意してください。

. モジュールが装着されたらすぐにシリアル コンソールを接続し、ノード 2 の AUTOBOOT を中断する準備をします。
. 自動ブートを中断すると、ノード2はLOADERプロンプトで停止します。時間内に自動ブートを中断せずにnode2がブートを開始した場合は、プロンプトが表示されてからCtrl+Cキーを押してブートメニューに移動します。ノードがブートメニューで停止したら、オプションを使用し `8` てノードをリブートし、リブート時に自動ブートを中断します。
. node2のLOADER>プロンプトで、デフォルトの環境変数を設定します。
+
「デフォルト設定」

. デフォルトの環境変数設定を保存します。
+
'aveenv

. 2ノードのスイッチレス構成の場合、ノード2のスロット1にX60132A（4ポート10/25GbEカード）が装着されていることを確認してください。X60132Aカードは、アップグレード中のクラスタ相互接続に必要です。

