---
sidebar: sidebar 
permalink: upgrade-arl-auto-affa900/install-asaa150-affa150-fas2820-on-node2.html 
keywords: aff, fas, asa, install, NVRAM, node2, controller, module, modules, replacement 
summary: 同じシャーシのコントローラモデルをARLでアップグレードする際に、交換用システムモジュールをノード2に取り付けます。 
---
= ASA A150、AFF A150、またはFAS2820コントローラモジュールをノード2に設置します。
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
アップグレード用に受け取ったASA A150、AFF A150、またはFAS2820コントローラモジュールをノード2に取り付けます。node2 は、システムの背面からコントローラを見るときにシャーシの右側に配置されたコントローラ B です。

.作業を開始する前に
* 接地対策がまだの場合は、自身で適切に実施します。
* 取り外すコントローラから、コンソール、管理、SASストレージ、データネットワークのケーブルをすべて外します。


.手順
. コントローラモジュールの端をシャーシのベイ B に合わせ、コントローラモジュールをシステムに半分までそっと押し込みます。
+

TIP: ベイ B はシャーシの右側にあります。

+

WARNING: 指示があるまでコントローラモジュールをシャーシに完全に挿入しないでください。

. 管理ポートとコンソールポートを node2 コントローラモジュールにケーブル接続します。
+

NOTE: シャーシの電源はすでにオンになっているため、ノード 2 は完全に装着されるとすぐに起動を開始します。ノード 2 が起動しないようにするには、コントローラ モジュールを完全に挿入する前に、コンソール ケーブルと管理ケーブルを接続します。

. コントローラモジュールをシャーシに挿入し、ミッドプレーンまでしっかりと押し込んで完全に装着します。
+
コントローラモジュールが完全に装着されると、ロックラッチが上がります。

+

NOTE: コネクタの破損を防ぐため、コントローラモジュールをシャーシに挿入する際に力を入れすぎないように注意してください。

. モジュールが装着されたらすぐにシリアル コンソールを接続し、ノード 2 の AUTOBOOT を中断する準備をします。
. 自動ブートを中断すると、ノード2はLOADERプロンプトで停止します。時間内に自動ブートを中断せずにnode2がブートを開始した場合は、プロンプトが表示されてからCtrl+Cキーを押してブートメニューに移動します。ノードがブートメニューで停止したら、オプションを使用し `8` てノードをリブートし、リブート時に自動ブートを中断します。

