---
sidebar: sidebar 
permalink: upgrade-arl-auto-affa900/install_replacement_system_modules_on_node2.html 
keywords: install, NVRAM, node2, controller, module, modules, replacement 
summary: 同じシャーシのコントローラモデルをARLでアップグレードする際に、交換用システムモジュールをノード2に取り付けます。 
---
= 交換用システムモジュールをノード2に取り付けます
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
アップグレード用に受け取った交換用システムモジュールをノード2にインストールします。node2 は、システムの背面からコントローラを見るときにシャーシの右側に配置されたコントローラ B です。

* <<AFF A150またはFAS2820コントローラモジュールをノード2に取り付けます>>
* <<AFF A900またはFAS9500 NVRAMとコントローラモジュールをnode2にインストールします>>




== AFF A150またはFAS2820コントローラモジュールをノード2に取り付けます

アップグレード用に受け取ったAFF A150またはFAS2820コントローラモジュールをノード2に取り付けます。node2 は、システムの背面からコントローラを見るときにシャーシの右側に配置されたコントローラ B です。

.作業を開始する前に
* 接地対策がまだの場合は、自身で適切に実施します。
* 取り外すコントローラから、コンソール、管理、SASストレージ、データネットワークのケーブルをすべて外します。


.手順
. コントローラモジュールの端をシャーシのベイ B に合わせ、コントローラモジュールをシステムに半分までそっと押し込みます。
+

TIP: ベイBは、シャーシの下部にあります。

+

WARNING: あとで手順 で指示があるまで、コントローラモジュールをシャーシに完全に挿入しないでください。

. 管理ポートとコンソールポートを node2 コントローラモジュールにケーブル接続します。
+

NOTE: シャーシはすでに電源がオンになっているため、完全に装着されるとすぐに node2 がブートを開始します。ノード2がブートしないように、NetAppでは、コントローラモジュールをスロットに完全に挿入する前に、コンソールケーブルと管理ケーブルをノード2のコントローラモジュールに接続することを推奨しています。

. コントローラモジュールをシャーシに挿入し、ミッドプレーンまでしっかりと押し込んで完全に装着します。
+
コントローラモジュールが完全に装着されると、ロックラッチが上がります。

+

NOTE: コネクタの破損を防ぐため、コントローラモジュールをシャーシに挿入する際に力を入れすぎないようにしてください。

. モジュールを装着したらすぐにシリアルコンソールに接続し、 node1 の自動ブートを中断できるようにします。
. 自動ブートを中断すると、ノード2はLOADERプロンプトで停止します。ブートを中断せずに node2 でブートが開始された場合は、プロンプトが表示されるまで待ち、 * Ctrl+C * を押してブートメニューに進みます。ノードがブートメニューで停止したら、オプション8を使用してノードをリブートし、リブート時に自動ブートを中断します。




== AFF A900またはFAS9500 NVRAMとコントローラモジュールをnode2にインストールします

AFF A900またはFAS9500 NVRAMと、node2にアップグレード用に受け取ったコントローラモジュールをインストールします。node2 は、システムの背面からコントローラを見るときにシャーシの右側に配置されたコントローラ B です。

インストールを実行する際には、次の点に注意する必要があります。

* スロット6-1および6-2の空のフィラーモジュールをすべて古いNVRAMモジュールから新しいNVRAMモジュールに移動します。
* コアダンプデバイスをAFF A700 NVRAMモジュールからAFF A900 NVRAMモジュールに移動しないでください。
* FAS9000 NVRAMモジュールに取り付けられているすべてのフラッシュキャッシュモジュールをFAS9500 NVRAMモジュールに移動します。


.作業を開始する前に
接地対策がまだの場合は、自身で適切に実施します。



=== AFF A900またはFAS9500 NVRAMモジュールを取り付けます

次の手順 を使用して、AFF A900またはFAS9500 NVRAMモジュールをnode2のスロット6に取り付けます。

.手順
. NVRAM モジュールをスロット 6 のシャーシ開口部の端に合わせます。
. NVRAM モジュールをスロットにそっと挿入し、文字と数字が記載された I/O カムラッチを上に押して NVRAM モジュールを所定の位置にロックします。




=== AFF A900またはFAS9500コントローラモジュールをnode2にインストールします

次の手順 を使用して、AFF A900またはFAS9500コントローラモジュールをnode2にインストールします。

.手順
. コントローラモジュールの端をシャーシのベイ B に合わせ、コントローラモジュールをシステムに半分までそっと押し込みます。
+

TIP: ベイラベルは、シャーシのコントローラモジュールのすぐ上にあります。

+

NOTE: あとで手順 で指示があるまで、コントローラモジュールをシャーシに完全に挿入しないでください。

. 管理ポートとコンソールポートを node2 コントローラモジュールにケーブル接続します。
+

NOTE: シャーシはすでに電源がオンになっているため、完全に装着されるとすぐに node2 がブートを開始します。node2 のブートを避けるため、コントローラモジュールをスロットに完全に挿入する前に、コンソールケーブルと管理ケーブルを node2 のコントローラモジュールに接続することを推奨します。

. コントローラモジュールをシャーシに挿入し、ミッドプレーンまでしっかりと押し込んで完全に装着します。
+
コントローラモジュールが完全に装着されると、ロックラッチが上がります。

+

WARNING: コネクタの破損を防ぐため、コントローラモジュールをシャーシに挿入する際に力を入れすぎないようにしてください。

. モジュールを装着したらすぐにシリアルコンソールに接続し、 node1 の自動ブートを中断できるようにします。
. 自動ブートを中断すると、 node2 で LOADER プロンプトが停止します。ブートを中断せずに node2 でブートが開始された場合は、プロンプトが表示されるまで待ち、 * Ctrl+C * を押してブートメニューに進みます。ノードがブートメニューで停止したら、オプション「 8 」を使用してノードをリブートし、リブート中に自動ブートを中断します。
. node2のLOADER>プロンプトで、デフォルトの環境変数を設定します。
+
「デフォルト設定」

. デフォルトの環境変数設定を保存します。
+
'aveenv


