---
sidebar: sidebar 
permalink: upgrade-arl-auto-affa900/install-asaa900-affa900-fas9500-on-node2.html 
keywords: aff, fas, asa, install, NVRAM, node2, controller, module, modules, replacement 
summary: 同じシャーシのコントローラモデルをARLでアップグレードする際に、交換用システムモジュールをノード2に取り付けます。 
---
= ASA A900、AFF A900、またはFAS9500のNVRAMとコントローラモジュールをノード2に設置します。
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
アップグレード用に受け取ったASA A900、AFF A900、またはFAS9500のNVRAMとコントローラモジュールをノード2に取り付けます。node2 は、システムの背面からコントローラを見るときにシャーシの右側に配置されたコントローラ B です。

インストールを実行する際には、次の点に注意する必要があります。

* スロット6-1および6-2の空のフィラーモジュールをすべて古いNVRAMモジュールから新しいNVRAMモジュールに移動します。
* コアダンプデバイスをAFF A700 NVRAMモジュールからASA A900またはAFF A900 NVRAMモジュールに移動しないでください。
* FAS9000 NVRAMモジュールに取り付けられているすべてのフラッシュキャッシュモジュールをFAS9500 NVRAMモジュールに移動します。


.作業を開始する前に
接地対策がまだの場合は、自身で適切に実施します。



== ASA A900、AFF A900、またはFAS9500 NVRAMモジュールの設置

ASA A900、AFF A900、またはFAS9500 NVRAMモジュールをノード2のスロット6に取り付けます。

.手順
. NVRAM モジュールをスロット 6 のシャーシ開口部の端に合わせます。
. NVRAM モジュールをスロットにそっと挿入し、文字と数字が記載された I/O カムラッチを上に押して NVRAM モジュールを所定の位置にロックします。




== ASA A900、AFF A900、またはFAS9500コントローラモジュールをノード2に設置します。

ノード2のASA A900、AFF A900、またはFAS9500コントローラモジュールを設置、ケーブル接続します。

.手順
. コントローラモジュールの端をシャーシのベイ B に合わせ、コントローラモジュールをシステムに半分までそっと押し込みます。
+

TIP: ベイラベルは、シャーシのコントローラモジュールのすぐ上にあります。

+

NOTE: 指示があるまでコントローラモジュールをシャーシに完全に挿入しないでください。

. 管理ポートとコンソールポートを node2 コントローラモジュールにケーブル接続します。
+

NOTE: シャーシはすでに電源がオンになっているため、完全に装着されるとすぐに node2 がブートを開始します。node2 のブートを避けるため、コントローラモジュールをスロットに完全に挿入する前に、コンソールケーブルと管理ケーブルを node2 のコントローラモジュールに接続することを推奨します。

. コントローラモジュールをシャーシに挿入し、ミッドプレーンまでしっかりと押し込んで完全に装着します。
+
コントローラモジュールが完全に装着されると、ロックラッチが上がります。

+

WARNING: コネクタの破損を防ぐため、コントローラモジュールをシャーシに挿入する際に力を入れすぎないように注意してください。

. モジュールが装着されたらすぐにシリアル コンソールを接続し、ノード 2 の AUTOBOOT を中断する準備をします。
. 自動ブートを中断すると、ノード2はLOADERプロンプトで停止します。時間内に自動ブートを中断せずにnode2がブートを開始した場合は、プロンプトが表示されてからCtrl+Cキーを押してブートメニューに移動します。ノードがブートメニューで停止したら、オプションを使用し `8` てノードをリブートし、リブート時に自動ブートを中断します。
. node2のLOADER>プロンプトで、デフォルトの環境変数を設定します。
+
「デフォルト設定」

. デフォルトの環境変数設定を保存します。
+
'aveenv


