---
sidebar: sidebar 
permalink: upgrade-arl-auto-affa900/install-aff-a30-a50-c30-c50-node2.html 
keywords: aff, fas, asa, install, NVRAM, node2, controller, module, modules, replacement 
summary: 同じシャーシのコントローラモデルをARLでアップグレードする際に、交換用システムモジュールをノード2に取り付けます。 
---
= AFF A30、AFF A50、AFF C30、またはAFF C60モジュールをノード2に取り付けます。
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
アップグレード用に受け取った交換用コントローラモジュールをノード2に取り付けます。Node2 は、システムの背面からコントローラを見たときにシャーシの下半分に配置されているコントローラ B です。

.手順
. キャビネットまたはTelcoラックの中央にあるレールにストレージシステムを配置し、ストレージシステムを下から支えて所定の位置にスライドさせます。
+

NOTE: 手順の後半で指示されるまで、コントローラモジュールをシャーシに完全に挿入しないでください。

. 管理ポートとコンソールポートを node1 コントローラモジュールにケーブル接続します。
+

NOTE: シャーシの電源がすでにオンになっているため、ノード1はBIOSの初期化を開始し、完全に装着されるとすぐに自動ブートを実行します。ノード 1 のブートを中断するには、コントローラモジュールをスロットに完全に挿入する前に、シリアルコンソールケーブルと管理ケーブルをノード 1 のコントローラモジュールに接続することを推奨します。

. カムハンドルを開いた状態で、コントローラモジュールをミッドプレーンまでしっかりと押し込んで完全に装着します。コントローラモジュールが完全に装着されると、ロックラッチが上がります。カムハンドルをロック位置まで閉じます。
+

NOTE: コネクタの破損を防ぐため、コントローラモジュールをシャーシに挿入する際に力を入れすぎないように注意してください。

. モジュールを装着したらすぐにシリアルコンソールに接続し、 node1 の自動ブートを中断できるようにします。
. 自動ブートを中断すると、ノード1はLOADERプロンプトで停止します。時間内に自動ブートを中断せずにnode1がブートを開始した場合は、プロンプトが表示されるまで待ち、Ctrl+Cキーを押してブートメニューに移動します。ノードがブートメニューで停止したら、オプションを使用し `8` てノードをリブートし、リブート時に自動ブートを中断します。
. node1 の LOADER プロンプトで、デフォルトの環境変数を設定します。
+
「デフォルト設定」

. デフォルトの環境変数設定を保存します。
+
'aveenv

. 2ノードのスイッチレス構成の場合、ノード2のスロット1にX60132A（4ポート10/25GbEカード）が装着されていることを確認してください。X60132Aカードは、アップグレード中のクラスタ相互接続に必要です。

