---
sidebar: sidebar 
permalink: /upgrade-arl-auto-affa900/move_non_root_aggr_and_nas_data_lifs_back_to_node2.html 
keywords: moving, non-root, aggregates, nas, lif, node1, node2 
summary: AFF A700 から AFF A900 へのアップグレード時に、ノード 1 上のノード 2 の NAS データ LIF がノード 1 からノード 2 に再配置されたことを確認します。 
---
= ルート以外のアグリゲートと NAS データ LIF を node2 に戻します
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ノード 2 のネットワーク設定を確認し、アグリゲートをノード 1 からノード 2 に再配置する前に、ノード 1 に現在あるノード 2 に属する NAS データ LIF がノード 1 からノード 2 に再配置されたことを確認する必要があります。また、 SAN LIF が node2 に存在することも確認する必要があります。

アップグレード手順の実行中、リモート LIF は SAN LUN へのトラフィックを処理します。アップグレード時にクラスタやサービスの健全性を維持するために、 SAN LIF を移動する必要はありません。SAN LIF は、新しいポートにマッピングする必要がないかぎり移動されません。node2 をオンラインにしたあと、 LIF が正常に機能しており、適切なポートに配置されていることを確認する必要があります。

.手順
. 再配置処理を再開します。
+
「システムコントローラの交換が再開」

+
システムは次のタスクを実行します。

+
--
** クラスタクォーラムチェック
** システム ID の確認
** イメージのバージョンチェック
** ターゲットプラットフォームのチェック
** ネットワーク到達可能性チェック


--
+
ネットワーク到達可能性チェックのこの段階で処理が一時停止します。

. 再配置処理を再開します。
+
「システムコントローラの交換が再開」

+
システムは次のチェックを実行します。

+
--
** クラスタの健全性チェック
** クラスタ LIF のステータスを確認します


--
+
これらのチェックの実行後、システムによってルート以外のアグリゲートと NAS データ LIF が node2 に再配置され、 AFF A900 コントローラで実行されるようになります。

+
リソースの再配置が完了すると、コントローラの交換処理が一時停止します。

. アグリゲートの再配置処理と NAS データ LIF の移動処理のステータスを確認します。
+
「 system controller replace show-sdetails 」というエラーが表示されます

+
コントローラ交換用手順が一時停止している場合は、エラーがある場合はチェックして修正し、次に「問題 re sume 」をクリックして操作を続行します。

. 必要に応じて、取り外した LIF をリストアしてリバートします。取り外した LIF を表示します。
+
cluster controller -replacement network ヒエラー（クラスタコントローラ交換ネットワークが取り外されました） -interface show

+
LIF が取り外された場合、ホームノードを node2 にリストアします。

+
クラスタ・コントローラ交換ネットワークが取り外されましたインタフェース・リストア -home-node

. この処理を再開すると、必要なポストチェックの実行をシステムに求めるプロンプトが表示されます。
+
「システムコントローラの交換が再開」

+
次のポストチェックが実行されます。

+
** クラスタクォーラムチェック
** クラスタの健全性チェック
** アグリゲートの再構築チェック
** アグリゲートのステータスを確認します
** ディスクのステータスを確認します
** クラスタ LIF のステータスを確認します
** ボリュームチェック



