---
sidebar: sidebar 
permalink: upgrade-arl-auto-affa900/netboot_node2.html 
keywords: preparing, netboot, ontap, aff, a900, node2 
summary: 対応する AFF A900 node2 コントローラモジュールと NVRAM モジュールをスワップしたら、ネットブートが必要になることがあります。 
---
= ネットブート node2
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
対応するAFF A900またはFAS9500 node2のコントローラモジュールとNVRAMを交換したあと、モジュールでネットブートが必要になることがあります。ネットブートという用語は、リモート・サーバに保存された ONTAP イメージからブートすることを意味します。ネットブートの準備を行うときは、システムがアクセスできる Web サーバに、 ONTAP 9 ブート・イメージのコピーを配置する必要があります。

AFF A900またはFAS9500コントローラモジュールのブートメディアにインストールされているONTAP のバージョンは、シャーシに取り付けて電源がオンになっていないかぎり確認できません。AFF A900またはFAS9500ブートメディア上のONTAP バージョンは、アップグレードするAFF A700またはFAS9000システム上で実行されているONTAP バージョンと同じであり、プライマリブートイメージとバックアップブートイメージの両方が一致している必要があります。イメージを設定するには、ネットブートを実行してからブートメニューの「 wipeconfig 」コマンドを実行します。コントローラモジュールが以前に別のクラスタで使用されていた場合は、「 wipeconfig 」コマンドはブートメディア上の残留設定をクリアします。


NOTE: また、 USB ブートオプションを使用してネットブートを実行することもできます。を参照してください link:https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/How_to_use_the_boot_recovery_LOADER_command_for_installing_ONTAP_for_initial_setup_of_a_system["ネットアップの技術情報アーティクル：「 How to use the boot_recovery loader command for installing ONTAP for initial setup of a system."^]。

.作業を開始する前に
* システムから HTTP サーバにアクセスできることを確認します。
* ご使用のシステムに必要なシステムファイルと適切なバージョンの ONTAP を、 _NetApp サポートサイトからダウンロードします。を参照してください link:other_references.html["参考資料"] からネットアップサポートサイトにリンクできます。


元のコントローラと同じバージョンの ONTAP 9 がインストールされていない場合は、新しいコントローラをネットブートする必要があります。新しいコントローラをそれぞれ取り付けたら、 Web サーバに保存されている ONTAP 9 イメージからシステムをブートします。その後、以降のシステムブートで使用するブートメディアデバイスに正しいファイルをダウンロードできます。

.手順
. を参照してください link:other_references.html["参考資料"] ネットアップサポートサイトへのリンクをクリックして、システムのネットブートの実行に使用するファイルをダウンロードします。
. [netboot_t2_step2] ネットアップサポートサイトのソフトウェアダウンロードセクションから適切な ONTAP ソフトウェアをダウンロードし、「 ONTAP_version_image.tgz 」ファイルを Web にアクセスできるディレクトリに保存します。
. Web にアクセスできるディレクトリに移動し、必要なファイルが利用可能であることを確認します。
. ディレクトリの一覧に「 ONTAP_version_image.tgz 」が含まれている必要があります。
. 次のいずれかを実行してネットブート接続を設定します。
+

NOTE: ネットブート接続として管理ポートおよび IP を使用する必要があります。アップグレードの実行中にデータ LIF IP を使用しないでください。データ LIF が停止する可能性があります。

+
[cols="35,65"]
|===
| 動的ホスト構成プロトコル（ DHCP ）の状態 | 作業 


| 実行中です | ブート環境プロンプトで次のコマンドを使用して、自動的に接続を設定します。 ifconfig e0M -auto 


| 実行されていません  a| 
ブート環境プロンプトで次のコマンドを使用して、接続を手動で設定します。ifconfig e0M -addr=_filer_addr_-mask=_netmask_-gw=_gateway_-dns=_dns _domain =_dns_domain_`_filer_addr_`は、ストレージシステムのIPアドレスです。`_netmask_`はストレージ・システムのネットワーク・マスクです`_gateway_`はストレージ・システムのゲートウェイです`_dNS_addr_`は'ネットワーク上のネーム・サーバのIPアドレスですこのパラメータはオプションです。`_dNS_domain_`はDomain Name Service (DNS)ドメイン名ですこのパラメータはオプションです。


NOTE: インターフェイスによっては、その他のパラメータが必要になる場合もあります。ファームウェア・プロンプトで「 help ifconfig 」と入力すると、詳細が表示されます。

|===
. node2 でネットブートを実行します。
+
netboot\http://web_server_ip/path_to_web_accessible_directory/netboot/kernel`

+

NOTE: トランクを中断しないでください。

. 次の出力に示すように、AFF A900またはFAS9500コントローラモジュールで実行されているnode2がブートするまで待ち、ブートメニューのオプションを表示します。
+
[listing]
----
Please choose one of the following:

(1)  Normal Boot.
(2)  Boot without /etc/rc.
(3)  Change password.
(4)  Clean configuration and initialize all disks.
(5)  Maintenance mode boot.
(6)  Update flash from backup config.
(7)  Install new software first.
(8)  Reboot node.
(9)  Configure Advanced Drive Partitioning.
(10) Set Onboard Key Manager recovery secrets.
(11) Configure node for external key management.
Selection (1-11)?
----
. 起動メニューからオプション（ 7 ） Install new software first （新しいソフトウェアを最初にインストール）を選択します。
+
このメニューオプションを選択すると、新しい ONTAP イメージがブートデバイスにダウンロードおよびインストールされます。

+
[NOTE]
====
次のメッセージは無視してください 'This 手順 is not supported for Non-Disruptive Upgrade on an HA pair'環境の無停止の ONTAP ソフトウェアアップグレード。コントローラのアップグレードは含まれません。

新しいノードを希望するイメージに更新する場合は、必ずネットブートを使用してください。別の方法で新しいコントローラにイメージをインストールすると、正しいイメージがインストールされない場合があります。この問題環境 All ONTAP リリース

====
. 手順を続行するかどうかを確認するメッセージが表示されたら 'y' と入力し ' パッケージの入力を求められたら 'URL:\http://web_server_ip/path_to_web-accessible_directory/ontap_version_image.tgz` と入力します
+
「 path_to_the_web-accessible_directory 」は、「 ONTAP_version_image.tgz 」をダウンロードした場所を指します ,手順 2。

. 次の手順を実行してコントローラモジュールをリブートします。
+
.. 次のプロンプトが表示されたら 'n' を入力してバックアップ・リカバリをスキップします
+
[listing]
----
Do you want to restore the backup configuration now? {y|n}
----
.. 次のプロンプトが表示されたら 'y' と入力して再起動します
+
[listing]
----
The node must be rebooted to start using the newly installed software. Do you want to reboot now? {y|n}
----
+
コントローラモジュールはリブートしますが、ブートメニューで停止します。これは、ブートデバイスが再フォーマットされたことにより、構成データをリストアする必要があるためです。



. プロンプトで「 wipeconfig 」コマンドを実行して、ブートメディア上の以前の設定をクリアします。
+
.. 次のメッセージが表示されたら、回答は「はい」を選択します。
+
[listing]
----
This will delete critical system configuration, including cluster membership.
Warning: do not run this option on a HA node that has been taken over.
Are you sure you want to continue?:
----
.. ノードがリブートして「 wipeconfig 」を終了し、ブートメニューで停止します。


. ブート・メニューからメンテナンス・モード「 5 」を選択し、ブートを続行するように求めるプロンプトが表示されたら「 y 」と入力します。
. コントローラとシャーシが「 HA 」として構成されていることを確認します。
+
「 ha-config show 」

+
次に 'ha-config show コマンドの出力例を示します

+
[listing]
----
Chassis HA configuration: ha
Controller HA configuration: ha
----
. コントローラとシャーシが「 ha 」として設定されていない場合は、次のコマンドを使用して設定を修正します。
+
「 ha-config modify controller ha 」を参照してください

+
「 ha-config modify chassis ha 」を参照してください

. ノード 2 を停止します。
+
「 halt 」

+
node2 で LOADER プロンプトが停止します。

. node2 で、システムの日付、時刻、およびタイムゾーンを確認します。
+
「食事」

. node2 で、ブート環境のプロンプトで次のコマンドを使用して日付を確認します。
+
「日付」

. 必要に応じて、 node2 で日付を設定します。
+
'set date_mm/dd/yyyy_`

+

NOTE: node2 で対応する UTC 日付を設定します。

. node2 で、ブート環境のプロンプトで次のコマンドを使用して時刻を確認します。
+
「時間」

. 必要に応じて、 node2 で時刻を設定します。
+
'set time_hh:mm:ss_`

+

NOTE: node2 で対応する UTC 時間を設定します。

. 必要に応じて、 node2 にパートナーシステム ID を設定します。
+

NOTE: AFF A900 にアップグレードするノード 1 のシステム ID です。

+
setENV partner-sysid_node1_sysid_`

+
.. 設定を保存します。
+
'aveenv



. node2 の LOADER プロンプトで、 node1 の「 partner-sysid 」を確認します。
+
printenv partner-sysid

+
node2 の場合 'partner-sysid' は node1 のものである必要があります


