---
sidebar: sidebar 
permalink: upgrade-arl-auto-affa900/netboot_node1.html 
keywords: preparing, netboot, ontap, node1, aff, a900 
summary: 対応する AFF A900 ノード 1 のコントローラモジュールと NVS をスワップしたら、ノード 1 をネットブートする必要があります。 
---
= ネットブート node1
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
対応する AFF A900 ノード 1 のコントローラモジュールと NVS をスワップしたら、ノード 1 をネットブートする必要があります。ネットブートという用語は、リモート・サーバに保存された ONTAP イメージからブートすることを意味します。ネットブートの準備を行うときは、システムがアクセスできる Web サーバに、 ONTAP 9 ブート・イメージのコピーを追加する必要があります。

AFF A900 コントローラモジュールのブートメディアにインストールされている ONTAP のバージョンは、シャーシに取り付けて電源がオンになっていないかぎり確認できません。AFF A900 ブートメディアの ONTAP バージョンは、アップグレード対象の AFF A700 システムで実行されている ONTAP バージョンと同じで、プライマリブートイメージとバックアップブートイメージの両方が一致している必要があります。イメージを設定するには、ネットブートを実行してからブートメニューの「 wipeconfig 」コマンドを実行します。コントローラモジュールが以前に別のクラスタで使用されていた場合は、「 wipeconfig 」コマンドはブートメディア上の残留設定をクリアします。


NOTE: また、 USB ブートオプションを使用してネットブートを実行することもできます。を参照してください link:https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/How_to_use_the_boot_recovery_LOADER_command_for_installing_ONTAP_for_initial_setup_of_a_system["ネットアップの技術情報アーティクル：「 How to use the boot_recovery loader command for installing ONTAP for initial setup of a system."^]。

.作業を開始する前に
* システムから HTTP サーバにアクセスできることを確認します。
* ご使用のシステムに必要なシステムファイルと適切なバージョンの ONTAP を、 _NetApp サポートサイトからダウンロードします。を参照してください link:other_references.html["参考資料"] からネットアップサポートサイトにリンクできます。


元のコントローラと同じバージョンの ONTAP 9 がインストールされていない場合は、新しいコントローラをネットブートする必要があります。新しいコントローラをそれぞれ取り付けたら、 Web サーバに保存されている ONTAP 9 イメージからシステムをブートします。その後、以降のシステムブートで使用するブートメディアデバイスに正しいファイルをダウンロードできます。

.手順
. を参照してください link:other_references.html["参考資料"] ネットアップサポートサイトへのリンクをクリックして、システムのネットブートの実行に使用するファイルをダウンロードします。
. [netboot_node1_step2] _netapp サポートサイト _ のソフトウェアダウンロードセクションから適切な ONTAP ソフトウェアをダウンロードし、「 ONTAP_version_image.tgz 」ファイルを Web にアクセスできるディレクトリに保存します。
. Web にアクセスできるディレクトリに移動し、必要なファイルが利用可能であることを確認します。
. ディレクトリの一覧に「 ONTAP_version_image.tgz 」が含まれている必要があります。
. 次のいずれかを実行してネットブート接続を設定します。
+

NOTE: ネットブート接続として管理ポートおよび IP を使用する必要があります。アップグレードの実行中にデータ LIF IP を使用しないでください。データ LIF が停止する可能性があります。

+
[cols="35,65"]
|===
| 動的ホスト構成プロトコル（ DHCP ）の状態 | 作業 


| 実行中です | ブート環境プロンプトで次のコマンドを使用して、自動的に接続を設定します。 ifconfig e0M -auto 


| 実行されていません  a| 
ブート環境プロンプトで次のコマンドを使用して、接続を手動で設定します。 ifconfig e0M -addr= filer_addr -mask= netmask -gw= gateway -dns= dns_addr domain= dns_domain`filer_addr' は、ストレージシステムの IP アドレスです。「 netmask 」は、ストレージ・システムのネットワーク・マスクです。「 gateway 」はストレージ・システムのゲートウェイです。「 dns_addr 」は、ネットワーク上のネームサーバの IP アドレスです。このパラメータはオプションです。「 dns_domain 」はドメインネームサービス（ DNS ）ドメイン名です。このパラメータはオプションです。


NOTE: インターフェイスによっては、その他のパラメータが必要になる場合もあります。ファームウェア・プロンプトで「 help ifconfig 」と入力すると、詳細が表示されます。

|===
. node1 でネットブートを実行します。
+
netboot\http://web_server_ip/path_to_web_accessible_directory/netboot/kernel`

+

NOTE: トランクを中断しないでください。

. AFF A900 コントローラモジュールでノード 1 が起動するまで待ち、次のようにブートメニューオプションを表示します。
+
[listing]
----
Please choose one of the following:

(1)  Normal Boot.
(2)  Boot without /etc/rc.
(3)  Change password.
(4)  Clean configuration and initialize all disks.
(5)  Maintenance mode boot.
(6)  Update flash from backup config.
(7)  Install new software first.
(8)  Reboot node.
(9)  Configure Advanced Drive Partitioning.
(10) Set Onboard Key Manager recovery secrets.
(11) Configure node for external key management.
Selection (1-11)?
----
. 起動メニューからオプション（ 7 ） Install new software first （新しいソフトウェアを最初にインストール）を選択します。
+
このメニューオプションを選択すると、新しい ONTAP イメージがブートデバイスにダウンロードおよびインストールされます。

+
[NOTE]
====
次のメッセージは無視してください 'This 手順 is not supported for Non-Disruptive Upgrade on an HA pair'環境の無停止の ONTAP ソフトウェアアップグレード。コントローラのアップグレードは含まれません。

新しいノードを希望するイメージに更新する場合は、必ずネットブートを使用してください。別の方法で新しいコントローラにイメージをインストールすると、正しいイメージがインストールされない場合があります。この問題環境 All ONTAP リリース

====
. 手順を続行するかどうかを確認するメッセージが表示されたら 'y' と入力し ' パッケージの入力を求められたら 'URL:\http://web_server_ip/path_to_web-accessible_directory/ontap_version_image.tgz` と入力します
+
「 path_to_the_web-accessible_directory 」は、「 ONTAP_version_image.tgz 」をダウンロードした場所を指します <<netboot_node1_step2,手順 2>>。

. 次の手順を実行してコントローラモジュールをリブートします。
+
.. 次のプロンプトが表示されたら 'n' を入力してバックアップ・リカバリをスキップします
+
[listing]
----
Do you want to restore the backup configuration now? {y|n}
----
.. 次のプロンプトが表示されたら 'y' と入力して再起動します
+
[listing]
----
The node must be rebooted to start using the newly installed software. Do you want to reboot now? {y|n}
----
+
コントローラモジュールはリブートしますが、ブートメニューで停止します。これは、ブートデバイスが再フォーマットされたことにより、構成データのリストアが必要なためです。



. プロンプトで「 wipeconfig 」コマンドを実行して、ブートメディアの以前の設定をクリアします。
+
.. 次のメッセージが表示されたら、回答は「はい」を選択します。
+
[listing]
----
This will delete critical system configuration, including cluster membership.
Warning: do not run this option on a HA node that has been taken over.
Are you sure you want to continue?:
----
.. ノードがリブートして「 wipeconfig 」を終了し、ブートメニューで停止します。


. ブート・メニューからオプション「 5 」を選択して、保守モードに切り替えます。ノードがメンテナンス・モードで停止し ' コマンド・プロンプト *' が表示されるまで 'yes' を選択します回答
. コントローラとシャーシが「 HA 」として構成されていることを確認します。
+
「 ha-config show 」

+
次に 'ha-config show コマンドの出力例を示します

+
[listing]
----
Chassis HA configuration: ha
Controller HA configuration: ha
----
. コントローラとシャーシが「 ha 」として設定されていない場合は、次のコマンドを使用して設定を修正します。
+
「 ha-config modify controller ha 」を参照してください

+
「 ha-config modify chassis ha 」を参照してください

. 「 ha-config 」の設定を確認します。
+
「 ha-config show 」

+
[listing]
----
Chassis HA configuration: ha
Controller HA configuration: ha
----
. ノード 1 を停止します。
+
「 halt 」

+
ノード 1 は LOADER プロンプトで停止します。

. node2 で、システムの日付、時刻、およびタイムゾーンを確認します。
+
「食事」

. node1 で、ブート環境プロンプトで次のコマンドを使用して日付を確認します。
+
「日付」

. 必要に応じて、 node1 に日付を設定します。
+
'Set date <mm/dd/yyyy>`

+

NOTE: node1 で対応する UTC 日付を設定します。

. ノード 1 で、ブート環境のプロンプトで次のコマンドを使用して時間を確認します。
+
「時間」

. 必要に応じて、 node1 で時刻を設定します。
+
時刻を設定します

+

NOTE: node1 で対応する UTC 時間を設定します。

. node1 でパートナーシステム ID を設定します。
+
'setenv partner-sysid <node2 _sysid>`

+
node2 のシステム ID は 'node show -node node2 コマンドの出力から取得できます

+
.. 設定を保存します。
+
'aveenv



. node1 の LOADER プロンプトで、「 partner-sysid 」を確認する必要があります。node1 の場合 'partner-sysid' は node2 のものである必要がありますnode1 の「 partner-sysid 」を確認します。
+
printenv partner-sysid


