---
sidebar: sidebar 
permalink: upgrade-arl-auto-affa900/overview_of_the_arl_upgrade.html 
keywords: overview, arl, upgrade, owner, controller, hardware 
summary: AFF A700 から AFF A900 ARL コントローラへの手順 のアップグレードの仕組みを理解します。 
---
= ARL アップグレードの概要
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ARL を使用してノードをアップグレードする前に、手順の動作について理解しておく必要があります。このコンテンツでは、手順はいくつかの段階に分かれています。



== ノードペアをアップグレードします

ノードペアをアップグレードするには、元のノードを準備し、元のノードと新しいノードの両方で一連の手順を実行する必要があります。その後、元のノードの運用を停止できます。



== ARL アップグレードシーケンスの概要

手順では、交換用コントローラハードウェアを使用して元のコントローラハードウェアを一度に 1 台ずつアップグレードし、 HA ペア構成を利用してルート以外のアグリゲートの所有権を切り替えます。すべてのルート以外のアグリゲートで、アップグレード後の正しいノードである最終デスティネーションに到達するために、 2 つの再配置を実行する必要があります。

各アグリゲートにはホーム所有者と現在の所有者があります。ホーム所有者はアグリゲートの実際の所有者であり、現在の所有者は一時的な所有者です。

次の表に、各フェーズで実行するタスクの概要と、そのフェーズの最後で実行したアグリゲートの所有権の状態を示します。詳細な手順については、手順の後半で説明します。

[cols="35,65"]
|===
| 段階 | 手順 


| link:stage_1_index.html["ステージ 1 ：アップグレードの準備"]  a| 
ステージ2で、ノード1の非ルートアグリゲートとNASデータLIFをノード2に再配置します。このプロセスは主に自動化されており、ステータスを確認するために処理が一時停止します。この処理は手動で再開する必要があります。必要に応じて、障害が発生したアグリゲートまたは拒否されたアグリゲートを再手順 の後半で使用するために必要なノード1の情報を記録してから、対応するノード1のコントローラとNVRAMモジュールを交換し、ノード1を廃棄して、アップグレードしたノード1をネットブートする必要があります。

ステージ 1 終了時のアグリゲートの所有権：

* node1 は、 node1 アグリゲートのホーム所有者と現在の所有者です
* node2 には、 node2 アグリゲートのホーム所有者と現在の所有者を指定します




| link:stage_2_index.html["ステージ2：リソースをノード1から再配置し、AFF A700またはFAS9000 node1から撤去します"]  a| 
ステージ2で、ノード1の非ルートアグリゲートとNASデータLIFをノード2に再配置します。このプロセスは主に自動化されており、ステータスを確認するために処理が一時停止します。この処理は手動で再開する必要があります。必要に応じて、障害が発生したアグリゲートまたは拒否されたアグリゲートを再ノード1を撤去する前に、手順 の後半で使用するために情報をメモしておきます。ネットブートの準備は、手順 のあとから行うこともできます。

ステージ 2 終了時のアグリゲートの所有権：

* node2 には、 node1 アグリゲートの現在の所有者を指定します
* node2 には、 node2 アグリゲートのホーム所有者と現在の所有者を指定します




| link:stage_3_index.html["ステージ3：AFF A900またはFAS9500コントローラとNVRAMモジュールでnode1をブートします"]  a| 
ステージ3では、コントローラとNVRAMモジュールをアップグレードしてnode1をブートし、アップグレードしたnode1のインストールを確認します。NetApp Volume Encryption（NVE）を使用している場合は、キー管理ツールの設定をリストアします。ノード1のルート以外のアグリゲートとNASデータLIFをnode2からアップグレードしたnode1に再配置し、SAN LIFがnode1に存在することを確認します。

ステージ 3 終了時のアグリゲートの所有権：

* アップグレード後のAFF A900またはFAS9500 node1は、node1個のアグリゲートのホーム所有者と現在の所有者です
* node2 には、 node2 アグリゲートのホーム所有者と現在の所有者を指定します




| link:stage_4_index.html["ステージ 4 ：リソースを node2 から再配置し、 node2 を撤去"]  a| 
ステージ4で、ルート以外のアグリゲートとNASデータLIFをノード2からアップグレード後のノード1に再配置し、ノード2を撤去します。

ステージ 4 終了時のアグリゲートの所有権：

* アップグレードした node1 は、元は node1 に属していたアグリゲートのホーム所有者および現在の所有者です
* アップグレードした node1 は、 node2 アグリゲートの現在の所有者です




| link:stage_5_index.html["ステージ5：AFF A900またはFAS9500 NVRAMとコントローラモジュールをnode2にインストールします"]  a| 
ステージ5で、アップグレードしたnode2に提供された新しいNVRAMとコントローラモジュールを取り付け、さらにnode2をネットブートします。

ステージ 5 終了時のアグリゲートの所有権：

* アップグレードしたnode1は、最初にnode1に属していたアグリゲートのホーム所有者および現在の所有者です。
* アップグレードされた node2 は、元々 node2 に属していたアグリゲートのホーム所有者と現在の所有者です。




| link:stage_6_index.html["ステージ6：AFF A900またはFAS9500コントローラとNVRAMモジュールでnode2をブートします"]  a| 
ステージ6で、コントローラとNVRAMモジュールをアップグレードしてnode2をブートし、アップグレードしたnode2のインストールを確認します。NVEを使用している場合は、key-manager configurationをリストアします。さらに、node1のルート以外のアグリゲートとNASデータLIFをnode1からアップグレードされたnode2に再配置し、SAN LIFがnode2に存在することを確認します。



| link:stage_7_index.html["ステージ 7 ：アップグレードを完了する"]  a| 
ステージ7では、新しいノードが正しくセットアップされていることを確認し、暗号化が有効な新しいノードがある場合は、ストレージ暗号化またはNVEを設定してセットアップします。また、古いノードの運用を停止し、SnapMirrorの処理を再開する必要があります。

|===