---
sidebar: sidebar 
permalink: upgrade-arl-auto-affa900/relocate_non_root_aggr_nas_lifs_from_node2_to_node1.html 
keywords: relocate, non-root, aggregates, nas, lif, node2, node1. aff, a900, NVRAM, controller 
summary: AFF A700 から AFF A900 へのアップグレード中に、ノード 2 のルート以外のアグリゲートをノード 1 に再配置します。 
---
= ルート以外のアグリゲートと NAS データ LIF を node2 から node1 に再配置します
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
node2 を AFF A900 コントローラモジュールおよび NVRAM モジュールと交換する前に、 node2 に所有されているルート以外のアグリゲートを node1 に再配置する必要があります。

前の段階で確認したあとに、 node2 のリソースリリースが自動的に開始されます。ルート以外のアグリゲートと SAN 以外のデータ LIF が node2 から新しい node1 に移行されます。

アグリゲートと LIF の移行が完了すると、検証のために処理が一時停止されます。この段階で、ルート以外のアグリゲートと SAN 以外のデータ LIF がすべて新しい node1 に移行されたことを確認する必要があります。

アグリゲートおよび LIF のホーム所有者は変更されません。現在の所有者のみが変更されます。

.手順
. ルート以外のすべてのアグリゲートがオンラインで、 node1 上のそれらの状態になっていることを確認します。
+
storage aggregate show -node node1 -state online -root false

+
次の例は、 node1 にあるルート以外のアグリゲートがオンラインになっていることを示しています。

+
[listing]
----
cluster::> storage aggregate show -node node1 state online -root false

Aggregate     Size        Available   Used%   State	 #Vols	 Nodes	  RAID	   Status
----------    ---------   ---------   ------  -----   -----  ------  -------  ------
aggr_1	      744.9GB      744.8GB	 0%	 online	  5	 node1	  raid_dp  normal
aggr_2	      825.0GB	    825.0GB	 0%	 online	  1	 node1	  raid_dp  normal
2 entries were displayed.
----
+
アグリゲートがオフラインになった場合、またはノード 1 で外部になった場合は、新しいノード 1 で各アグリゲートに対して 1 回、次のコマンドを実行してアグリゲートをオンラインにします。

+
「 storage aggregate online -aggregate <aggr_name>` 」という名前になります

. node1 で次のコマンドを使用し、出力を調べて、すべてのボリュームが node1 でオンラインになっていることを確認します。
+
volume show -node node1 -state offline`

+
ノード 1 上のボリュームのいずれかがオフラインになっている場合は、各ボリュームについて 1 回、 node1 で次のコマンドを使用してボリュームをオンラインにします。

+
'volume online -vserver <vserver-name> -volume <volume-name>`

+
このコマンドで使用する '<vserver-name> は ' 前の volume show コマンドの出力にあります

. LIF が正しいポートに移動され、ステータスが「 up 」になっていることを確認します。LIF が 1 つでも停止している場合は、次のコマンドを LIF ごとに 1 回入力して、 LIF の管理ステータスを up に設定します。
+
「 network interface modify -vserver <vserver_name> -lif <lif_name> -home-node <nodename> -status-admin up 」という形式で指定します

. 次のコマンドを使用して、 node2 にデータ LIF が残っていないことを確認します。
+
network interface show -curr-node <node2> -role data


