---
sidebar: sidebar 
permalink: upgrade-arl-auto-affa900/verify_node2_installation.html 
keywords: verifying, verify, node, install, installation, aff, a900, NVRAM, controller 
summary: AFF A900 コントローラモジュールと NVRAM モジュールを使用して、 node2 のインストールを確認します。 
---
= node2 のインストールを確認します
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
AFF A900またはFAS9500コントローラとNVRAMモジュールで、node2のインストールを確認する必要があります。物理ポートは変更されないため、古いnode2の物理ポートを交換するnode2にマッピングする必要はありません。

AFF A900またはFAS9500コントローラモジュールでnode1をブートしたあと、正しくインストールされていることを確認する必要があります。node2 がクォーラムに参加するまで待ってから、コントローラの交換処理を再開する必要があります。

手順のこの時点で、 node2 がクォーラムに参加する間、処理が一時停止します。

.手順
. node2 がクォーラムに参加していることを確認します
+
cluster show -node node2 -fields health`

+
「 health 」フィールドの出力は「 true 」でなければなりません。

. node2 がノード 1 と同じクラスタに含まれており、正常な状態であることを確認します。
+
「 cluster show 」を参照してください

. advanced 権限モードに切り替えます。
+
「高度」

. コントローラ交換処理のステータスを確認し、コントローラが一時停止状態で、 node2 を停止する前と同じ状態になっていることを確認して、新しいコントローラの取り付けやケーブルの移動の物理的なタスクを実行します。
+
「 system controller replace show 」と表示されます

+
「 system controller replace show-sdetails 」というエラーが表示されます

. コントローラの交換処理を再開します。
+
「システムコントローラの交換が再開」

. コントローラの交換処理が一時停止し、次のメッセージが表示されます。
+
[listing]
----
Cluster::*> system controller replace show
Node          Status                       Error-Action
------------  ------------------------     ------------------------------------
Node2         Paused-for-intervention      Follow the instructions given in
                                           Step Details
Node1         None

Step Details:
--------------------------------------------
To complete the Network Reachability task, the ONTAP network configuration must be manually adjusted to match the new physical network configuration of the hardware. This includes:


1. Re-create the interface group, if needed, before restoring VLANs. For detailed commands and instructions, refer to the "Re-creating VLANs, ifgrps, and broadcast domains" section of the upgrade controller hardware guide for the ONTAP version running on the new controllers.
2. Run the command "cluster controller-replacement network displaced-vlans show" to check if any VLAN is displaced.
3. If any VLAN is displaced, run the command "cluster controller-replacement network displaced-vlans restore" to restore the VLAN on the desired port.
2 entries were displayed.
----
+

NOTE: この手順 では、 VLAN 、 ifgrp 、およびブロードキャストドメインのセクションの再作成が、 node2 で _ ネットワーク設定の名前が _Restore に変更されています。

. コントローラの交換が一時停止状態になった状態で、に進みます <<Restore network configuration on node2>>。




== node2 でネットワーク設定をリストアします

node2 がクォーラムにあり、 node1 と通信できることを確認したら、 node1 の VLAN 、インターフェイスグループ、およびブロードキャストドメインが node2 に表示されていることを確認します。また、 node2 のすべてのネットワークポートが正しいブロードキャストドメインに設定されていることを確認します。

VLAN 、インターフェイスグループ、およびブロードキャストドメインの作成と再作成の詳細については、を参照してください link:other_references.html["参考資料"] をクリックして、 _Network Management_content にリンクします。

.手順
. アップグレードした node2 上のすべての物理ポートを表示します。
+
network port show -node node2`

+
ノードのすべての物理ネットワークポート、 VLAN ポート、およびインターフェイスグループポートが表示されます。この出力から、 ONTAP によって「 Cluster 」ブロードキャストドメインに移動された物理ポートを確認できます。この出力を使用して、インターフェイスグループメンバーポート、 VLAN ベースポート、または LIF をホストするスタンドアロンの物理ポートとして使用するポートを決定できます。

. クラスタのブロードキャストドメインの一覧を表示します。
+
「 broadcast-domain show 」

. node2 のすべてのポートの到達可能性を表示します。
+
network port reachability show -node node2`

+
次の例のような出力が表示されます。ポート名とブロードキャスト名はさまざまです。

+
[listing]
----
Cluster::*> network port reachability show -node local
Node      Port     Expected Reachability                Reachability Status
--------- -------- ------------------------------------ ---------------------
Node2
          e0M      Default:Mgmt                         no-reachability
          e10a     Default:Default-3                    ok
          e10b     Default:Default-4                    ok
          e11a     Cluster:Cluster                      no-reachability
          e11b     Cluster:Cluster                      no-reachability
          e11c     -                                    no-reachability
          e11d     -                                    no-reachability
          e2a      Default:Default-1                    ok
          e2b      Default:Default-2                    ok
          e9a      Default:Default                      no-reachability
          e9b      Default:Default                      no-reachability
          e9c      Default:Default                      no-reachability
          e9d      Default:Default                      no-reachability
13 entries were displayed.
----
+
上記の例では、コントローラの交換後に node2 がブートし、クォーラムに参加しています。到達可能性のない複数のポートがあり、到達可能性スキャンを保留しています。

. [[restore_node2 _step4] 次のコマンドを使用して、 node2 の各ポートの到達可能性を「 ok 」以外の到達可能性ステータスで修復します。
+
'network port reachability repair-node <node_name > -port <port_name> ’

+
--
.. 物理ポート
.. VLAN ポート


--
+
次の例のような出力が表示されます。

+
[listing]
----
Cluster ::> reachability repair -node node2 -port e9d
----
+
[listing]
----
Warning: Repairing port "node2:e9d" may cause it to move into a different broadcast domain, which can cause LIFs to be re-homed away from the port. Are you sure you want to continue? {y|n}:
----
+
上記の例に示すように、ポートの到達可能性ステータスが、現在配置されているブロードキャストドメインの到達可能性ステータスと異なる場合があることを示す警告メッセージが表示されます。ポートと回答 'y' または 'n' の接続を適宜確認します

+
すべての物理ポートに想定される到達可能性があることを確認します。

+
「 network port reachability show 」のように表示されます

+
到達可能性の修復が実行されると、 ONTAP は正しいブロードキャストドメインにポートを配置しようとします。ただし、ポートの到達可能性を判別できず、既存のどのブロードキャストドメインにも属していない場合、 ONTAP はこれらのポート用に新しいブロードキャストドメインを作成します。

. ポートの到達可能性を確認します
+
「 network port reachability show 」のように表示されます

+
すべてのポートが正しく設定され、正しいブロードキャストドメインに追加されている場合、「 network port reachability show 」コマンドは、接続されているすべてのポートの到達可能性ステータスを「 ok 」、物理的に接続されていないポートのステータスを「 no-reachability 」と報告する必要があります。この 2 つ以外のステータスが報告されたポートがある場合は、到達可能性修復を実行し、の手順に従ってブロードキャストドメインにポートを追加または削除します <<restore_node2_step4,手順 4>>。

. すべてのポートがブロードキャストドメインに配置されたことを確認します。
+
「 network port show 」のように表示されます

. ブロードキャストドメインのすべてのポートで、正しい Maximum Transmission Unit （ MTU ；最大伝送ユニット）が設定されていることを確認します。
+
「 network port broadcast-domain show 」

. 次の手順に従って、リストアが必要な SVM および LIF のホームポートがある場合は、それらを指定して LIF のホームポートをリストアします。
+
.. 移動された LIF を表示します。
+
「 dispaced-interface show 」

.. LIF のホームノードとホームポートをリストアします。
+
「変位インターフェイス restore -home-node -node node_name -vserver vserver_name -lif -name lif_name 」のように指定します



. すべての LIF にホームポートがあり、意図的に稼働状態になっていることを確認します。
+
network interface show -fields home-port 、 status-admin


