---
sidebar: sidebar 
permalink: upgrade-arl-manual-app/decide_to_use_arl_guide.html 
keywords: decision, decision, what to use, upgrade, HA pair, metrocluster, storage encryption, volume encryption, NSE, NVE 
summary: ONTAP 9.8 以降を実行する新しいコントローラを手順 使用して HA ペアのストレージコントローラを手動でアップグレードするかどうかを決定します。 
---
= アグリゲートの再配置手順を使用するかどうかを決定します
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
このコンテンツでは、 HA ペアのストレージコントローラを新しいコントローラにアップグレードし、既存のデータとディスクをすべて残す方法について説明します。これは複雑な手順であり、経験豊富な管理者のみが使用する必要があります。

このコンテンツは、次の状況で使用します。

* 新しいコントローラを新しい HA ペアとしてクラスタに追加し、ボリューム移動を使用してデータを移行する必要はありません。
* ONTAP の管理経験があり、 diagnostic 権限モードで作業する場合のリスクが十分にあります。
* MetroCluster 9.8 以降を実行する 4 ノードおよび 8 ノードの Fabric ONTAP 構成を使用するシステムがある場合。
* システムにハイブリッドアグリゲートがある。



NOTE: この手順 では、NetApp Storage Encryption（NSE）、NetApp Volume Encryption（NVE）、およびNetApp Aggregate Encryption（NAE）を使用できます。

コントローラハードウェアを別の方法でアップグレードして、ボリュームの移動を希望する場合は、を参照してください link:other_references.html["参考資料"] をクリックして、ボリュームまたは storage _ を移動して _ Upgrade にリンクします。

を参照してください link:other_references.html["参考資料"] から ONTAP 9 ドキュメントセンターにリンクして、 ONTAP 9 製品ドキュメントにアクセスできます。
