---
sidebar: sidebar 
permalink: upgrade-arl-manual-app/ensure_controllers_set_up_correctly.html 
keywords: set up, controllers, correctly, ha pair, lif, aggregate, node, failover 
summary: HA ペアを有効にし、 node3 と node4 にあるストレージアクセスを確認し、 ONTAP 9.8 以降を実行しているコントローラで ARL を手動でアップグレードしたあとにアグリゲートの所有権を確認します。 
---
= 新しいコントローラが正しくセットアップされていることを確認します
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
正しいセットアップを確認するには、 HA ペアを有効にする必要があります。さらに、 node3 と node4 が相互のストレージにアクセスできること、およびクラスタ内の他のノードに属するデータ LIF を所有していないことを確認する必要があります。また、 node3 が node1 のアグリゲートを所有しており、 node4 が node2 のアグリゲートを所有していること、および両方のノードのボリュームがオンラインであることを確認する必要があります。

.手順
. いずれかのノードで次のコマンドを入力して、ストレージフェイルオーバーを有効にします。
+
storage failover modify -enabled true -node _node3_`

. ストレージフェイルオーバーが有効になっていることを確認します。
+
「 storage failover show 」をクリックします

+
次の例は、ストレージフェイルオーバーが有効になっている場合のコマンドの出力例を示しています。

+
[listing]
----
cluster::> storage failover show
                              Takeover
Node           Partner        Possible State Description
-------------- -------------- -------- ------------------
node3          node4          true     Connected to node4
node4          node3          true     Connected to node3
----
. 次のいずれかを実行します。
+
|===
| クラスタの種類 | 説明 


| 2 ノードクラスタ | どちらかのノードで cluster ha modify -configured true コマンドを入力して ' クラスタの高可用性を有効にします 


| 3 ノード以上のクラスタ | に進みます ,手順 4。 
|===
. [[man_ver_setup_Step4]] 次のコマンドを入力して、 node3 と node4 が同じクラスタに属していることを確認します。
+
「 cluster show 」を参照してください

. 次のコマンドを入力し、出力を調べて、 node3 と node4 が相互のストレージにアクセスできることを確認します。
+
「 storage failover show -fields local-missing-disks 、 partner-missing-disks 」というメッセージが表示されます

. 次のコマンドを入力し、出力を調べて、 node3 と node4 がクラスタ内の他のノードによってホーム所有されているデータ LIF を所有していないことを確認します。
+
「 network interface show 」を参照してください

+
node3 または node4 に、クラスタ内の他のノードがホーム所有するデータ LIF がある場合は、「 network interface revert 」コマンドを使用して、データ LIF をホーム所有者にリバートします。

. ノード 3 がノード 1 のアグリゲートを所有していること、およびノード 4 がノード 2 のアグリゲートを所有していることを確認します。
+
storage aggregate show-owner-name_node3_`storage aggregate show-owner-name_node4 _`

. オフラインになっているボリュームがないかを確認します。
+
volume show -node _node3 --state offline `volume show -node _node4 --state off`

. オフラインのボリュームがある場合は、で取得したオフラインボリュームのリストと比較します link:prepare_nodes_for_upgrade.html#step19d["手順 19 （ d ）"] で、各ボリュームに対して次のコマンドを 1 回入力して、アップグレードの準備をし、必要に応じてオフラインのボリュームをオンラインにします。
+
'volume online -vserver_name_-volume_name_`

. ノードごとに次のコマンドを入力して、新しいノード用の新しいライセンスをインストールします。
+
'system license add -license-code_license_code'license_code'license_code..._`

+
license-code パラメータには、アルファベットの文字キーをアルファベットの大文字 28 個まで入力できます。ライセンスは一度に 1 つずつ追加することも、ライセンスキーごとにカンマで区切って複数ずつ追加することもできます。

. 構成に NetApp Storage Encryption （ NSE ）を使用していた場合は、「 kmip.init.maxwait` 」変数を「 off 」にして「 etenv bootarg storageencryption.support 」コマンドを「 true 」に設定します（を参照） link:install_boot_node3.html#step16["手順 16"] OF_Installおよびboot node3 _)では、変数をリセットする必要があります。「set diag」、「systemshell -node _node_name _ command sudo kenv -u -p kmip.init.maxwait`
. 元のノードから古いライセンスをすべて削除するには、次のいずれかのコマンドを入力します。
+
system license clean-up-unused -expired `system license delete -serial-number_node_name --package_license_package_package_`

+
** 期限切れのライセンスをすべて削除するには、次のように入力します
+
「システムライセンスのクリーンアップ - 期限切れ」

** 未使用のライセンスをすべて削除するには、次のように入力し
+
'System license clean-up-unused （システムライセンスのクリーンアップ - 未使用） '

** クラスタから特定のライセンスを削除するには、ノードで次のコマンドを入力します。
+
'system license delete -serial-number_node1_serial_number_-package *`system license delete -serial-number_node2 _serial_number_-package *`

+
次の出力が表示されます。

+
[listing]
----
Warning: The following licenses will be removed:
<list of each installed package>
Do you want to continue? {y|n}: y
----
+
すべてのパッケージを削除するには 'y' を入力します



. 次のコマンドを入力し、出力を調べて、ライセンスが正しくインストールされていることを確認します。
+
「 system license show 」を参照してください

+
でキャプチャした出力と比較できます link:prepare_nodes_for_upgrade.html#step30["手順 30"] で、ノードをアップグレードする準備をしています。

. 両方のノードで次のコマンドを実行して、 SP を設定します。
+
system service-processor network modify -node _node_name _`

+
に進みます link:other_references.html["参考資料"] SP の詳細については ' システム管理リファレンスにリンクし '_System ONTAP 9 コマンド：マニュアルページリファレンスにリンクし 'system service-processor network modify コマンドの詳細については ' を参照してください



. 新しいノードにスイッチレスクラスタをセットアップする場合は、に進みます link:other_references.html["参考資料"] ネットワークサポートサイトへのリンクをクリックし、 2 ノードスイッチレスクラスタへの移行の手順に従ってください。


ノード 3 とノード 4 でストレージ暗号化が有効になっている場合は、の手順を実行します link:set_up_storage_encryption_new_controller.html["新しいコントローラモジュールで Storage Encryption をセットアップします"]。それ以外の場合は、の手順を実行します link:decommission_old_system.html["古いシステムの運用を停止"]。
