---
sidebar: sidebar 
permalink: upgrade-arl-manual-app/guidelines_upgrade_with_arl.html 
keywords: guidelines, upgrade 
summary: ONTAP 9.8 以降を実行しているコントローラペアで ARL の手動アップグレード手順 を使用できるかどうかを確認します。 
---
= ARL を使用したコントローラのアップグレードに関するガイドライン
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
アグリゲートの再配置（ ARL ）を使用して ONTAP 9.8 を実行しているコントローラのペアをアップグレードできるかどうかは、プラットフォームおよび元のコントローラと交換用コントローラの両方の構成によって異なります。



[[supported-upgrades-for-arl]]
== ARL のアップグレードがサポートされます

ARL を使用してノードのペアをアップグレードできる状況は次のとおりです。

* アップグレード前に、元のコントローラと交換用コントローラの両方で同じバージョンの ONTAP 9.8 を実行している必要があります。
* 交換用コントローラの容量は元のコントローラと同じかそれ以上である必要があります。容量が等しいかそれよりも大きい場合は、 NVRAM サイズ、ボリューム、 LUN 、アグリゲート数の上限などの属性を表し、新しいノードのボリュームまたはアグリゲートの最大サイズも表します。
* 次の種類のシステムをアップグレードできます。
+
** FAS システムから FAS システムへの移動。
** AFF システムへの AFF システム。


* 一部の ARL コントローラアップグレードでは、交換用コントローラの一時的なクラスタポートをアップグレードに使用できます。たとえば、 AFF A300 から AFF A400 システムにアップグレードする場合、 AFF A400 構成に応じて、 2 つのメザニンポートのいずれかを使用するか、 4 ポート 10GbE ネットワークインターフェイスカードを追加して一時的なクラスタポートを提供できます。一時的なクラスタポートを使用してコントローラのアップグレードを完了したら、交換用コントローラの 100GbE ポートにクラスタを無停止で移行できます。
* ARL を使用したコントローラのアップグレードは、 SnapLock Enterprise ボリュームおよび SnapLock Compliance ボリュームが設定されたシステムでサポートされます。


ARL が元のコントローラーと交換用コントローラーで実行可能かどうかを確認する必要があります。定義済みのすべてのアグリゲートのサイズと、元のシステムでサポートされているディスクの数を確認する必要があります。次に、それらを新しいシステムでサポートされるアグリゲート サイズおよびディスクの数と比較します。この情報にアクセスするには、link:other-references.html["参考資料"]を参照して _Hardware Universe_ にリンクしてください。新しいシステムでサポートされるアグリゲート サイズおよびディスクの数は、元のシステムでサポートされるアグリゲート サイズおよびディスクの数以上である必要があります。

クラスタ混合ルールにおいて、元のコントローラが交換された際に、新しいノードが既存のノードと共にクラスタの一部となることができるかどうかを検証する必要があります。クラスタ混合ルールの詳細については、link:other-references.html["参考資料"]を参照して _Hardware Universe_ にアクセスしてください。


NOTE: どちらのシステムもハイアベイラビリティ（ HA ）と非 HA のどちらかです。両方のノードがこの機能を有効または無効にする必要があります。オールフラッシュで最適化されたノードと同じ HA ペアで最適化が有効になっていないノードを組み合わせることはできません。パーソナリティが異なる場合は、テクニカルサポートに連絡してください。


NOTE: 新しいシステムのスロット数が元のシステムより少ない場合、またはポート数が少ない、もしくはポートの種類が異なる場合は、新しいシステムにアダプタを追加する必要があります。link:other-references.html["参考資料"]を参照して、特定のプラットフォームの詳細については、NetApp Support Site の _Hardware Universe_ にアクセスしてください。

FAS8080 や AFF8080 システムなど、ノードあたり 3 つ以上のクラスタポートを備えたシステムは、アップグレードを開始する前に、ノードあたり 2 つのクラスタポートにクラスタ LIF を移行してホームに戻す必要があります。ノードごとに 3 つ以上のクラスタポートを使用してコントローラのアップグレードを実行すると、アップグレード後に新しいコントローラのクラスタ LIF がなくなる可能性があります。



[[upgrades-not-supported-for-arl]]
== ARL のアップグレードはサポートされていません

次のアップグレードは実行できません。

* ONTAP 9.8 以降を実行できないコントローラとの間。
* 元のコントローラに接続されたディスクシェルフをサポートしない交換用コントローラへの接続
+
ディスクのサポート情報については、link:other-references.html["参考資料"]を参照して _Hardware Universe_ にアクセスしてください。

* ルートアグリゲートまたは内蔵ドライブ上のデータアグリゲートを含むコントローラからのアクセス。
+
内部ディスクドライブ上のルートアグリゲートまたはデータアグリゲートを使用してコントローラをアップグレードする場合は、link:other-references.html["参考資料"] を参照して「ボリュームまたはストレージの移動によるアップグレード」にリンクし、「ボリュームの移動によるクラスタ化された Data ONTAP を実行するノードペアのアップグレード」の手順に進んでください。

+

NOTE: クラスター内のノードの ONTAP をアップグレードする場合は、link:other-references.html["参考資料"] を参照して「_Upgrade ONTAP_」にリンクしてください。





[[assumptions-and-terminology]]
== 前提条件と用語

このマニュアルの記述は次の前提に基づいています。

* 交換用コントローラハードウェアは新しく購入され、使用されていません。
+

WARNING: 中古コントローラーを準備するために必要な手順は、 `wipeconfig`この手順では、交換用コントローラ ハードウェアが新品であり、使用されていないことを前提としているため、これらのコマンドはこの手順には含まれていません。交換用コントローラ ハードウェアが以前に使用されていた場合、特にコントローラが 7-Mode でData ONTAPを実行していた場合には、テクニカル サポートに連絡する必要があります。

* ノードのペアをアップグレードする際のガイドラインを確認し、理解しておきます。
+

WARNING: NVRAM の内容を消去しないでください。  NVRAMの内容をクリアする必要がある場合は、 NetAppテクニカル サポートにお問い合わせください。

* 「 mody 」コマンドの前後に適切なコマンドを実行し、両方の「 show 」コマンドの出力を比較して、「 mody 」コマンドが成功したことを確認しています。
* SAN 構成の場合、 HA ペア上の各 Storage Virtual Machine （ SVM ）にローカル LIF とパートナー LIF があります。各 SVM にローカル LIF とパートナー LIF がない場合は、アップグレードを開始する前に、その SVM のリモートノードとローカルノードに SAN データ LIF を追加します。
* SAN 構成でポートセットを使用する場合は、バインドされた各ポートセットに HA ペアの各ノードの LIF が少なくとも 1 つ含まれていることを確認しておく必要があります。


この手順では、ノードのリブートや環境変数の出力や設定など、特定のタスクを実行できるノード上のプロンプトを「 _boot environment prompt_ 」で参照します。このプロンプトは、 _boot loader prompt_ と非公式に呼ばれることがあります。

ブート環境のプロンプトの例を次に示します。

[listing]
----
LOADER>
----


[[licensing-in-ontap-9-8-or-later]]
== ONTAP 9.8 以降のライセンス

一部の機能にはライセンスが必要ですが、1つ以上の機能を含む_packages_として発行されます。クラスタで使用する各機能のキーは、クラスタ内の各ノードに独自に設定する必要があります。

新しいライセンスキーがない場合は、クラスタで現在ライセンスされている機能を新しいコントローラで使用でき、引き続き使用できます。ただし、ライセンスされていない機能をコントローラで使用するとライセンス契約に違反する可能性があるため、アップグレードの完了後に新しいコントローラの新しいライセンスキーをインストールする必要があります。

ライセンスキーはすべて、28文字の大文字アルファベットで構成されています。link:other-references.html["参考資料"]を参照して、ONTAP 9.8以降の新しい28文字のライセンスキーを入手できる_NetAppサポートサイト_にアクセスしてください。ライセンスキーは、_マイサポート_セクションの_ソフトウェアライセンス_から入手できます。必要なライセンスキーがサイトに掲載されていない場合は、NetAppの営業担当者にお問い合わせください。

ライセンスに関する詳細については、link:other-references.html["参考資料"] を参照して『システム管理リファレンス』にアクセスしてください。



[[storage-encryption]]
== ストレージ暗号化

元のノードまたは新しいノードでストレージ暗号化が有効になっている場合があります。その場合は、この手順 で追加の手順を実行して、ストレージ暗号化が正しく設定されていることを確認する必要があります。

ストレージ暗号化を使用する場合は、ノードに関連付けられているすべてのディスクドライブに自己暗号化ディスクドライブが必要です。



[[two-node-switchless-clusters]]
== 2 ノードスイッチレスクラスタ

2 ノードスイッチレスクラスタのノードをアップグレードする場合は、アップグレードの実行中もスイッチレスクラスタのノードをそのまま使用できます。スイッチクラスタに変換する必要はありません。



[[troubleshoot]]
== トラブルシューティングを行う

ノードペアのアップグレード中に障害が発生する可能性があります。ノードがクラッシュする、アグリゲートが再配置されない、または LIF が移行されない可能性があります。障害の原因とその解決策は、アップグレード手順の実行中に障害が発生したタイミングによって異なります。

コントローラのアップグレード中に問題が発生した場合は、 link:aggregate_relocation_failures.html["トラブルシューティングを行う"]セクション。発生する可能性のある障害に関する情報は、手順のフェーズごとに記載されています。 link:arl_upgrade_workflow.html["ARLアップグレードシーケンス"] 。

発生した問題に対する解決策 が見つからない場合は、テクニカルサポートにお問い合わせください。

.次の手順
ARLによるコントローラーのアップグレードに関するガイドラインを確認した後、link:required_tools_documentation.html["必要なツールとドキュメントを確認する"]。
