---
sidebar: sidebar 
permalink: upgrade-arl-manual-app/index.html 
keywords: controller, aggregate, relocation, flexarray, manual, upgrade, metrocluster 
summary: 交換用コントローラハードウェアを使用して元のコントローラハードウェアをアップグレードし、ルート以外のアグリゲートの所有権を切り替えます。 
---
= ONTAP 9.8 以降を実行しているコントローラハードウェアは、アグリゲートの再配置を使用して手動でアップグレードします
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
手順の実行中に、交換用コントローラハードウェアを使用して元のコントローラハードウェアをアップグレードし、ルート以外のアグリゲートの所有権を切り替えます。アグリゲートをノードからノードに複数回移行して、アップグレード手順全体を通じて少なくとも 1 つのノードがアグリゲートからデータを提供していることを確認します。また、処理を続行する前に、データ論理インターフェイス（ LIF ）を移行し、新しいコントローラのネットワークポートをインターフェイスグループに割り当てます。


NOTE: このドキュメントでは、元のノードの名前は _node1_AND _node2 _ で、新しいノードの名前は _node3 _ と _node4 _ です。説明されている手順では、 node1 は node3 に置き換えられ、 node2 は node4 に置き換えられます。_node1_、 _node2 、 _node3 _ 、および _node4 _ という用語は、元のノードと新しいノードを区別するためだけに使用されます。手順を使用するときは、元のノードと新しいノードの実際の名前を置き換える必要があります。ただし実際には、ノードの名前は変更されません。 node3 には node1 という名前が付けられ、 node4 にはコントローラハードウェアのアップグレード後に node2 という名前が付けられます。本ドキュメントでは、 FlexArray 仮想化ソフトウェアを搭載した「 _systems 」という用語は、これらの新しいプラットフォームに属するシステムを意味します。用語 V シリーズシステム _ とは、ストレージアレイに接続可能な独立したハードウェアシステムを指します



==== 重要

* この手順は複雑で、 ONTAP の高度な管理スキルがあることを前提としています。また、を読んで理解する必要があります link:guidelines_upgrade_with_arl.html["ARL を使用したコントローラのアップグレードに関するガイドライン"] および  アップグレード開始前のセクション。
* この手順は、交換用コントローラハードウェアが新しく購入され、使用されていないことを前提としています。使用済みのコントローラを「 wipeconfig 」コマンドで準備するために必要な手順は、この手順には含まれていません。交換用コントローラハードウェアを以前に使用していた場合は、テクニカルサポートに問い合わせる必要があります。特に、コントローラが Data ONTAP 7-Mode を実行していた場合は、テクニカルサポートにお問い合わせください。
* この手順を使用して、ノードが 3 つ以上あるクラスタでコントローラハードウェアをアップグレードできます。ただし、クラスタ内のハイアベイラビリティ（ HA ）ペアごとに手順を個別に実行する必要があります。
* この FlexArray システム、 V シリーズシステム、 AFF システム、および手順環境 FAS 仮想化ソフトウェアを搭載したシステムです。必要なライセンスがインストールされていれば、 ONTAP 9 以降にリリースされた FAS システムをストレージアレイに接続できます。既存の V シリーズシステムは ONTAP 9 でサポートされます。ストレージアレイと V シリーズのモデルについては、を参照してください link:other_references.html["参考資料"] Hardware Universe へのリンクおよび V シリーズサポートマトリックスを参照してください。
* この MetroCluster ファブリック手順環境は、 MetroCluster 以外の構成に加えて、 ONTAP 9.8 以降を実行する 4 ノードおよび 8 ノード構成の Fabric Manager です。
+
** ONTAP 9.7 以前を実行する MetroCluster 構成の場合は、に進みます link:other_references.html["参考資料"] ONTAP 9.7 以前を実行しているコントローラハードウェアを手動でアップグレードするには、アグリゲートの再配置を使用するには、をリンクしてください。
** MetroCluster IP 構成および Fabric MetroCluster 構成のその他のアップグレードオプションについては、を参照してください link:other_references.html["参考資料"] MetroCluster アップグレードおよび拡張ガイド _ へのリンク。



