---
sidebar: sidebar 
permalink: upgrade-arl-manual-app/map_ports_node1_node3.html 
keywords: map, ports, node1, node3, cluster, home port, vlan ports, broadcast domain, connectivity 
summary: ONTAP 9.8 以降を実行しているコントローラで、 ARL を手動でアップグレードする際に、 node1 の物理ポートが node3 に正しくマッピングされていることを確認します。 
---
= ポートを node1 から node3 にマッピングします
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ノード 1 の物理ポートがノード 3 の物理ポートに正しくマッピングされていることを確認します。これにより、ノード 3 はクラスタ内の他のノードと通信し、アップグレード後にネットワークと通信できるようになります。

.作業を開始する前に
新しいノードのポートに関する情報を Hardware Universe から取得しておく必要があります。に進みます link:other_references.html["参考資料"] をクリックして、 Hardware Universe にリンクします。この情報は、このセクションおよびの後半で使用します link:map_ports_node2_node4.html["node2 のポートを node4 にマッピングします"]。

ノード 3 のソフトウェア設定は、ノード 3 の物理的な接続と同じである必要があります。また、アップグレードを続行する前に、 IP 接続をリストアする必要があります。

.このタスクについて
ポート設定は、ノードのモデルによって異なる場合があります。

.手順
. [[step1] 次の手順を実行して、セットアップが 2 ノードのスイッチレスクラスタであるかどうかを確認します。
+
.. 権限レベルを advanced に設定します。
+
「 advanced 」の権限が必要です

.. セットアップが 2 ノードスイッチレスクラスタかどうかを確認します。
+
network options switchless-cluster show

+
例：

+
[listing]
----
 cluster::*> network options switchless-cluster show
 Enable Switchless Cluster: false/true
----
+
このコマンドの値は、システムの物理状態と一致している必要があります。

.. 管理者権限レベルに戻ります。
+
「特権管理者」



. [[step2] 次の変更を行います。
+
.. クラスタブロードキャストドメインに追加するポートを変更します。
+
「network port modify -node _node_name --port_port_name_-mtu 9000 -ipspace Cluster」

+
次の例では、「 node1 」にクラスタポート e1b を追加します。

+
[listing]
----
network port modify -node node1 -port e1b -ipspace Cluster -mtu 9000
----
.. LIF を 1 つずつ新しいポートに移行します。
+
「network interface migrate -vserver _Vserver_name -lif_lif_name_-source-node-node1_destination-node-node1 __ destination-port_port_name_`

+
すべてのクラスタ LIF が移行され、クラスタ通信が確立されたら、クラスタがクォーラムに参加する必要があります。

.. クラスタ LIF のホームポートを変更します。
+
「network interface modify -vserver Cluster -lif LIF_name–home-port_port_name_`」です

.. クラスタブロードキャストドメインから古いポートを削除します。
+
「network port broadcast-domain remove-ports -ipspace Cluster -broadcast-domain Cluster -ports_node1：port_」のようになります

.. node1 と node3 のヘルス状態を表示します。
+
'cluster show -node-node1_-fields health`

.. アップグレードするHAペアで実行しているONTAPのバージョンに応じて、次のいずれかの操作を実行します。
+
[cols="30,70"]
|===
| ONTAP のバージョン | 作業 


| 9.8 ~ 9.11.1 | クラスタ LIF がポート 7700 をリスンしていることを確認します。

`::> network connections listening show -vserver Cluster` 


| 9.12.1以降 | この手順をスキップして、 <<man_map_1_step3,手順 3>>。 
|===
+
次の 2 ノードクラスタの例に示すように、クラスタポートでリスンしているポート 7700 は想定される結果です。

+
[listing]
----
Cluster::> network connections listening show -vserver Cluster
Vserver Name     Interface Name:Local Port     Protocol/Service
---------------- ----------------------------  -------------------
Node: NodeA
Cluster          NodeA_clus1:7700               TCP/ctlopcp
Cluster          NodeA_clus2:7700               TCP/ctlopcp
Node: NodeB
Cluster          NodeB_clus1:7700               TCP/ctlopcp
Cluster          NodeB_clus2:7700               TCP/ctlopcp
4 entries were displayed.
----
.. ポート7700をリスンしていない各クラスタLIFについて、LIFの管理ステータスをに設定します。 `down` 次に `up`：
+
`::> net int modify -vserver Cluster-lif cluster_lif_cluster-status-admin down；net int modify -vserver Cluster-lif cluster_lif_-status-admin up

+
手順（ f ）を繰り返して、クラスタ LIF がポート 7700 でリスンしていることを確認します。



. [man_map_1_step3] データ LIF をホストする物理ポートのブロードキャストドメインメンバーシップを変更します。
+
.. すべてのポートの到達可能性ステータスを表示します。
+
「 network port reachability show 」のように表示されます

.. 物理ポートと VLAN ポートの到達可能性を修復するには、各ポートで次のコマンドを 1 つずつ実行します。
+
到達可能性修復-node_name -- port_port_name_`

+
次のような警告が表示されます。「 y 」または「 n 」を確認し、必要に応じて入力します。

+
[listing]
----
WARNING: Repairing port "node_name:port" might cause it to move into a different broadcast domain, which can cause LIFs to be re-homed away from the port. Are you sure you want to continue? {y|n}:
----
.. ONTAP が修復を完了できるようにするには、最後のポートで「 reachability repair repair repair repair repair repair repair 」コマンドを実行してから約 1 分待ちます。
.. クラスタのすべてのブロードキャストドメインを一覧表示します。
+
「 network port broadcast-domain show 」

.. 到達可能性の修復が実行されると、 ONTAP は正しいブロードキャストドメインにポートを配置しようとします。ただし、ポートの到達可能性を判別できず、既存のブロードキャストドメインのいずれにも対応していない場合、 ONTAP はこれらのポート用に新しいブロードキャストドメインを作成します。すべてのメンバーポートがインターフェイスグループのメンバーポートになる場合は、必要に応じて、新しく作成したブロードキャストドメインを削除できます。ブロードキャストドメインを削除する
+
「broadcast-domain delete -broadcast-domain broadcast_domain_domain _」のようになります

.. インターフェイスグループの設定を確認し、必要に応じてメンバーポートを追加または削除します。
+
インターフェイスグループポートにメンバーポートを追加します。

+
ifgrp add-port -node node_name -ifgrp_ifgrp_port_-port_port_port_name_`

+
インターフェイスグループポートからメンバーポートを削除します。

+
ifgrp remove-port -node_name -ifgrp_ifgrp_port_-port_port_port_name_`です

.. 必要に応じて VLAN ポートを削除し、再作成します。VLAN ポートを削除します。
+
'vlan delete -node_name -- vlan-name_vlan_port_`

+
VLAN ポートを作成します。

+
'vlan create -node_node_name -- vlan-name _vlan_port_`

+

NOTE: アップグレードするシステムのネットワーク構成の複雑さによっては、すべてのポートが必要な場所に正しく配置されるまで手順（ a ）から（ g ）を繰り返してください。



. [[step4]] システムに VLAN が設定されていない場合は、に進みます <<man_map_1_step5,手順 5>>。VLAN が設定されている場合は、すでに存在しないポートまたは別のブロードキャストドメインに移動されたポートで設定されていたポート上で、取り外された VLAN を復元します。
+
.. 取り外された VLAN を表示します。
+
「cluster controller -replacement network変位- VLANs show」と表示されます

.. 取り外した VLAN を目的の宛先ポートに復元します。
+
「変位VLAN restore -node _node_name」-port_port_name -- destination -port_destination_destination_port_`

.. すべての取り外された VLAN が復元されたことを確認します。
+
「cluster controller -replacement network変位- VLANs show」と表示されます

.. VLAN は、作成後約 1 分後に適切なブロードキャストドメインに自動的に配置されます。リストアした VLAN が適切なブロードキャストドメインに配置されていることを確認します。
+
「 network port reachability show 」のように表示されます



. [man_map_1_step5] ONTAP 9.8以降手順 、ONTAP では、ネットワークポートの到達可能性の修復時にブロードキャストドメイン間でポートが移動された場合に、LIFのホームポートが自動的に変更されます。LIF のホームポートが別のノードに移動された場合や割り当てが解除された場合、その LIF は移動された LIF として表示されます。ホームポートがなくなった、または別のノードに再配置された、取り外した LIF のホームポートをリストアします。
+
.. ホームポートの LIF が別のノードに移動されたか、すでに存在していない可能性がある LIF を表示します。
+
「 dispaced-interface show 」

.. 各 LIF のホームポートをリストアします。
+
「変位インターフェイスrestore -vserver _Vserver_name -lif-name_lif_name_`」のように指定します

.. すべての LIF ホームポートがリストアされたことを確認します。
+
「 dispaced-interface show 」



+
すべてのポートが正しく設定され、正しいブロードキャストドメインに追加されている場合、「 network port reachability show 」コマンドは、接続されているすべてのポートの到達可能性ステータスを「 ok 」、物理的な接続がないポートのステータスを「 no-reachability 」と報告する必要があります。これら 2 つ以外のステータスを報告しているポートがある場合は、に記載されているように、到達可能性を修復します <<man_map_1_step3,手順 3>>。

. [[man_map_1_step6] すべての LIF が、正しいブロードキャストドメインに属するポートで管理上の理由で稼働していることを確認します。
+
.. 管理上の理由で停止している LIF がないか確認します。
+
「network interface show -vserver _Vserver_name --status -admin down」を参照してください

.. 動作状態が down になっている LIF がないか確認します。
+
「network interface show -vserver_Vserver_name --status-oper down」を参照してください

.. 変更する必要がある LIF のホームポートを変更します。
+
「network interface modify -vserver _Vserver_name -lif_lif_name_-home-port_`

+

NOTE: iSCSI LIF の場合、ホームポートを変更するには LIF が管理上停止している必要があります。

.. ホームでない LIF をそれぞれのホームポートにリバートします。
+
「 network interface revert * 」の略




