---
sidebar: sidebar 
permalink: upgrade-arl-manual-app/map_ports_node2_node4.html 
keywords: map, node2, node4, physical ports, cluster, network, connectivity 
summary: ONTAP 9.8 以降を実行しているコントローラで ARL を手動でアップグレードする場合は、 node2 の物理ポートが node4 に正しくマッピングされていることを確認します。 
---
= node2 のポートを node4 にマッピングします
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
node2の物理ポートがnode4の物理ポートに正しくマッピングされていることを確認する必要があります。これにより、アップグレード後、node4はクラスタ内の他のノードおよびネットワークと通信できるようになります。

.作業を開始する前に
新しいノードのポートに関する情報を確認しておく必要があります。を参照してください link:other_references.html["参考資料"] Hardware Universe にリンクするには、次の手順を実行します。このセクションの後半の情報を使用します。

ノード 4 のソフトウェア設定がノード 4 の物理的な接続と一致している必要があります。また、アップグレードを続行する前に、 IP 接続をリストアする必要があります。

.このタスクについて
ポート設定は、ノードのモデルによって異なる場合があります。

.手順
. セットアップが 2 ノードスイッチレスクラスタかどうかを確認するには、次の手順を実行します。
+
.. 権限レベルを advanced に設定します。
+
「 advanced 」の権限が必要です

.. セットアップが 2 ノードスイッチレスクラスタかどうかを確認します。
+
network options switchless-cluster show

+
例：

+
[listing]
----
cluster::*> network options switchless-cluster show
Enable Switchless Cluster:  false/true
----
+
このコマンドの値は、システムの物理状態と一致している必要があります。

.. 次のコマンドを使用して、管理者権限レベルに戻ります。
+
「特権管理者」



. 次の変更を行います。
+
.. 「 Cluster 」ブロードキャストドメインの一部となるポートを変更します。
+
「network port modify -node _node_name --port_port_name_-mtu 9000 -ipspace Cluster」

+
次の例では、「 node2 」にクラスタポート「 e1b 」を追加します。

+
network port modify -node node2 -port e1b -ipspace Cluster -mtu 9000`

.. LIF を 1 つずつ新しいポートに移行します。
+
「network interface migrate -vserver_name_-lif_lif_name_source -node node2 -destination-node node2 -destination-port_port_name_`

+
すべてのクラスタ LIF が移行され、クラスタ通信が確立されたら、クラスタがクォーラムに参加する必要があります。

.. クラスタ LIF のホームポートを変更します。
+
「network interface modify -vserver Cluster -lif LIF_name–home-port_port_name_`」です

.. 'Cluster' ブロードキャスト・ドメインから古いポートを削除します
+
「network port broadcast-domain remove-ports -ipspace Cluster -broadcast-domain Cluster -ports_node2：port_`」を実行します

.. node2 / node4 の「 health 」状態を表示します。
+
cluster show -node node2 -fields health`

.. アップグレードするHAペアで実行しているONTAPのバージョンに応じて、次のいずれかの操作を実行します。
+
[cols="30,70"]
|===
| ONTAP のバージョン | 作業 


| 9.8 ~ 9.11.1 | クラスタ LIF がポート 7700 をリスンしていることを確認します。

`::> network connections listening show -vserver Cluster` 


| 9.12.1以降 | この手順をスキップして、 <<man_map_2_Step3,手順 3>>。 
|===
+
次の 2 ノードクラスタの例に示すように、クラスタポートでリスンしているポート 7700 は想定される結果です。

+
[listing]
----
Cluster::> network connections listening show -vserver Cluster
Vserver Name     Interface Name:Local Port     Protocol/Service
---------------- ----------------------------  -------------------
Node: NodeA
Cluster          NodeA_clus1:7700               TCP/ctlopcp
Cluster          NodeA_clus2:7700               TCP/ctlopcp
Node: NodeB
Cluster          NodeB_clus1:7700               TCP/ctlopcp
Cluster          NodeB_clus2:7700               TCP/ctlopcp
4 entries were displayed.
----
.. ポート7700をリスンしていない各クラスタLIFについて、LIFの管理ステータスをに設定します。 `down` 次に `up`：
+
`::> net int modify -vserver Cluster-lif cluster_lif_cluster-status-admin down；net int modify -vserver Cluster-lif cluster_lif_-status-admin up

+
手順（ f ）を繰り返して、クラスタ LIF がポート 7700 でリスンしていることを確認します。



. [man_map_2_Step3] データ LIF をホストする物理ポートのブロードキャストドメインメンバーシップを変更します。
+
.. すべてのポートの到達可能性ステータスを表示します。
+
「 network port reachability show 」のように表示されます

.. 物理ポートと VLAN ポートの到達可能性を修復するには、各ポートで次のコマンドを 1 つずつ実行します。
+
到達可能性修復-node_name -- port_port_name_`

+
次のような警告が表示されます。y または n を確認し、必要に応じて入力します。

+
[listing]
----
Warning: Repairing port "node_name:port" may cause it to move into a different broadcast domain, which can cause LIFs to be re-homed away from the port. Are you sure you want to continue? {y|n}:
----
.. ONTAP が修復を完了できるようにするには、最後のポートで「 reachability repair repair repair repair repair repair repair 」コマンドを実行してから約 1 分待ちます。
.. クラスタのすべてのブロードキャストドメインを一覧表示します。
+
「 network port broadcast-domain show 」

.. 到達可能性修復が実行されると、ONTAPはポートを正しいブロードキャストドメインに配置しようと試みます。ただし、ONTAPがポートの到達可能性を判断できず、そのポートが既存のブロードキャストドメインのいずれにも対応していない場合、ONTAPはこれらのポート用に新しいブロードキャストドメインを作成しようとします。必要に応じて、新しく作成されたブロードキャストドメインのすべてのメンバーポートがインターフェースグループのメンバーポートになる場合は、それらのドメインを削除できます。ブロードキャストドメインを削除します：
+
「broadcast-domain delete -broadcast-domain broadcast_domain_domain _」のようになります

.. インターフェイスグループの設定を確認し、必要に応じてメンバーポートを追加または削除します。
+
インターフェイスグループポートにメンバーポートを追加します。

+
ifgrp add-port -node node_name -ifgrp_ifgrp_port_port_port_port_port_name_`です

+
インターフェイスグループポートからメンバーポートを削除します。

+
ifgrp remove-port -node node_name -ifgrp_ifgrp_port_-port_port_port_name_`です

.. 必要に応じて VLAN ポートを削除し、再作成します。VLAN ポートを削除します。
+
'vlan delete -node_name -- vlan-name_vlan_port_`

+
VLAN ポートを作成します。

+
'vlan create -node_node_name -- vlan-name _vlan_port_`



+

NOTE: アップグレードするシステムのネットワーク構成の複雑さによっては、すべてのポートが必要な場所に正しく配置されるまで手順（ a ）から（ g ）を繰り返してください。

. システムに VLAN が設定されていない場合は、に進みます <<man_map_2_Step5,手順 5>>。VLAN が設定されている場合は、すでに存在しないポートまたは別のブロードキャストドメインに移動されたポートで設定されていたポート上で、取り外された VLAN を復元します。
+
.. 取り外された VLAN を表示します。
+
「cluster controller -replacement network変位- VLANs show」と表示されます

.. 取り外した VLAN を目的の宛先ポートに復元します。
+
「変位VLAN restore -node _node_name」-port_port_name -- destination -port_destination_destination_port_`

.. すべての取り外された VLAN が復元されたことを確認します。
+
「cluster controller -replacement network変位- VLANs show」と表示されます

.. VLAN は、作成後約 1 分後に適切なブロードキャストドメインに自動的に配置されます。リストアした VLAN が適切なブロードキャストドメインに配置されていることを確認します。
+
「 network port reachability show 」のように表示されます



. [[man_map_2_Step5]]ONTAP 9.8以降では、ネットワークポート到達可能性修復手順中にポートがブロードキャストドメイン間で移動された場合、ONTAPはLIFのホームポートを自動的に変更します。LIFのホームポートが別のノードに移動された場合、または割り当てられていない場合、そのLIFは移動されたLIFとして表示されます。ホームポートが存在しなくなった、または別のノードに再配置された、移動されたLIFのホームポートをリストアします。
+
.. ホームポートの LIF が別のノードに移動されたか、すでに存在していない可能性がある LIF を表示します。
+
「 dispaced-interface show 」

.. 各 LIF のホームポートをリストアします。
+
「変位インターフェイスのリストア- vserver_vserver_name _- lif-name _lif_name_`

.. すべての LIF ホームポートがリストアされたことを確認します。
+
「 dispaced-interface show 」



+
すべてのポートが正しく設定され、正しいブロードキャストドメインに追加されている場合、「 network port reachability show 」コマンドは、接続されているすべてのポートの到達可能性ステータスを「 ok 」、物理的に接続されていないポートのステータスを「 no-reachability 」と報告する必要があります。これら 2 つ以外のステータスを報告しているポートがある場合は、に記載されているように、到達可能性を修復します <<man_map_2_Step3,手順 3>>。

. 正しいブロードキャストドメインに属するポート上ですべての LIF が意図的に稼働していることを確認します。
+
.. 管理上の理由で停止している LIF がないか確認します。
+
「network interface show -vserver_vserver_name --status-admin down」を参照してください

.. 動作状態が down になっている LIF がないか確認します。
+
「network interface show -vserver _vserver_name --status-oper down」を参照してください

.. 変更する必要がある LIF のホームポートを変更します。
+
「network interface modify -vserver _vserver_name __ lif_lif_name_-home-port_`

+

NOTE: iSCSI LIF の場合、ホームポートを変更するには LIF が管理上停止している必要があります。

.. ホームでない LIF をそれぞれのホームポートにリバートします。
+
「 network interface revert * 」の略





.次の手順
node2からnode4にポートをマッピングした後、link:move_nas_lifs_node2_from_node3_node4_verify_san_lifs_node4.html["node2が所有するNASデータLIFをnode3からnode4に移動し、node4でSAN LIFを検証する"]。
