---
sidebar: sidebar 
permalink: upgrade-arl-manual-app/map_ports_node1_node3.html 
keywords: map, ports, node1, node3, cluster, home port, vlan ports, broadcast domain, connectivity 
summary: ポートを node1 から node3 にマッピングします 
---
= ポートを node1 から node3 にマッピングします
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ノード 1 の物理ポートがノード 3 の物理ポートに正しくマッピングされていることを確認する必要があります。ポート 3 を使用すると、クラスタ内の他のノードおよびアップグレード後にネットワークと通信できます。

新しいノードのポートに関する情報を Hardware Universe から取得しておく必要があります。に進みます link:other_references.html["参考資料"] をクリックして、 Hardware Universe にリンクします。この情報は、このセクションおよびの後半で使用します 。

ノード 3 のソフトウェア設定は、ノード 3 の物理的な接続と同じである必要があります。また、アップグレードを続行する前に、 IP 接続をリストアする必要があります。

ポート設定は、ノードのモデルによって異なる場合があります。

.手順
. [[step1] 次の手順を実行して、セットアップが 2 ノードのスイッチレスクラスタであるかどうかを確認します。
+
.. 権限レベルを advanced に設定します。
+
「 advanced 」の権限が必要です

.. セットアップが 2 ノードスイッチレスクラスタかどうかを確認します。
+
network options switchless-cluster show

+
例：

+
[listing]
----
 cluster::*> network options switchless-cluster show
 Enable Switchless Cluster: false/true
----
+
このコマンドの値は、システムの物理状態と一致している必要があります。

.. 管理者権限レベルに戻ります。
+
「特権管理者」



. [[step2] 次の変更を行います。
+
.. クラスタブロードキャストドメインに追加するポートを変更します。
+
network port modify -node node_name -port port_name -mtu 9000 -ipspace Cluster `

+
次の例では、「 node1 」にクラスタポート e1b を追加します。

+
[listing]
----
network port modify -node node1 -port e1b -ipspace Cluster -mtu 9000
----
.. LIF を 1 つずつ新しいポートに移行します。
+
「 network interface migrate -vserver Vserver_name -lif LIF_name -source-node node1 -destination-node node1 -destination-port port_name 」の略

+
すべてのクラスタ LIF が移行され、クラスタ通信が確立されたら、クラスタがクォーラムに参加する必要があります。

.. クラスタ LIF のホームポートを変更します。
+
「 network interface modify -vserver Cluster -lif <lif_name> – home-port <port_name> 」という形式になります

.. クラスタブロードキャストドメインから古いポートを削除します。
+
「 network port broadcast-domain remove-ports -ipspace Cluster -broadcast-domain Cluster -port node1 ： port 」のようになります

.. node1 と node3 のヘルス状態を表示します。
+
cluster show -node node1 -fields health`

.. 各クラスタ LIF がポート 7700 をリスンしている必要があります。クラスタ LIF がポート 7700 をリスンしていることを確認します。
+
`::> network connections listening show -vserver Cluster `

+
次の 2 ノードクラスタの例に示すように、クラスタポートでリスンしているポート 7700 は想定される結果です。

+
[listing]
----
Cluster::> network connections listening show -vserver Cluster
Vserver Name     Interface Name:Local Port     Protocol/Service
---------------- ----------------------------  -------------------
Node: NodeA
Cluster          NodeA_clus1:7700               TCP/ctlopcp
Cluster          NodeA_clus2:7700               TCP/ctlopcp
Node: NodeB
Cluster          NodeB_clus1:7700               TCP/ctlopcp
Cluster          NodeB_clus2:7700               TCP/ctlopcp
4 entries were displayed.
----
.. 必要に応じて、ポート 7700 でリスンしていない各クラスタ LIF の管理ステータスを「 down 」に設定してから「 up 」に設定します。
+
`::> net int modify -vserver Cluster -lif <cluster-lif> -status-admin down ； net int modify -vserver Cluster -lif <cluster-lif> -status-admin up

+
手順（ f ）を繰り返して、クラスタ LIF がポート 7700 でリスンしていることを確認します。



. [man_map_1_step3] データ LIF をホストする物理ポートのブロードキャストドメインメンバーシップを変更します。
+
.. すべてのポートの到達可能性ステータスを表示します。
+
「 network port reachability show 」のように表示されます

.. 物理ポートと VLAN ポートの到達可能性を修復するには、各ポートで次のコマンドを 1 つずつ実行します。
+
「機能修復 - node node_name -port port_name 」

+
次のような警告が表示されます。「 y 」または「 n 」を確認し、必要に応じて入力します。

+
[listing]
----
WARNING: Repairing port "node_name:port" might cause it to move into a different broadcast domain, which can cause LIFs to be re-homed away from the port. Are you sure you want to continue? {y|n}:
----
.. ONTAP が修復を完了できるようにするには、最後のポートで「 reachability repair 」コマンドを実行してから約 1 分待ちます。
.. クラスタのすべてのブロードキャストドメインを一覧表示します。
+
「 broadcast-domain show 」

.. 到達可能性の修復が実行されると、 ONTAP は正しいブロードキャストドメインにポートを配置しようとします。ただし、ポートの到達可能性を判別できず、既存のブロードキャストドメインのいずれにも対応していない場合、 ONTAP はこれらのポート用に新しいブロードキャストドメインを作成します。すべてのメンバーポートがインターフェイスグループのメンバーポートになる場合は、必要に応じて、新しく作成したブロードキャストドメインを削除できます。ブロードキャストドメインを削除する
+
'broadcast-domain delete -broadcast-domain broadcast_domain'

.. インターフェイスグループの設定を確認し、必要に応じてメンバーポートを追加または削除します。
+
インターフェイスグループポートにメンバーポートを追加します。

+
ifgrp add-port node_name -ifgrp ifgrp_name -port port_name - ポート port_name

+
インターフェイスグループポートからメンバーポートを削除します。

+
ifgrp remove-port -node-node_name -ifgrp ifgrp_port -port port_name の形式で指定します

.. 必要に応じて VLAN ポートを削除し、再作成します。VLAN ポートを削除します。
+
'vlan delete -node node_name -vlan-name vlan_port_' のように指定します

+
VLAN ポートを作成します。

+
'vlan create -node node_name -vlan-namevlan_port

+

NOTE: アップグレードするシステムのネットワーク構成の複雑さによっては、すべてのポートが必要な場所に正しく配置されるまで手順（ a ）から（ g ）を繰り返してください。



. [[step4]] システムに VLAN が設定されていない場合は、に進みます <<man_map_1_step5,手順 5>>。VLAN が設定されている場合は、すでに存在しないポートまたは別のブロードキャストドメインに移動されたポートで設定されていたポート上で、取り外された VLAN を復元します。
+
.. 取り外された VLAN を表示します。
+
「 displaced-vlans show 」を参照してください

.. 取り外した VLAN を目的の宛先ポートに復元します。
+
「 dispaced-vlans restore -node node_name -port port_name -destination port destination_port 」という形式で指定します

.. すべての取り外された VLAN が復元されたことを確認します。
+
「 displaced-vlans show 」を参照してください

.. VLAN は、作成後約 1 分後に適切なブロードキャストドメインに自動的に配置されます。リストアした VLAN が適切なブロードキャストドメインに配置されていることを確認します。
+
「 network port reachability show 」のように表示されます



. [man_map_1_step5] ONTAP 9.8 以降 ONTAP 、手順では、ネットワークポートの到達可能性の修復時にブロードキャストドメイン間でポートが移動された場合に、 LIF のホームポートが自動的に変更されます。LIF のホームポートが別のノードに移動された場合や割り当てが解除された場合、その LIF は移動された LIF として表示されます。ホームポートがなくなった、または別のノードに再配置された、取り外した LIF のホームポートをリストアします。
+
.. ホームポートの LIF が別のノードに移動されたか、すでに存在していない可能性がある LIF を表示します。
+
「 dispaced-interface show 」

.. 各 LIF のホームポートをリストアします。
+
「配置されたインターフェイスのリストア -vserver Vserver_name -lif LIF_name 」のようになります

.. すべての LIF ホームポートがリストアされたことを確認します。
+
「 dispaced-interface show 」



+
すべてのポートが正しく設定され、正しいブロードキャストドメインに追加されている場合、「 network port reachability show 」コマンドは、接続されているすべてのポートの到達可能性ステータスを「 ok 」、物理的な接続がないポートのステータスを「 no-reachability 」と報告する必要があります。これら 2 つ以外のステータスを報告しているポートがある場合は、に記載されているように、到達可能性を修復します <<man_map_1_step3,手順 3>>。

. [[man_map_1_step6] すべての LIF が、正しいブロードキャストドメインに属するポートで管理上の理由で稼働していることを確認します。
+
.. 管理上の理由で停止している LIF がないか確認します。
+
「 network interface show -vserver Vserver_name -status-admin down 」という形式で表示されます

.. 動作状態が down になっている LIF がないか確認します。
+
「 network interface show -vserver Vserver_name -status -oper down 」を参照してください

.. 変更する必要がある LIF のホームポートを変更します。
+
「 network interface modify -vserver Vserver_name -lif LIF_name -home-node home_port 」のようになります

+

NOTE: iSCSI LIF の場合、ホームポートを変更するには LIF が管理上停止している必要があります。

.. ホームでない LIF をそれぞれのホームポートにリバートします。
+
「 network interface revert * 」の略




