---
sidebar: sidebar 
permalink: upgrade-arl-manual-app/map_ports_node2_node4.html 
keywords: map, node2, node4, physical ports, cluster, network, connectivity 
summary: ONTAP 9.8 以降を実行しているコントローラで ARL を手動でアップグレードする場合は、 node2 の物理ポートが node4 に正しくマッピングされていることを確認します。 
---
= node2 のポートを node4 にマッピングします
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
node2 の物理ポートが node4 の物理ポートに正しくマッピングされていることを確認する必要があります。そうすれば、 node4 はクラスタ内の他のノードおよびアップグレード後のネットワークと通信できるようになります。

新しいノードのポートに関する情報を確認しておく必要があります。を参照してください link:other_references.html["参考資料"] Hardware Universe にリンクするには、次の手順を実行します。このセクションの後半の情報を使用します。

ノード 4 のソフトウェア設定がノード 4 の物理的な接続と一致している必要があります。また、アップグレードを続行する前に、 IP 接続をリストアする必要があります。

ポート設定は、ノードのモデルによって異なる場合があります。

.手順
. セットアップが 2 ノードスイッチレスクラスタかどうかを確認するには、次の手順を実行します。
+
.. 権限レベルを advanced に設定します。
+
「 advanced 」の権限が必要です

.. セットアップが 2 ノードスイッチレスクラスタかどうかを確認します。
+
network options switchless-cluster show

+
例：

+
[listing]
----
cluster::*> network options switchless-cluster show
Enable Switchless Cluster:  false/true
----
+
このコマンドの値は、システムの物理状態と一致している必要があります。

.. 次のコマンドを使用して、管理者権限レベルに戻ります。
+
「特権管理者」



. 次の変更を行います。
+
.. 「 Cluster 」ブロードキャストドメインの一部となるポートを変更します。
+
network port modify -node node_name -port port_name -mtu 9000 -ipspace Cluster `

+
次の例では、「 node2 」にクラスタポート「 e1b 」を追加します。

+
network port modify -node node2 -port e1b -ipspace Cluster -mtu 9000`

.. LIF を 1 つずつ新しいポートに移行します。
+
「 network interface migrate -vserver vserver_name -lif lif_name source-node node2 -destination-node node2 -destination-port port_name

+
すべてのクラスタ LIF が移行され、クラスタ通信が確立されたら、クラスタがクォーラムに参加する必要があります。

.. クラスタ LIF のホームポートを変更します。
+
「 network interface modify -vserver Cluster -lif <lif_name> – home-port <port_name> 」という形式になります

.. 'Cluster' ブロードキャスト・ドメインから古いポートを削除します
+
「 network port broadcast-domain remove-ports -ipspace Cluster -broadcast-domain Cluster -ports node2 ： port 」のようになります

.. node2 / node4 の「 health 」状態を表示します。
+
cluster show -node node2 -fields health`

.. 各クラスタ LIF がポート 7700 をリスンしている必要があります。クラスタ LIF がポート 7700 をリスンしていることを確認します。
+
`::> network connections listening show -vserver Cluster `

+
次の 2 ノードクラスタの例に示すように、クラスタポートでリスンしているポート 7700 は想定される結果です。

+
[listing]
----
Cluster::> network connections listening show -vserver Cluster
Vserver Name     Interface Name:Local Port     Protocol/Service
---------------- ----------------------------  -------------------
Node: NodeA
Cluster          NodeA_clus1:7700               TCP/ctlopcp
Cluster          NodeA_clus2:7700               TCP/ctlopcp
Node: NodeB
Cluster          NodeB_clus1:7700               TCP/ctlopcp
Cluster          NodeB_clus2:7700               TCP/ctlopcp
4 entries were displayed.
----
.. 必要に応じて、ポート 7700 でリスンしていない各クラスタ LIF の管理ステータスを「 down 」に設定してから「 up 」に設定します。
+
`::> net int modify -vserver Cluster -lif <cluster-lif> -status-admin down ； net int modify -vserver Cluster -lif <cluster-lif> -status-admin up

+
手順（ f ）を繰り返して、クラスタ LIF がポート 7700 でリスンしていることを確認します。



. [man_map_2_Step3] データ LIF をホストする物理ポートのブロードキャストドメインメンバーシップを変更します。
+
.. すべてのポートの到達可能性ステータスを表示します。
+
「 network port reachability show 」のように表示されます

.. 物理ポートと VLAN ポートの到達可能性を修復するには、各ポートで次のコマンドを 1 つずつ実行します。
+
「機能修復 - node node_name -port port_name 」

+
次のような警告が表示されます。y または n を確認し、必要に応じて入力します。

+
[listing]
----
Warning: Repairing port "node_name:port" may cause it to move into a different broadcast domain, which can cause LIFs to be re-homed away from the port. Are you sure you want to continue? {y|n}:
----
.. ONTAP が修復を完了できるようにするには、最後のポートで「 reachability repair repair repair repair repair repair repair 」コマンドを実行してから約 1 分待ちます。
.. クラスタのすべてのブロードキャストドメインを一覧表示します。
+
「 broadcast-domain show 」

.. 到達可能性の修復が実行されると、 ONTAP は正しいブロードキャストドメインにポートを配置しようとします。ただし、ポートの到達可能性を判別できず、既存のブロードキャストドメインのいずれにも対応していない場合、 ONTAP はこれらのポート用に新しいブロードキャストドメインを作成します。すべてのメンバーポートがインターフェイスグループのメンバーポートになる場合は、必要に応じて、新しく作成したブロードキャストドメインを削除できます。ブロードキャストドメインを削除する
+
'broadcast-domain delete -broadcast-domain broadcast_domain'

.. インターフェイスグループの設定を確認し、必要に応じてメンバーポートを追加または削除します。
+
インターフェイスグループポートにメンバーポートを追加します。

+
ifgrp add-port node_name -ifgrp ifgrp_name -port port_name - ポート port_name

+
インターフェイスグループポートからメンバーポートを削除します。

+
ifgrp remove-port -node node_name -ifgrp ifgrp_name -port port_name - ポート port_name

.. 必要に応じて VLAN ポートを削除し、再作成します。VLAN ポートを削除します。
+
'vlan delete -node node_name -vlan-name vlan_port'

+
VLAN ポートを作成します。

+
'vlan create -node node_name -vlan-name vlan_port'



+

NOTE: アップグレードするシステムのネットワーク構成の複雑さによっては、すべてのポートが必要な場所に正しく配置されるまで手順（ a ）から（ g ）を繰り返してください。

. システムに VLAN が設定されていない場合は、に進みます <<man_map_2_Step5,手順 5>>。VLAN が設定されている場合は、すでに存在しないポートまたは別のブロードキャストドメインに移動されたポートで設定されていたポート上で、取り外された VLAN を復元します。
+
.. 取り外された VLAN を表示します。
+
「 displaced-vlans show 」を参照してください

.. 取り外した VLAN を目的の宛先ポートに復元します。
+
「 dispaced-vlans restore -node node_name -port port_name -destination port destination_port 」という形式で指定します

.. すべての取り外された VLAN が復元されたことを確認します。
+
「 displaced-vlans show 」を参照してください

.. VLAN は、作成後約 1 分後に適切なブロードキャストドメインに自動的に配置されます。リストアした VLAN が適切なブロードキャストドメインに配置されていることを確認します。
+
「 network port reachability show 」のように表示されます



. [man_map_2_Step5] ONTAP 9.8 以降手順では、ネットワークポートの到達可能性が修復されたときにブロードキャストドメイン間でポートが移動された場合、 ONTAP によって LIF のホームポートが自動的に変更されます。LIF のホームポートが別のノードに移動された場合や割り当てが解除された場合、その LIF は移動された LIF として表示されます。ホームポートがなくなった、または別のノードに再配置された、取り外した LIF のホームポートをリストアします。
+
.. ホームポートの LIF が別のノードに移動されたか、すでに存在していない可能性がある LIF を表示します。
+
「 dispaced-interface show 」

.. 各 LIF のホームポートをリストアします。
+
「 dispaced-interface restore -vserver vserver_name -lif -name lif_name 」のようになります

.. すべての LIF ホームポートがリストアされたことを確認します。
+
「 dispaced-interface show 」



+
すべてのポートが正しく設定され、正しいブロードキャストドメインに追加されている場合、「 network port reachability show 」コマンドは、接続されているすべてのポートの到達可能性ステータスを「 ok 」、物理的に接続されていないポートのステータスを「 no-reachability 」と報告する必要があります。これら 2 つ以外のステータスを報告しているポートがある場合は、に記載されているように、到達可能性を修復します <<man_map_2_Step3,手順 3>>。

. 正しいブロードキャストドメインに属するポート上ですべての LIF が意図的に稼働していることを確認します。
+
.. 管理上の理由で停止している LIF がないか確認します。
+
network interface show -vserver vserver_name -status-admin down

.. 動作状態が down になっている LIF がないか確認します。
+
network interface show -vserver vserver_name -status-oper down を実行します

.. 変更する必要がある LIF のホームポートを変更します。
+
「 network interface modify -vserver vserver_name -lif lif_name -home-port home_port 」を参照してください

+

NOTE: iSCSI LIF の場合、ホームポートを変更するには LIF が管理上停止している必要があります。

.. ホームでない LIF をそれぞれのホームポートにリバートします。
+
「 network interface revert * 」の略




