---
sidebar: sidebar 
permalink: upgrade-arl-manual-app/move_nas_lifs_node1_node2.html 
keywords: nas, node1, node2, lifs, cluster, san 
summary: 2 ノードクラスタの場合はノード 2 に、 ONTAP 9.8 以降を実行しているコントローラでは ARL を手動でアップグレードする場合は 3 つ目のノードにそれぞれノード 1 のデータ LIF を移動します。 
---
= node1 で所有されている NAS データ LIF を node2 に移動します
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ノード 1 をノード 3 に交換する前に、 2 ノードクラスタの場合はノード 1 で所有されている NAS データ LIF をノード 2 に、クラスタに 3 つ以上のノードがある場合はノード 3 に移動する必要があります。使用する方法は、クラスタが NAS 用に設定されているか SAN 用に設定されているかによって異なります。

アップグレード手順の実行中、リモート LIF は SAN LUN へのトラフィックを処理します。アップグレード時にクラスタやサービスの健全性を維持するために、 SAN LIF を移動する必要はありません。ノード 3 をオンラインにしたあと、 LIF が正常に機能しており、適切なポートに配置されていることを確認する必要があります。

.手順
. 次のコマンドを入力し、出力をキャプチャして、 node1 でホストされているすべての NAS データ LIF を表示します。
+
'network interface show -data-protocol nfs|cifs -curr-node node_name

+
[listing]
----
 cluster::> network interface show -data-protocol nfs|cifs -curr-node node1

          Logical     Status      Network             Current   Current Is
 Vserver  Interface   Admin/Oper  Address/Mask        Node      Port    Home
 -------- ----------  ----------  ------------------  --------- ------- ----
 vs0
          a0a         up/down     10.63.0.53/24       node1     a0a     true
          data1       up/up       10.63.0.50/18       node1     e0c     true
          rads1       up/up       10.63.0.51/18       node1     e1a     true
          rads2       up/down     10.63.0.52/24       node1     e1b     true
 vs1
          lif1        up/up       192.17.176.120/24   node1     e0c     true
          lif2        up/up       172.17.176.121/24   node1     e1a     true
----
. [step2] ノード 1 およびノード 2 のすべての LIF の自動リバート設定を変更します。
+
「network interface modify -vserver _Vserver_name --lif_lif_name_-auto-revert false」という名前のコマンドを実行します

. [[step3] インターフェイスグループおよび VLAN でホストされる NAS データ LIF を node1 で移行するには、次の手順を実行します。
+
.. [[substepa]] すべてのインターフェイスグループでホストされている LIF と node1 上の VLAN を、インターフェイスグループと同じネットワーク上の LIF をホストできる node2 のポートに移行します。そのためには、各 LIF に対して次のコマンドを 1 回入力します。
+
「network interface migrate -vserver _Vserver_name -lif_lif_name_-destination-node-node2 _–destination-port_netport | ifgrp_`

.. で、 LIF および VLAN のホームポートとホームノードを変更します ,手順 a LIF をホストしているポートとノードに対して次のコマンドを 1 回入力します。
+
「network interface modify -vserver _Vserver_name -lif_lif_name_-home-node2_-home-node _port_netport | ifgrp_`」



. [[step4]] 次のいずれかの操作を実行します。
+
[cols="20,80"]
|===
| クラスタの設定対象 | 作業 


| NAS | - 完了しました ,手順 5 から ,手順 8。 


| SAN | ノード上のすべてのSAN LIFを無効にしてアップグレード用に停止します。「network interface modify -vserver _Vserver -name _-lif LIF_name -home-node _node_name _to _upgrade _-home-port port | ifgrp-status-admin down 
|===
. [man_lif_1_2_step5] 各データ LIF に対して次のコマンドを 1 回入力して、 NAS データ LIF を node1 から node2 に移行します。
+
「network interface migrate -vserver_Vserver -name _-lif_lif_name_-destination -node _node2 _-destination-port_data_port_`

. [[step6] ] 次のコマンドを入力し、その出力を調べて、 LIF が正しいポートに移動されていること、およびいずれかのノードで次のコマンドを入力して LIF のステータスが up になっていることを確認します。
+
'network interface show -curr-node _node2 __-data-protocol nfs|cifs

. [step7] 移行された LIF のホームノードを変更します。
+
「network interface modify -vserver _Vserver -name _-lif_lif_name_-home-node2_-home-node _port_name_`

. [man_lif_1_2_step8] LIF がホームまたは現在のポートとして使用しているかどうかを確認しますポートがホームでない場合や現在のポートでない場合は、に進みます ,手順 9：
+
「network interface show -home-node _node2」-home-port_port_name_`

+
'network interface show -curr-node node_name --curr -port_port_port_name_`

. [man_lif_1_2_step9] LIF がホームポートまたは現在のポートとしてポートを使用している場合は、別のポートを使用するように LIF を変更します。
+
「network interface migrate -vserver_Vserver -name _-lif_lif_name_-destination–node_node_name _-destination -port_port_port_name _」

+
「network interface modify -vserver _Vserver -name _-lif_lif_name_home–node_name _-home-port_port_port_name _

. [[step10]] いずれかの LIF が停止している場合は、各 LIF に対して次のコマンドを 1 回入力して、 LIF の管理ステータスを「 up 」に設定します。
+
「network interface modify -vserver _Vserver -name _-lif_lif_name_-home-nodename_-status-admin up

+

NOTE: MetroCluster 構成では、ポートのブロードキャストドメインを変更できない場合があります。これは、ポートがデスティネーション Storage Virtual Machine （ SVM ）の LIF をホストしているポートに関連付けられているためです。デスティネーションLIFを適切なポートに再割り当てするには、リモートサイトの対応するソースSVMで次のコマンドを入力します：「MetroCluster vserver resync -vserver _Vserver_name _`

. [[step11]] 次のコマンドを入力し、その出力を調べて、 node1 にデータ LIF が残っていないことを確認します。
+
network interface show -curr-node node1 __-role data


