---
sidebar: sidebar 
permalink: upgrade-arl-manual-app/prepare_for_netboot.html 
keywords: prepare, netboot, rack, node3, node4 
summary: ONTAP 9.8 以降を実行しているコントローラで ARL を手動でアップグレードする際に、 node3 と node4 をネットブートする準備をします。 
---
= ネットブートを準備
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
ノード 3 とノード 4 を手順の後半で物理的にラックに設置したあと、ネットブートが必要になることがあります。「 _netboot_ 」は、リモートサーバに保存されている ONTAP イメージからブートすることを意味します。ネットブートの準備を行うときは、システムがアクセスできる Web サーバに、 ONTAP 9 ブート・イメージのコピーを配置する必要があります。

.作業を開始する前に
* システムから HTTP サーバにアクセスできることを確認します。
* を参照してください link:other_references.html["参考資料"] からネットアップサポートサイトにリンクして、使用しているプラットフォームに必要なシステムファイルと、適切なバージョンの ONTAP をダウンロードします。


.このタスクについて
元のコントローラと同じバージョンの ONTAP 9 がインストールされていない場合は、新しいコントローラをネットブートする必要があります。新しいコントローラをそれぞれ取り付けたら、 Web サーバに保存されている ONTAP 9 イメージからシステムをブートします。その後、以降のシステムブートで使用するブートメディアデバイスに正しいファイルをダウンロードできます。

ただし、元のコントローラと同じバージョンの ONTAP 9 がインストールされているコントローラには、ネットブートする必要はありません。その場合は、このセクションをスキップしてに進みます link:install_boot_node3.html["ステージ 3 ：ノード 3 をインストールしてブートします"]。

.手順
. [man_netboot_Step1] ネットアップサポートサイトにアクセスして、システムのネットブートの実行に使用するファイルをダウンロードします。
. ネットアップサポートサイトのソフトウェアダウンロードセクションから適切な ONTAP ソフトウェアをダウンロードし、「 <ONTAP_version>_image.tgz 」ファイルを Web にアクセスできるディレクトリに保存します。
. Web にアクセスできるディレクトリに移動し、必要なファイルが利用可能であることを確認します。
+
[cols="35,65"]
|===
| 用途 | 作業 


| FAS/AFF8000 シリーズシステム  a| 
の内容を展開します `<ontap_version>_image.tgz` ファイルをターゲットディレクトリに移動します。

`tar -zxvf <ontap_version>_image.tgz`


NOTE: Windows で内容を展開する場合は、 7-Zip または WinRAR を使用してネットブートイメージを展開します。

ディレクトリの一覧に、カーネルファイルを含むネットブートフォルダが含まれるようにします。

`netboot/kernel`



| その他すべてのシステム | ディレクトリの一覧に次のファイルが表示されます。 `<ontap_version>_image.tgz`注：の内容を展開する必要はありません `<ontap_version>_image.tgz` ファイル。 
|===
+
ディレクトリ内の情報を使用するには、 link:install_boot_node3.html["ステージ 3"] 。


