---
sidebar: sidebar 
permalink: upgrade-arl-manual-app/prepare_for_netboot.html 
keywords: prepare, netboot, rack, node3, node4 
summary: ノードを物理的にラックに設置したあとで、 node3 と node4 をネットブートする必要がある場合があります。 
---
= ネットブートを準備
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ノード 3 とノード 4 を手順の後半で物理的にラックに設置したあと、ネットブートが必要になることがあります。「 _netboot_ 」は、リモートサーバに保存されている ONTAP イメージからブートすることを意味します。ネットブートの準備を行うときは、システムがアクセスできる Web サーバに、 ONTAP 9 ブート・イメージのコピーを配置する必要があります。

.作業を開始する前に
* システムから HTTP サーバにアクセスできることを確認します。
* を参照してください link:other_references.html["参考資料"] からネットアップサポートサイトにリンクして、使用しているプラットフォームに必要なシステムファイルと、適切なバージョンの ONTAP をダウンロードします。


元のコントローラと同じバージョンの ONTAP 9 がインストールされていない場合は、新しいコントローラをネットブートする必要があります。新しいコントローラをそれぞれ取り付けたら、 Web サーバに保存されている ONTAP 9 イメージからシステムをブートします。その後、以降のシステムブートで使用するブートメディアデバイスに正しいファイルをダウンロードできます。

ただし、元のコントローラと同じバージョンの ONTAP 9 がインストールされているコントローラには、ネットブートする必要はありません。その場合は、このセクションをスキップしてに進みます link:stage_3_install_boot_node3.html["ステージ 3 ：ノード 3 をインストールしてブートします"]。

.手順
. [man_netboot_Step1] ネットアップサポートサイトにアクセスして、システムのネットブートの実行に使用するファイルをダウンロードします。
. ネットアップサポートサイトのソフトウェアダウンロードセクションから適切な ONTAP ソフトウェアをダウンロードし、「 <ONTAP_version>_image.tgz 」ファイルを Web にアクセスできるディレクトリに保存します。
. Web にアクセスできるディレクトリに移動し、必要なファイルが利用可能であることを確認します。
+
[cols="35,65"]
|===
| 用途 | 作業 


| FAS/AFF8000 シリーズシステム | 「 ONTAP_version_image.tgz 」ファイルの内容をターゲットディレクトリに展開します。 tar -zxvf ONTAP_version_image.tgz * 注： Windows で内容を展開する場合は、 7-Zip または WinRAR を使用してネットブートイメージを抽出します。ディレクトリの一覧には、カーネル・ファイル「 netboot/ kernel 」を含むネットブート・フォルダが含まれている必要があります 


| その他すべてのシステム | ディレクトリの一覧に次のファイルが含まれている必要があります。 "ONTAP_version_image.tgz *Note: 「 ONTAP_version_image.tgz 」ファイルの内容を抽出する必要はありません。 
|===
+
では、ディレクトリの情報を使用します link:stage_3_install_boot_node3.html["ステージ 3"]。


