---
sidebar: sidebar 
permalink: upgrade-arl-manual-app/relocate_non_root_aggr_node2_node3.html 
keywords: non-root, non-root, aggregates, relocate, node2, node3 
summary: node2 に AutoSupport メッセージを送信し、 ONTAP 9.8 以降を実行しているコントローラで ARL を手動でアップグレードする際に、 node2 の非ルートアグリゲートをノード 3 に手動で再配置します。 
---
= ルート以外のアグリゲートを node2 から node3 に再配置します。
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
ノード2をノード4に交換する前に、ノード2に関するAutoSupportメッセージを送信し、ノード2で所有されているルート以外のアグリゲートをノード3に再配置する必要があります。

[[sysconfig-a-command]]
.手順
. ノード2とノード3でパートナーシステムIDが正しく設定されていることを確認します。
+
** `system node run -node _node2_ -command sysconfig -a`
** `system node run -node _node3_ -command sysconfig -a`
+
次の例のような出力が表示されます。

+
[listing, subs="+quotes"]
----
NetApp Release 9.16.1: Mon Feb 10 07:55:45 EST 2025
System ID: _system-ID_; *partner ID: _partner-system-ID_*
System Serial Number: _system-serial-number_
System Rev: A0
System Storage Configuration: Mixed-Path HA
----
+
ノード2またはノード3の「パートナーID」が正しくない場合は、次の手順を実行します。

+
... 値が正しくないノードをリブートします。
... のコマンドを再実行し<<sysconfig-a-command,手順 1.>>、「partner ID」が正しい値に変更されたことを確認します。




. ノード2のAutoSupportメッセージをNetAppに送信します。
+
「system node AutoSupport invoke -node _node2 _-type all -message」「Upgrading _node2 _from_platform_old_to _platform_new_new_」というメッセージが表示されます

. AutoSupport メッセージが送信されたことを確認します。
+
system node AutoSupport show -node _node2 _-instanceです

+
「 Last Subject Sent ：」および「 Last Time Sent ：」のフィールドには、最後に送信されたメッセージのメッセージタイトルと、メッセージが送信された時刻が含まれています。

. ルート以外のアグリゲートを再配置します。
+
.. 権限レベルを advanced に設定します。
+
「 advanced 」の権限が必要です

.. node2 が所有するアグリゲートを表示します。
+
storage aggregate show-owner-name_node2_`

.. アグリゲートの再配置を開始する：
+
storage aggregate relocation start -node2_-destination_node3_aggregate-list *-nd-controller-upgrade trueを指定します

+

NOTE: コマンドは、ルート以外のアグリゲートのみを特定します。

.. プロンプトが表示されたら、「 y 」と入力します。
+
再配置はバックグラウンドで実行されます。アグリゲートの再配置には数秒から数分かかる場合があります。この時間には、クライアントの停止部分と停止部分の両方が含まれます。コマンドでは、オフラインまたは制限されたアグリゲートは再配置されません。

.. admin 権限レベルに戻ります。
+
「特権管理者」



. node2 の再配置のステータスを確認します。
+
storage aggregate relocation show -node-node2 _`

+
再配置後のアグリゲートについては、出力に「done」と表示されます。

+

NOTE: node2 に所有されているすべてのアグリゲートが node3 に再配置されてから次の手順に進む必要があります。

. 次のいずれかを実行します。
+
[cols="35,65"]
|===
| 再配置する対象 | 作業 


| すべてのアグリゲートが完了しました | にアクセスします。 


| アグリゲートに障害が発生したか、拒否された  a| 
.. 詳細なステータスメッセージを表示します。
+
「 storage aggregate show -instance 」のように表示されます

+
EMS ログで必要な対処方法を確認することもできます。

+

NOTE: event log showコマンドを実行すると'発生したエラーが表示されます

.. 対処方法を実行します。
.. 権限レベルを advanced に設定します。
+
「 advanced 」の権限が必要です

.. 障害が発生したアグリゲートまたは拒否されたアグリゲートを
+
storage aggregate relocation start -node2_-destination_node3_aggregate-list *-nd-controllerupgrade true」を実行します

.. プロンプトが表示されたら、「 y 」と入力します。
.. admin 権限レベルに戻ります。
+
「特権管理者」



必要に応じて、次のいずれかの方法で強制的に再配置を実行できます。

** 拒否のチェックを無視する：
+
「 storage aggregate relocation start -override-vetoes true -nd-controller-upgrade

** 送信先チェックを無効にする：
+
「 storage aggregate relocation start -override-destination-checks true -ndocontroller -upgrade 」を実行します



storage aggregate relocation コマンドの詳細については、を参照してください link:other_references.html["参考資料"] CLI_ および ONTAP 9 コマンド：マニュアルページリファレンス _ を使用してディスクおよびアグリゲートの管理にリンクするには、次の手順を実行します。

|===
. [man_relocate_2_3_step7] ルート以外のアグリゲートがすべてノード 3 でオンラインになっていることを確認します。
+
storage aggregate show -node _node3 --state offline-root false

+
オフラインになったアグリゲートや外部になったアグリゲートがある場合は、各アグリゲートを 1 つずつオンラインにする必要があります。

+
storage aggregate online -aggregate _aggr_name_`

. ノード 3 ですべてのボリュームがオンラインになっていることを確認します。
+
volume show -node _node3 --state offline`

+
ノード 3 でオフラインになっているボリュームがある場合は、各ボリュームについて 1 回、オンラインにする必要があります。

+
'volume online -vserver_Vserver -name_volume_volume-name _`

. node2がルート以外のオンラインのアグリゲートを所有していないことを確認します。
+
「storage aggregate show-owner-name_node2」-ha -policy sfo-state online」と表示されます

+
ルート以外のオンラインアグリゲートがすべて node3 にすでに再配置されているため、コマンドの出力にルート以外のオンラインアグリゲートが表示されないようにする必要があります。


