---
sidebar: sidebar 
permalink: upgrade-arl-manual-app/retire_node1.html 
keywords: retire, node1, epsilon, shut down, failover 
summary: ONTAP 9.8 以降を実行しているコントローラでは、ノード 2 と HA ペアを無効にし、 ARL を手動でアップグレードする際に、ノード 1 を正しくシャットダウンします。 
---
= ノード 1 を撤去
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
ノード 1 を撤去するには、ノード 2 で HA ペアを無効にし、ノード 1 を正しくシャットダウンしてラックまたはシャーシから取り外します。

.手順
. クラスタ内のノード数を確認します。
+
「 cluster show 」を参照してください

+
次の例に示すように、クラスタ内のノードが表示されます。

+
[listing]
----
cluster::> cluster show
Node                  Health  Eligibility
--------------------- ------- ------------
node1                 true    true
node2                 true    true
2 entries were displayed.
----
. [[man_stリタイヤ 1_step2] ストレージフェイルオーバーを無効にします。
+
[cols="35,65"]
|===
| クラスタの種類 | 作業 


| 2 ノードクラスタ  a| 
.. いずれかのノードで次のコマンドを入力して、クラスタハイアベイラビリティを無効にします。


cluster ha modify -configured false

.. ストレージフェイルオーバーを無効にします。


storage failover modify -node _node1_-enabled false



| 3 つ以上のノードで構成されるクラスタ | ストレージ・フェイルオーバーを無効にします：storage failover modify -node _node1 _-enabled false 
|===
+

WARNING: ストレージフェイルオーバーを無効にしないと、コントローラのアップグレードに失敗してデータアクセスが中断され、データが失われる可能性があります。

. ストレージフェイルオーバーが無効になっていることを確認します。
+
「 storage failover show 」をクリックします

+
次の例は、ノードでストレージフェイルオーバーが無効になっている場合の「 storage failover show 」コマンドの出力を示しています。

+
[listing]
----
 cluster::> storage failover show
                               Takeover
 Node           Partner        Possible State Description
 -------------- -------------- -------- -------------------------------------
 node1          node2          false    Connected to node2, Takeover
                                        is not possible: Storage failover is
                                        disabled

 node2          node1          false    Node owns partner's aggregates as part
                                        of the nondisruptive controller upgrade
                                        procedure. Takeover is not possible:
                                        Storage failover is disabled
 2 entries were displayed.
----
. データ LIF のステータスを確認します。
+
network interface show -role data -curr-node 2_node2 -home-node1_home_`

+
「 * Status Admin/Oper * 」列を参照して、停止している LIF がないかどうかを確認します。LIFがダウンしている場合は、 link:aggregate_relocation_failures.html["不具合のすす"]セクション。

. 次のいずれかを実行します。
+
[cols="35,65"]
|===
| クラスタの種類 | 作業 


| 2 ノードクラスタ | に進みます <<man_retire_1_step6,手順 6>>。 


| 3 つ以上のノードで構成されるクラスタ | に進みます <<man_retire_1_step8,手順 8>>。 
|===
. [[man_denter_1_step6] どちらかのノードの advanced 権限レベルにアクセスします。
+
「 advanced 」の権限が必要です

. [[step7] クラスタ HA が無効になっていることを確認します。
+
cluster ha show

+
次のメッセージが表示されます。

+
[listing]
----
High Availability Configured: false
----
+
クラスタ HA が無効になっていない場合は、この手順を繰り返します <<man_retire_1_step2,手順 2>>。

. [[man_リタイヤ _1_step8] 現在 node1 にイプシロンが設定されているかどうかを確認します。
+
「 cluster show 」を参照してください

+
ノード数が偶数のクラスタの場合は同票となる可能性があるため、 1 つのノードにイプシロンと呼ばれる追加の投票荷重が設定されます。を参照してください link:other_references.html["参考資料"] 詳細については ' を参照してください

+
[NOTE]
====
4 ノードクラスタの場合は、クラスタ内の別の HA ペアのノードにイプシロンが設定されていることがあります。

複数の HA ペアがあるクラスター内の HA ペアをアップグレードする場合は、コントローラーのアップグレードが行われていない HA ペアのノードにイプシロンを移動する必要があります。たとえば、 HA ペア構成の nodeA / nodeB および nodeC / ノードを含むクラスタで nodeA / nodeB をアップグレードする場合は、イプシロンを nodeC またはノードに移動する必要があります。

====
+
次の例では、 node1 にイプシロンが設定されています。

+
[listing]
----
 cluster::*> cluster show

 Node                 Health  Eligibility  Epsilon
 -------------------- ------- ------------ ------------
 node1                true    true         true
 node2                true    true         false
----
. node1 にイプシロンが設定されている場合は、 node2 に転送できるように、イプシロンを false に設定します。
+
cluster modify -node1_-epsilon false

. node2 のイプシロンを true に設定して ' イプシロンを node2 に転送します
+
cluster modify -node _node2 _-epsilon true

. node2 に対する変更が発生したことを確認します。
+
「 cluster show 」を参照してください

+
[listing]
----
 cluster::*> cluster show
 Node                 Health  Eligibility  Epsilon
 -------------------- ------- ------------ ------------
 node1                true    true         false
 node2                true    true         true
----
+
node2 のイプシロンを true に設定し、 node1 のイプシロンを false に設定します。

. セットアップが 2 ノードスイッチレスクラスタかどうかを確認します。
+
network options switchless-cluster show

+
[listing]
----
 cluster::*> network options switchless-cluster show

 Enable Switchless Cluster: false/true
----
+
このコマンドの値は、システムの物理状態と一致している必要があります。

. admin レベルに戻ります。
+
「特権管理者」

. node1 プロンプトから node1 を停止します。
+
system node halt -node _node1_`

+

WARNING: * 注意 * ： node1 が node2 と同じシャーシにある場合は、電源スイッチを使用するか、電源ケーブルを引き抜いて、シャーシの電源を切断しないでください。その場合は、データを提供している node2 が停止します。

. システムを停止するかどうかを確認するメッセージが表示されたら、「 y 」と入力します。
+
ノードはブート環境のプロンプトで停止します。

. node1 にブート環境プロンプトが表示されたら、シャーシまたはラックからブート環境プロンプトを削除します。
+
アップグレードが完了したら、 node1 の運用を停止できます。を参照してください link:decommission_old_system.html["古いシステムの運用を停止"]。


