---
sidebar: sidebar 
permalink: upgrade-arl-manual-app/set_up_netapp_encryption_on_new_controller.html 
keywords: set up, netapp volume encryption, encryption, controller, module 
summary: 必要に応じて、ONTAP 9.8以降を実行しているコントローラで、NVEまたはNAE用に新しいコントローラモジュールを手動でアップグレードする際に設定します。 
---
= 新しいコントローラモジュールでNetApp VolumeまたはAggregte Encryptionをセットアップします
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
交換したコントローラまたは新しいコントローラのハイアベイラビリティ（HA）パートナーがNetApp Volume Encryption（NVE）またはNetApp Aggregate Encryption（NAE）を使用する場合は、NVEまたはNAE用に新しいコントローラモジュールを設定する必要があります。

.このタスクについて
この手順には、新しいコントローラモジュールで実行する手順が含まれています。コマンドは正しいノードで入力する必要があります。

.手順
. キー管理サーバがまだ使用可能であり、ステータスと認証キー情報が正しいことを確認します。
+
「 securitykey manager key query -node node 」を参照してください

. 前の手順で確認したキー管理サーバを新しいコントローラのキー管理サーバリストに追加します。
+
.. 次のコマンドを使用して、キー管理サーバを追加します。
+
「security key-manager -add_key_manager_server_ip_address_`」

.. リストされている各キー管理サーバについて、同じ手順を繰り返します。最大 4 台のキー管理サーバをリンクできます。
.. 次のコマンドを使用して、キー管理サーバが正常に追加されたことを確認します。
+
「 securitykey -manager show 」を参照してください



. 新しいコントローラモジュールで、キー管理セットアップウィザードを実行して、キー管理サーバをセットアップしてインストールします。
+
既存のコントローラモジュールと同じキー管理サーバをインストールする必要があります。

+
.. 次のコマンドを使用して、新しいノードでキー管理サーバセットアップウィザードを起動します。
+
security key-manager setup -node _new_controller_name_`

.. ウィザードの手順に従って、キー管理サーバを設定します。


. リンクされたすべてのキー管理サーバから新しいノードに認証キーをリストアします。
+
[cols="35,65"]
|===
| 用途 | 使用するコマンド 


| 外部キー管理ツール | 「 securitykey-manager external restore 」このコマンドには、 OKM のパスフレーズが必要です 


| オンボードキーマネージャ（ OKM ） | 「セキュリティキーマネージャオンボード同期」 
|===
+
詳細については、技術情報アーティクルを参照してください https://kb.netapp.com/onprem/ontap/dm/Encryption/How_to_restore_external_key_manager_server_configuration_from_the_ONTAP_boot_menu["ONTAP ブートメニューから外部キー管理サーバの設定をリストアする方法"^]。



.完了後
認証キーを使用できなかったか、外部キー管理サーバにアクセスできなかったためにボリュームがオフラインになっていないかを確認します。を使用して、それらのボリュームをオンラインに戻します `volume online` コマンドを実行します
