---
sidebar: sidebar 
permalink: upgrade-arl-manual-app/set_fc_uta_uta2_config_node4.html 
keywords: fc configuration, uta configuration, uta2 configuration, configure FC ports, uta/uta2 card, node4, target, adapter, ports 
summary: ONTAP 9.8 以降を実行しているコントローラで、 ARL を手動でアップグレードする際に、ノード 4 のオンボード FC ポート、 UTA / UTA2 ポート、または UTA / UTA2 カードを設定します。 
---
= ノード 4 で FC または UTA / UTA2 設定を設定します
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
ノード 4 でオンボードの FC ポート、オンボードのユニファイドターゲットアダプタ（ UTA / UTA2 ）ポート、または UTA / UTA2 カードが使用されている場合は、残りの手順を完了する前に設定する必要があります。

.このタスクについて
完了する必要があるかもしれません<<ノード 4 の FC ポートを設定します>>または<<ノード 4 の UTA / UTA2 ポートを確認して設定してください>>、または両方のセクション。

ノード4にオンボードFCポート、オンボードUTA/UTA2ポート、またはUTA/UTA2カード（たとえば、 ONTAP 9.15.1以降に導入されたAFFおよびFASシステム）がなく、ストレージディスクを備えたシステムをアップグレードする場合は、link:map_ports_node2_node4.html["node2 のポートを node4 にマッピングします"] 。



== ノード 4 の FC ポートを設定します

ノード 4 にオンボードまたは FC アダプタのいずれかの FC ポートがある場合は、ポートが事前に構成されていないため、ノードを稼働状態にする前にポートの設定を行う必要があります。ポートが設定されていないと、サービスが停止する可能性があります。

.作業を開始する前に
セクションに保存した node2 の FC ポート設定の値を確認しておく必要があります link:prepare_nodes_for_upgrade.html["ノードをアップグレードする準備をします"]。

.このタスクについて
システムに FC 構成がない場合は、このセクションをスキップしてかまいません。システムにオンボード UTA / UTA2 ポートまたは UTA / UTA2 アダプタが搭載されている場合は、で設定します <<ノード 4 の UTA / UTA2 ポートを確認して設定してください>>。


IMPORTANT: このセクションのコマンドをクラスタープロンプトに入力します。

.手順
. システム上のすべての FC および統合ネットワーク アダプタに関する情報を表示します。
+
「 system node hardware unified-connect show 」を参照してください

. 新しいノードの FC 設定を、元のノードで取り込んだ設定と比較します。
. 必要に応じて、ノード 4 の FC ポートを変更します。
+
** ターゲットポートをプログラムする場合：
+
`system node hardware unified-connect modify -type \| -t target -adapter _port_name_`

** イニシエータポートをプログラミングする場合：
+
`system node unified-connect modify type \| -t initiator -adapter _port_name_`

+
`-type ` は FC4 のタイプ、ターゲットまたはイニシエータである。



. 次のコマンドを入力して出力を調べ、新しい設定を確認します。
+
`system node unified-connect show`

. 次のいずれかを実行します。
+
[cols="35,65"]
|===
| 新しいノードのデフォルトの FC 設定 | 次に、 


| 元のノードでキャプチャしたのと同じです | 行きます <<man_config_4_Step9,手順 9>>。 


| 元のノードでキャプチャしたものとは異なります | 行きます <<man_config_4_Step6,ステップ6>>。 
|===
. [[man_config_4_Step6]]メンテナンスモードを終了します。
+
「 halt 」

. コマンドを入力したら、ブート環境のプロンプトでシステムが停止するまで待ちます。
. ブート環境プロンプトで次のコマンドを入力して、node4 をブートします。
+
「 boot_ontap 」

. [[man_config_4_Step9]]次のいずれかのアクションを実行します。
+
** に進みます <<ノード 4 の UTA / UTA2 ポートを確認して設定してください>> ノード 4 に UTA / UTA2A カードまたは UTA / UTA2 オンボードポートがある場合
** セクションをスキップして、に進みます link:map_ports_node2_node4.html["node2 のポートを node4 にマッピングします"] ノード 4 に UTA / UTA2 カードまたは UTA / UTA2 オンボードポートがない場合






== ノード 4 の UTA / UTA2 ポートを確認して設定してください

ノード 4 でオンボード UTA / UTA2 ポートまたは UTA / UTA2A カードが使用されている場合は、アップグレードしたシステムの使用方法に応じて、ポートの設定を確認して設定する必要があります。

.作業を開始する前に
UTA / UTA2 ポートに対応する正しい SFP+ モジュールが必要です。

.このタスクについて
UTA / UTA2 ポートは、ネイティブの FC モードまたは UTA / UT2A モードに設定できます。FC モードは FC イニシエータと FC ターゲットをサポートします。 UTA / UTA2 モードを使用すると、 NIC と FCoE の同時トラフィックで同じ 10GbE SFP+ インターフェイスを共有し、 FC ターゲットをサポートすることができます。


NOTE: ネットアップのマーケティング資料では、 UTA2 という用語を CNA アダプタとポートという意味で使用している場合があります。ただし、 CLI では CNA という用語が使用されます。

UTA / UTA2 ポートはアダプタまたはコントローラ上に次の構成で配置されます。

* UTA / UTA2 カードは、コントローラと同時に注文しても、希望するパーソナリティを持つ未設定の状態で出荷されます。
* コントローラとは別に発注した UTA / UTA2 カードは、デフォルトの FC ターゲットパーソナリティとして出荷されます。
* 新しいコントローラのオンボード UTA / UTA2 ポートは、要求したパーソナリティを持つように（出荷前に）設定されています。


ただし、ノード 4 の UTA / UTA2 ポートの設定を確認し、必要に応じて変更することができます。


WARNING: メンテナンス モードに入るように指示されない限り、このセクションのコマンドをクラスター プロンプトに入力します。  MetroCluster FC システムを使用している場合は、UTA/UTA2 ポートを構成するにはメンテナンス モードにする必要があります。

.手順
. ノード 4 でポートが現在どのように構成されているかを確認します。
+
「 system node hardware unified-connect show 」を参照してください

. 現在の SFP+ モジュールが目的の用途と一致しない場合は、正しい SFP+ モジュールに交換します。
+
ネットアップの担当者に連絡して、正しい SFP+ モジュールを入手します。

. 「 system node hardware unified-connect show 」コマンドと「 ucadmin show 」コマンドの出力を調べ、 UTA / UTA2 ポートに希望するパーソナリティが設定されているかどうかを確認します。
. 次のいずれかを実行します。
+
[cols="35,65"]
|===
| CNA ポートの状況 | 作業 


| 希望するパーソナリティがない | に進みます <<man_check_4_Step5,手順 5>>。 


| あなたがほしい人格を持っている | 手順 5 から 12 を省略して、に進みます <<man_check_4_Step13,手順 13>>。 
|===
. [[man_check_4_Step5]]システムにストレージディスクがあり、 Data ONTAP 8.3 を実行している場合は、ノード 4 を起動してメンテナンス モードに入ります。
+
「 boot_ontap maint 」を使用してください

. 次のコマンドを入力し、出力を確認して、設定を確認します。
+
ucadmin show

. 次のいずれかを実行します。
+
[cols="35,65"]
|===
| を設定する場合 | 作業 


| UTA / UTA2A カードのポート | 行きます <<man_check_4_Step8,手順 8>>。 


| オンボードの UTA/UTA2 ポート | ステップ8をスキップして<<man_check_4_Step9,手順 9>>。 
|===
. [[man_check_4_Step8]]アダプタがイニシエーターモードであり、UTA/UTA2 ポートがオンラインの場合は、UTA/UTA2 ポートをオフラインにします。
+
storage disable adapter_adapter_adapter_adapter_name_`

+
ターゲットモードのアダプタは、メンテナンスモードで自動的にオフラインになります。

. [[man_check_4_Step9]]現在の構成が目的の用途と一致しない場合は、次のコマンドを入力して、必要に応じて構成を変更します。
+
ucadmin modify -m fc | cna-t initiator | target_adapter_name_`

+
** 「 -m' 」はパーソナリティ・モードである FC または 10 GbE UTA です。
** `-t` は FC4 のタイプで ' ターゲットまたはイニシエータです


+

NOTE: テープ ドライブには FC イニシエーターを使用し、SAN クライアントには FC ターゲットを使用する必要があります。

. システムにストレージ ディスクがある場合は、次のコマンドを入力します。
+
「 halt 」

+
ブート環境プロンプトが表示されます。

+
.. 次のコマンドを入力します。
+
「 boot_ontap 」



. システムにストレージ ディスクがある場合は、次のコマンドを入力します。
+
「 system node hardware unified-connect show 」を参照してください

+
次の例の出力では ' アダプタ「 1b 」の FC4 タイプがイニシエータに変更されており ' アダプタ「 2a 」と「 2b 」のモードが CNA に変更されています

+
[listing]
----
cluster1::> system node hardware unified-connect show
               Current  Current   Pending  Pending    Admin
Node  Adapter  Mode     Type      Mode     Type       Status
----  -------  -------  --------- -------  -------    -----
f-a    1a      fc       initiator -        -          online
f-a    1b      fc       target    -        initiator  online
f-a    2a      fc       target    cna      -          online
f-a    2b      fc       target    cna      -          online
4 entries were displayed.
----
. 次のいずれかのコマンドをポートごとに 1 回入力して、ターゲットポートをオンラインにします。
+
「network fcp adapter modify -node node_name --adapter_adapter_adapter_adapter_name_-state up」の形式で指定します

. [[man_check_4_Step13]] ポートをケーブル接続します。

