---
sidebar: sidebar 
permalink: upgrade-arl/index.html 
keywords: aggregate, relocation, moving, manual, upgrade, relocate, hardware 
summary: アグリゲートの再配置を使用してコントローラハードウェアをアップグレードする 
---
= 概要
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
このコンテンツでは、アグリゲートの再配置（ ARL ）を使用して、システムを停止することなくコントローラハードウェアをアップグレードする方法について説明します。

コントローラハードウェアをアップグレードするその他の方法については、を参照してください link:other_references.html["参考資料"] をクリックして、ボリュームまたは storage _ を移動して _ Upgrade にリンクします。

ONTAP を実行しているノードペアで、元のノードから同じクラスタ内の新しいノードにルート以外のアグリゲートを移行することで、コントローラハードウェアを無停止でアップグレードできます。アップグレード中は、アップグレード対象のノードでホストされているデータにアクセスできます。

ARL では HA 構成を利用して、ルート以外のアグリゲートの所有権をノード間で移動できます（ルート以外のアグリゲートが同じクラスタ内のストレージを共有している場合）。

ARL には、システムコマンドまたは手動アップグレードを使用したコントローラハードウェアのアップグレード用の方法が 2 つあります。を開始する前に、コントローラハードウェアのアップグレードに適したコンテンツを選択していることを確認する必要があります。

システムコマンドを使用してアップグレードを実行する場合は、次の表を参照してください。

[cols="30,70"]
|===
| この ONTAP バージョンを実行している場合 | システムコマンドでアップグレードするには、次のコマンドを使用します。 


| 9.10.1 以降 | link:https://docs.netapp.com/us-en/ontap-systems-upgrade/upgrade-arl-auto-affa900/index.html["「system controller replace」コマンドを使用して、同じシャーシ内のコントローラモデルをアップグレードします"^]

この手順を使用して、特定のモデルおよびONTAPソフトウェアバージョンのオールSANアレイ（ASA）として構成されたAFFコントローラをASAコントローラにアップグレードできます。 link:https://docs.netapp.com/us-en/ontap-systems-upgrade/upgrade-arl-auto-affa900/index.html["詳細はこちら。"]。 


| 9.8 以降 | link:https://docs.netapp.com/us-en/ontap-systems-upgrade/upgrade-arl-auto-app/index.html["ONTAP 9.8 以降を実行しているコントローラハードウェアをアップグレードするには、「 system controller replace 」コマンドを使用します"] 


| 9.5 から 9.7 | link:https://docs.netapp.com/us-en/ontap-systems-upgrade/upgrade-arl-auto/index.html["「 system controller replace 」コマンドを使用して、 ONTAP 9.5 を実行するコントローラハードウェアを ONTAP 9.7 にアップグレードします"] 
|===
手動アップグレードを実行する場合は、次の表を参照してください。

[cols="30,70"]
|===
| この ONTAP バージョンを実行している場合 | 手動でアップグレードするには、次を使用します 


| 9.8 以降 | link:https://docs.netapp.com/us-en/ontap-systems-upgrade/upgrade-arl-manual-app/index.html["ONTAP 9.8 以降を実行しているコントローラハードウェアを手動でアップグレードします"] 


| 9.0 から 9.7 | link:https://docs.netapp.com/us-en/ontap-systems-upgrade/upgrade-arl-manual/index.html["ONTAP 9.7 以前を実行しているコントローラハードウェアを手動でアップグレードします"] 
|===